import { GHOST_RUN_SECTION as RAW_GHOST_RUN_SECTION } from './section';
export { GHOST_RUN_STYLES } from './styles';

function replaceBlock(source: string, startToken: string, endToken: string, replacement: string): string {
  const start = source.indexOf(startToken);
  const end = start >= 0 ? source.indexOf(endToken, start) : -1;
  if (start < 0 || end < 0) return source;
  return source.slice(0, start) + replacement + source.slice(end);
}

function patchGhostRunSection(section: string): string {
  let patched = section;

  const crashCss = `<style>
#ghostrun .ghost-run-hud{position:absolute!important;left:0!important;right:0!important;top:0!important;height:0!important;z-index:70!important;pointer-events:none!important;display:block!important}
#ghostrun .ghost-run-fear-wrap{display:none!important;opacity:0!important;visibility:hidden!important}
#ghostrun .ghost-run-state{display:none!important;opacity:0!important;visibility:hidden!important}
#ghostrun .ghost-run-reaper{display:none!important;opacity:0!important;visibility:hidden!important}
#ghostrun .ghost-run-multiplier{position:absolute!important;top:52px!important;left:50%!important;right:auto!important;transform:translateX(-50%)!important;display:flex!important;align-items:center!important;justify-content:center!important;min-width:92px!important;height:auto!important;padding:0!important;margin:0!important;border:0!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;color:rgba(255,83,137,.78)!important;font-size:26px!important;font-weight:900!important;line-height:1!important;letter-spacing:.01em!important;text-shadow:0 5px 14px rgba(0,0,0,.42),0 0 18px rgba(255,46,99,.18)!important;z-index:90!important}
#ghostrun .ghost-run-countdown{position:absolute!important;top:84px!important;left:50%!important;transform:translateX(-50%)!important;display:none!important;min-width:52px!important;text-align:center!important;color:rgba(255,255,255,.62)!important;font-size:13px!important;font-weight:850!important;line-height:1!important;text-shadow:0 6px 16px rgba(0,0,0,.48)!important;z-index:90!important}
#ghostrun .ghost-run-screen[data-ghost-phase='betting'] .ghost-run-countdown{display:block!important}
#ghostrun .ghost-run-scene{order:1!important}#ghostrun .ghost-run-controls{order:2!important;margin-top:0!important;position:relative!important;z-index:80!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important;padding:12px 16px calc(20px + env(safe-area-inset-bottom))!important;align-content:start!important;background:rgba(13,13,13,.54)!important;pointer-events:auto!important}#ghostrun .crash-live{order:3!important}
#ghostrun .ghost-run-control-card{min-height:56px!important;padding:8px 4px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;color:#fff!important}
#ghostrun .ghost-run-control-card span{display:block!important;margin:0 0 5px!important;color:rgba(255,255,255,.45)!important;font-size:10px!important;font-weight:800!important;letter-spacing:.04em!important;text-transform:uppercase!important;line-height:1!important}
#ghostrun .ghost-run-control-card strong{display:flex!important;align-items:center!important;justify-content:flex-start!important;margin:0!important;min-height:34px!important;color:#fff!important;font-size:22px!important;font-weight:950!important;letter-spacing:-.04em!important;line-height:1!important}
#ghostrun .ghost-run-bet-card strong{border:1px solid rgba(255,255,255,.10)!important;border-radius:16px!important;padding:0 5px 0 10px!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;gap:0!important}
#ghostrun .ghost-run-win-card strong{border:1px solid rgba(255,255,255,.10)!important;border-radius:16px!important;padding:0 10px!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important}
#ghostrun .ghost-run-auto{display:inline-flex!important;align-items:center!important;justify-content:flex-start!important;gap:0!important;color:#fff!important}
#ghostrun .ghost-run-auto input{width:52px!important;height:34px!important;min-width:0!important;margin:0!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;font:inherit!important;font-size:22px!important;font-weight:950!important;letter-spacing:-.04em!important;text-align:left!important;box-shadow:none!important;-webkit-appearance:none!important;appearance:textfield!important}
#ghostrun .ghost-run-auto input::-webkit-outer-spin-button,#ghostrun .ghost-run-auto input::-webkit-inner-spin-button{-webkit-appearance:none!important;margin:0!important}
#ghostrun .ghost-run-auto span{display:inline!important;margin:0!important;color:#fff!important;font-size:22px!important;font-weight:950!important;letter-spacing:-.04em!important;text-transform:none!important;line-height:1!important}
#ghostrun [data-ghost-bet-input]{width:86px!important;flex:0 1 86px!important;height:34px!important;min-width:0!important;margin:0!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;font:inherit!important;font-size:22px!important;font-weight:950!important;letter-spacing:-.04em!important;text-align:left!important;box-shadow:none!important;-webkit-appearance:none!important;appearance:textfield!important}
#ghostrun [data-ghost-bet-input]::-webkit-outer-spin-button,#ghostrun [data-ghost-bet-input]::-webkit-inner-spin-button{-webkit-appearance:none!important;margin:0!important}
#ghostrun .ghost-run-back-button,#ghostrun .ghost-run-forward-button,#ghostrun .ghost-run-claim-button,#ghostrun .ghost-run-note{display:none!important}
#ghostrun .ghost-run-main-button{position:relative!important;z-index:90!important;background:#3b0715!important;background-image:none!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;pointer-events:auto!important;touch-action:manipulation!important;cursor:pointer!important;grid-column:1 / 3!important;height:60px!important;border-radius:17px!important;font-size:15px!important;font-weight:1000!important;letter-spacing:-.02em!important;transition:transform .18s ease,opacity .18s ease,background .18s ease,color .18s ease!important}
#ghostrun .ghost-run-main-button.cashout{background:#0f3f2a!important;border-color:rgba(120,255,179,.22)!important;color:#d8ffe8!important;-webkit-text-fill-color:#d8ffe8!important}
#ghostrun .ghost-run-main-button.is-placed{background:#030303!important;border-color:rgba(255,255,255,.24)!important;color:#fff!important;-webkit-text-fill-color:#fff!important}
#ghostrun .ghost-run-main-button:not(:disabled):active{transform:scale(.975)!important}
#ghostrun .ghost-run-main-button:disabled{opacity:.58!important;transform:scale(.985)!important}
#ghostrun .crash-live{margin-top:6px!important;margin-bottom:4px!important}
#ghostrun .ghost-run-scene{width:calc(100vw - 24px)!important;width:calc(100dvw - 24px)!important;max-width:430px!important;margin:10px auto 0!important;border-radius:34px!important;border:1px solid rgba(255,255,255,.12)!important;box-shadow:0 24px 70px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.12)!important;overflow:hidden!important}
#ghostrun .ghost-run-background-panel{flex:0 0 min(100vw - 24px,430px)!important;flex-basis:min(calc(100dvw - 24px),430px)!important;width:min(calc(100vw - 24px),430px)!important;width:min(calc(100dvw - 24px),430px)!important}
#ghostrun .ghost-run-history{position:absolute!important;left:18px!important;right:18px!important;top:12px!important;z-index:65!important;display:flex!important;gap:6px!important;overflow-x:auto!important;overflow-y:visible!important;margin:0!important;min-height:28px!important;padding:4px!important;scrollbar-width:none!important;background:rgba(255,255,255,.018)!important;border:0!important;border-radius:16px!important;box-shadow:none!important;backdrop-filter:blur(2px)!important;-webkit-backdrop-filter:blur(2px)!important}
#ghostrun .ghost-run-history::-webkit-scrollbar{display:none!important}
#ghostrun .ghost-run-history span{flex:0 0 auto!important;border-radius:999px!important;padding:4px 8px!important;min-height:20px!important;line-height:12px!important;font-size:10px!important;font-weight:890!important;color:rgba(255,255,255,.94)!important;background:transparent!important;border:0!important;box-shadow:none!important}
html body:has(#ghostrun.active) .content{overflow:hidden!important}
html body:has(#ghostrun.active) #ghostrun.ghost-run-view{height:100%!important;min-height:100%!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;scrollbar-width:none!important}
html body:has(#ghostrun.active) #ghostrun.ghost-run-view::-webkit-scrollbar{display:none!important;width:0!important;height:0!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-screen{min-height:100%!important;height:auto!important;overflow:visible!important;padding-bottom:calc(30px + env(safe-area-inset-bottom))!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-controls{width:calc(100% - 24px)!important;max-width:430px!important;margin:6px auto 0!important;padding:8px!important;display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;gap:7px!important;align-items:stretch!important;align-content:start!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:visible!important;isolation:isolate!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-win-card{order:1!important;grid-column:1 / 4!important;min-height:42px!important;height:42px!important;margin:0!important;padding:7px 12px!important;border-radius:16px!important;background:rgba(26,11,15,.54)!important;border:0!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-win-card>span{display:block!important;margin:0!important;color:rgba(255,255,255,.50)!important;font-size:11px!important;line-height:1!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;white-space:nowrap!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-win-card>strong{min-height:0!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;display:flex!important;justify-content:flex-end!important;align-items:center!important;overflow:visible!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:3px!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto input{width:46px!important;height:auto!important;font-size:17px!important;font-weight:800!important;line-height:1!important;text-align:right!important;background:transparent!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto span{font-size:17px!important;font-weight:800!important;line-height:1!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-bet-card{order:3!important;grid-column:2!important;min-height:38px!important;height:38px!important;margin:0!important;padding:0!important;border-radius:16px!important;background:rgba(26,11,15,.54)!important;border:0!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-win-card>span{display:block!important;margin:0!important;color:rgba(255,255,255,.50)!important;font-size:11px!important;line-height:1!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;white-space:nowrap!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-win-card>strong{min-height:0!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;display:flex!important;justify-content:flex-end!important;align-items:center!important;overflow:visible!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:3px!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto input{width:46px!important;height:auto!important;font-size:17px!important;font-weight:800!important;line-height:1!important;text-align:right!important;background:transparent!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-auto span{font-size:17px!important;font-weight:800!important;line-height:1!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-bet-card{order:3!important;grid-column:2!important;min-height:38px!important;height:38px!important;margin:0!important;padding:0!important;border-radius:16px!important;background:rgba(26,11,15,.54)!important;border:0!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-bet-card>span{display:none!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-bet-card>strong{width:100%!important;height:38px!important;min-height:38px!important;margin:0!important;padding:0!important;border:0!important;border-radius:16px!important;background:transparent!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:1px!important;overflow:hidden!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-bet-card>strong::before{content:""!important;display:block!important;width:24px!important;height:24px!important;flex:0 0 24px!important;background:url('/app/api/uploaded-image/ton-icon.png') center/contain no-repeat!important;filter:drop-shadow(0 2px 8px rgba(0,0,0,.34))!important;opacity:.98!important;pointer-events:none!important}
html body:has(#ghostrun.active) #ghostrun [data-ghost-bet-input]{field-sizing:content!important;width:auto!important;min-width:4ch!important;max-width:7ch!important;flex:0 0 auto!important;height:36px!important;padding:0!important;font-size:16px!important;font-weight:900!important;letter-spacing:-.025em!important;text-align:left!important;background:transparent!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-move-button{display:flex!important;align-items:center!important;justify-content:center!important;height:38px!important;min-height:38px!important;margin:0!important;padding:0!important;border-radius:16px!important;border:0!important;background:rgba(26,11,15,.54)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;position:relative!important;overflow:hidden!important;touch-action:manipulation!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-move-button::before,html body:has(#ghostrun.active) #ghostrun .ghost-run-move-button::after{display:none!important;content:none!important;border:0!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-back-button{order:2!important;grid-column:1!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-forward-button{order:4!important;grid-column:3!important}
html body:has(#ghostrun.active) #ghostrun .ghost-run-main-button{order:5!important;grid-column:1 / 4!important;height:42px!important;border-radius:17px!important;font-size:15px!important;margin:0!important}
html body:has(#ghostrun.active) #ghostrun #ghostLive{order:6!important;grid-column:1 / 4!important;width:100%!important;margin:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important}
html body:has(#ghostrun.active) #ghostrun #ghostLive .crash-live-toggle{background:rgba(26,11,15,.54)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
html body:has(#ghostrun.active) #ghostrun #ghostLive .crash-live-list{max-height:none!important;overflow:visible!important;padding-right:0!important;scrollbar-width:none!important}
html body:has(#ghostrun.active) #ghostrun #ghostLive .crash-live-list::-webkit-scrollbar{display:none!important}
html body:has(#ghostrun.active) #ghostrun #ghostLive .crash-live-row{background:rgba(26,11,15,.54)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
#ghostrun .ghost-run-screen[data-ghost-state='movingForward'] .ghost-run-ghost{animation:ghostRunMoveBob .46s ease-in-out infinite alternate!important;filter:drop-shadow(0 0 16px rgba(255,255,255,.18))!important}
#ghostrun .ghost-run-screen[data-ghost-state='caught'] .ghost-run-ghost{animation:ghostRunGraveTransform 1.05s cubic-bezier(.18,.9,.18,1) both!important;opacity:1!important;filter:drop-shadow(0 0 22px rgba(255,255,255,.18)) drop-shadow(0 18px 26px rgba(0,0,0,.56))!important;background-position:center bottom!important;background-size:contain!important;background-repeat:no-repeat!important}
#ghostrun .ghost-run-screen[data-ghost-state='caught'] .ghost-run-ghost:before{content:''!important;position:absolute!important;inset:-22px!important;border-radius:50%!important;background:radial-gradient(circle,rgba(255,255,255,.30),rgba(255,255,255,.10) 28%,transparent 66%)!important;filter:blur(7px)!important;animation:ghostRunGraveFlash .72s ease-out both!important;pointer-events:none!important}
#ghostrun .ghost-run-screen[data-ghost-state='caught'] .ghost-run-ghost:after{content:''!important;position:absolute!important;left:50%!important;bottom:-10px!important;width:92px!important;height:18px!important;transform:translateX(-50%)!important;border-radius:50%!important;background:radial-gradient(ellipse,rgba(255,255,255,.22),transparent 70%)!important;filter:blur(4px)!important;animation:ghostRunGraveDust .9s ease-out both!important;pointer-events:none!important}
#ghostrun .ghost-run-result{display:flex!important;align-items:center!important;justify-content:center!important;gap:12px!important;background:rgba(255,255,255,.08)!important;background-image:linear-gradient(180deg,rgba(255,255,255,.12),rgba(255,255,255,.035))!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.16),0 22px 60px rgba(0,0,0,.28)!important;backdrop-filter:blur(2px) saturate(1.15)!important;-webkit-backdrop-filter:blur(2px) saturate(1.15)!important;padding:18px 14px!important;border-radius:24px!important;pointer-events:none!important;text-align:center!important}
#ghostrun .ghost-run-result button{display:none!important}
#ghostrun .ghost-run-result strong{display:inline!important;font-size:28px!important;font-weight:1000!important;color:#fff!important;text-shadow:0 10px 24px rgba(0,0,0,.52)!important;margin:0!important;line-height:1!important}
#ghostrun .ghost-run-result span{display:inline!important;font-size:20px!important;font-weight:900!important;color:rgba(255,255,255,.86)!important;text-shadow:0 8px 20px rgba(0,0,0,.44)!important;margin:0!important;line-height:1!important}
@keyframes ghostRunMoveBob{0%{margin-bottom:0}100%{margin-bottom:5px}}
@keyframes ghostRunGraveTransform{0%{opacity:1;transform:translate3d(0,0,0) scale(1) rotate(0);filter:drop-shadow(0 0 18px rgba(255,255,255,.22))}26%{opacity:.84;transform:translate3d(0,-14px,0) scale(1.08) rotate(-2deg)}48%{opacity:.18;transform:translate3d(0,0,0) scale(.62) rotate(3deg);filter:blur(4px)}49%{opacity:0;transform:translate3d(0,7px,0) scale(.45)}50%{opacity:0;transform:translate3d(0,6px,0) scale(.72)}72%{opacity:1;transform:translate3d(0,-16px,0) scale(1.08)}100%{opacity:1;transform:translate3d(0,-10px,0) scale(1)}}
@keyframes ghostRunGraveFlash{0%{opacity:0;transform:scale(.45)}40%{opacity:1;transform:scale(1.08)}100%{opacity:0;transform:scale(1.55)}}
@keyframes ghostRunGraveDust{0%{opacity:0;transform:translateX(-50%) scale(.2)}35%{opacity:.75;transform:translateX(-50%) scale(1)}100%{opacity:0;transform:translateX(-50%) scale(1.65)}}
</style>`;

  patched = patched.replace('<section id="ghostrun" class="view ghost-run-view" aria-label="Ghost Run">', '<section id="ghostrun" class="view ghost-run-view" aria-label="Ghost Run">' + crashCss);
  patched = patched.replace('<strong class="ghost-run-multiplier" data-ghost-multiplier>1.00x</strong>', '<strong class="ghost-run-multiplier" data-ghost-multiplier>1.00x</strong><span class="ghost-run-countdown" data-ghost-countdown>6.50s</span>');

  const crashScript = `<script>
(function(){
  var script=document.currentScript;
  var root=(script&&script.closest&&script.closest('#ghostrun'))||document.getElementById('ghostrun');
  if(!root)return;
  root.dataset.ghostReady=String(Date.now());

  var screen=root.querySelector('.ghost-run-screen');
  var ghost=root.querySelector('.ghost-run-ghost');
  var multiplierEl=root.querySelector('[data-ghost-multiplier]');
  var historyEl=root.querySelector('[data-ghost-history]');
  var countdownEl=root.querySelector('[data-ghost-countdown]');
  var betInput=root.querySelector('[data-ghost-bet-input]');
  var autoCashoutInput=root.querySelector('[data-ghost-auto-cashout]');
  var startButton=root.querySelector('[data-ghost-start]');
  var halfButton=root.querySelector('[data-ghost-back]');
  var doubleButton=root.querySelector('[data-ghost-forward]');
  var controls=root.querySelector('.ghost-run-controls');
  var ghostBox=document.getElementById('ghostLive');
  var result=root.querySelector('[data-ghost-result]');
  var resultTitle=root.querySelector('[data-ghost-result-title]');
  var resultDetail=root.querySelector('[data-ghost-result-detail]');
  var panels=[].slice.call(root.querySelectorAll('.ghost-run-background-panel'));

  if(halfButton){halfButton.textContent='1/2';halfButton.setAttribute('aria-label','Half bet')}
  if(doubleButton){doubleButton.textContent='2x';doubleButton.setAttribute('aria-label','Double bet')}
  if(controls&&startButton&&ghostBox&&ghostBox.parentElement!==controls)startButton.insertAdjacentElement('afterend',ghostBox);

  var socket=null,state=null,currentBet=null,reconnectTimer=0,reconnectAttempt=0;
  var serverOffsetMs=0,clockSynced=false,syncSentAt=0;
  var multiplier=1,position=18,backgroundOffset=0,raf=0;
  var betBusy=false,cashBusy=false,autoRequestedRound=-1,lastCrashSyncRound=-1,lastPreparedRound=-1;
  var graveUrl='';
  var liveRows=[],liveLoaded=false,liveUsersCache=null;

  function tonToNano(v){var n=parseFloat(String(v||'').replace(',','.'));return Number.isFinite(n)&&n>0?Math.floor(n*1e9):0}
  function nanoToTon(v){return Math.max(0,Math.floor(Number(v)||0))/1e9}
  function readBalance(){if(window.VexaTonBalance&&window.VexaTonBalance.read)return Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0));return Math.max(0,Math.floor(Number(root.dataset.walletBalanceNano||0)||0))}
  function setServerBalance(value){var balance=Math.max(0,Math.floor(Number(value)||0));root.dataset.walletBalanceNano=String(balance);if(window.VexaTonBalance&&window.VexaTonBalance.write){var before=readBalance();window.VexaTonBalance.write(balance,balance-before,false)}else window.dispatchEvent(new CustomEvent('vexa-ton-balance-sync',{detail:{tonBalanceNano:balance,deltaNano:0}}))}
  function initData(){try{return String(window.Telegram&&window.Telegram.WebApp&&window.Telegram.WebApp.initData||'')}catch(e){return ''}}
  function wsUrl(){var p=location.protocol==='https:'?'wss:':'ws:';return p+'//'+location.host+'/app/api/ghost-run/live?initData='+encodeURIComponent(initData())}
  function serverNow(){return Date.now()+serverOffsetMs}
  function connected(){return !!(socket&&socket.readyState===1)}
  function send(message){if(!connected())return false;try{socket.send(JSON.stringify(message));return true}catch(e){return false}}
  function requestSync(){if(!connected())return;syncSentAt=Date.now();send({type:'sync',clientSentAt:syncSentAt})}
  function clearReconnect(){if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=0}}
  function reconnectDelay(){return Math.min(10000,500*Math.pow(2,Math.min(reconnectAttempt++,4)))}
  function scheduleReconnect(){if(document.hidden||reconnectTimer||connected())return;reconnectTimer=setTimeout(function(){reconnectTimer=0;connect()},reconnectDelay())}
  function cssUrl(url){var clean=String(url||'').split("'").join('').split(')').join('').split('"').join('');return "url('"+clean+"')"}
  function cacheAsset(url){if(!url)return;try{var img=new Image();img.decoding='async';img.loading='eager';img.src=url}catch(e){}try{if('caches'in window)caches.open('ghost-run-assets-v1').then(function(c){c.match(url).then(function(hit){if(!hit)c.add(url).catch(function(){})})})}catch(e){}}
  function setBg(sel,url){var el=root.querySelector(sel);if(el&&url)el.style.setProperty('background-image',cssUrl(url),'important')}
  function loadAssets(){fetch('/app/api/ghost-run-assets',{cache:'force-cache'}).then(function(r){return r.ok?r.json():null}).then(function(j){var u=j&&j.urls;if(!u)return;Object.keys(u).forEach(function(k){cacheAsset(u[k])});graveUrl=u.ground||u.ghostidle||'';setBg('.ghost-run-background-panel-1',u.background);setBg('.ghost-run-background-panel-2',u.background2);setBg('.ghost-run-background-panel-3',u.background3);setBg('.ghost-run-background-panel-4',u.background4);setBg('.ghost-run-background-panel-5',u.background5);setBg('.ghost-run-background-panel-6',u.background6);setBg('.ghost-run-background-panel-copy',u.background);if(u.ghostidle){var st=document.getElementById('ghostRunCrashAssets');if(!st){st=document.createElement('style');st.id='ghostRunCrashAssets';document.head.appendChild(st)}st.textContent=["#ghostrun .ghost-run-ghost{background-image:"+cssUrl(u.ghostidle)+"!important;background-size:contain!important;background-position:center!important;background-repeat:no-repeat!important}","#ghostrun .ghost-run-screen[data-ghost-state='movingForward'] .ghost-run-ghost{background-image:"+cssUrl(u.ghostmove||u.ghostidle)+"!important}","#ghostrun .ghost-run-screen[data-ghost-state='caught'] .ghost-run-ghost{background-image:"+cssUrl(graveUrl||u.ghostidle)+"!important}"].join('\n')}}).catch(function(){})}

  function cleanText(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]})}
  function tonText(n){return Math.max(0,Number(n)||0).toFixed(2).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1')}
  function fallbackUsers(){return [{name:'Ari Stone',bets:[{amount:5,cashoutMultiplier:1.24}]},{name:'Mika',bets:[{amount:2.5,cashoutMultiplier:1.38}]},{name:'کیان مهر',bets:[{amount:6,cashoutMultiplier:1.19}]},{name:'Sasha',bets:[{amount:1.8,cashoutMultiplier:1.52}]},{name:'User 4821',bets:[{amount:.7,cashoutMultiplier:1.33}]},{name:'0xA91...F2',bets:[{amount:3.2,cashoutMultiplier:1.73}]},{name:'Lina',bets:[{amount:4,cashoutMultiplier:1.16}]},{name:'Amir',bets:[{amount:1.1,cashoutMultiplier:1.44}]}]}
  function pickBet(user,i){var bets=Array.isArray(user&&user.bets)?user.bets:[];if(!bets.length)return {amount:.1,cashoutMultiplier:1.35};var roundId=Number(state&&state.roundId)||0;return bets[Math.abs(roundId+i)%bets.length]}
  function prepareLive(){if(!state||lastPreparedRound===state.roundId)return;lastPreparedRound=state.roundId;function build(users){users=Array.isArray(users)&&users.length?users:fallbackUsers();liveRows=users.slice(0,24).map(function(u,i){var b=pickBet(u,i),second=Math.max(0,Math.min(6.5,Number(u.betSecond)||0));return {name:u.name||'Player',amount:Number(b.amount)||.1,target:Number(b.cashoutMultiplier)||1.4,betSecond:second,visible:second<=0,status:'bet',cashoutMultiplier:0}});renderLive()}if(liveLoaded&&liveUsersCache){build(liveUsersCache);return}fetch('/app/api/ghost-run-virtual-users',{cache:'no-store'}).then(function(r){return r.ok?r.json():null}).then(function(j){liveUsersCache=j&&Array.isArray(j.users)?j.users:fallbackUsers();liveLoaded=true;build(liveUsersCache)}).catch(function(){build(fallbackUsers())})}
  function currentUserRow(){if(!currentBet||!state||Number(currentBet.roundId)!==Number(state.roundId))return null;var u=null;try{u=window.Telegram&&window.Telegram.WebApp&&window.Telegram.WebApp.initDataUnsafe&&window.Telegram.WebApp.initDataUnsafe.user}catch(e){}var name=u?String([u.first_name,u.last_name].filter(Boolean).join(' ')||('@'+String(u.username||'').replace(/^@+/,''))||'You'):'You';return {name:name,amount:nanoToTon(currentBet.amountNano),status:currentBet.status,target:Number(currentBet.autoCashout)||999,cashoutMultiplier:Number(currentBet.cashoutMultiplier)||0,visible:true,real:true}}
  function visibleLiveRows(){var rows=liveRows.filter(function(r){return r.visible!==false}).slice();var me=currentUserRow();if(me)rows.unshift(me);return rows}
  function renderLive(){var list=document.getElementById('ghostLiveList'),total=document.getElementById('ghostLiveTotal');if(!list)return;var rows=visibleLiveRows(),sum=rows.reduce(function(s,r){return s+(Number(r.amount)||0)},0);if(total)total.textContent=tonText(sum)+' TON';if(!rows.length){list.innerHTML='<div class="crash-live-empty">No bets yet</div>';return}list.innerHTML=rows.sort(function(a,b){var rank={cashed:0,cashout:0,lost:1,crashed:1,placed:2,bet:2};var ra=rank[a.status]===undefined?3:rank[a.status],rb=rank[b.status]===undefined?3:rank[b.status];if(ra!==rb)return ra-rb;return Number(b.amount||0)-Number(a.amount||0)}).map(function(r){var cash=r.status==='cashed'||r.status==='cashout',lost=r.status==='lost'||r.status==='crashed';var cm=Number(r.cashoutMultiplier||r.target||1);var status=cash?'<span class="crash-live-mult">'+cleanText(cm.toFixed(2).replace(/\.00$/,'')+'×')+'</span>':(lost?'<span class="crash-live-lost">Lost</span>':'Bet');return '<div class="crash-live-row '+(cash?'cashout':lost?'crashed':'')+'"><span class="crash-live-user">'+cleanText(r.name)+'</span><span class="crash-live-amount">'+(cash?'<span class="crash-live-plus">+</span>':'')+cleanText(tonText(r.amount)+' TON')+'</span><span class="crash-live-status">'+status+'</span></div>'}).join('')}
  function bettingElapsed(){return state?Math.max(0,(serverNow()-Number(state.bettingStartedAt||0))/1000):0}
  function revealLive(force){var elapsed=bettingElapsed(),changed=false;liveRows.forEach(function(r){if(force&&!r.visible){r.visible=true;changed=true}else if(!r.visible&&elapsed>=Number(r.betSecond||0)){r.visible=true;changed=true}});if(changed)renderLive()}
  function updateLive(){var changed=false;liveRows.forEach(function(r){if(r.visible===false)return;if(r.status==='bet'&&Number(r.target)<=multiplier){r.status='cashout';r.cashoutMultiplier=Number(r.target);changed=true}});if(changed)renderLive()}
  function crashLive(){var changed=false;liveRows.forEach(function(r){if(!r.visible){r.visible=true;changed=true}if(r.status==='bet'){r.status='crashed';changed=true}});if(changed)renderLive()}

  function renderHistory(){if(!historyEl)return;var values=state&&Array.isArray(state.history)?state.history:[];historyEl.innerHTML=values.slice(0,18).map(function(v){return '<span>'+Number(v||1).toFixed(2).replace(/\.00$/,'')+'x</span>'}).join('');historyEl.scrollLeft=0}
  function setScreenState(value){if(screen)screen.setAttribute('data-ghost-state',value)}
  function showResult(title,detail){if(result)result.setAttribute('data-visible','1');if(resultTitle)resultTitle.textContent=title;if(resultDetail)resultDetail.textContent=detail}
  function hideResult(){if(result)result.removeAttribute('data-visible')}
  function readAutoCashout(){var n=parseFloat(String(autoCashoutInput&&autoCashoutInput.value||'').replace(',','.'));return Number.isFinite(n)&&n>=1.01?Math.floor(n*100)/100:0}
  function adjustBet(factor){if(!betInput||betInput.disabled)return;var value=parseFloat(String(betInput.value||'').replace(',','.'));if(!Number.isFinite(value)||value<=0)value=.1;value=Math.max(.01,Math.round(value*factor*100)/100);betInput.value=value.toFixed(2);hideResult()}
  function timeLeft(){if(!state||state.phase!=='betting')return 0;return Math.max(0,(Number(state.runningStartedAt||0)-serverNow())/1000)}
  function timeLeftText(){return timeLeft().toFixed(2)}
  function activeProfitText(){if(!currentBet)return '0.00';return nanoToTon(Math.max(0,Math.floor(Number(currentBet.amountNano||0)*multiplier)-Number(currentBet.amountNano||0))).toFixed(2)}
  function buttonText(){if(!state||!connected())return 'Connecting...';if(state.phase==='betting')return currentBet&&currentBet.status==='placed'?'Bet Placed · starts in '+timeLeftText()+'s':'Place Bet';if(state.phase==='running')return currentBet&&currentBet.status==='placed'?'Cash Out '+activeProfitText():(currentBet&&currentBet.status==='cashed'?'Cashed Out':'Running');return 'Next Round'}
  function render(){if(multiplierEl)multiplierEl.textContent=multiplier.toFixed(2)+'x';if(countdownEl)countdownEl.textContent=timeLeftText()+'s';if(ghost)ghost.style.left=position+'px';root.style.setProperty('--ghost-x',position+'px');root.style.setProperty('--ghost-bg-x',(-backgroundOffset).toFixed(1)+'px');panels.forEach(function(p){p.style.transform='translate3d('+(-backgroundOffset).toFixed(1)+'px,0,0)'});if(screen){screen.setAttribute('data-round-active',state&&state.phase==='running'?'1':'0');screen.setAttribute('data-ghost-phase',state?state.phase:'connecting')}if(betInput)betInput.disabled=!state||state.phase!=='betting'||!!currentBet||betBusy;if(autoCashoutInput)autoCashoutInput.disabled=!state||state.phase!=='betting'||!!currentBet||betBusy;if(startButton){var canBet=state&&state.phase==='betting'&&!currentBet&&!betBusy;var canCash=state&&state.phase==='running'&&currentBet&&currentBet.status==='placed'&&!cashBusy;startButton.disabled=!connected()||(!canBet&&!canCash);startButton.classList.toggle('cashout',!!canCash);startButton.classList.toggle('is-placed',!!(state&&state.phase==='betting'&&currentBet&&currentBet.status==='placed'));startButton.textContent=buttonText()}renderLive()}

  function applyState(next){if(!next||!Number.isFinite(Number(next.roundId)))return;var previousRound=state&&Number(state.roundId);state=next;if(!clockSynced&&Number.isFinite(Number(next.serverNow)))serverOffsetMs=Number(next.serverNow)-Date.now();if(previousRound!==Number(state.roundId)){if(currentBet&&Number(currentBet.roundId)!==Number(state.roundId))currentBet=null;autoRequestedRound=-1;lastCrashSyncRound=-1;hideResult();position=18;backgroundOffset=0;multiplier=1;prepareLive()}renderHistory();if(state.phase==='betting'){setScreenState('idle');revealLive(false)}else if(state.phase==='running'){setScreenState('movingForward');revealLive(true)}else{setScreenState('caught');crashLive();if(currentBet&&currentBet.status==='placed'&&lastCrashSyncRound!==state.roundId){lastCrashSyncRound=state.roundId;requestSync()}}render()}
  function applyBet(bet){currentBet=bet||null;if(currentBet&&state&&Number(currentBet.roundId)!==Number(state.roundId))currentBet=null;if(currentBet&&currentBet.status==='cashed'){var payout=nanoToTon(currentBet.payoutNano).toFixed(2),cm=Number(currentBet.cashoutMultiplier||1).toFixed(2);showResult('Won',payout+' TON · '+cm+'x')}else if(currentBet&&currentBet.status==='lost'&&state&&state.phase==='ended'){showResult('You Lost',nanoToTon(currentBet.amountNano).toFixed(2)+' TON · crashed at '+Number(state.crashMultiplier||state.multiplier||1).toFixed(2)+'x')}render()}
  function handleMessage(event){var msg=null;try{msg=JSON.parse(String(event.data||''))}catch(e){return}if(!msg)return;if(msg.type==='ghost-state'){applyState(msg.state);return}if(msg.type==='ghost-sync'){var sent=Number(msg.clientSentAt);if(Number.isFinite(sent)&&sent>0){var received=Date.now(),mid=sent+(received-sent)/2;serverOffsetMs=Number(msg.state&&msg.state.serverNow||received)-mid;clockSynced=true}else if(!clockSynced&&msg.state)serverOffsetMs=Number(msg.state.serverNow||Date.now())-Date.now();applyState(msg.state);if(Number.isFinite(Number(msg.tonBalanceNano)))setServerBalance(msg.tonBalanceNano);applyBet(msg.bet);return}if(msg.type==='ghost-bet'){betBusy=false;applyState(msg.state);if(Number.isFinite(Number(msg.tonBalanceNano)))setServerBalance(msg.tonBalanceNano);applyBet(msg.bet);hideResult();render();return}if(msg.type==='ghost-cashout'){cashBusy=false;applyState(msg.state);if(Number.isFinite(Number(msg.tonBalanceNano)))setServerBalance(msg.tonBalanceNano);applyBet(msg.bet);return}if(msg.type==='ghost-error'){betBusy=false;cashBusy=false;showResult('Could not complete',String(msg.error||'Ghost Run action failed.'));render()}}

  function connect(){if(socket&&(socket.readyState===0||socket.readyState===1))return;clearReconnect();if(!initData()){showResult('Connection required','Open Ghost Run inside Telegram.');render();return}try{socket=new WebSocket(wsUrl())}catch(e){socket=null;render();scheduleReconnect();return}socket.addEventListener('open',function(){clearReconnect();reconnectAttempt=0;requestSync();render()});socket.addEventListener('message',handleMessage);socket.addEventListener('close',function(){socket=null;betBusy=false;cashBusy=false;render();scheduleReconnect()});socket.addEventListener('error',function(){try{socket&&socket.close()}catch(e){}render()})}
  function placeBet(){if(!state||state.phase!=='betting'||currentBet||betBusy)return;var amount=tonToNano(betInput&&betInput.value||0);if(amount<=0){showResult('Invalid Bet','Enter a TON amount.');return}if(readBalance()<amount){showResult('Not enough balance','Add TON before placing this bet.');return}betBusy=true;hideResult();if(!send({type:'bet',amountNano:amount,autoCashout:readAutoCashout()})){betBusy=false;scheduleReconnect()}render()}
  function cashOut(){if(!state||state.phase!=='running'||!currentBet||currentBet.status!=='placed'||cashBusy)return;cashBusy=true;if(!send({type:'cashout'})){cashBusy=false;scheduleReconnect()}render()}

  function tick(){if(state){var now=serverNow();if(state.phase==='betting'){multiplier=1;position=18;backgroundOffset=0;revealLive(false)}else if(state.phase==='running'){var t=Math.max(0,(now-Number(state.runningStartedAt||now))/1000);multiplier=Math.max(1,Math.floor((1+t*.038+Math.pow(t,1.12)*.020)*100)/100);var width=Math.max(1,(screen&&screen.clientWidth)||window.innerWidth||320),center=Math.max(18,width*.5-42),walkSpeed=25;position=Math.min(center,18+t*walkSpeed);backgroundOffset=Math.max(0,t-((center-18)/walkSpeed))*17;updateLive();var auto=Number(currentBet&&currentBet.autoCashout||0);if(currentBet&&currentBet.status==='placed'&&auto>=1.01&&multiplier>=auto&&autoRequestedRound!==state.roundId){autoRequestedRound=state.roundId;cashOut()}}else{multiplier=Math.max(1,Number(state.crashMultiplier||state.multiplier||multiplier||1));position=Math.max(position,18)}}render();raf=requestAnimationFrame(tick)}

  var ghostToggle=document.getElementById('ghostLiveToggle');if(ghostToggle&&ghostBox)ghostToggle.onclick=function(){var open=!ghostBox.classList.contains('open');ghostBox.classList.toggle('open',open);ghostToggle.setAttribute('aria-expanded',open?'true':'false')};
  if(halfButton)halfButton.addEventListener('click',function(){adjustBet(.5)});
  if(doubleButton)doubleButton.addEventListener('click',function(){adjustBet(2)});
  if(startButton)startButton.addEventListener('click',function(){if(state&&state.phase==='running')cashOut();else placeBet()});
  if(betInput)betInput.addEventListener('input',hideResult);
  if(autoCashoutInput)autoCashoutInput.addEventListener('input',hideResult);
  document.addEventListener('visibilitychange',function(){if(document.hidden){clearReconnect();return}if(connected())requestSync();else connect()});
  window.addEventListener('online',function(){clearReconnect();connect()});
  window.addEventListener('focus',function(){if(connected())requestSync();else connect()});
  window.addEventListener('pageshow',function(){if(connected())requestSync();else connect()});

  loadAssets();
  renderHistory();
  connect();
  raf=requestAnimationFrame(tick);
})();
`;
  patched = replaceBlock(patched, '<script>', '</script>', crashScript);
  return patched;
}

export const GHOST_RUN_SECTION = patchGhostRunSection(RAW_GHOST_RUN_SECTION);