export const ACTIVITY_CORE_SCRIPT = `
(function(){
  var tg=window.Telegram&&window.Telegram.WebApp;
  var user=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};
  var lastPayload='';
  var lastSent=0;
  var lastSection='';
  var resetHandled=false;
  function activeSection(){var active=document.querySelector('.view.active');return active&&active.id?active.id:'home'}
  function userId(){return String(user.id||localStorage.getItem('ownerId')||'').trim()}
  function resetKey(){var id=userId();return id?'vexa:client-reset-version:'+id:''}
  function resetAllKey(){return 'vexa:client-reset-version:all'}
  function applyServerTonBalance(value){var balance=Math.max(0,Math.floor(Number(value)||0));if(!Number.isFinite(balance))return;try{window.dispatchEvent(new CustomEvent('vexa-ton-balance-sync',{detail:{tonBalanceNano:balance}}))}catch(e){}}
  function needsReset(j){var userReset=String(j&&j.resetVersion||'');var allReset=String(j&&j.resetAllVersion||'');var current='',currentAll='';try{current=localStorage.getItem(resetKey())||'';currentAll=localStorage.getItem(resetAllKey())||''}catch(e){}return Boolean((userReset&&userReset!==current)||(allReset&&allReset!==currentAll))}
  function clearUserCache(j){if(resetHandled)return;resetHandled=true;var id=userId();var userReset=String(j&&j.resetVersion||'');var allReset=String(j&&j.resetAllVersion||'');try{var keepOwner=localStorage.getItem('ownerId')||'';Object.keys(localStorage).forEach(function(k){if(k==='ownerId')return;if(/^vexa:/.test(k)||/^vexa/.test(k)||k.indexOf(id)>=0)localStorage.removeItem(k)});if(keepOwner)localStorage.setItem('ownerId',keepOwner);if(userReset)localStorage.setItem(resetKey(),userReset);if(allReset)localStorage.setItem(resetAllKey(),allReset)}catch(e){}try{sessionStorage.clear()}catch(e){}try{if('caches' in window)caches.keys().then(function(keys){keys.forEach(function(k){if(/^vexa/i.test(k))caches.delete(k)})})}catch(e){}try{window.dispatchEvent(new CustomEvent('vexa-user-cache-reset',{detail:{userId:id}}))}catch(e){}setTimeout(function(){try{location.reload()}catch(e){}},80)}
  function ensureBanOverlay(){var el=document.getElementById('vexaBanOverlay');if(el)return el;var st=document.getElementById('vexaBanOverlayStyle');if(!st){st=document.createElement('style');st.id='vexaBanOverlayStyle';st.textContent='#vexaBanOverlay{position:fixed;left:14px;right:14px;top:calc(12px + env(safe-area-inset-top));z-index:2147483000;padding:12px 14px;border:1px solid rgba(255,255,255,.28);border-radius:20px;background:transparent!important;color:#fff;text-align:center;font:800 13px/1.35 system-ui,-apple-system,Segoe UI,sans-serif;letter-spacing:.01em;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);box-shadow:none;pointer-events:auto}.vexa-user-banned main,.vexa-user-banned nav,.vexa-user-banned .tab,.vexa-user-banned button:not(#vexaBanOverlay *){pointer-events:none!important;filter:grayscale(.35);opacity:.45}';document.head.appendChild(st)}el=document.createElement('div');el.id='vexaBanOverlay';el.setAttribute('role','alert');el.textContent='Your access to all sections is blocked.';document.body.appendChild(el);return el}
  function applyBanState(banned){document.documentElement.classList.toggle('vexa-user-banned',!!banned);document.body.classList.toggle('vexa-user-banned',!!banned);if(banned)ensureBanOverlay();else{var el=document.getElementById('vexaBanOverlay');if(el)el.remove()}}
  function sendActivity(force){if(document.hidden)return;var section=activeSection();var body={userId:userId(),username:user.username||null,firstName:user.first_name||null,section:section};if(!body.userId)return;var encoded=JSON.stringify(body);var now=Date.now();var sectionChanged=section!==lastSection;if(!force&&!sectionChanged&&encoded===lastPayload&&now-lastSent<300000)return;lastPayload=encoded;lastSent=now;lastSection=section;fetch('/app/api/activity',{method:'POST',headers:{'content-type':'application/json'},body:encoded,keepalive:true}).then(function(r){return r.json().catch(function(){return null})}).then(function(j){if(j&&j.ok){if(needsReset(j)){clearUserCache(j);return}applyBanState(!!j.banned);if(j.banned)return;if(j.tonBalanceNano!==undefined)applyServerTonBalance(j.tonBalanceNano);if(j.winChancePercent!==undefined&&window.VexaGameChance&&window.VexaGameChance.set)window.VexaGameChance.set(j.winChancePercent)}}).catch(function(){});}
  function smartSync(){sendActivity(false)}
  document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('button');if(b&&(b.getAttribute('data-action')||b.getAttribute('data-tab')||b.closest('.tabs')))setTimeout(function(){smartSync();},120);},true);
  document.addEventListener('visibilitychange',function(){if(!document.hidden)sendActivity(true)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){sendActivity(true)});else sendActivity(true)
})();
`;
