export const CRASH_LIVE_D1_SCRIPT = `
(function(){
  var UNIT=1000000000, WAIT_BETWEEN_MS=9000, CRASH_HOLD_MS=2200, MAX_RUN_MS=18000, DAY_MS=86400000, HOUSE_EDGE=.04;
  var cache=null, cacheRound=0, lastFetch=0, syncing=false, localBet=null, lastRendered='';
  function ton(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(4).replace(/\\.0+$/,'').replace(/(\\.\\d*?)0+$/,'$1')}
  function betTon(n,isVirtual){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;if(!isVirtual)return ton(n);if(Math.abs(v-Math.round(v))<.000001)return String(Math.round(v));if(Math.abs(v*10-Math.round(v*10))<.000001)return String(Math.round(v*10)/10);return String(Math.round(v*100)/100).replace(/\\.0+$/,'')}
  function nano(v){return Math.max(0,Math.floor((Number(String(v||'').replace(',','.'))||0)*UNIT))}
  function tgUser(){var tg=window.Telegram&&window.Telegram.WebApp;var u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;var id=String((u&&u.id)||localStorage.getItem('ownerId')||'local').trim();var name=u?String(u.first_name||u.last_name||'User'):'You';return{id:id||'local',name:name||'User'}}
  function cleanText(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
  function seeded(seed){var x=Math.sin(seed*9301.777+49297.31)*233280;return x-Math.floor(x)}
  function roundStop(roundId){var u=Math.max(.000001,seeded(roundId));var raw=(1-HOUSE_EDGE)/u;if(seeded(roundId+17)<HOUSE_EDGE)raw=1;return Math.max(1,Math.min(60,Math.floor(raw*100)/100))}
  function multAt(seconds){return 1+seconds*.078+seconds*seconds*.0175}
  function stopTime(stop){var target=Math.max(1,Number(stop)||1),lo=0,hi=MAX_RUN_MS;for(var i=0;i<24;i++){var mid=(lo+hi)/2;if(multAt(mid/1000)>=target)hi=mid;else lo=mid}return hi}
  function cycleFor(id){var stop=roundStop(id);var runMs=Math.max(1100,Math.min(MAX_RUN_MS,stopTime(stop)));return{id:id,stop:stop,runMs:runMs,cycleMs:runMs+WAIT_BETWEEN_MS}}
  var schedule=null;
  function locate(now){var dayStart=Math.floor(now/DAY_MS)*DAY_MS,baseId=Math.floor(dayStart/1000);if(!schedule||schedule.dayStart!==dayStart||now<schedule.start){schedule={dayStart:dayStart,baseId:baseId,localId:0,start:dayStart,cycle:cycleFor(baseId)}}while(now>=schedule.start+schedule.cycle.cycleMs){schedule.start+=schedule.cycle.cycleMs;schedule.localId++;schedule.cycle=cycleFor(schedule.baseId+schedule.localId)}var c=schedule.cycle,local=now-schedule.start,running=local<c.runMs,waitElapsed=running?0:local-c.runMs;return{id:c.id,running:running,waiting:!running,inCrashHold:!running&&waitElapsed<CRASH_HOLD_MS}}
  function liveRound(state){return state.running||state.inCrashHold?state.id:state.id+1}
  async function post(path,body){try{return await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),keepalive:true}).then(function(r){return r.json().catch(function(){return null})})}catch(e){return null}}
  async function pull(roundId,force){var now=Date.now();if(syncing||(!force&&cacheRound===roundId&&now-lastFetch<900))return;syncing=true;lastFetch=now;try{var j=await fetch('/app/api/crash-live?roundId='+encodeURIComponent(String(roundId)),{cache:'no-store'}).then(function(r){return r.json().catch(function(){return null})});if(j&&j.ok){cache=j;cacheRound=roundId;render(j)}}catch(e){}syncing=false}
  function render(j){var list=document.getElementById('crashLiveList'),total=document.getElementById('crashLiveTotal');if(!list||!j||!j.ok)return;if(total)total.textContent=ton(j.totalNano)+' TON';var bets=j.bets||[];var html='';if(!bets.length)html='<div class="crash-live-empty">No bets yet</div>';else html=bets.map(function(b){var cash=b.status==='cashout';var crash=b.status==='crashed';var status=cash?(ton(b.payoutNano)+' TON'):(crash?'Crashed':'Bet');var cls=cash?'cashout':(crash?'crashed':'');return '<div class="crash-live-row '+cls+'"><span class="crash-live-user">'+cleanText(b.user)+'</span><span class="crash-live-amount">'+betTon(b.amountNano,b.isVirtual)+' TON</span><span class="crash-live-status">'+cleanText(status)+'</span></div>'}).join('');if(html!==lastRendered){list.innerHTML=html;lastRendered=html}}
  function frame(){var st=locate(Date.now()),rid=liveRound(st);pull(rid,false);if(cache&&cacheRound===rid)render(cache);requestAnimationFrame(frame)}
  function bind(){document.addEventListener('click',function(ev){var btn=ev.target&&ev.target.closest&&ev.target.closest('button');if(!btn)return;var st=locate(Date.now()),u=tgUser();if(btn.id==='crashStart'){setTimeout(function(){var start=document.getElementById('crashStart');if(!start||start.textContent!=='Bet Placed')return;var amount=nano((document.getElementById('crashAmount')||{}).value);var rid=liveRound(locate(Date.now()));localBet={roundId:rid,userId:u.id,amount:amount};post('/app/api/crash-live/bet',{roundId:rid,userId:u.id,username:u.name,amountNano:amount}).then(function(){pull(rid,true)})},60)}if(btn.id==='crashCashout'&&localBet){var multText=(document.getElementById('crashMultiplier')||{}).textContent||'1';var m=Number(String(multText).replace('x',''))||1;var rid=localBet.roundId;post('/app/api/crash-live/cashout',{roundId:rid,userId:u.id,multiplier:m}).then(function(){pull(rid,true)});localBet=null}},true);setInterval(function(){var st=locate(Date.now());if(localBet&&st.id>localBet.roundId){post('/app/api/crash-live/crash',{roundId:localBet.roundId,userId:localBet.userId});localBet=null}pull(liveRound(st),false)},1000);requestAnimationFrame(frame)}
  window.VexaCrashLiveD1={load:function(roundId){return pull(roundId,true)},postBet:function(roundId,amountNano){var u=tgUser();return post('/app/api/crash-live/bet',{roundId:roundId,userId:u.id,username:u.name,amountNano:amountNano})},postCashout:function(roundId,multiplier){var u=tgUser();return post('/app/api/crash-live/cashout',{roundId:roundId,userId:u.id,multiplier:multiplier})},postCrash:function(roundId){var u=tgUser();return post('/app/api/crash-live/crash',{roundId:roundId,userId:u.id})}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;
