export const CRASH_CONTROLS_MODERN_STYLES = `
#crash .crash-controls{position:relative!important;margin:0 2px!important;border:0!important;outline:0!important;border-radius:30px!important;background:transparent!important;box-shadow:none!important;padding:13px!important;display:grid!important;gap:11px!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;overflow:visible!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}
#crash .crash-control-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;align-items:stretch!important}
#crash .crash-field{min-height:74px!important;border:0!important;outline:0!important;border-radius:20px!important;background:transparent!important;padding:11px 10px!important;text-align:left!important;color:#fff!important;box-shadow:none!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important;margin:0!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important}
#crash .crash-field small,#crash .crash-label{display:block!important;color:rgba(255,255,255,.56)!important;font-size:12px!important;font-weight:500!important;letter-spacing:0!important;text-transform:none!important;white-space:nowrap!important;text-shadow:none!important;line-height:1.1!important}
#crash .crash-field b{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:6px!important;margin-top:10px!important;font-size:20px!important;font-weight:600!important;letter-spacing:-.025em!important;font-variant-numeric:tabular-nums lining-nums!important;white-space:nowrap!important;color:rgba(255,255,255,.96)!important;line-height:1.05!important}
#crash .crash-field i{font-style:normal!important;font-size:15px!important;color:rgba(255,255,255,.58)!important;font-weight:500!important}
#crash .crash-auto-field{margin-top:0!important}
#crash .crash-auto{display:flex!important;align-items:baseline!important;justify-content:flex-start!important;gap:2px!important;width:100%!important;height:auto!important;min-height:0!important;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#crash .crash-auto input{width:100%!important;min-width:0!important;height:auto!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:rgba(255,255,255,.96)!important;-webkit-text-fill-color:rgba(255,255,255,.96)!important;text-align:left!important;font:inherit!important;font-size:20px!important;font-weight:600!important;letter-spacing:-.025em!important;line-height:1.05!important;box-shadow:none!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-auto input::-webkit-outer-spin-button,#crash .crash-auto input::-webkit-inner-spin-button,#crash .crash-bet-main input::-webkit-outer-spin-button,#crash .crash-bet-main input::-webkit-inner-spin-button{appearance:none!important;-webkit-appearance:none!important;margin:0!important}
#crash .crash-auto span{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:0!important;color:rgba(255,255,255,.80)!important;font-size:19px!important;font-weight:500!important;line-height:1!important}
#crash .crash-bet{display:grid!important;grid-template-columns:.68fr minmax(0,1.55fr) .68fr!important;gap:8px!important;align-items:center!important}
#crash .crash-bet button,#crash .crash-bet-main,#crash .crash-primary,#crash .crash-secondary{border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;box-shadow:none!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;text-shadow:none!important;font-family:inherit!important;font-weight:600!important;letter-spacing:0!important}
#crash .crash-bet button,#crash .crash-bet-main{height:48px!important;border-radius:18px!important;font-size:16px!important}
#crash .crash-bet-main{display:flex!important;align-items:center!important;justify-content:center!important;padding:0 4px!important;min-width:0!important}
#crash .crash-bet-main input{width:100%!important;min-width:0!important;height:48px!important;border:0!important;outline:0!important;background:transparent!important;color:rgba(255,255,255,.98)!important;-webkit-text-fill-color:rgba(255,255,255,.98)!important;text-align:center!important;font-size:22px!important;font-weight:600!important;letter-spacing:-.03em!important;line-height:1!important;box-shadow:none!important;padding:0!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:9px!important;margin-top:0!important}
#crash .crash-primary,#crash .crash-secondary{height:60px!important;border-radius:999px!important;font-size:17px!important;transition:transform .18s ease,opacity .18s ease!important}
#crash .crash-primary{font-weight:650!important;color:#fff!important;-webkit-text-fill-color:#fff!important}
#crash .crash-secondary{color:rgba(255,255,255,.86)!important;-webkit-text-fill-color:rgba(255,255,255,.86)!important}
#crash .crash-primary:not(:disabled):active,#crash .crash-secondary:not(:disabled):active,#crash .crash-bet button:active{transform:scale(.975)!important}
#crash .crash-primary:disabled,#crash .crash-secondary:disabled{opacity:.46!important;transform:scale(.985)!important;filter:none!important}
#crash .crash-history{display:flex!important;gap:6px!important;overflow-x:auto!important;overflow-y:hidden!important;margin-top:0!important;min-height:30px!important;padding:0!important;scrollbar-width:none!important;visibility:visible!important;opacity:1!important}
#crash .crash-history::-webkit-scrollbar{display:none!important}
#crash .crash-history span{flex:0 0 auto!important;border:0!important;border-radius:999px!important;padding:7px 10px!important;font-size:11px!important;font-weight:500!important;letter-spacing:0!important;color:rgba(255,255,255,.86)!important;background:transparent!important;box-shadow:none!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important}
#crash .crash-live{border-radius:30px!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:14px!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;overflow:hidden!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}
#crash .crash-live-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:10px!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:500!important;letter-spacing:0!important;text-transform:none!important}
#crash .crash-live-head b{color:rgba(255,255,255,.90)!important;font-size:13px!important;font-weight:600!important;letter-spacing:0!important;text-transform:none!important}
#crash .crash-live-list{display:grid!important;gap:6px!important;max-height:792px!important;overflow-y:auto!important;overflow-x:hidden!important;padding-right:2px!important;scrollbar-width:thin!important;scrollbar-color:rgba(255,255,255,.18) transparent!important}
#crash .crash-live-list::-webkit-scrollbar{width:4px!important;display:block!important}
#crash .crash-live-list::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18)!important;border-radius:999px!important}
#crash .crash-live-empty{font-size:12px!important;font-weight:500!important;color:rgba(255,255,255,.45)!important;padding:14px 0!important;text-align:center!important}
#crash .crash-live-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto auto!important;align-items:center!important;gap:8px!important;min-height:34px!important;border-radius:17px!important;background:transparent!important;border:0!important;outline:0!important;box-shadow:none!important;color:#fff!important;padding:2px 10px!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important}
#crash .crash-live-user{min-width:0!important;font-size:12px!important;font-weight:600!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;color:rgba(255,255,255,.90)!important}
#crash .crash-live-amount{font-size:11px!important;font-weight:500!important;color:rgba(255,255,255,.62)!important;white-space:nowrap!important}
#crash .crash-live-status{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:5px!important;font-size:11px!important;font-weight:600!important;color:rgba(255,255,255,.82)!important;white-space:nowrap!important}
#crash .crash-live-win{color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;font-size:12px!important;font-weight:650!important;font-variant-numeric:tabular-nums lining-nums!important;text-shadow:0 0 14px rgba(120,255,179,.16)!important}
#crash .crash-live-row.cashout .crash-live-status{color:#78ffb3!important}
#crash .crash-live-row.crashed .crash-live-status{color:rgba(255,140,160,.86)!important}
@media(max-width:380px){#crash .crash-controls{padding:11px!important}#crash .crash-control-grid{gap:6px!important}#crash .crash-field{padding:10px 8px!important}#crash .crash-field small,#crash .crash-label{font-size:10.5px!important}#crash .crash-field b,#crash .crash-auto input,#crash .crash-auto span{font-size:17px!important}#crash .crash-primary,#crash .crash-secondary{font-size:15px!important}}
`;
