export const CRASH_BREAK_FX_SCRIPT = `
(function(){
  var audioCtx=null, master=null, musicGain=null, delayNode=null, feedback=null, musicNodes=[], musicOn=false, lastState='idle', crashedLock=false, lastStartKey='', timer=null, step=0;
  function q(id){return document.getElementById(id)}
  function active(){var c=q('crash');return !!(c&&c.classList.contains('active'))}
  function getAudio(){var C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioCtx){audioCtx=new C();master=audioCtx.createGain();master.gain.value=.95;master.connect(audioCtx.destination)}return audioCtx}
  function unlock(){var ctx=getAudio();if(!ctx)return null;if(ctx.state==='suspended')ctx.resume().catch(function(){});return ctx}
  function canPlay(){return !!(audioCtx&&audioCtx.state==='running')}
  function stopMusic(){if(!musicOn)return;musicOn=false;if(timer){clearInterval(timer);timer=null}var ctx=audioCtx;if(musicGain&&ctx){try{musicGain.gain.cancelScheduledValues(ctx.currentTime);musicGain.gain.setTargetAtTime(0,ctx.currentTime,.06)}catch(e){}}musicNodes.forEach(function(n){try{n.stop((ctx?ctx.currentTime:0)+.16)}catch(e){}try{n.disconnect()}catch(e){}});musicNodes=[];step=0;delayNode=null;feedback=null}
  function bell(freq,when,len,vol,type,out){var ctx=audioCtx;if(!ctx||!canPlay())return;var o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=type||'triangle';o.frequency.setValueAtTime(freq,when);o.frequency.exponentialRampToValueAtTime(freq*.985,when+len);f.type='bandpass';f.frequency.setValueAtTime(freq*2.15,when);f.Q.value=1.65;g.gain.setValueAtTime(.001,when);g.gain.linearRampToValueAtTime(vol,when+.01);g.gain.exponentialRampToValueAtTime(.001,when+len);o.connect(f);f.connect(g);g.connect(out||master);if(delayNode)g.connect(delayNode);o.start(when);o.stop(when+len+.035)}
  function melody(){if(!musicOn||!canPlay()||!musicGain)return;var ctx=audioCtx,t=ctx.currentTime;var a=[587.33,523.25,466.16,392,440,349.23,392,466.16,523.25,440,392,293.66,349.23,392,466.16,587.33];var f=a[step%a.length];bell(f,t,.22,.20,step%5===0?'sine':'triangle',musicGain);if(step%4===1)bell(f*1.5,t+.09,.15,.065,'sine',musicGain);if(step%2===0)bell(f/2,t+.015,.40,.055,'sine',musicGain);step++}
  function startSound(){var ctx=unlock();if(!ctx||!canPlay())return;var t=ctx.currentTime;bell(587.33,t,.16,.18,'sine',master);bell(466.16,t+.06,.18,.15,'triangle',master);bell(293.66,t+.13,.20,.12,'sine',master)}
  function startMusic(){if(musicOn||!active())return;var ctx=unlock();if(!ctx||!canPlay())return;musicOn=true;musicGain=ctx.createGain();musicGain.gain.setValueAtTime(0,ctx.currentTime);musicGain.gain.linearRampToValueAtTime(.50,ctx.currentTime+.22);musicGain.connect(master);delayNode=ctx.createDelay(.7);delayNode.delayTime.value=.285;feedback=ctx.createGain();feedback.gain.value=.30;delayNode.connect(feedback);feedback.connect(delayNode);delayNode.connect(musicGain);var drone=ctx.createOscillator(),dg=ctx.createGain(),df=ctx.createBiquadFilter();drone.type='sine';drone.frequency.value=73.42;dg.gain.value=.065;df.type='lowpass';df.frequency.value=360;drone.connect(dg);dg.connect(df);df.connect(musicGain);drone.start();musicNodes.push(drone,dg,df);var pulse=function(){if(!musicOn||!audioCtx||!musicGain)return;var tt=audioCtx.currentTime;try{musicGain.gain.cancelScheduledValues(tt);musicGain.gain.setValueAtTime(.36,tt);musicGain.gain.linearRampToValueAtTime(.52,tt+.09);musicGain.gain.linearRampToValueAtTime(.38,tt+.30)}catch(e){}};melody();timer=setInterval(function(){pulse();melody()},285)}
  function burst(ctx,delay,dur,gainVal){if(!canPlay())return;var b=ctx.createBuffer(1,Math.floor(ctx.sampleRate*dur),ctx.sampleRate),d=b.getChannelData(0);for(var i=0;i<d.length;i++){var t=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-t,3)}var s=ctx.createBufferSource();s.buffer=b;var f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=850+Math.random()*1000;var g=ctx.createGain();g.gain.setValueAtTime(gainVal,ctx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+dur);s.connect(f);f.connect(g);g.connect(master);s.start(ctx.currentTime+delay)}
  function crackSound(){var ctx=unlock();if(!ctx||!canPlay())return;burst(ctx,0,.08,.18);burst(ctx,.04,.06,.11);bell(146.83,ctx.currentTime,.20,.075,'triangle',master)}
  function triggerBreak(){var n=q('crashMultiplier');if(!n)return;n.setAttribute('data-crash-text',n.textContent||'');n.classList.remove('crash-broken');void n.offsetWidth;n.classList.add('crash-broken');crackSound()}
  function state(){if(!active())return 'inactive';var label=q('crashNextRound'),txt=String((label&&label.textContent)||'');if(/Crashed/i.test(txt))return 'crashed';if(/Round starts/i.test(txt))return 'waiting';return 'running'}
  function roundKey(){var n=q('crashMultiplier');return String((n&&n.textContent)||'')+'|'+String(Date.now()).slice(0,-3)}
  function sync(){unlock();var s=state(),n=q('crashMultiplier');if(s==='inactive'){stopMusic();lastState='inactive';crashedLock=false;return}if(s==='running'){crashedLock=false;if(n)n.classList.remove('crash-broken');if(lastState!=='running'){var k=roundKey();if(k!==lastStartKey&&canPlay()){lastStartKey=k;startSound()}}startMusic()}else stopMusic();if(s==='crashed'&&!crashedLock){crashedLock=true;triggerBreak()}if(s==='waiting'&&lastState==='crashed')crashedLock=true;if(s==='waiting'&&n)n.classList.remove('crash-broken');lastState=s}
  function unlockAndSync(){unlock();setTimeout(sync,30);setTimeout(sync,180);setTimeout(sync,420);setTimeout(sync,800)}
  document.addEventListener('pointerdown',unlockAndSync,true);document.addEventListener('touchstart',unlockAndSync,true);document.addEventListener('click',unlockAndSync,true);setInterval(sync,180);
})();
`;
