export const CRASH_SCRIPT = `
(function(){
  var UNIT=1000000000, MIN_BET_NANO=10000000, HOUSE_EDGE=.04, WAIT_BETWEEN_MS=9000, CRASH_HOLD_MS=2200, MAX_RUN_MS=34000, DAY_MS=86400000;
  var activeBet=null, settledRoundId=null, currentRoundId=-1, current=1, chartCurrent=1, lastDraw=0, lastProgress=0, lastHistoryId=null, canvasCache=null, ctxCache=null, scheduleCache=null, crashFrame=0, crashIdleTimer=0, roundEndSignalId=null;
  function q(id){return document.getElementById(id)}
  function show(text){var n=q('toast');if(!n)return;n.textContent=text;n.style.display='block';setTimeout(function(){n.style.display='none'},2200)}
  function balance(){return window.VexaTonBalance?Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0)):0}
  function change(delta){if(window.VexaTonBalance)window.VexaTonBalance.add(Math.floor(Number(delta)||0));else window.dispatchEvent(new CustomEvent('vexa-ton-balance-game-change',{detail:{deltaNano:Math.floor(Number(delta)||0)}}))}
  function toNano(value){return Math.max(0,Math.floor((Number(String(value||'').replace(/,/g,'.'))||0)*UNIT))}
  function toTon(nano){var v=Math.max(0,Math.floor(Number(nano)||0))/UNIT;return v.toFixed(2)}
  function normalizeAmount(){var input=q('crashAmount');var n=toNano(input&&input.value);if(n<MIN_BET_NANO)n=MIN_BET_NANO;if(input){input.setAttribute('step','0.01');input.setAttribute('inputmode','decimal');input.value=toTon(n)}return n}
  function normalizeAutoCashout(){var input=q('crashAutoCashout');if(!input)return 0;var v=Number(String(input.value||'').replace(/,/g,'.'))||0;if(v>0&&v<1.01)v=1.01;if(v>200)v=200;if(input.value&&String(input.value)!==String(v))input.value=v.toFixed(2).replace(/\.00$/,'');return v>=1.01?v:0}
  function fmt(v){return Math.max(1,Number(v)||1).toFixed(2)+'x'}
  function status(text){var n=q('crashStatus');if(n)n.textContent=text}
  function mult(v){var text=fmt(v),n=q('crashMultiplier'),p=q('crashPanelMultiplier');if(n)n.textContent=text;if(p)p.textContent=text}
  function nextLabel(text){var n=q('crashNextRound');if(n)n.textContent=text}
  function setCountdown(text,hide){var box=q('crashStarting'),n=q('crashCountdown');if(n)n.textContent=text;if(box)box.classList.toggle('hidden',!!hide)}
  function setTotal(seconds){var n=q('crashTotalTime');if(n)n.textContent='Total '+Math.max(0,Math.floor(seconds))+'s'}
  function seeded(seed){var x=Math.sin(seed*9301.777+49297.31)*233280;return x-Math.floor(x)}
  function rawRoundStop(roundId){var u=Math.max(.000001,seeded(roundId));var raw=(1-HOUSE_EDGE)/u;if(seeded(roundId+17)<HOUSE_EDGE)raw=1;return Math.max(1,Math.min(60,Math.floor(raw*100)/100))}
  function multAt(seconds){return 1+seconds*.12+seconds*seconds*.0042}
  function maxReachableStop(){return Math.floor(multAt(MAX_RUN_MS/1000)*100)/100}
  function roundStop(roundId){return Math.min(rawRoundStop(roundId),maxReachableStop())}
  function stopTime(stop){var target=Math.max(1,Number(stop)||1),lo=0,hi=MAX_RUN_MS;for(var i=0;i<24;i++){var mid=(lo+hi)/2;if(multAt(mid/1000)>=target)hi=mid;else lo=mid}return hi}
  function cycleFor(id){var stop=roundStop(id);var runMs=Math.max(1100,stopTime(stop));return{id:id,stop:stop,runMs:runMs,cycleMs:runMs+WAIT_BETWEEN_MS}}
  function locateRound(now){var dayStart=Math.floor(now/DAY_MS)*DAY_MS,baseId=Math.floor(dayStart/1000);if(!scheduleCache||scheduleCache.dayStart!==dayStart||now<scheduleCache.start){scheduleCache={dayStart:dayStart,baseId:baseId,localId:0,start:dayStart,cycle:cycleFor(baseId)}}while(now>=scheduleCache.start+scheduleCache.cycle.cycleMs){scheduleCache.start+=scheduleCache.cycle.cycleMs;scheduleCache.localId++;scheduleCache.cycle=cycleFor(scheduleCache.baseId+scheduleCache.localId)}var c=scheduleCache.cycle,local=now-scheduleCache.start,running=local<c.runMs,waitElapsed=running?0:local-c.runMs,nextIn=running?0:Math.max(0,WAIT_BETWEEN_MS-waitElapsed),inCrashHold=!running&&waitElapsed<CRASH_HOLD_MS;return{id:c.id,start:scheduleCache.start,local:local,runElapsed:Math.min(local,c.runMs),waitElapsed:waitElapsed,stop:c.stop,runMs:c.runMs,running:running,waiting:!running,inCrashHold:inCrashHold,nextIn:nextIn}}
  function previousRoundIds(state,count){var ids=[];for(var id=state.id-(state.waiting?0:1);ids.length<count;id--)ids.push(id);return ids}
  function targetBetRoundId(state){return state.waiting?state.id+1:state.id}
  function progressAt(runElapsed){return Math.max(0,runElapsed/1000)}
  function smoothstep(t){t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)}
  function getCanvas(){var canvas=q('crashCanvas');if(!canvas)return null;var dpr=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect(),w=Math.max(320,Math.floor(rect.width||360)),h=Math.max(260,Math.floor(rect.height||320));if(canvasCache!==canvas||canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;canvasCache=canvas;ctxCache=canvas.getContext('2d')}ctxCache.setTransform(dpr,0,0,dpr,0,0);ctxCache.__w=w;ctxCache.__h=h;return ctxCache}
  function drawGrid(ctx,w,h){ctx.save();var bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#050506');bg.addColorStop(.58,'#000');bg.addColorStop(1,'#070405');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);var glow=ctx.createRadialGradient(w*.50,h*.10,0,w*.50,h*.10,Math.max(w,h)*.78);glow.addColorStop(0,'rgba(92,10,31,.18)');glow.addColorStop(.42,'rgba(92,10,31,.045)');glow.addColorStop(1,'rgba(92,10,31,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=1;for(var y=36;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,Math.round(y)+.5);ctx.lineTo(w,Math.round(y)+.5);ctx.stroke()}ctx.strokeStyle='rgba(255,255,255,.034)';for(var x=-h;x<w+h;x+=46){ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(x+h,0);ctx.stroke()}ctx.strokeStyle='rgba(255,255,255,.018)';for(var x2=0;x2<w;x2+=58){ctx.beginPath();ctx.moveTo(Math.round(x2)+.5,0);ctx.lineTo(Math.round(x2)+.5,h);ctx.stroke()}ctx.restore()}
  function drawTip(ctx,x,y,ended){ctx.save();ctx.shadowColor=ended?'rgba(255,125,145,.30)':'rgba(255,255,255,.38)';ctx.shadowBlur=14;ctx.fillStyle=ended?'rgba(255,125,145,.96)':'#fff';ctx.beginPath();ctx.arc(x,y,6.5,0,Math.PI*2);ctx.fill();ctx.restore()}
  function drawGraph(progress,ended){var now=performance.now();if(!ended&&now-lastDraw<18)return;lastDraw=now;var ctx=getCanvas();if(!ctx)return;var w=ctx.__w,h=ctx.__h;ctx.clearRect(0,0,w,h);drawGrid(ctx,w,h);var visual=ended?chartCurrent:current,left=4,bottom=h-8,right=w-62,top=36,safeTop=top+(h-top)*.28,raw=Math.max(0,visual-1);var threshold=4.5;var earlyT=Math.min(1,raw/threshold);var earlyEase=Math.pow(earlyT,.55);var after=Math.max(0,raw-threshold);var afterEase=1-(1/(1+after*.16));var blend=smoothstep(Math.min(1,after/.95));var earlyX=earlyEase*.52;var earlyY=earlyEase*.42;var lateX=.52+afterEase*.32;var lateY=.42+(1-(1/(1+after*.115)))*.16;var xProgress=earlyX*(1-blend)+lateX*blend;var yProgress=earlyY*(1-blend)+lateY*blend;xProgress=Math.min(.86,Math.max(.03,xProgress));yProgress=Math.min(.56,Math.max(.018,yProgress));var tipX=left+(right-left)*xProgress;var tipY=bottom-(bottom-safeTop)*yProgress;if(tipY<safeTop)tipY=safeTop;lastProgress=progress;var curveBlend=smoothstep(Math.max(0,(visual-5.5)/2.8));var curvePower=1.01+(Math.min(2.45,1.01+Math.max(0,visual-5.5)*.16)-1.01)*curveBlend;var points=[];for(var i=0;i<=120;i++){var t=i/120;points.push([left+(tipX-left)*t,bottom-(bottom-tipY)*Math.pow(t,curvePower)])}ctx.save();ctx.beginPath();ctx.moveTo(left,bottom);for(var a=0;a<points.length;a++)ctx.lineTo(points[a][0],points[a][1]);ctx.lineTo(tipX,h);ctx.lineTo(left,h);ctx.closePath();var shadow=ctx.createLinearGradient(0,tipY,0,h);shadow.addColorStop(0,ended?'rgba(255,125,145,.38)':'rgba(255,255,255,.42)');shadow.addColorStop(.32,ended?'rgba(255,125,145,.20)':'rgba(255,255,255,.23)');shadow.addColorStop(.72,ended?'rgba(255,125,145,.08)':'rgba(255,255,255,.09)');shadow.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=shadow;ctx.globalAlpha=.92;ctx.fill();ctx.restore();ctx.save();var line=ctx.createLinearGradient(left,bottom,tipX,tipY);line.addColorStop(0,'rgba(255,255,255,.32)');line.addColorStop(.55,'rgba(255,255,255,1)');line.addColorStop(1,ended?'rgba(255,125,145,.72)':'rgba(255,255,255,.64)');ctx.strokeStyle=line;ctx.lineWidth=4.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor='transparent';ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(left,bottom);for(var c=0;c<points.length;c++)ctx.lineTo(points[c][0],points[c][1]);ctx.stroke();ctx.restore();drawTip(ctx,tipX,tipY,ended);if(!ended)chartCurrent=visual}
  function drawIdle(){current=1;chartCurrent=1;mult(1);drawGraph(0,true)}
  function drawCrashHold(state){var holdProgress=lastProgress>0?lastProgress:progressAt(state.runMs);if(lastProgress<=0)chartCurrent=state.stop;current=state.stop;mult(state.stop);drawGraph(holdProgress,true)}
  function renderHistory(state){var n=q('crashHistory');if(!n)return;n.innerHTML=previousRoundIds(state,12).map(function(id){return '<span>'+fmt(roundStop(id))+'</span>'}).join('')}
  function buttons(state){var s=q('crashStart'),c=q('crashCashout'),betRound=targetBetRoundId(state),hasBet=activeBet&&activeBet.roundId===betRound&&!activeBet.settled;if(s){s.disabled=!!hasBet||state.running||state.inCrashHold;s.textContent=hasBet?'Bet Placed':state.running?'Round Running':state.inCrashHold?'Crashed':'Place Bet'}if(c){var canCash=activeBet&&activeBet.roundId===state.id&&!activeBet.settled&&!activeBet.cashed&&state.running;c.disabled=!canCash;c.textContent=activeBet&&activeBet.cashed?'Cashed Out':'Cash Out'}}
  function placeBet(){var state=locateRound(Date.now());if(state.running||state.inCrashHold){show('Wait for next round');return}var betRound=targetBetRoundId(state);if(activeBet&&activeBet.roundId===betRound&&!activeBet.settled){show('Bet already placed');return}var bet=normalizeAmount();if(balance()<bet){show('Not enough TON balance');return}change(-bet);activeBet={roundId:betRound,amount:bet,cashed:false,settled:false,autoCashout:normalizeAutoCashout()};show('Bet placed for next round');scheduleUpdate(0)}
  function cashout(){var state=locateRound(Date.now());if(!activeBet||activeBet.roundId!==state.id||activeBet.settled||activeBet.cashed||state.waiting)return;activeBet.cashed=true;activeBet.settled=true;var m=current,back=Math.max(0,Math.floor(activeBet.amount*m));change(back);status('Cashed +' + toTon(back) + ' TON');show('Cashed at '+fmt(m));window.dispatchEvent(new CustomEvent('vexa-crash-cashout',{detail:{roundId:state.id,multiplier:m,payoutNano:back}}));buttons(state);scheduleUpdate(0)}
  function maybeAutoCashout(state){if(!activeBet||activeBet.roundId!==state.id||activeBet.settled||activeBet.cashed||!state.running)return;var target=Number(activeBet.autoCashout)||0;if(target>=1.01&&current>=target)cashout()}
  function settleIfNeeded(state){if(activeBet&&activeBet.roundId<state.id&&!activeBet.settled)activeBet.settled=true;if(activeBet&&activeBet.roundId===state.id&&state.waiting&&!activeBet.settled){activeBet.settled=true;status(activeBet.cashed?'Round ended':'Crashed')}if(settledRoundId!==state.id&&state.waiting){settledRoundId=state.id;renderHistory(state)}}
  function isCrashActive(){var view=q('crash');return !!(view&&view.classList.contains('active'))}
  function scheduleUpdate(delay){if(crashFrame||crashIdleTimer)return;if(delay&&delay>0){crashIdleTimer=setTimeout(function(){crashIdleTimer=0;scheduleUpdate(0)},delay);return}crashFrame=requestAnimationFrame(update)}
  function update(){crashFrame=0;var active=isCrashActive();var now=Date.now(),state=locateRound(now);if(currentRoundId!==state.id){currentRoundId=state.id;chartCurrent=1;current=1;lastProgress=0;lastHistoryId=null;roundEndSignalId=null}if(active){setTotal(state.local/1000);if(state.inCrashHold){nextLabel('Crashed');setCountdown('Crashed',false);status('Crashed');if(roundEndSignalId!==state.id){roundEndSignalId=state.id;window.dispatchEvent(new CustomEvent('vexa-round-ended',{detail:{roundId:state.id,multiplier:state.stop}}))}drawCrashHold(state)}else if(state.waiting){var waitLeft=(state.nextIn/1000).toFixed(1);nextLabel('Round starts '+waitLeft+'s');setCountdown(waitLeft+'s',false);status('Waiting');drawIdle()}else{nextLabel('');setCountdown('',true);status('Running');current=Math.min(state.stop,multAt(state.runElapsed/1000));chartCurrent=current;mult(current);drawGraph(progressAt(state.runElapsed),false);maybeAutoCashout(state)}if(state.waiting&&lastHistoryId!==state.id){lastHistoryId=state.id;renderHistory(state)}}else if(activeBet&&activeBet.roundId===state.id&&!activeBet.settled&&!activeBet.cashed&&state.running){current=Math.min(state.stop,multAt(state.runElapsed/1000));maybeAutoCashout(state)}settleIfNeeded(state);if(active)buttons(state);scheduleUpdate(active?0:1000)}
  function half(){var input=q('crashAmount');var value=normalizeAmount();if(input)input.value=toTon(Math.max(MIN_BET_NANO,Math.floor(value/2)))}
  function doubleAmount(){var input=q('crashAmount');var value=normalizeAmount();if(input)input.value=toTon(Math.max(MIN_BET_NANO,Math.min(balance(),value*2)))}
  function cleanDecimalInput(input){if(!input)return;var raw=String(input.value||'').replace(/,/g,'.'),out='',dot=false;for(var i=0;i<raw.length;i++){var ch=raw.charAt(i);if(ch>='0'&&ch<='9'){out+=ch;continue}if(ch==='.'&&!dot){out+=ch;dot=true}}if(out!==raw)input.value=out}
  function bind(){mult(1);status('Waiting');renderHistory(locateRound(Date.now()));var s=q('crashStart'),c=q('crashCashout'),input=q('crashAmount'),auto=q('crashAutoCashout');if(s)s.onclick=placeBet;if(c)c.onclick=cashout;if(input){input.setAttribute('step','0.01');input.setAttribute('inputmode','decimal');input.addEventListener('input',function(){cleanDecimalInput(input)});input.addEventListener('change',normalizeAmount);input.addEventListener('blur',normalizeAmount)}if(auto){auto.addEventListener('input',function(){cleanDecimalInput(auto)});auto.addEventListener('change',normalizeAutoCashout);auto.addEventListener('blur',normalizeAutoCashout)}document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('button');if(!b)return;var a=b.getAttribute('data-action');if(a==='crash-half'){ev.preventDefault();half()}if(a==='crash-double'){ev.preventDefault();doubleAmount()}if(b.getAttribute('data-game-view')==='crash'||b.getAttribute('data-view')==='crash')setTimeout(function(){normalizeAmount();scheduleUpdate(0)},120)});document.addEventListener('visibilitychange',function(){if(!document.hidden)scheduleUpdate(0)});window.addEventListener('resize',function(){var state=locateRound(Date.now());drawGraph(lastProgress,state.inCrashHold)});scheduleUpdate(0)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;