export const CRASH_CONTROLS_MODERN_STYLES = `
#crash .crash-controls{position:relative!important;margin:0!important;border-radius:28px!important;background:#050505!important;border:1px solid rgba(255,255,255,.10)!important;outline:0!important;box-shadow:0 20px 58px rgba(0,0,0,.54),inset 0 1px 0 rgba(255,255,255,.08)!important;padding:10px!important;display:grid!important;gap:8px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;isolation:isolate!important}
#crash .crash-controls:before,#crash .crash-controls:after{display:none!important}
#crash .crash-controls *{box-sizing:border-box!important}
#crash .crash-control-grid{display:grid!important;grid-template-columns:1fr!important;gap:0!important;align-items:stretch!important}
#crash .crash-field{min-width:0!important;min-height:54px!important;border-radius:18px!important;background:#030303!important;border:1px solid rgba(255,255,255,.10)!important;outline:0!important;padding:9px 14px!important;text-align:left!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important;display:block!important;margin:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important}
#crash .crash-field small,#crash .crash-label{display:block!important;color:rgba(255,255,255,.50)!important;font-size:11px!important;line-height:normal!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;white-space:nowrap!important;text-shadow:none!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field b{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:7px!important;margin-top:4px!important;font-size:18px!important;line-height:normal!important;font-weight:760!important;letter-spacing:-.04em!important;font-variant-numeric:tabular-nums lining-nums!important;white-space:nowrap!important;color:#fff!important;min-width:0!important;overflow:hidden!important}
#crash .crash-field b>span:first-child{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field i{font-style:normal!important;font-size:18px!important;line-height:normal!important;color:rgba(255,255,255,.72)!important;font-weight:800!important;flex:0 0 auto!important}
#crash .crash-auto-field{margin-top:0!important}
#crash .crash-auto{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:2px!important;width:100%!important;min-width:0!important;height:auto!important;min-height:0!important;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important}
#crash .crash-auto input{width:100%!important;min-width:0!important;height:auto!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:left!important;font:inherit!important;font-size:18px!important;font-weight:760!important;line-height:normal!important;letter-spacing:-.04em!important;box-shadow:none!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-auto input::-webkit-outer-spin-button,#crash .crash-auto input::-webkit-inner-spin-button,#crash .crash-bet-main input::-webkit-outer-spin-button,#crash .crash-bet-main input::-webkit-inner-spin-button{appearance:none!important;-webkit-appearance:none!important;margin:0!important}
#crash .crash-auto span{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:0!important;color:#fff!important;font-size:18px!important;font-weight:760!important;line-height:normal!important;flex:0 0 auto!important}
#crash .crash-bet{display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;gap:8px!important;align-items:center!important}
#crash .crash-bet button,#crash .crash-bet-main,#crash .crash-primary,#crash .crash-secondary{height:40px!important;border-radius:16px!important;border:1px solid rgba(255,255,255,.12)!important;outline:0!important;background:rgba(255,255,255,.075)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;text-shadow:none!important;overflow:hidden!important}
#crash .crash-bet-main{display:flex!important;align-items:center!important;justify-content:center!important;padding:0 12px!important;min-width:0!important;font-size:16px!important;background:#030303!important;border-color:rgba(255,255,255,.14)!important}
#crash .crash-bet-main.active{background:#030303!important;border-color:rgba(255,255,255,.14)!important}
#crash .crash-bet-main input{width:100%!important;height:38px!important;border:0!important;outline:0!important;background:#030303!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:center!important;font-size:16px!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;padding:0!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-bet-main input::placeholder,#crash .crash-auto input::placeholder{color:rgba(255,255,255,.42)!important;-webkit-text-fill-color:rgba(255,255,255,.42)!important}
#crash .crash-bet button.active{background:rgba(255,255,255,.18)!important;border-color:rgba(255,255,255,.24)!important}
#crash .crash-bet button:focus-visible,#crash .crash-bet-main:focus-within,#crash .crash-primary:focus-visible,#crash .crash-secondary:focus-visible{outline:0!important;box-shadow:none!important}
#crash .crash-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;margin-top:0!important}
#crash .crash-primary,#crash .crash-secondary{height:52px!important;border-radius:999px!important;background:#fff!important;border-color:#fff!important;color:#050506!important;-webkit-text-fill-color:#050506!important;font-size:16px!important;box-shadow:0 12px 24px rgba(0,0,0,.28)!important;transition:transform .18s ease,opacity .18s ease!important}
#crash .crash-primary:not(:disabled):active,#crash .crash-secondary:not(:disabled):active,#crash .crash-bet button:active{transform:scale(.975)!important}
#crash .crash-primary:disabled,#crash .crash-secondary:disabled{opacity:.48!important;transform:scale(.985)!important;filter:none!important}
#crash .crash-history{display:flex!important;gap:6px!important;overflow-x:auto!important;overflow-y:visible!important;margin-top:0!important;min-height:28px!important;padding:0 1px 2px!important;scrollbar-width:none!important;visibility:visible!important;opacity:1!important;clip-path:none!important}
#crash .crash-history::-webkit-scrollbar{display:none!important}
#crash .crash-history span{flex:0 0 auto!important;border-radius:999px!important;padding:6px 10px!important;min-height:24px!important;line-height:12px!important;font-size:10px!important;font-weight:890!important;color:rgba(255,255,255,.94)!important;background:transparent!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;overflow:visible!important;clip-path:none!important}
#crash .crash-live{border-radius:32px!important;background:#050505!important;border:1px solid rgba(255,255,255,.10)!important;box-shadow:0 24px 74px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.08)!important;padding:14px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important}
#crash .crash-live-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:10px!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important}
#crash .crash-live-head b{color:rgba(255,255,255,.92)!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important}
#crash .crash-live-list{display:grid!important;gap:6px!important;max-height:792px!important;overflow-y:auto!important;overflow-x:hidden!important;padding-right:2px!important;scrollbar-width:thin!important;scrollbar-color:rgba(255,255,255,.18) transparent!important}
#crash .crash-live-list::-webkit-scrollbar{width:4px!important;display:block!important}
#crash .crash-live-list::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18)!important;border-radius:999px!important}
#crash .crash-live-empty{font-size:12px!important;font-weight:820!important;color:rgba(255,255,255,.45)!important;padding:14px 0!important;text-align:center!important}
#crash .crash-live-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto auto!important;align-items:center!important;gap:8px!important;min-height:34px!important;border-radius:17px!important;background:#030303!important;border:1px solid rgba(255,255,255,.08)!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.035)!important;color:#fff!important;padding:2px 10px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#crash .crash-live-user{min-width:0!important;font-size:12px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;color:rgba(255,255,255,.92)!important}
#crash .crash-live-amount{font-size:11px!important;font-weight:900!important;color:rgba(255,255,255,.62)!important;white-space:nowrap!important}
#crash .crash-live-status{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:5px!important;font-size:11px!important;font-weight:930!important;color:rgba(255,255,255,.84)!important;white-space:nowrap!important}
#crash .crash-live-win{color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;font-size:12px!important;font-weight:950!important;font-variant-numeric:tabular-nums lining-nums!important;text-shadow:0 0 14px rgba(120,255,179,.16)!important}
#crash .crash-live-row.cashout .crash-live-user,#crash .crash-live-row.cashout .crash-live-amount,#crash .crash-live-row.cashout .crash-live-status{color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important}
#crash .crash-live-row.cashout{border-color:rgba(120,255,179,.22)!important;background:rgba(120,255,179,.055)!important}
#crash .crash-live-row.crashed .crash-live-status{color:rgba(255,140,160,.86)!important}
@media(max-width:380px){#crash .crash-controls{padding:9px!important;gap:7px!important}#crash .crash-field{padding:8px 12px!important;min-height:50px!important}#crash .crash-field small,#crash .crash-label{font-size:10px!important}#crash .crash-field b,#crash .crash-auto input,#crash .crash-auto span{font-size:16px!important}#crash .crash-bet button,#crash .crash-bet-main{height:38px!important}#crash .crash-primary,#crash .crash-secondary{height:48px!important;font-size:15px!important}}
`;