export const CRASH_BREAK_FX_SCRIPT = `
(function(){
  var audioCtx=null, master=null, musicGain=null, musicNodes=[], musicOn=false, lastState='idle', crashedLock=false, lastStartKey='', timer=null, step=0;
  function q(id){return document.getElementById(id)}
  function active(){var c=q('crash');return !!(c&&c.classList.contains('active'))}
  function getAudio(){var C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioCtx){audioCtx=new C();master=audioCtx.createGain();master.gain.value=.75;master.connect(audioCtx.destination)}return audioCtx}
  function unlock(){var ctx=getAudio();if(!ctx)return null;if(ctx.state==='suspended')ctx.resume().catch(function(){});return ctx}
  function canPlay(){return !!(audioCtx&&audioCtx.state==='running')}
  function stopMusic(){if(!musicOn)return;musicOn=false;if(timer){clearInterval(timer);timer=null}var ctx=audioCtx;if(musicGain&&ctx){try{musicGain.gain.cancelScheduledValues(ctx.currentTime);musicGain.gain.setTargetAtTime(0,ctx.currentTime,.05)}catch(e){}}musicNodes.forEach(function(n){try{n.stop((ctx?ctx.currentTime:0)+.14)}catch(e){}try{n.disconnect()}catch(e){}});musicNodes=[];step=0}
  function beep(freq,when,len,vol,type,out){var ctx=audioCtx;if(!ctx||!canPlay())return;var o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=type||'triangle';o.frequency.setValueAtTime(freq,when);f.type='lowpass';f.frequency.setValueAtTime(1900,when);f.frequency.exponentialRampToValueAtTime(700,when+len);g.gain.setValueAtTime(.001,when);g.gain.linearRampToValueAtTime(vol,when+.018);g.gain.exponentialRampToValueAtTime(.001,when+len);o.connect(f);f.connect(g);g.connect(out||master);o.start(when);o.stop(when+len+.03)}
  function melody(){if(!musicOn||!canPlay()||!musicGain)return;var ctx=audioCtx,t=ctx.currentTime;var notes=[392,523.25,493.88,392,329.63,392,293.66,329.63];var f=notes[step%notes.length];beep(f,t,.24,.13,step%3===1?'sine':'triangle',musicGain);if(step%2===0)beep(f/2,t+.01,.36,.04,'sine',musicGain);step++}
  function startSound(){var ctx=unlock();if(!ctx||!canPlay())return;var t=ctx.currentTime;beep(523.25,t,.18,.12,'sine',master);beep(659.25,t+.05,.18,.10,'sine',master);beep(783.99,t+.10,.20,.09,'sine',master)}
  function startMusic(){if(musicOn||!active())return;var ctx=unlock();if(!ctx||!canPlay())return;musicOn=true;musicGain=ctx.createGain();musicGain.gain.setValueAtTime(0,ctx.currentTime);musicGain.gain.linearRampToValueAtTime(.34,ctx.currentTime+.22);musicGain.connect(master);var drone=ctx.createOscillator(),dg=ctx.createGain();drone.type='sine';drone.frequency.value=98;dg.gain.value=.045;drone.connect(dg);dg.connect(musicGain);drone.start();musicNodes.push(drone,dg);melody();timer=setInterval(melody,430)}
  function burst(ctx,delay,dur,gainVal){if(!canPlay())return;var b=ctx.createBuffer(1,Math.floor(ctx.sampleRate*dur),ctx.sampleRate),d=b.getChannelData(0);for(var i=0;i<d.length;i++){var t=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-t,3)}var s=ctx.createBufferSource();s.buffer=b;var f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=850+Math.random()*1000;var g=ctx.createGain();g.gain.setValueAtTime(gainVal,ctx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+dur);s.connect(f);f.connect(g);g.connect(master);s.start(ctx.currentTime+delay)}
  function crackSound(){var ctx=unlock();if(!ctx||!canPlay())return;burst(ctx,0,.08,.18);burst(ctx,.04,.06,.11);beep(150,ctx.currentTime,.18,.055,'triangle',master)}
  function triggerBreak(){var n=q('crashMultiplier');if(!n)return;n.setAttribute('data-crash-text',n.textContent||'');n.classList.remove('crash-broken');void n.offsetWidth;n.classList.add('crash-broken');crackSound()}
  function state(){if(!active())return 'inactive';var label=q('crashNextRound'),txt=String((label&&label.textContent)||'');if(/Crashed/i.test(txt))return 'crashed';if(/Round starts/i.test(txt))return 'waiting';return 'running'}
  function roundKey(){var n=q('crashMultiplier');return String((n&&n.textContent)||'')+'|'+String(Date.now()).slice(0,-3)}
  function sync(){unlock();var s=state(),n=q('crashMultiplier');if(s==='inactive'){stopMusic();lastState='inactive';crashedLock=false;return}if(s==='running'){crashedLock=false;if(n)n.classList.remove('crash-broken');if(lastState!=='running'){var k=roundKey();if(k!==lastStartKey&&canPlay()){lastStartKey=k;startSound()}}startMusic()}else stopMusic();if(s==='crashed'&&!crashedLock){crashedLock=true;triggerBreak()}if(s==='waiting'&&lastState==='crashed')crashedLock=true;if(s==='waiting'&&n)n.classList.remove('crash-broken');lastState=s}
  function unlockAndSync(){unlock();setTimeout(sync,30);setTimeout(sync,180);setTimeout(sync,420);setTimeout(sync,800)}
  document.addEventListener('pointerdown',unlockAndSync,true);document.addEventListener('touchstart',unlockAndSync,true);document.addEventListener('click',unlockAndSync,true);setInterval(sync,180);
})();
`;
