export const DAILY_REWARDS_SCRIPT = `
(function(){
  var tg=window.Telegram&&window.Telegram.WebApp;
  var tgUser=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};
  var backBound=false;
  var backKeepTimer=0;
  var rewardsLoaded=false;
  var rewardsLoading=false;
  var rewardsData=null;
  var activeDay=0;
  var claimBusy={};
  var dayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  var fallbackMissions={
    Monday:[{id:'play_predict_3',title:'Play 3 Predict rounds',description:'Start the week with activity',xp:90},{id:'win_predict_1',title:'Win 1 Predict round',description:'Get one correct prediction',xp:120},{id:'place_bets_5',title:'Place 5 total bets',description:'Stay active in Play Zone',xp:100},{id:'open_app',title:'Open the app today',description:'Keep your daily streak alive',xp:40},{id:'check_level_progress',title:'Check your rank',description:'View your current level progress',xp:35},{id:'deposit_any',title:'Deposit TON',description:'Charge balance for more games',xp:250}],
    Tuesday:[{id:'play_predict_5',title:'Play 4 Predict rounds',description:'Build your weekly XP',xp:110},{id:'win_predict_2',title:'Win 2 rounds',description:'Score two wins today',xp:160},{id:'use_up_down',title:'Use both Up and Down',description:'Try both directions in Predict',xp:80},{id:'open_market',title:'Open Market',description:'Check available items',xp:35},{id:'daily_streak',title:'Keep streak active',description:'Come back without missing a day',xp:70},{id:'invite_friend',title:'Invite a friend',description:'Bring one player to Vexa',xp:220}],
    Wednesday:[{id:'play_predict_5',title:'Play 5 rounds',description:'Midweek XP boost',xp:130},{id:'win_predict_2',title:'Win 2 Predict rounds',description:'Stay sharp',xp:160},{id:'bet_20_ton',title:'Bet 20 TON total',description:'Reach today volume goal',xp:180},{id:'open_play_zone',title:'Open Play Zone',description:'Check all games',xp:40},{id:'check_level_progress',title:'Reach next XP step',description:'Progress toward level up',xp:90},{id:'open_app',title:'Daily login',description:'Claim activity credit',xp:40}],
    Thursday:[{id:'play_predict_3',title:'Play 3 rounds',description:'Keep weekly momentum',xp:90},{id:'win_predict_1',title:'Win 1 round',description:'One clean win today',xp:120},{id:'try_new_game',title:'Try a new game',description:'Open another Play Zone game',xp:80},{id:'check_top_players',title:'Check Top Players',description:'See weekly competition',xp:45},{id:'daily_streak',title:'Keep streak active',description:'Do not miss today',xp:70},{id:'deposit_any',title:'Deposit TON',description:'Add more play balance',xp:250}],
    Friday:[{id:'play_predict_7',title:'Play 6 rounds',description:'Push before weekend',xp:150},{id:'win_predict_3',title:'Win 3 rounds',description:'High performance bonus',xp:220},{id:'place_bets_10',title:'Place 8 bets',description:'Stay active',xp:150},{id:'open_market',title:'Open Market',description:'Check drops and NFTs',xp:35},{id:'invite_friend',title:'Invite a friend',description:'Grow the competition',xp:220},{id:'open_app',title:'Daily login',description:'Claim activity credit',xp:40}],
    Saturday:[{id:'play_predict_5',title:'Play 5 rounds',description:'Weekend activity',xp:130},{id:'win_predict_2',title:'Win 2 rounds',description:'Keep your win rate up',xp:160},{id:'bet_30_ton',title:'Bet 30 TON total',description:'Weekend volume mission',xp:240},{id:'open_play_zone',title:'Open Play Zone',description:'Explore games',xp:40},{id:'daily_streak',title:'Keep streak active',description:'Weekend streak bonus',xp:90},{id:'check_level_progress',title:'Check level progress',description:'See XP to next level',xp:45}],
    Sunday:[{id:'play_predict_7',title:'Play 7 rounds',description:'Final weekly push',xp:180},{id:'win_predict_3',title:'Win 3 rounds',description:'Finish strong',xp:220},{id:'place_bets_10',title:'Place 10 bets',description:'Last day activity goal',xp:190},{id:'check_top_players',title:'Check Top Players',description:'See your final weekly place',xp:60},{id:'daily_streak',title:'Keep streak active',description:'Complete the week',xp:140},{id:'open_app',title:'Daily login',description:'Final day login reward',xp:50}]
  };
  function q(id){return document.getElementById(id)}
  function userId(){return String(tgUser.id||localStorage.getItem('ownerId')||'').trim()}
  function esc(value){return String(value||'').replace(/[&<>]/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]||ch})}
  function mondayIndex(date){var js=date.getDay();return js===0?6:js-1}
  function startOfWeek(date){var d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-mondayIndex(d));return d}
  function isOpen(){var p=q('dailyRewardsPage');return !!(p&&p.classList.contains('open'))}
  function claimKey(day,missionId){return String(Number(day)||0)+':'+String(missionId||'')}
  function claimedSet(){return new Set((rewardsData&&Array.isArray(rewardsData.claimed)?rewardsData.claimed:[]).map(String))}
  function showBack(){if(!tg||!tg.BackButton)return;try{tg.BackButton.show()}catch(e){}}
  function stopKeepBack(){if(backKeepTimer){clearInterval(backKeepTimer);backKeepTimer=0}}
  function startKeepBack(){stopKeepBack();showBack();setTimeout(function(){if(isOpen())showBack()},40);setTimeout(function(){if(isOpen())showBack()},180);setTimeout(function(){if(isOpen())showBack()},520);backKeepTimer=setInterval(function(){if(isOpen())showBack();else stopKeepBack()},700)}
  function syncBack(open){if(!tg||!tg.BackButton)return;if(!backBound){backBound=true;try{tg.BackButton.onClick(function(){if(isOpen())close()})}catch(e){}}try{if(open)startKeepBack();else{stopKeepBack();tg.BackButton.hide()}}catch(e){}}
  function clampBottomScroll(){var p=q('dailyRewardsPage');if(!p)return;var max=Math.max(0,p.scrollHeight-p.clientHeight-1);if(p.scrollTop>max)p.scrollTop=max}
  function ensurePageOnBody(){var p=q('dailyRewardsPage');if(p&&p.parentNode!==document.body)document.body.appendChild(p);return p}
  function missionList(index){if(rewardsData&&Array.isArray(rewardsData.days)){var day=rewardsData.days.find(function(item){return Number(item.day)===Number(index)});if(day&&Array.isArray(day.missions)&&day.missions.length)return day.missions.slice(0,6).map(function(m){return{title:m.title,description:m.description,xp:m.xp,id:m.id,type:m.type}})}var name=dayNames[index]||dayNames[0];return (fallbackMissions[name]||fallbackMissions.Monday).slice(0,6)}
  function renderDays(active){var wrap=q('dailyRewardsDays');if(!wrap)return;var start=startOfWeek(new Date());wrap.innerHTML=dayNames.map(function(name,i){var d=new Date(start);d.setDate(start.getDate()+i);return '<button class="daily-rewards-day '+(i===active?'active':'')+'" type="button" data-daily-rewards-day="'+i+'"><small>'+name.slice(0,3)+'</small><strong>'+d.getDate()+'</strong><span>Day '+(i+1)+'</span></button>'}).join('')}
  function renderMissions(index){activeDay=Number(index)||0;var name=dayNames[activeDay]||dayNames[0];var list=missionList(activeDay);var claimed=claimedSet();var title=q('dailyRewardsMissionTitle');if(title)title.textContent=name+' missions';var count=q('dailyRewardsMissionCount');if(count)count.textContent=list.length+' missions';var box=q('dailyRewardsMissions');if(!box)return;box.innerHTML=list.map(function(m,i){var xp=Math.max(1,Math.floor(Number(m.xp)||0));var id=String(m.id||'');var key=claimKey(activeDay,id);var done=claimed.has(key);var busy=claimBusy[key];var label=done?'Claimed':(busy?'...':'Claim');var disabled=done||busy||!id||!userId();return '<div class="daily-rewards-mission '+(done?'claimed':'')+'" data-mission-id="'+esc(id)+'" data-mission-type="'+esc(m.type||'')+'"><div class="daily-rewards-mission-icon">'+(done?'✓':(i+1))+'</div><div class="daily-rewards-mission-main"><strong>'+esc(m.title)+'</strong><span>'+esc(m.description)+'</span></div><button class="daily-rewards-xp daily-rewards-claim" type="button" data-action="claim-daily-reward" data-day="'+activeDay+'" data-mission-id="'+esc(id)+'" '+(disabled?'disabled':'')+'>'+label+' · +'+xp+' XP</button></div>'}).join('');setTimeout(clampBottomScroll,80)}
  async function loadRewards(force){if((rewardsLoaded&&!force)||rewardsLoading)return rewardsData;rewardsLoading=true;try{var id=userId();var url='/app/api/daily-rewards'+(id?'?userId='+encodeURIComponent(id):'');var res=await fetch(url,{credentials:'same-origin',cache:'no-store'});var json=await res.json();if(!res.ok)throw new Error(json.error||'Could not load Daily Rewards');rewardsData=json;rewardsLoaded=true;return rewardsData}catch(error){rewardsLoaded=true;return null}finally{rewardsLoading=false}}
  async function refreshAndRender(day,force){await loadRewards(!!force);renderDays(day);renderMissions(day)}
  async function claim(day,missionId){var id=userId();if(!id)return;var key=claimKey(day,missionId);if(claimBusy[key])return;claimBusy[key]=true;renderMissions(activeDay);try{var res=await fetch('/app/api/daily-rewards/claim',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({userId:id,day:day,missionId:missionId})});var json=await res.json();if(!res.ok)throw new Error(json.error||'Could not claim');if(!rewardsData)rewardsData={days:[],claimed:[]};if(!Array.isArray(rewardsData.claimed))rewardsData.claimed=[];if(json.claimedKey&&rewardsData.claimed.indexOf(json.claimedKey)===-1)rewardsData.claimed.push(json.claimedKey);if(json.profile)rewardsData.profile=json.profile;try{window.dispatchEvent(new CustomEvent('vexa-xp-updated',{detail:{profile:json.profile,missionId:missionId,day:day,xp:json.xp}}))}catch(e){}await refreshAndRender(activeDay,true)}catch(error){var status=q('dailyRewardsMissionCount');if(status)status.textContent=error.message||'Claim failed'}finally{delete claimBusy[key];renderMissions(activeDay)}}
  function open(){var p=ensurePageOnBody();if(!p)return;var active=mondayIndex(new Date());activeDay=active;renderDays(active);renderMissions(active);refreshAndRender(active,true);document.body.classList.add('daily-rewards-open');p.classList.add('open');p.setAttribute('aria-hidden','false');syncBack(true);try{p.scrollTop=0}catch(e){}setTimeout(clampBottomScroll,180)}
  function close(){var p=q('dailyRewardsPage');if(!p)return;document.body.classList.remove('daily-rewards-open');p.classList.remove('open');p.setAttribute('aria-hidden','true');syncBack(false)}
  function mount(){var old=document.getElementById('dailyRewardsMount');if(old)return;var home=document.getElementById('home');if(!home)return;var mount=document.createElement('div');mount.id='dailyRewardsMount';mount.innerHTML=window.DAILY_REWARDS_SECTION||'';var page=mount.querySelector('#dailyRewardsPage');if(page)document.body.appendChild(page);var finance=home.querySelector('.home-finance-split');if(finance&&finance.parentNode)finance.parentNode.insertBefore(mount,finance.nextSibling);else home.appendChild(mount);activeDay=mondayIndex(new Date());renderDays(activeDay);renderMissions(activeDay);loadRewards(true).then(function(){renderDays(activeDay);renderMissions(activeDay)})}
  document.addEventListener('click',function(ev){var target=ev.target&&ev.target.closest?ev.target.closest('[data-action], [data-daily-rewards-day]'):null;if(!target)return;var day=target.getAttribute('data-daily-rewards-day');if(day!==null){activeDay=Number(day);renderDays(activeDay);renderMissions(activeDay);return}var action=target.getAttribute('data-action');if(action==='open-daily-rewards'){open();return}if(action==='close-daily-rewards'){close();return}if(action==='claim-daily-reward'){ev.preventDefault();claim(Number(target.getAttribute('data-day')),target.getAttribute('data-mission-id'));return}},true);
  window.addEventListener('focus',function(){if(isOpen())startKeepBack()});
  document.addEventListener('visibilitychange',function(){if(!document.hidden&&isOpen()){startKeepBack();refreshAndRender(activeDay,true)}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
`;