export const DAILY_REWARDS_INFO_SECTION = `<section id="dailyrewardsinfo" class="view daily-rewards-info-view">
  <style>
    body:has(#dailyrewardsinfo.active) .top,body:has(#dailyrewardsinfo.active) .tabs{display:none!important}
    body:has(#dailyrewardsinfo.active) .content{height:100vh!important;padding:0!important;overflow:hidden!important}
    body:has(#dailyrewardsinfo.active) .app{padding:0!important;height:100vh!important;max-height:100vh!important}
    .daily-rewards-info-view{position:fixed!important;inset:0!important;z-index:10040;height:100vh!important;width:100vw!important;overflow:hidden!important;padding:calc(50px + env(safe-area-inset-top)) 18px calc(16px + env(safe-area-inset-bottom))!important;background:radial-gradient(circle at 18% -10%,rgba(126,20,48,.34),rgba(126,20,48,0) 36%),radial-gradient(circle at 92% 14%,rgba(126,20,48,.22),rgba(126,20,48,0) 30%),#050507;box-sizing:border-box}
    .daily-rewards-info-view:not(.active){display:none!important}
    .daily-info-page{position:relative;height:100%;min-height:0;padding:0;display:grid;grid-template-rows:auto minmax(0,1fr);gap:12px;align-content:start}
    .daily-info-head{position:relative;border-radius:28px;padding:16px 16px 14px;background:linear-gradient(135deg,rgba(255,255,255,.075),rgba(255,255,255,.026));box-shadow:0 18px 48px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.13);backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);overflow:hidden;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}
    .daily-info-head:before{content:"";position:absolute;right:-64px;top:-78px;width:174px;height:174px;border-radius:999px;background:radial-gradient(circle,rgba(126,20,48,.38),rgba(126,20,48,.10) 52%,rgba(126,20,48,0) 72%);pointer-events:none}
    .daily-info-copy{position:relative;z-index:2;min-width:0}.daily-info-copy span{display:block;margin-bottom:8px;color:rgba(255,255,255,.52);font-size:9px;font-weight:900;text-transform:uppercase;letter-spacing:.17em}.daily-info-copy h2{margin:0;color:#fff;font-size:30px;line-height:.94;font-weight:930;letter-spacing:-.065em;text-shadow:0 18px 34px rgba(0,0,0,.28)}.daily-info-copy p{margin:7px 0 0;max-width:210px;color:rgba(255,255,255,.58);font-size:10.5px;line-height:1.3;font-weight:620}
    .daily-info-translate{position:relative;z-index:2;height:36px;border:0;border-radius:999px;background:#fff;color:#23050d;padding:0 14px;font-size:12px;font-weight:900;box-shadow:0 14px 34px rgba(0,0,0,.20)}
    .daily-info-list{position:relative;min-height:0;display:grid;gap:22px;align-content:start;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch;overscroll-behavior-y:contain;scrollbar-width:none;padding:4px 0 92px!important;mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 58px),rgba(0,0,0,0));-webkit-mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 58px),rgba(0,0,0,0));scroll-snap-type:y proximity}.daily-info-list::-webkit-scrollbar{display:none}
    @keyframes dailyInfoStepIn{from{opacity:0;transform:translateY(16px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}
    .daily-info-row{display:grid;grid-template-columns:126px minmax(0,1fr);align-items:start;gap:13px;min-height:124px;padding:0 13px 8px 0;border-radius:26px;background:rgba(255,255,255,.04);box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 14px 28px rgba(0,0,0,.14);backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);overflow:visible!important;position:relative!important;width:100%;margin:0!important;animation:dailyInfoStepIn .36s cubic-bezier(.2,.8,.2,1) both;scroll-snap-align:start;transition:transform .22s ease,box-shadow .22s ease,opacity .22s ease;box-sizing:border-box;top:auto!important;left:auto!important;z-index:auto!important}
    .daily-info-row:nth-child(1),.daily-info-row:nth-child(2),.daily-info-row:nth-child(3),.daily-info-row:nth-child(4),.daily-info-row:nth-child(5),.daily-info-row:nth-child(6),.daily-info-row:nth-child(7){top:auto!important;margin-left:0!important;z-index:auto!important;position:relative!important}
    .daily-info-row:nth-child(1){animation-delay:.02s}.daily-info-row:nth-child(2){animation-delay:.05s}.daily-info-row:nth-child(3){animation-delay:.08s}.daily-info-row:nth-child(4){animation-delay:.11s}.daily-info-row:nth-child(5){animation-delay:.14s}.daily-info-row:nth-child(6){animation-delay:.17s}.daily-info-row:nth-child(7){animation-delay:.20s}
    .daily-info-row.today{background:linear-gradient(135deg,rgba(126,20,48,.24),rgba(255,255,255,.065));box-shadow:inset 0 1px 0 rgba(255,255,255,.13),0 16px 34px rgba(126,20,48,.10)}
    .daily-info-img{align-self:start;width:112px;height:136px;margin-left:12px;border-radius:0;background:transparent!important;overflow:visible;display:grid;place-items:start center;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.daily-info-img img{width:100%;height:100%;object-fit:contain;object-position:top center;display:block;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;filter:drop-shadow(0 14px 22px rgba(0,0,0,.26))}.daily-info-img span{color:rgba(255,255,255,.3);font-size:9px;font-weight:800}
    .daily-info-main{min-width:0;padding:16px 0 10px}.daily-info-main b{display:block;color:#fff;font-size:16px;font-weight:900;line-height:1;letter-spacing:-.025em}.daily-info-main small{display:block;margin-top:8px;color:rgba(255,255,255,.6);font-size:11.5px;font-weight:620;line-height:1.34}.daily-info-day{height:26px;display:inline-grid;place-items:center;padding:0 10px;border-radius:999px;background:rgba(126,20,48,.16);color:rgba(255,255,255,.84);font-size:9.5px;font-weight:900;margin-bottom:9px}
  </style>
  <div class="daily-info-page">
    <div class="daily-info-head">
      <div class="daily-info-copy"><span>Daily Rewards</span><h2>Reward Guide</h2><p>See what each day gives you before you claim it.</p></div>
      <button id="dailyInfoTranslate" class="daily-info-translate" type="button">Translate</button>
    </div>
    <div id="dailyInfoList" class="daily-info-list"></div>
  </div>
</section>`;
