export const DAILY_REWARDS_INFO_SECTION = `<section id="dailyrewardsinfo" class="view daily-rewards-info-view" aria-hidden="true">
  <style>
    .daily-rewards-info-view{display:block!important;position:fixed!important;inset:0!important;z-index:10040;height:100vh!important;width:100vw!important;overflow:hidden!important;padding:calc(66px + env(safe-area-inset-top)) 18px calc(16px + env(safe-area-inset-bottom))!important;background:rgba(0,0,0,.02)!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important;box-sizing:border-box;opacity:0!important;visibility:hidden!important;pointer-events:none!important;transform:translate3d(0,24px,0) scale(.975)!important;transition:opacity .26s cubic-bezier(.2,.8,.2,1),transform .30s cubic-bezier(.2,.8,.2,1),visibility 0s linear .30s!important;will-change:opacity,transform!important;contain:layout paint style!important}
    .daily-rewards-info-view.active{opacity:1!important;visibility:visible!important;pointer-events:auto!important;transform:translate3d(0,0,0) scale(1)!important;transition:opacity .26s cubic-bezier(.2,.8,.2,1),transform .30s cubic-bezier(.2,.8,.2,1),visibility 0s!important}
    .daily-rewards-info-view.is-closing{opacity:0!important;visibility:visible!important;pointer-events:none!important;transform:translate3d(0,18px,0) scale(.985)!important;transition:opacity .18s cubic-bezier(.4,0,1,1),transform .20s cubic-bezier(.4,0,1,1),visibility 0s linear .20s!important}
    .daily-info-page{position:relative;height:100%;min-height:0;padding:0;display:grid;grid-template-rows:minmax(0,1fr);gap:0;align-content:start;background:transparent!important;transform:translateZ(0)}
    .daily-info-list{position:relative;min-height:0;display:block;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch;overscroll-behavior-y:contain;scrollbar-width:none;padding:0 0 360px!important;mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 58px),rgba(0,0,0,0));-webkit-mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 58px),rgba(0,0,0,0));scroll-snap-type:y proximity}.daily-info-list::-webkit-scrollbar{display:none}
    @keyframes dailyInfoStepIn{from{opacity:0;transform:translateY(16px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}
    .daily-info-row{display:grid;grid-template-columns:122px minmax(0,1fr);align-items:start;gap:13px;min-height:112px;padding:0 13px 6px 0;border-radius:26px;background:linear-gradient(135deg,rgba(24,24,27,.96),rgba(10,10,12,.96))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 16px 34px rgba(0,0,0,.24);backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);overflow:visible!important;position:sticky!important;width:100%;margin:0 0 42px 0!important;animation:dailyInfoStepIn .28s cubic-bezier(.2,.8,.2,1) both;scroll-snap-align:start;transition:transform .22s ease,box-shadow .22s ease,opacity .22s ease;box-sizing:border-box;left:0!important;will-change:transform,opacity}
    .daily-info-row:nth-child(1){top:0!important;z-index:17}.daily-info-row:nth-child(2){top:24px!important;z-index:16}.daily-info-row:nth-child(3){top:48px!important;z-index:15}.daily-info-row:nth-child(4){top:72px!important;z-index:14}.daily-info-row:nth-child(5){top:96px!important;z-index:13}.daily-info-row:nth-child(6){top:120px!important;z-index:12}.daily-info-row:nth-child(7){top:144px!important;z-index:11}
    .daily-info-row:nth-child(1),.daily-info-row:nth-child(2),.daily-info-row:nth-child(3),.daily-info-row:nth-child(4),.daily-info-row:nth-child(5),.daily-info-row:nth-child(6),.daily-info-row:nth-child(7){margin-left:0!important;transform:none!important}
    .daily-info-row:nth-child(1){animation-delay:.01s}.daily-info-row:nth-child(2){animation-delay:.03s}.daily-info-row:nth-child(3){animation-delay:.05s}.daily-info-row:nth-child(4){animation-delay:.07s}.daily-info-row:nth-child(5){animation-delay:.09s}.daily-info-row:nth-child(6){animation-delay:.11s}.daily-info-row:nth-child(7){animation-delay:.13s}
    .daily-info-row.today{background:linear-gradient(135deg,rgba(24,24,27,.96),rgba(10,10,12,.96))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 16px 34px rgba(0,0,0,.24)!important}
    .daily-info-img{align-self:start;width:108px;height:136px;margin-left:12px;border-radius:0;background:transparent!important;overflow:visible;display:grid;place-items:start center;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.daily-info-img img{width:100%;height:100%;object-fit:contain;object-position:top center;display:block;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;filter:drop-shadow(0 14px 22px rgba(0,0,0,.26))}.daily-info-img span{color:rgba(255,255,255,.3);font-size:9px;font-weight:800}
    .daily-info-main{min-width:0;padding:14px 0 9px}.daily-info-main b{display:block;color:#fff;font-size:16px;font-weight:900;line-height:1;letter-spacing:-.025em}.daily-info-main small{display:block;margin-top:8px;color:rgba(255,255,255,.6);font-size:11.5px;font-weight:620;line-height:1.34}.daily-info-day{height:26px;display:inline-grid;place-items:center;padding:0 10px;border-radius:999px;background:rgba(126,20,48,.16);color:rgba(255,255,255,.84);font-size:9.5px;font-weight:900;margin-bottom:9px}
  </style>
  <div class="daily-info-page">
    <div id="dailyInfoList" class="daily-info-list"></div>
  </div>
</section>`;
