export const DAILY_REWARDS_STYLES = `
.content:has(#home.active){overflow:visible!important}
#home.view.active{overflow-y:hidden!important;overflow-x:visible!important;padding-bottom:0!important}
#home .home-daily-rewards-section{position:fixed;left:50%;top:0;width:min(100%,560px);height:100dvh;transform:translateX(-50%);overflow:visible!important;box-sizing:border-box;z-index:95;pointer-events:none;margin:0!important;padding:0!important}
#home .home-daily-rewards-head{display:none!important}
#home .home-daily-rewards-days{position:absolute;left:0;right:0;top:0;bottom:0;width:100%;height:100%;overflow:visible!important;pointer-events:none;margin:0!important;padding:0!important;contain:none!important}
#home .home-daily-rewards-days::-webkit-scrollbar{display:none}
#home .daily-rewards-drop-banner{position:absolute;left:59%;top:calc(-16px + env(safe-area-inset-top));width:148px;height:194px;border:0!important;outline:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;box-sizing:border-box;overflow:visible!important;padding:0!important;display:block!important;cursor:pointer;appearance:none!important;-webkit-appearance:none!important;pointer-events:auto;transform:translate(-42%,0);transform-origin:50% 0;animation:dailyRewardFlagDrop 1.04s cubic-bezier(.16,.92,.2,1.02) both;will-change:transform,opacity;z-index:96}
#home .daily-rewards-drop-banner:before,#home .daily-rewards-drop-banner:after{display:none!important;content:none!important;background:none!important;border:0!important;box-shadow:none!important}
#home .daily-rewards-banner-frame{position:absolute;inset:0;display:block;border-radius:0!important;overflow:visible!important;background:transparent!important;transform-origin:50% 0;animation:dailyRewardFlagUnfurl 1.04s cubic-bezier(.18,.86,.18,1) both}
#home .daily-rewards-banner-img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;object-position:center top;display:block;border:0!important;outline:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;opacity:1;filter:brightness(.94);transform-origin:50% 0;animation:dailyRewardFlagWave 1.04s ease-out both}
#home .daily-rewards-drop-banner.locked .daily-rewards-banner-img{filter:grayscale(.35) brightness(.62);opacity:.48}
#home .daily-rewards-drop-banner.claimed .daily-rewards-banner-img{opacity:.72;filter:saturate(.82) brightness(.82)}
#home .daily-rewards-drop-banner.can-claim:active{transform:translate(-42%,0) scale(.985)}
#home .daily-rewards-drop-banner.claiming{pointer-events:none;filter:brightness(1.08)!important}
@keyframes dailyRewardFlagDrop{0%{opacity:0;transform:translate(-42%,-118%) rotate(.2deg)}42%{opacity:1;transform:translate(-42%,-8%) rotate(-1.6deg)}64%{opacity:1;transform:translate(-42%,3px) rotate(1.1deg)}82%{opacity:1;transform:translate(-42%,-2px) rotate(-.45deg)}100%{opacity:1;transform:translate(-42%,0) rotate(0)}}
@keyframes dailyRewardFlagUnfurl{0%{clip-path:inset(0 0 100% 0);transform:scaleY(.18)}46%{clip-path:inset(0 0 13% 0);transform:scaleY(1.025)}72%{clip-path:inset(0 0 0 0);transform:scaleY(.985)}100%{clip-path:inset(0 0 0 0);transform:scaleY(1)}}
@keyframes dailyRewardFlagWave{0%{transform:perspective(420px) rotateX(-5deg) skewX(0deg)}45%{transform:perspective(420px) rotateX(3deg) skewX(-1.8deg)}68%{transform:perspective(420px) rotateX(-1.2deg) skewX(1deg)}100%{transform:perspective(420px) rotateX(0) skewX(0)}}
@media(max-width:380px){#home .daily-rewards-drop-banner{left:60%;top:calc(-18px + env(safe-area-inset-top));width:136px;height:178px;transform:translate(-42%,0)}#home .daily-rewards-drop-banner.can-claim:active{transform:translate(-42%,0) scale(.985)}}
`;