export const DEPOSIT_ENHANCEMENTS_SCRIPT = `
(function(){
  var STARS_TO_NANO=5890080;
  var tg=window.Telegram&&window.Telegram.WebApp;
  var ownerId=localStorage.getItem('ownerId')||String((tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user&&tg.initDataUnsafe.user.id)||'');
  function q(id){return document.getElementById(id)}
  function tonText(nano){var value=Math.abs(Math.floor(Number(nano)||0))/1000000000;return value.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')+' TON'}
  function dateText(value){try{return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return String(value||'')}}
  function escapeHtml(value){return String(value||'').replace(/[&<>'\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]||c})}
  function toast(text){var n=q('toast');if(!n)return;n.textContent=text;n.style.display='block';setTimeout(function(){n.style.display='none'},2600)}
  async function api(path,payload){var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Request failed');return j}
  async function getJson(path){var r=await fetch(path,{headers:{'accept':'application/json'}});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Request failed');return j}
  function installSheetFixStyles(){
    var style=document.getElementById('vexa-deposit-withdraw-sheet-fix');
    if(!style){style=document.createElement('style');style.id='vexa-deposit-withdraw-sheet-fix';document.head.appendChild(style)}
    style.textContent='#depositSheet.deposit-sheet,#withdrawSheet.deposit-sheet{position:fixed!important;inset:0!important;z-index:10080!important;display:none!important;align-items:flex-end!important;justify-content:center!important;padding:16px 16px calc(16px + env(safe-area-inset-bottom))!important;pointer-events:none!important;opacity:1!important;visibility:visible!important}#depositSheet.deposit-sheet.open,#withdrawSheet.deposit-sheet.open{display:flex!important;pointer-events:auto!important;opacity:1!important;visibility:visible!important}#depositSheet .deposit-backdrop,#withdrawSheet .deposit-backdrop{position:absolute!important;inset:0!important;z-index:0!important;background:rgba(0,0,0,.56)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important}#depositSheet .deposit-panel,#withdrawSheet .deposit-panel{position:relative!important;z-index:2!important;left:auto!important;right:auto!important;bottom:auto!important;width:min(100%,528px)!important;max-height:min(86dvh,680px)!important;margin:0 auto!important;padding:0!important;border-radius:32px!important;background:linear-gradient(180deg,rgba(24,24,24,.92),rgba(8,8,8,.82))!important;border:1px solid rgba(255,255,255,.10)!important;box-shadow:0 24px 70px rgba(0,0,0,.58),inset 0 1px 0 rgba(255,255,255,.12)!important;overflow:auto!important;display:block!important;opacity:1!important;visibility:visible!important;transform:translateY(0) scale(1)!important;animation:depositIn .28s cubic-bezier(.2,.8,.2,1)!important}#depositSheet .deposit-panel .pad,#withdrawSheet .deposit-panel .pad{padding:18px!important;display:block!important;opacity:1!important;visibility:visible!important}#depositSheet .deposit-title,#withdrawSheet .deposit-title{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;opacity:1!important;visibility:visible!important}#depositSheet .deposit-copy,#withdrawSheet .deposit-copy,#depositSheet .deposit-custom-field,#withdrawSheet .deposit-custom-field,#depositSheet .deposit-pay-button,#withdrawSheet .deposit-pay-button,#depositSheet .deposit-stars-logo,#withdrawSheet .withdraw-status{opacity:1!important;visibility:visible!important}#depositSheet .deposit-title-main,#withdrawSheet .deposit-title-main{display:flex!important;align-items:center!important;gap:10px!important;min-width:0!important}#depositSheet .deposit-title h3,#withdrawSheet .deposit-title h3{margin:0!important;color:#fff!important}#depositSheet input,#withdrawSheet input{display:block!important;color:#fff!important;background:rgba(255,255,255,.06)!important;border:1px solid rgba(255,255,255,.14)!important}#depositSheet .primary,#withdrawSheet .primary{display:flex!important}body.deposit-open .tabs,body.withdraw-open .tabs{opacity:0!important;transform:translateY(80px)!important;pointer-events:none!important}';
  }
  function updateEquivalent(){var input=q('starsAmountSheet');var out=q('starsTonEquivalent');if(!out)return;var stars=Math.max(0,Math.floor(Number(input&&input.value)||0));out.textContent=stars>0?'≈ '+tonText(stars*STARS_TO_NANO):'≈ 0 TON'}
  function makeSheetsGlobal(){['depositSheet','withdrawSheet','transactionsSheet'].forEach(function(id){var sheet=q(id);if(sheet&&sheet.parentElement!==document.body)document.body.appendChild(sheet)})}
  function makeTransactionsGlobal(){makeSheetsGlobal()}
  function syncOpenState(){var deposit=q('depositSheet');var withdraw=q('withdrawSheet');var transactions=q('transactionsSheet');document.body.classList.toggle('deposit-open',!!(deposit&&deposit.classList.contains('open')));document.body.classList.toggle('withdraw-open',!!(withdraw&&withdraw.classList.contains('open')));document.body.classList.toggle('transactions-open',!!(transactions&&transactions.classList.contains('open')))}
  function setDepositKeyboard(open){document.body.classList.toggle('deposit-keyboard-open',!!open)}
  function setSheet(id,open){installSheetFixStyles();makeSheetsGlobal();var sheet=q(id);if(!sheet)return;sheet.classList.toggle('open',!!open);sheet.setAttribute('aria-hidden',open?'false':'true');setTimeout(syncOpenState,20)}
  function openTransactions(){setSheet('transactionsSheet',true);loadTransactions()}
  function resetWithdraw(){var status=q('withdrawStatus');var success=q('withdrawSuccess');var content=document.querySelector('.withdraw-content');if(status)status.textContent='';if(success){success.classList.remove('show');success.setAttribute('aria-hidden','true')}if(content)content.classList.remove('withdraw-done')}
  function transactionIcon(kind,positive){if(positive)return '<svg viewBox="0 0 48 48" fill="none"><path d="M24 8v24" stroke="currentColor" stroke-width="3.2" stroke-linecap="round"/><path d="M14 22l10 10 10-10" stroke="currentColor" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></svg>';return '<svg viewBox="0 0 48 48" fill="none"><path d="M24 40V16" stroke="currentColor" stroke-width="3.2" stroke-linecap="round"/><path d="M14 26l10-10 10 10" stroke="currentColor" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></svg>'}
  function rowHtml(item){var amountNano=Math.floor(Number(item.amountNano)||0);var positive=amountNano>=0;var kind=String(item.kind||'adjustment');var title=escapeHtml(item.title||((kind==='deposit')?'Stars purchase':'TON withdrawal'));var desc=escapeHtml(item.description||(kind==='deposit'?'Deposit':'Withdraw'));var sub=desc+' • '+dateText(item.createdAt);var status=String(item.status||'completed').toLowerCase();var amount=(positive?'+':'-')+tonText(amountNano);return '<div class="transaction-row"><span class="transaction-icon '+(positive?'in':'out')+'">'+transactionIcon(kind,positive)+'</span><span class="transaction-main"><strong>'+title+'</strong><span>'+sub+'</span></span><span class="transaction-side"><b>'+amount+'</b><em class="'+status+'">'+escapeHtml(status)+'</em></span></div>'}
  function isWalletTransaction(item){var kind=String(item&&item.kind||'').toLowerCase();return kind==='deposit'||kind==='withdraw'}
  async function loadTransactions(){var list=q('transactionsList');if(!list)return;if(!ownerId){list.innerHTML='<div class="transactions-empty">Telegram user not found</div>';return}list.innerHTML='<div class="transactions-empty">Loading transactions</div>';try{var result=await getJson('/app/api/ton/history?wallet=1&userId='+encodeURIComponent(ownerId)+'&limit=100');var items=(result.transactions||[]).filter(isWalletTransaction);list.innerHTML=items.length?items.map(rowHtml).join(''):'<div class="transactions-empty">No deposits or withdrawals yet</div>'}catch(error){list.innerHTML='<div class="transactions-empty">'+escapeHtml(error&&error.message?error.message:'Could not load transactions')+'</div>'}}
  async function submitWithdraw(){var amount=q('withdrawAmountTon');var wallet=q('withdrawWalletAddress');var status=q('withdrawStatus');var success=q('withdrawSuccess');var content=document.querySelector('.withdraw-content');if(!ownerId){toast('Telegram user not found');return}if(status)status.textContent='Submitting withdrawal request';if(success){success.classList.remove('show');success.setAttribute('aria-hidden','true')}if(content)content.classList.remove('withdraw-done');try{await api('/app/api/ton/withdrawals',{userId:ownerId,amountTon:amount&&amount.value,walletAddress:wallet&&wallet.value});if(status)status.textContent='';if(content)content.classList.add('withdraw-done');if(success){success.classList.add('show');success.setAttribute('aria-hidden','false')}if(window.VexaTonBalance&&window.VexaTonBalance.load)setTimeout(function(){window.VexaTonBalance.load()},500)}catch(error){if(status)status.textContent=error&&error.message?error.message:'Withdrawal failed';toast(error&&error.message?error.message:'Withdrawal failed')}}
  function ownFinanceEvent(ev){ev.preventDefault();ev.stopPropagation();if(ev.stopImmediatePropagation)ev.stopImmediatePropagation()}
  function bind(){installSheetFixStyles();makeSheetsGlobal();updateEquivalent();syncOpenState();['depositSheet','withdrawSheet','transactionsSheet'].forEach(function(id){var sheet=q(id);if(sheet&&window.MutationObserver)new MutationObserver(syncOpenState).observe(sheet,{attributes:true,attributeFilter:['class','aria-hidden']})});document.addEventListener('input',function(ev){if(ev.target&&ev.target.id==='starsAmountSheet')updateEquivalent()});document.addEventListener('focusin',function(ev){if(ev.target&&(ev.target.id==='starsAmountSheet'||ev.target.id==='withdrawAmountTon'||ev.target.id==='withdrawWalletAddress'))setDepositKeyboard(true)});document.addEventListener('focusout',function(ev){if(ev.target&&(ev.target.id==='starsAmountSheet'||ev.target.id==='withdrawAmountTon'||ev.target.id==='withdrawWalletAddress'))setTimeout(function(){var a=document.activeElement;if(!a||!['starsAmountSheet','withdrawAmountTon','withdrawWalletAddress'].includes(a.id))setDepositKeyboard(false)},80)});document.addEventListener('click',function(ev){var target=ev.target;var creditTarget=target&&target.closest&&target.closest('[data-ton-balance-display],.top-balance-pill,.ton-mini-icon');if(creditTarget){ev.preventDefault();ev.stopPropagation();openTransactions();return}var button=target&&target.closest?target.closest('button'):null;if(!button)return;var action=button.getAttribute('data-action');if(action==='open-deposit'){ownFinanceEvent(ev);setSheet('depositSheet',true);updateEquivalent();return}if(action==='close-deposit'){ownFinanceEvent(ev);setDepositKeyboard(false);setSheet('depositSheet',false);return}if(action==='open-withdraw'){ownFinanceEvent(ev);resetWithdraw();setSheet('withdrawSheet',true);return}if(action==='close-withdraw'){ownFinanceEvent(ev);setDepositKeyboard(false);setSheet('withdrawSheet',false);return}if(action==='submit-withdraw'){ownFinanceEvent(ev);submitWithdraw();return}if(action==='open-transactions'){openTransactions()}if(action==='close-transactions'){setSheet('transactionsSheet',false)}},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;