import { DICE_SECTION as RAW_DICE_SECTION } from './dice';

const DICE_SAFE_STYLES = `
body:has(#dice.active) #brandTitle{display:inline-flex!important;align-items:center!important;gap:8px!important}
.dice-view .dice-range-card{position:fixed!important;top:calc(env(safe-area-inset-top) + 138px)!important;left:14px!important;right:14px!important;z-index:8!important;width:auto!important;max-width:520px!important;height:170px!important;margin:0 auto!important;padding:18px 12px!important;border-radius:28px!important;background:rgba(0,0,0,.62)!important;border:1px solid rgba(255,255,255,.12)!important;box-sizing:border-box!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;justify-content:center!important;gap:0!important;backdrop-filter:blur(14px) saturate(1.16)!important;-webkit-backdrop-filter:blur(14px) saturate(1.16)!important}.dice-view .dice-track-labels{height:18px!important;padding:0 19px!important;transform:translateY(14px)!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:800!important}.dice-view .dice-slider-shell{width:100%!important;margin-top:0!important}.dice-view .dice-slider-visual{background:rgba(0,0,0,.78)!important}.dice-view .dice-slider-thumb{width:34px!important;height:34px!important}
.dice-view .dice-panel{position:relative!important;padding:0 14px 7px!important;overflow:hidden!important}.dice-view .dice-stats{display:none!important}.dice-view .dice-uploaded-stats-image{position:absolute!important;left:50%!important;top:138px!important;transform:translateX(-50%)!important;width:min(486px,calc(100% - 28px))!important;height:auto!important;display:none!important;margin:0!important;object-fit:contain!important;pointer-events:none!important;z-index:1!important}.dice-view .dice-uploaded-stats-image.is-visible{display:block!important}.dice-view .dice-control-grid{position:relative!important;z-index:2!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:9px!important;width:min(486px,100%)!important;height:74px!important;min-height:74px!important;margin:138px auto -6px!important;align-items:center!important}.dice-view .dice-field,.dice-view .dice-field.active,.dice-view .dice-mode-field,.dice-view .dice-mode-field.active,.dice-view .dice-mode-field:hover,.dice-view .dice-mode-field:focus,.dice-view .dice-mode-field:active{height:74px!important;min-height:74px!important;padding:12px 13px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;border:0!important;box-shadow:none!important;outline:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.dice-view .dice-field:before,.dice-view .dice-field:after,.dice-view .dice-mode-field:before,.dice-view .dice-mode-field:after{display:none!important;content:none!important}.dice-view .dice-field small{font-size:13px!important;color:rgba(255,255,255,.62)!important;font-weight:900!important;text-shadow:0 4px 12px rgba(0,0,0,.75)!important}.dice-view .dice-field b{margin-top:13px!important;font-size:22px!important;color:#fff!important;font-weight:900!important;text-shadow:0 7px 18px rgba(0,0,0,.85)!important}.dice-view .dice-mode-field i{color:rgba(255,255,255,.78)!important}
.dice-view .dice-bet{grid-column:1/-1!important;justify-self:center!important;position:relative!important;display:grid!important;grid-template-columns:.74fr 1.52fr .74fr!important;width:min(486px,100%)!important;height:48px!important;margin:24px auto -12px!important;overflow:visible!important;background:transparent!important;border:0!important;box-shadow:none!important}.dice-view .dice-bet .dice-bet-row-image{position:absolute!important;left:0!important;top:50%!important;width:100%!important;height:auto!important;transform:translateY(-50%) scale(1.25)!important;object-fit:contain!important;opacity:0!important;pointer-events:none!important}.dice-view .dice-bet.has-dice-image .dice-bet-row-image{opacity:1!important}.dice-view .dice-bet.has-dice-image button,.dice-view .dice-bet.has-dice-image button.active,.dice-view .dice-bet.has-dice-image .dice-bet-main{position:relative!important;z-index:1!important;background:transparent!important;border:0!important;box-shadow:none!important;color:transparent!important;text-shadow:none!important}.dice-view .dice-roll-button{grid-column:1/-1!important;justify-self:center!important;position:relative!important;display:flex!important;align-items:center!important;justify-content:center!important;width:min(486px,100%)!important;height:56px!important;margin:28px auto -4px!important;overflow:visible!important;background:transparent!important;border:0!important;box-shadow:none!important;color:transparent!important;padding:0!important}.dice-view .dice-roll-button .dice-roll-button-image{position:absolute!important;left:0!important;top:50%!important;width:100%!important;height:auto!important;transform:translateY(-22%) scale(1.18)!important;object-fit:contain!important;opacity:0!important;pointer-events:none!important}.dice-view .dice-roll-button.has-dice-image .dice-roll-button-image{opacity:1!important}.dice-view .dice-slider-shell.has-dice-thumb-image .dice-slider-thumb{width:52px!important;height:52px!important;border:0!important;border-radius:0!important;background-color:transparent!important;background-image:var(--dice-slider-image)!important;background-size:contain!important;background-position:center!important;background-repeat:no-repeat!important;box-shadow:none!important}
@media(max-width:420px){.dice-view .dice-range-card{top:calc(env(safe-area-inset-top) + 130px)!important;height:150px!important}.dice-view .dice-panel{padding:0 12px 6px!important}.dice-view .dice-uploaded-stats-image{top:134px!important;width:min(432px,calc(100% - 24px))!important}.dice-view .dice-control-grid{width:min(432px,100%)!important;height:70px!important;min-height:70px!important;margin:134px auto -7px!important;gap:7px!important}.dice-view .dice-field,.dice-view .dice-field.active,.dice-view .dice-mode-field,.dice-view .dice-mode-field.active{height:70px!important;min-height:70px!important;padding:11px 11px!important;background:transparent!important;border:0!important;box-shadow:none!important}.dice-view .dice-field small{font-size:12px!important}.dice-view .dice-field b{margin-top:12px!important;font-size:21px!important}.dice-view .dice-bet{width:min(432px,100%)!important;height:46px!important;margin:24px auto -12px!important}.dice-view .dice-bet .dice-bet-row-image{transform:translateY(-50%) scale(1.30)!important}.dice-view .dice-roll-button{width:min(432px,100%)!important;height:54px!important;margin:30px auto -4px!important}.dice-view .dice-roll-button .dice-roll-button-image{transform:translateY(-20%) scale(1.22)!important}.dice-view .dice-slider-shell.has-dice-thumb-image .dice-slider-thumb{width:48px!important;height:48px!important}}
`;

const DICE_ACTION_BUTTON_STYLE = 'style="background:transparent!important;background-image:none!important;color:transparent!important;border:0!important;box-shadow:none!important;outline:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;text-shadow:none!important;"';
const DICE_ASSET_SCRIPT = `(function(){var root=document.getElementById('dice');if(!root||root.dataset.diceAssetsReady)return;root.dataset.diceAssetsReady='1';var rollUrl='',betUrl='',statsUrl='';function addImg(parent,cls,url){if(!parent||!url)return;var img=parent.querySelector('.'+cls);if(!img){img=document.createElement('img');img.className=cls;img.alt='';img.setAttribute('aria-hidden','true');parent.insertBefore(img,parent.firstChild)}if(img.getAttribute('src')!==url)img.src=url}function paint(){var roll=root.querySelector('[data-dice-play]');var bet=root.querySelector('.dice-bet');var grid=root.querySelector('.dice-control-grid');if(roll&&rollUrl){addImg(roll,'dice-roll-button-image',rollUrl);roll.classList.add('has-dice-image')}if(bet&&betUrl){addImg(bet,'dice-bet-row-image',betUrl);bet.classList.add('has-dice-image')}if(grid&&statsUrl){var img=root.querySelector('.dice-uploaded-stats-image');if(!img){img=document.createElement('img');img.className='dice-uploaded-stats-image';img.alt='';img.setAttribute('aria-hidden','true');grid.parentNode.insertBefore(img,grid)}if(img.getAttribute('src')!==statsUrl)img.src=statsUrl;img.classList.add('is-visible')}}function apply(assets){var map={};(assets||[]).forEach(function(a){if(a&&a.id&&a.imageUrl)map[a.id]=a.imageUrl});rollUrl=map.roll||rollUrl;betUrl=map.bet||betUrl;statsUrl=map.stats||statsUrl;paint();var slider=root.querySelector('[data-dice-slider-wrap]');if(slider&&map.slider){slider.style.setProperty('--dice-slider-image','url("'+String(map.slider).replace(/"/g,'%22')+'")');slider.classList.add('has-dice-thumb-image')}}fetch('/app/api/dice-assets',{cache:'no-store',credentials:'same-origin'}).then(function(r){return r.ok?r.json():null}).then(function(j){if(j)apply(j.assets||[])}).catch(function(){});var roll=root.querySelector('[data-dice-play]');if(roll){try{new MutationObserver(paint).observe(roll,{childList:true,characterData:true,subtree:true})}catch(e){}roll.addEventListener('click',function(){setTimeout(paint,0);setTimeout(paint,100);setTimeout(paint,500)},true)}})();`;

export const DICE_SECTION = RAW_DICE_SECTION
  .replace('</style>', DICE_SAFE_STYLES + '</style>')
  .replace('<button class="dice-roll-button" type="button" data-dice-play>', '<button class="dice-roll-button" type="button" data-dice-play ' + DICE_ACTION_BUTTON_STYLE + '>')
  .replace('</script></section>', DICE_ASSET_SCRIPT + '</script></section>')
  .replace('data-dice-bet-input-open>1</button>', 'data-dice-bet-input-open>1.00</button>')
  .replace('<b data-dice-current>1</b>', '<b data-dice-current>1.00</b>')
  .replace('min="1" inputmode="decimal" value="1"', 'min="0.01" step="0.01" inputmode="decimal" value="1.00"')
  .replace("function money(n){var x=Number(n)||0;return x.toFixed(4).replace(/\\.0+$/,'').replace(/(\\.\\d*?)0+$/,'$1')}", "function money(n){var x=Number(n)||0;return x.toFixed(2)}")
  .replace("function cleanBet(n){var s=String(n==null?'':n).replace(',','.').trim();if(!s)return 1;return Math.max(.0001,Number(s)||1)}", "function cleanBet(n){var s=String(n==null?'':n).replace(',','.').trim();if(!s)return 1;var v=Math.max(.01,Number(s)||1);return Math.round(v*100)/100}")
  .replace('setBet(Math.max(.0001,bet/2))', 'setBet(Math.max(.01,bet/2))');