import { DICE_SECTION as RAW_DICE_SECTION } from './dice';

const DICE_POLISH_STYLES = `
body:has(#dice.active) #brandTitle{display:inline-flex!important;align-items:center!important;gap:8px!important}
#dice.dice-view{filter:brightness(1.08) contrast(1.02)!important}
.dice-view .dice-wrap{width:100%!important;max-width:520px!important;box-sizing:border-box!important;margin-left:auto!important;margin-right:auto!important;gap:12px!important;padding-bottom:max(14px,env(safe-area-inset-bottom))!important}
.dice-view .dice-range-card{position:fixed!important;top:calc(env(safe-area-inset-top) + 138px)!important;left:14px!important;right:14px!important;z-index:8!important;width:auto!important;max-width:520px!important;height:170px!important;margin:0 auto!important;padding:18px 12px!important;box-sizing:border-box!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;transform:none!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;justify-content:center!important;gap:0!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
.dice-view .dice-track-labels{flex:0 0 auto!important;height:18px!important;padding:0 19px!important;transform:translateY(14px)!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:800!important;z-index:5!important}
.dice-view .dice-slider-shell{flex:0 0 auto!important;width:100%!important;margin-top:0!important}.dice-view .dice-slider-visual{background:rgba(0,0,0,.78)!important}.dice-view .dice-slider-thumb{width:34px!important;height:34px!important;border-radius:12px!important;backdrop-filter:blur(7px) saturate(1.22)!important;-webkit-backdrop-filter:blur(7px) saturate(1.22)!important}
.dice-online-badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;min-width:0!important;color:rgba(255,255,255,.90)!important;font-size:10.5px!important;font-weight:900!important;letter-spacing:-.02em!important;white-space:nowrap!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:0!important;margin-left:2px!important;transform:translateY(1px)!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}.dice-online-badge i{width:8px!important;height:8px!important;border-radius:50%!important;background:#18ff84!important;box-shadow:0 0 0 1px rgba(24,255,132,.25),0 0 10px rgba(24,255,132,.46),0 0 20px rgba(24,255,132,.18),inset 0 1px 0 rgba(255,255,255,.34)!important;flex:0 0 auto!important;position:relative!important;animation:liveDotSoft 1.35s ease-in-out infinite!important}.dice-online-badge i::before{content:''!important;position:absolute!important;inset:-5px!important;border-radius:inherit!important;border:1px solid rgba(24,255,132,.46)!important;opacity:.45!important;animation:liveDotRing 1.35s ease-in-out infinite!important}.dice-online-badge em{font-style:normal!important;font-size:8px!important;font-weight:900!important;letter-spacing:.08em!important;color:rgba(24,255,132,.92)!important;text-transform:uppercase!important;line-height:1!important}.dice-online-badge b{display:inline-block!important;min-width:23px!important;font-size:10.5px!important;font-weight:900!important;color:rgba(255,255,255,.90)!important;text-shadow:0 6px 14px rgba(0,0,0,.56),0 0 10px rgba(255,255,255,.08)!important;font-variant-numeric:tabular-nums!important}
.dice-view .dice-result-card{position:fixed!important;top:calc(env(safe-area-inset-top) + 318px)!important;left:14px!important;right:14px!important;z-index:7!important;width:auto!important;max-width:520px!important;margin:0 auto!important;padding:14px!important;box-sizing:border-box!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;overflow:hidden!important;max-height:430px!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),padding .28s ease,opacity .2s ease!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}.dice-view .dice-result-card:not(.open){max-height:54px!important;padding-bottom:12px!important}.dice-view .dice-result-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:10px!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important}.dice-view .dice-result-title{display:inline-flex!important;align-items:center!important;gap:7px!important;min-width:0!important;color:rgba(255,255,255,.58)!important}.dice-view .dice-result-title svg{width:17px!important;height:17px!important;display:block!important;flex:0 0 auto!important;color:rgba(255,255,255,.55)!important}.dice-view .dice-result-title svg path{fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}.dice-view .dice-result-head-actions{display:flex!important;align-items:center!important;gap:8px!important}.dice-view .dice-result-total{color:rgba(255,255,255,.92)!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important}.dice-view .dice-result-toggle{width:28px!important;height:28px!important;border:0!important;outline:0!important;border-radius:10px!important;background:rgba(255,255,255,.055)!important;color:rgba(255,255,255,.85)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;box-shadow:none!important;transition:transform .22s ease,background .18s ease!important}.dice-view .dice-result-toggle svg{width:18px!important;height:18px!important;display:block!important;transition:transform .28s cubic-bezier(.2,.8,.2,1)!important}.dice-view .dice-result-toggle path{fill:none!important;stroke:currentColor!important;stroke-width:2.4!important;stroke-linecap:round!important;stroke-linejoin:round!important}.dice-view .dice-result-card.open .dice-result-toggle svg{transform:rotate(180deg)!important}.dice-view .dice-result-toggle:active{transform:scale(.94)!important;background:rgba(255,255,255,.09)!important}
.dice-view .dice-result-list{display:grid!important;gap:6px!important;max-height:394px!important;overflow-y:auto!important;overflow-x:hidden!important;padding-right:2px!important;scrollbar-width:thin!important;scrollbar-color:rgba(255,255,255,.18) transparent!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),opacity .22s ease!important}.dice-view .dice-result-card:not(.open) .dice-result-list{max-height:0!important;opacity:0!important;pointer-events:none!important}.dice-view .dice-result-empty{font-size:12px!important;font-weight:820!important;color:rgba(255,255,255,.45)!important;padding:14px 0!important;text-align:center!important}.dice-view .dice-result-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto auto!important;align-items:center!important;gap:8px!important;min-height:34px!important;border-radius:17px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(255,255,255,.08)!important;box-shadow:none!important;color:#fff!important;padding:2px 10px!important;backdrop-filter:blur(3px) saturate(1.06)!important;-webkit-backdrop-filter:blur(3px) saturate(1.06)!important}.dice-view .dice-result-name{min-width:0!important;font-size:12px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;color:rgba(255,255,255,.92)!important}.dice-view .dice-result-value,.dice-view .dice-result-roll{font-size:11px!important;font-weight:930!important;color:rgba(255,255,255,.62)!important;white-space:nowrap!important}.dice-view .dice-result-row.is-positive .dice-result-value{color:#78ffb3!important}
.dice-view .dice-status{transform:none!important;min-height:22px!important;margin:0!important;display:flex!important;align-items:center!important;justify-content:center!important;line-height:1.15!important}.dice-view .dice-status.win{color:#35ff9a!important;text-shadow:0 0 14px rgba(53,255,154,.18)!important}.dice-view .dice-status.lose{color:#ff4f7b!important;text-shadow:0 0 14px rgba(255,79,123,.16)!important}
.dice-view .dice-panel{position:relative!important;width:min(520px,calc(100vw - 28px))!important;max-width:520px!important;box-sizing:border-box!important;margin-left:auto!important;margin-right:auto!important;align-self:center!important;padding:22px 20px 24px!important;gap:14px!important;min-height:0!important;height:auto!important;align-content:start!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;overflow:hidden!important;backdrop-filter:blur(30px) saturate(1.12)!important;-webkit-backdrop-filter:blur(30px) saturate(1.12)!important}
.dice-view .dice-control-grid{position:relative!important;z-index:2!important;display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;width:100%!important;height:58px!important;min-height:58px!important;margin:0 auto 2px!important;align-items:stretch!important}
.dice-view .dice-control-grid .dice-field,.dice-view .dice-control-grid .dice-field.active,.dice-view .dice-control-grid button.dice-mode-field,.dice-view .dice-control-grid button.dice-mode-field.active,.dice-view .dice-control-grid button.dice-mode-field:hover,.dice-view .dice-control-grid button.dice-mode-field:focus,.dice-view .dice-control-grid button.dice-mode-field:active{min-width:0!important;min-height:58px!important;height:58px!important;padding:7px 10px!important;border-radius:18px!important;background:rgba(255,255,255,.055)!important;background-color:rgba(255,255,255,.055)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045)!important;color:#fff!important;text-align:left!important;display:flex!important;flex-direction:column!important;justify-content:center!important;overflow:hidden!important;filter:none!important;appearance:none!important;-webkit-appearance:none!important;backdrop-filter:blur(8px) saturate(1.10)!important;-webkit-backdrop-filter:blur(8px) saturate(1.10)!important}
.dice-view .dice-control-grid button.dice-mode-field:before,.dice-view .dice-control-grid button.dice-mode-field:after{display:none!important;content:none!important}
.dice-view .dice-control-grid .dice-field small,.dice-view .dice-control-grid button.dice-mode-field small[data-dice-mode-label]{display:block!important;font-size:11px!important;line-height:1.05!important;font-weight:900!important;color:rgba(255,255,255,.52)!important;overflow:hidden!important;text-overflow:ellipsis!important;transform:none!important}
.dice-view .dice-control-grid .dice-field b,.dice-view .dice-control-grid button.dice-mode-field b{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-top:5px!important;min-width:0!important;width:100%!important;font-size:18px!important;line-height:1!important;font-weight:900!important;gap:5px!important;overflow:hidden!important;text-overflow:ellipsis!important;transform:none!important}
.dice-view .dice-control-grid .dice-field b span{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important}.dice-view .dice-mode-field i{color:rgba(255,255,255,.78)!important}.dice-view .dice-stats{display:none!important}.dice-view .dice-stat{display:none!important}
.dice-view .dice-bet{grid-column:1/-1!important;justify-self:center!important;position:relative!important;display:grid!important;grid-template-columns:.74fr 1.52fr .74fr!important;width:100%!important;height:56px!important;min-height:56px!important;margin:2px auto 0!important;gap:9px!important;overflow:visible!important;transform:none!important}.dice-view .dice-bet button{height:50px!important;border-radius:19px!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;line-height:1!important;text-align:center!important;font-size:16px!important}.dice-view .dice-bet .dice-bet-main,.dice-view .dice-bet .dice-bet-main.active{color:#fff!important;text-shadow:0 5px 14px rgba(0,0,0,.85)!important;font-size:18px!important;font-weight:900!important;letter-spacing:-.03em!important;font-variant-numeric:tabular-nums lining-nums!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:1px!important;padding-top:0!important;line-height:1!important;transform:none!important}.dice-view .dice-bet .dice-bet-main:before{content:''!important;width:25px!important;height:25px!important;flex:0 0 25px!important;display:block!important;background:url('/app/api/uploaded-image/ton-icon.png') center/contain no-repeat!important}
.dice-view .dice-bet-box{position:relative!important}.dice-view .dice-bet-box:before{content:''!important;position:absolute!important;left:calc(50% - 46px)!important;top:72px!important;width:32px!important;height:32px!important;z-index:2!important;pointer-events:none!important;background:url('/app/api/uploaded-image/ton-icon.png') center/contain no-repeat!important}.dice-view .dice-bet-input{padding-left:38px!important;padding-right:38px!important}
.dice-view .dice-roll-button{grid-column:1/-1!important;justify-self:center!important;position:relative!important;display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;height:62px!important;min-height:62px!important;margin:4px auto 0!important;padding:0!important;line-height:1!important;border-radius:24px!important;background:linear-gradient(180deg,rgba(92,10,34,.86),rgba(38,2,14,.92))!important;border-color:rgba(148,24,62,.32)!important;box-shadow:0 14px 32px rgba(0,0,0,.34),0 0 24px rgba(104,8,36,.22)!important;color:#fff!important;text-transform:uppercase!important;letter-spacing:.08em!important;font-weight:950!important;overflow:hidden!important;backdrop-filter:blur(3px) saturate(1.12)!important;-webkit-backdrop-filter:blur(3px) saturate(1.12)!important}.dice-view .dice-roll-button:before{display:none!important;content:none!important}.dice-view .dice-roll-button:active{transform:translateY(2px) scale(.98)!important;background:linear-gradient(180deg,rgba(64,5,23,.92),rgba(22,1,9,.96))!important}.dice-view .dice-roll-button.is-rolling{background:linear-gradient(180deg,rgba(64,5,23,.92),rgba(22,1,9,.96))!important}
@media(max-width:420px){.dice-view .dice-wrap{width:100%!important;max-width:520px!important;gap:10px!important;padding-bottom:max(12px,env(safe-area-inset-bottom))!important}.dice-view .dice-range-card{top:calc(env(safe-area-inset-top) + 126px)!important;left:14px!important;right:14px!important;width:auto!important;height:150px!important;padding:16px 10px!important}.dice-view .dice-track-labels{height:17px!important;font-size:12px!important;transform:translateY(13px)!important}.dice-view .dice-slider-thumb{width:32px!important;height:32px!important}.dice-view .dice-result-card{top:calc(env(safe-area-inset-top) + 288px)!important;left:14px!important;right:14px!important}.dice-view .dice-status{min-height:21px!important}.dice-view .dice-panel{width:calc(100vw - 28px)!important;max-width:520px!important;padding:18px 18px 20px!important;gap:12px!important;border-radius:28px!important}.dice-view .dice-control-grid{width:100%!important;height:56px!important;min-height:56px!important;margin:0 auto 0!important;gap:8px!important}.dice-view .dice-control-grid .dice-field,.dice-view .dice-control-grid .dice-field.active,.dice-view .dice-control-grid button.dice-mode-field,.dice-view .dice-control-grid button.dice-mode-field.active,.dice-view .dice-control-grid button.dice-mode-field:hover,.dice-view .dice-control-grid button.dice-mode-field:focus,.dice-view .dice-control-grid button.dice-mode-field:active{min-height:56px!important;height:56px!important;padding:6px 9px!important;border-radius:17px!important}.dice-view .dice-control-grid .dice-field small,.dice-view .dice-control-grid button.dice-mode-field small[data-dice-mode-label]{font-size:10.5px!important}.dice-view .dice-control-grid .dice-field b,.dice-view .dice-control-grid button.dice-mode-field b{margin-top:4px!important;font-size:17px!important}.dice-view .dice-bet{height:54px!important;min-height:54px!important;margin:2px auto 0!important;gap:8px!important}.dice-view .dice-bet button{height:48px!important;border-radius:18px!important}.dice-view .dice-bet .dice-bet-main:before{width:23px!important;height:23px!important;flex-basis:23px!important}.dice-view .dice-bet-box:before{left:calc(50% - 44px)!important;top:72px!important;width:30px!important;height:30px!important}.dice-view .dice-roll-button{height:58px!important;min-height:58px!important;margin:4px auto 0!important;border-radius:22px!important}}
`;

const DICE_RESULT_CARD = `<div class="dice-result-card" data-dice-result-card><div class="dice-result-head"><span class="dice-result-title"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16"/><path d="M7 12h10"/><path d="M9 17h6"/></svg><span>Results</span></span><div class="dice-result-head-actions"><b class="dice-result-total" data-dice-result-total>0</b><button class="dice-result-toggle" type="button" data-dice-result-toggle aria-label="Toggle results" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10l5 5 5-5"/></svg></button></div></div><div class="dice-result-list" data-dice-result-list><div class="dice-result-empty">No results yet</div></div></div>`;
const DICE_RESULT_SCRIPT = `(function(){var root=document.getElementById('dice');if(!root||root.dataset.resultHistoryReady)return;root.dataset.resultHistoryReady='1';var box=root.querySelector('[data-dice-result-card]'),toggle=root.querySelector('[data-dice-result-toggle]'),list=root.querySelector('[data-dice-result-list]'),total=root.querySelector('[data-dice-result-total]'),button=root.querySelector('[data-dice-play]'),roll=root.querySelector('[data-dice-roll]'),win=root.querySelector('[data-dice-win]'),amount=root.querySelector('[data-dice-current]'),rows=[];function value(el){return el?String(el.textContent||'').trim():''}function render(){if(!list)return;list.innerHTML='';if(!rows.length){var empty=document.createElement('div');empty.className='dice-result-empty';empty.textContent='No results yet';list.appendChild(empty);if(total)total.textContent='0';return}if(total)total.textContent=String(rows.length);rows.forEach(function(item){var row=document.createElement('div');row.className='dice-result-row'+(item.positive?' is-positive':'');var name=document.createElement('span');name.className='dice-result-name';name.textContent=item.label;var valueNode=document.createElement('b');valueNode.className='dice-result-value';valueNode.textContent=item.result;var rollNode=document.createElement('span');rollNode.className='dice-result-roll';rollNode.textContent=item.roll;row.appendChild(name);row.appendChild(valueNode);row.appendChild(rollNode);list.appendChild(row)})}function capture(){var resultValue=value(win),rollValue=value(roll),amountValue=value(amount),numericResult=Number(resultValue.replace(/[^0-9.-]/g,''))||0;rows.unshift({label:'You',result:numericResult>0?'+'+resultValue:resultValue,roll:rollValue?'Roll '+rollValue:'',positive:numericResult>0,amount:amountValue});rows=rows.slice(0,50);render()}if(toggle&&box){toggle.onclick=function(){var open=!box.classList.contains('open');box.classList.toggle('open',open);toggle.setAttribute('aria-expanded',open?'true':'false')}}if(button){button.addEventListener('click',function(){setTimeout(capture,520)})}})();`;

const LEGACY_DICE_CONTROL_STYLES = /\.dice-panel\{position:relative;border-radius:32px;[\s\S]*?letter-spacing:-\.04em;font-variant-numeric:tabular-nums lining-nums;white-space:nowrap\}/;
const LEGACY_DICE_CONTROL_MOBILE_STYLES = '.dice-panel{border-radius:30px}.dice-control-grid{gap:7px}.dice-field{min-height:80px;padding:11px 9px}.dice-field small{font-size:12px}.dice-field b{font-size:19px}';

export const DICE_SECTION = RAW_DICE_SECTION
  .replace(LEGACY_DICE_CONTROL_STYLES, '')
  .replace(LEGACY_DICE_CONTROL_MOBILE_STYLES, '')
  .replace('</style>', DICE_POLISH_STYLES + '</style>')
  .replace('<div class="dice-status" data-dice-status>', DICE_RESULT_CARD + '<div class="dice-status" data-dice-status>')
  .replace('</script></section>', DICE_RESULT_SCRIPT + '</script></section>')
  .replace('data-dice-bet-input-open>1</button>', 'data-dice-bet-input-open>1.00</button>')
  .replace('<b data-dice-current>1</b>', '<b data-dice-current>1.00</b>')
  .replace('min="1" inputmode="decimal" value="1"', 'min="0.01" step="0.01" inputmode="decimal" value="1.00"')
  .replace("function money(n){var x=Number(n)||0;return x.toFixed(4).replace(/\\.0+$/,'').replace(/(\\.\\d*?)0+$/,'$1')}", "function money(n){var x=Number(n)||0;return x.toFixed(2)}")
  .replace("function cleanBet(n){var s=String(n==null?'':n).replace(',','.').trim();if(!s)return 1;return Math.max(.0001,Number(s)||1)}", "function cleanBet(n){var s=String(n==null?'':n).replace(',','.').trim();if(!s)return 1;var v=Math.max(.01,Number(s)||1);return Math.round(v*100)/100}")
  .replace('setBet(Math.max(.0001,bet/2))', 'setBet(Math.max(.01,bet/2))');