// Final Dice control polish. Loaded after dice-fixed.ts so these rules are the last Dice control layer.
export const DICE_FINAL_TWEAK = `<style id="vexaDiceCrashGlassControls">
#dice .dice-panel{position:relative!important;display:grid!important;grid-template-columns:minmax(0,1fr)!important;grid-template-rows:41px 55px auto!important;width:100%!important;max-width:100%!important;min-width:0!important;margin:-8px 0 0!important;padding:8px 11px 10px!important;row-gap:0!important;column-gap:0!important;border-radius:28px!important;background:transparent!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;overflow:visible!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#dice .dice-panel>.dice-control-grid,#dice .dice-panel>.dice-bet{grid-column:1!important;width:100%!important;max-width:100%!important;min-width:0!important;justify-self:stretch!important;align-self:stretch!important;box-sizing:border-box!important}
#dice .dice-control-grid{height:41px!important;min-height:41px!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;column-gap:7px!important;row-gap:0!important;margin:0!important;padding:0!important;background:transparent!important;background-image:none!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
#dice .dice-control-grid .dice-field,#dice .dice-control-grid .dice-field.active,#dice .dice-control-grid button.dice-mode-field,#dice .dice-control-grid button.dice-mode-field.active,#dice .dice-control-grid button.dice-mode-field:hover,#dice .dice-control-grid button.dice-mode-field:focus,#dice .dice-control-grid button.dice-mode-field:active{min-width:0!important;min-height:41px!important;height:41px!important;display:grid!important;grid-template-rows:8px 15px!important;align-content:center!important;justify-content:stretch!important;row-gap:2px!important;padding:4px 9px!important;border-radius:15px!important;border:0!important;outline:0!important;background-color:rgba(255,255,255,.045)!important;background-image:linear-gradient(145deg,rgba(255,255,255,.105),rgba(255,255,255,.025) 58%,rgba(255,255,255,.045))!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.16),inset 0 -1px 0 rgba(255,255,255,.025),0 8px 22px rgba(0,0,0,.12)!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;filter:none!important;appearance:none!important;-webkit-appearance:none!important;overflow:hidden!important}
#dice .dice-control-grid .dice-field small,#dice .dice-control-grid button.dice-mode-field small[data-dice-mode-label]{display:flex!important;align-items:center!important;height:8px!important;margin:0!important;font-size:9px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important;color:rgba(255,255,255,.58)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;transform:none!important}
#dice .dice-control-grid .dice-field b,#dice .dice-control-grid button.dice-mode-field b{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;width:100%!important;height:15px!important;margin:0!important;column-gap:4px!important;min-width:0!important;font-size:15px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.035em!important;color:#fff!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;background:transparent!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;transform:none!important}
#dice .dice-control-grid .dice-field b>span,#dice .dice-control-grid button.dice-mode-field b>span{background:transparent!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#dice .dice-mode-field i{width:17px!important;height:17px!important;flex:0 0 17px!important;border-radius:0!important;display:grid!important;place-items:center!important;background:transparent!important;background-image:none!important;border:0!important;box-shadow:none!important;color:rgba(255,255,255,.78)!important;font-size:11px!important;line-height:1!important}
#dice .dice-bet{display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;height:41px!important;min-height:41px!important;margin:7px 0 7px!important;padding:0!important;column-gap:7px!important;row-gap:0!important;align-items:stretch!important;background:transparent!important;background-image:none!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;transform:none!important}
#dice .dice-bet button{width:100%!important;min-width:0!important;height:41px!important;border-radius:15px!important;border:0!important;outline:0!important;background-color:rgba(255,255,255,.038)!important;background-image:linear-gradient(145deg,rgba(255,255,255,.09),rgba(255,255,255,.018) 62%,rgba(255,255,255,.038))!important;color:#fff!important;-webkit-text-fill-color:#fff!important;display:grid!important;place-items:center!important;padding:0 8px!important;font-size:12px!important;line-height:1!important;font-weight:950!important;letter-spacing:0!important;text-align:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14),inset 0 -1px 0 rgba(255,255,255,.02),0 8px 22px rgba(0,0,0,.12)!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;text-shadow:none!important;overflow:hidden!important}
#dice .dice-bet .dice-bet-main,#dice .dice-bet .dice-bet-main.active{height:41px!important;border-radius:15px!important;border:0!important;background-color:rgba(255,255,255,.045)!important;background-image:linear-gradient(145deg,rgba(255,255,255,.105),rgba(255,255,255,.022) 60%,rgba(255,255,255,.045))!important;color:#fff!important;-webkit-text-fill-color:#fff!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:1px!important;padding:0 8px!important;font-size:16px!important;font-weight:900!important;letter-spacing:0!important;text-shadow:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.16),inset 0 -1px 0 rgba(255,255,255,.025),0 8px 22px rgba(0,0,0,.12)!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;transform:none!important}
#dice .dice-bet .dice-bet-main:before{content:''!important;width:27px!important;height:27px!important;flex:0 0 27px!important;display:block!important;margin-right:1px!important;background:url('/app/api/uploaded-image/ton-icon.png') center/contain no-repeat!important;filter:drop-shadow(0 2px 8px rgba(0,0,0,.34))!important;transform:translateY(2px)!important;pointer-events:none!important}
#dice .dice-roll-button{grid-column:1/-1!important;justify-self:center!important;width:100%!important;min-width:0!important;height:46px!important;min-height:46px!important;margin:0 auto!important;padding:0!important;border-radius:16px!important;border:0!important;outline:0!important;background-color:rgba(59,7,21,.58)!important;background-image:linear-gradient(145deg,rgba(112,22,48,.62),rgba(59,7,21,.40) 62%,rgba(39,4,13,.48))!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;font-size:15px!important;font-weight:900!important;letter-spacing:-.045em!important;text-transform:none!important;box-shadow:inset 0 1px 0 rgba(255,220,229,.14),inset 0 -1px 0 rgba(255,255,255,.018),0 10px 24px rgba(0,0,0,.20)!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;text-shadow:none!important;transition:transform .18s ease,opacity .18s ease,background .18s ease!important;overflow:hidden!important}
#dice .dice-roll-button.is-rolling{background-color:rgba(59,7,21,.58)!important;background-image:linear-gradient(145deg,rgba(112,22,48,.62),rgba(59,7,21,.40) 62%,rgba(39,4,13,.48))!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;transform:none!important}
#dice .dice-roll-button:not(:disabled):active{transform:scale(.975)!important}
#dice .dice-roll-button:disabled{opacity:.62!important;transform:none!important}
@media(max-width:420px){#dice .dice-panel{grid-template-rows:41px 55px auto!important;padding:8px 11px 10px!important}#dice .dice-control-grid{height:41px!important;min-height:41px!important;column-gap:7px!important}#dice .dice-control-grid .dice-field,#dice .dice-control-grid .dice-field.active,#dice .dice-control-grid button.dice-mode-field,#dice .dice-control-grid button.dice-mode-field.active,#dice .dice-control-grid button.dice-mode-field:hover,#dice .dice-control-grid button.dice-mode-field:focus,#dice .dice-control-grid button.dice-mode-field:active{height:41px!important;min-height:41px!important;border-radius:15px!important;padding:4px 8px!important}#dice .dice-bet{height:41px!important;min-height:41px!important;margin:7px 0 7px!important;column-gap:7px!important}#dice .dice-bet button,#dice .dice-bet .dice-bet-main,#dice .dice-bet .dice-bet-main.active{height:41px!important;border-radius:15px!important}#dice .dice-roll-button{height:46px!important;min-height:46px!important;margin:0 auto!important;border-radius:16px!important}}
</style>`;
