export const FOOTBALL_PREDICT_SCRIPT = `<script>
(function(){
  var NANO=1000000000;
  var ranges=['featured','today','tomorrow','week','all'];
  var labels={featured:'Featured',today:'Today',tomorrow:'Tomorrow',week:'This Week',all:'All Matches'};
  var state={matches:{featured:[],today:[],tomorrow:[],week:[],all:[]},history:[],sheet:null,loading:false,error:''};
  var timerId=0;
  function root(){return document.getElementById('predictzone')}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]||s})}
  function userId(){try{var tg=window.Telegram&&window.Telegram.WebApp;var u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;return String((u&&u.id)||localStorage.getItem('ownerId')||'').trim()}catch(e){return String(localStorage.getItem('ownerId')||'').trim()}}
  function ton(n){var v=Math.floor(Number(n)||0)/NANO;return v.toFixed(v>=10?2:3).replace(/0+$/,'').replace(/\.$/,'')}
  function dateText(v){try{return new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return ''}}
  function statusText(s){return s==='cancelled'?'Refunded':String(s||'open').charAt(0).toUpperCase()+String(s||'open').slice(1)}
  function pickLabel(m,p){return p==='team_a'?m.teamAName:p==='team_b'?m.teamBName:'Draw'}
  function logo(url,name){return '<span class="wc-team-logo '+(url?'has-logo':'')+'" '+(url?'style="background-image:url('+esc(url)+')"':'')+'>'+(url?'':esc(String(name||'?').slice(0,2).toUpperCase()))+'</span>'}
  function countdown(m){var st=m.computedStatus;if(st==='settled')return 'Settled';if(st==='cancelled')return 'Refunded';if(st==='locked')return 'Prediction locked';var left=Date.parse(m.lockAt)-Date.now();if(left<=0)return 'Prediction locked';var s=Math.ceil(left/1000),h=Math.floor(s/3600),mm=Math.floor((s%3600)/60),ss=s%60;return 'Closes in '+String(h).padStart(2,'0')+':'+String(mm).padStart(2,'0')+':'+String(ss).padStart(2,'0')}
  function poolsLine(m){return '<div class="wc-pools"><span>Total Pool: <b>'+ton((m.pools&&m.pools.total)||0)+' TON</b></span><span>Players: <b>'+Number(m.totalPlayers||0)+'</b></span></div>'}
  function userBetHtml(m){var b=m.userBet;if(!b)return '';var extra=b.status==='active'?'Potential '+ton(b.potentialPayoutNano||0)+' TON':(b.payoutNano?'Paid '+ton(b.payoutNano)+' TON':'');return '<div class="wc-user-bet"><b>Your pick: '+esc(pickLabel(m,b.pick))+'</b><span>Stake '+ton(b.stakeNano)+' TON • '+esc(statusText(b.status))+(extra?' • '+esc(extra):'')+'</span></div>'}
  function matchCard(m){var open=m.computedStatus==='open'&&!m.userBet;var disabled=open?'':' disabled';return '<article class="wc-match-card" data-wc-match="'+esc(m.id)+'"><div class="wc-match-top"><span>'+esc(m.tournament||'World Cup')+(m.stage?' / '+esc(m.stage):'')+'</span><b class="is-'+esc(m.computedStatus)+'">'+esc(statusText(m.computedStatus))+'</b></div><div class="wc-count" data-wc-lock="'+esc(m.lockAt)+'">'+esc(countdown(m))+'</div><div class="wc-teams"><div class="wc-team">'+logo(m.teamALogo,m.teamAName)+'<strong>'+esc(m.teamAName)+'</strong></div><div class="wc-vs"><span>VS</span><small>'+esc(dateText(m.startsAt))+'</small></div><div class="wc-team">'+logo(m.teamBLogo,m.teamBName)+'<strong>'+esc(m.teamBName)+'</strong></div></div>'+poolsLine(m)+'<div class="wc-pick-row"><button type="button" data-wc-pick="team_a"'+disabled+'>'+esc(m.teamAName)+'</button><button type="button" data-wc-pick="draw"'+disabled+'>Draw</button><button type="button" data-wc-pick="team_b"'+disabled+'>'+esc(m.teamBName)+'</button></div>'+userBetHtml(m)+'</article>'}
  function section(range){var list=state.matches[range]||[];return '<section class="wc-section"><div class="wc-section-head"><strong>'+labels[range]+'</strong><span>'+list.length+' matches</span></div>'+(list.length?'<div class="wc-list">'+list.map(matchCard).join('')+'</div>':'<div class="wc-empty">No matches here yet.</div>')+'</section>'}
  function historyHtml(){var rows=state.history||[];return '<section class="wc-history"><div class="wc-section-head"><strong>My Predictions</strong><span>Recent</span></div>'+(rows.length?rows.map(function(b){return '<div class="wc-history-row"><b>'+esc(b.match||'Match')+'</b><span>'+esc(b.pick)+' • '+ton(b.stakeNano)+' TON • '+esc(statusText(b.status))+' • Payout '+ton(b.payoutNano||0)+' TON</span><small>'+esc(dateText(b.createdAt))+'</small></div>'}).join(''):'<div class="wc-empty">Your World Cup predictions will appear here.</div>')+'</section>'}
  function render(){var r=root();if(!r)return;var shell=r.querySelector('.predict-zone-simple-shell');if(!shell)return;var view=r.querySelector('[data-football-predict-view]');if(!view){view=document.createElement('div');view.className='football-predict-view';view.setAttribute('data-football-predict-view','');shell.appendChild(view)}view.innerHTML='<section class="wc-hero"><p>Football / World Cup</p><h2>World Cup Predictions</h2><span>Pick the match result before kick-off</span></section>'+(state.error?'<div class="wc-error">'+esc(state.error)+'</div>':'')+ranges.map(section).join('')+historyHtml()+sheetHtml();syncBalance();tickTimers()}
  function sheetHtml(){var s=state.sheet;if(!s)return '<div class="wc-sheet" data-wc-sheet></div>';var m=s.match,p=s.pick,amount=s.amount||'';var title=p==='draw'?'Draw':pickLabel(m,p)+' to win';var est=estimate(m,p,Number(amount||0));return '<div class="wc-sheet open" data-wc-sheet><div class="wc-sheet-panel"><button class="wc-sheet-close" data-wc-close type="button">×</button><p>Selected Prediction</p><h3>'+esc(title)+'</h3><span>'+esc(m.teamAName)+' vs '+esc(m.teamBName)+'</span><label>Amount in TON<input data-wc-amount inputmode="decimal" value="'+esc(amount)+'" placeholder="0.1"></label><div class="wc-presets">'+[0.1,0.5,1,5].map(function(v){return '<button type="button" data-wc-preset="'+v+'">'+v+'</button>'}).join('')+'</div><div class="wc-est"><span>Estimated payout</span><b>'+ton(est)+' TON</b></div><div class="wc-est"><span>User balance</span><b data-wc-balance>'+ton(balance())+' TON</b></div><button class="wc-place" data-wc-place type="button">Place Prediction</button><div class="wc-status" data-wc-status>'+esc(s.status||'')+'</div></div></div>'}
  function balance(){return window.VexaTonBalance&&window.VexaTonBalance.read?Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0)):0}
  function estimate(m,p,amountTon){var stake=Math.floor((Number(amountTon)||0)*NANO);if(stake<=0)return 0;var pools=m.pools||{},winner=p==='team_a'?pools.teamA:p==='draw'?pools.draw:pools.teamB;winner=Math.max(0,Math.floor(Number(winner)||0))+stake;var total=Math.max(0,Math.floor(Number(pools.total)||0))+stake;var loser=Math.max(0,total-winner);return stake+Math.floor((stake/winner)*Math.max(0,loser-Math.floor(loser*500/10000)))}
  async function load(){var uid=userId();state.loading=true;try{var all=await Promise.all(ranges.map(function(range){return fetch('/app/api/world-cup/matches?range='+range+(uid?'&userId='+encodeURIComponent(uid):''),{cache:'no-store'}).then(function(r){return r.json()})}));ranges.forEach(function(range,i){state.matches[range]=(all[i]&&all[i].matches)||[]});if(uid){var h=await fetch('/app/api/world-cup/my-bets?userId='+encodeURIComponent(uid),{cache:'no-store'}).then(function(r){return r.json()}).catch(function(){return {predictions:[]}});state.history=h.predictions||[]}state.error=''}catch(e){state.error=e.message||'Could not load World Cup matches'}state.loading=false;render()}
  function show(){var r=root();if(!r)return;r.classList.add('football-predict-open');var grid=r.querySelector('[data-vexa-predict-group-grid]');if(grid)grid.style.display='none';var card=r.querySelector('[data-predict-card]');if(card)card.classList.add('predict-detail-hidden');var toolbar=r.querySelector('.predict-toolbar-row');if(toolbar)toolbar.style.display='none';var menu=r.querySelector('.predict-zone-category-menu');if(menu)menu.querySelectorAll('.predict-zone-category-card').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-vexa-predict-market')==='football')});load()}
  function hide(){var r=root();if(r)r.classList.remove('football-predict-open');state.sheet=null}
  function findMatch(id){var arr=state.matches.all.concat(state.matches.featured,state.matches.today,state.matches.tomorrow,state.matches.week);for(var i=0;i<arr.length;i++)if(arr[i].id===id)return arr[i];return null}
  async function place(){var s=state.sheet;if(!s)return;var uid=userId();var panel=document.querySelector('[data-wc-sheet]');var status=panel&&panel.querySelector('[data-wc-status]');try{if(!uid)throw new Error('Telegram user not found');var amount=Number((panel&&panel.querySelector('[data-wc-amount]')||{}).value||0);if(!(amount>0))throw new Error('Enter a valid TON amount');if(status)status.textContent='Placing prediction...';var res=await fetch('/app/api/world-cup/bets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({matchId:s.match.id,userId:uid,pick:s.pick,stakeTon:amount})});var json=await res.json();if(!res.ok||!json.ok)throw new Error(json.error||'Could not place prediction');if(json.userControls&&window.VexaTonBalance)window.VexaTonBalance.write(json.userControls.tonBalanceNano,0,false);state.sheet=null;await load()}catch(e){if(status)status.textContent=e.message||'Could not place prediction'}}
  function tickTimers(){var r=root();if(!r)return;r.querySelectorAll('[data-wc-lock]').forEach(function(el){var card=el.closest('[data-wc-match]'),m=card&&findMatch(card.getAttribute('data-wc-match'));if(m)el.textContent=countdown(m)})}
  function startTimers(){if(timerId)return;timerId=setInterval(tickTimers,1000)}
  function syncBalance(){try{if(window.VexaTonBalance&&window.VexaTonBalance.render)window.VexaTonBalance.render()}catch(e){}}
  function mount(){var r=root();if(!r||r.dataset.worldCupPredictReady==='1')return;r.dataset.worldCupPredictReady='1';startTimers();r.addEventListener('click',function(e){var close=e.target&&e.target.closest&&e.target.closest('[data-wc-close]');if(close){state.sheet=null;render();return}var preset=e.target&&e.target.closest&&e.target.closest('[data-wc-preset]');if(preset&&state.sheet){state.sheet.amount=preset.getAttribute('data-wc-preset');render();return}var placeBtn=e.target&&e.target.closest&&e.target.closest('[data-wc-place]');if(placeBtn){place();return}var pick=e.target&&e.target.closest&&e.target.closest('[data-wc-pick]');if(pick){var card=pick.closest('[data-wc-match]'),m=card&&findMatch(card.getAttribute('data-wc-match'));if(m){state.sheet={match:m,pick:pick.getAttribute('data-wc-pick'),amount:'0.1',status:''};render()}return}},true);r.addEventListener('input',function(e){var amt=e.target&&e.target.closest&&e.target.closest('[data-wc-amount]');if(amt&&state.sheet){state.sheet.amount=amt.value;var panel=amt.closest('[data-wc-sheet]');var est=panel&&panel.querySelector('.wc-est b');if(est)est.textContent=ton(estimate(state.sheet.match,state.sheet.pick,Number(amt.value||0)))+' TON'}},true);var menu=r.querySelector('.predict-zone-category-menu');if(menu){menu.addEventListener('click',function(e){var fb=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-market="football"]');if(fb){e.preventDefault();e.stopImmediatePropagation();show();return}var other=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-group],[data-vexa-predict-market]');if(other&&!fb)hide()},true)}document.addEventListener('click',function(e){var tab=e.target&&e.target.closest&&e.target.closest('[data-view="predictzone"]');if(tab)setTimeout(load,200)},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
</script>`;
