export const FOOTBALL_PREDICT_SCRIPT = `<script>
(function(){
  var matches=[],teams={},activeMatchId='',timerId=0,busy=0;
  function root(){return document.getElementById('predictzone')}
  function esc(v){return String(v==null?'':v).replace(/[&<>]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[s]||s})}
  function uid(){var tg=window.Telegram&&window.Telegram.WebApp,u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;return String((u&&u.id)||localStorage.getItem('ownerId')||'').trim()}
  function team(id){return teams[id]||{id:id,name:id.charAt(0).toUpperCase()+id.slice(1),logoUrl:''}}
  function logo(id,cls){var t=team(id),style=t.logoUrl?' style="background-image:url('+String(t.logoUrl).replace(/"/g,'')+')"':'';return '<span class="football-team-logo '+(cls||'')+' '+(t.logoUrl?'has-logo':'')+'"'+style+'></span>'}
  function findMatch(id){for(var i=0;i<matches.length;i++){if(matches[i].id===id)return matches[i]}return matches[0]||null}
  function liveBadge(cls){return '<span class="football-live-badge '+(cls||'')+'"><i class="football-live-dot"></i>LIVE</span>'}
  function matchStatus(m){return String((m&&m.status)||'open').toLowerCase()}
  function isOpen(m){return m&&!m.locked&&matchStatus(m)==='open'}
  function pickLabel(m,p){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b);return p==='draw'?'Draw':p==='team_b'?b.name:a.name}
  function headHtml(m,detail){return '<div class="football-match-head"><span class="football-match-left"><span class="football-match-tag">'+esc(m.stage||'Match')+'</span>'+liveBadge()+'</span>'+(detail?'':'<span class="football-match-time">'+esc(m.time||'')+'</span>')+'</div>'}
  function matchHtml(m){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b);return '<article class="football-match-card" data-football-match="'+esc(m.id)+'">'+headHtml(m,false)+'<div class="football-teams"><div class="football-team">'+logo(a.id)+'<b>'+esc(a.name)+'</b></div><div class="football-vs">VS</div><div class="football-team">'+logo(b.id)+'<b>'+esc(b.name)+'</b></div></div><div class="football-pick-row"><button type="button">'+esc(a.name)+'</button><button type="button">Draw</button><button type="button">'+esc(b.name)+'</button></div></article>'}
  function liveQuestion(label,key){return '<div class="football-live-question-row"><span>'+esc(label)+'</span><b data-football-countdown="'+esc(key)+'" data-football-deadline="'+(Date.now()+600000)+'">10:00</b><div class="football-live-actions"><button type="button">Yes</button><button type="button">No</button></div></div>'}
  function detailHtml(m){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b),ub=(m.userBets||[])[0],locked=!isOpen(m);return '<section class="football-detail-page" data-football-detail-view="" data-football-match-id="'+esc(m.id)+'"><div class="football-detail-scoreboard"><div class="football-detail-side">'+logo(a.id,'football-detail-logo')+'<b>'+esc(a.name)+'</b></div><div class="football-detail-vs">VS</div><div class="football-detail-side">'+logo(b.id,'football-detail-logo')+'<b>'+esc(b.name)+'</b></div></div><div class="football-detail-question"><strong>Who wins this match?</strong><span>'+(locked?'Match locked':ub?'Prediction placed':'Pick one result')+'</span></div><div class="football-detail-picks"><button type="button" class="football-detail-pick" data-football-pick="team_a" '+(locked||ub?'disabled':'')+'><span>'+esc(a.name)+'</span><b>Win</b></button><button type="button" class="football-detail-pick" data-football-pick="draw" '+(locked||ub?'disabled':'')+'><span>Draw</span><b>No winner</b></button><button type="button" class="football-detail-pick" data-football-pick="team_b" '+(locked||ub?'disabled':'')+'><span>'+esc(b.name)+'</span><b>Win</b></button></div><button type="button" class="football-confirm-pick" data-football-submit '+(locked||ub?'disabled':'')+'>'+(ub?'Prediction selected':locked?'Locked':'Choose prediction')+'</button><p class="football-pick-status" data-football-status>'+(ub?('Your pick: '+esc(pickLabel(m,ub.pick))):'')+'</p><section class="football-live-questions"><div class="football-live-questions-head"><strong>Live questions</strong><span>Next 10 min</span></div>'+liveQuestion('Corner in next 10 minutes?','corner')+liveQuestion('Foul in next 10 minutes?','foul')+liveQuestion('Goal in next 10 minutes?','goal')+'</section></section>'}
  function headerLiveBadge(){return '<span data-football-header-live="1" class="football-live-badge football-header-live-badge"><i class="football-live-dot"></i>LIVE</span>'}
  function syncHeaderLive(){var title=document.getElementById('brandTitle');if(!title)return;var badge=title.querySelector('[data-football-header-live]');if(activeMatchId){if(!badge)title.insertAdjacentHTML('beforeend',headerLiveBadge())}else if(badge){badge.remove()}}
  function render(){var r=root();if(!r)return;var shell=r.querySelector('.predict-zone-simple-shell');if(!shell)return;var view=r.querySelector('[data-football-predict-view]');if(!view){view=document.createElement('div');view.className='football-predict-view';view.setAttribute('data-football-predict-view','');shell.appendChild(view)}r.classList.toggle('football-match-detail-open',!!activeMatchId);var m=activeMatchId?findMatch(activeMatchId):null;view.innerHTML=activeMatchId&&m?detailHtml(m):'<section class="football-match-list">'+(matches.length?matches.map(matchHtml).join(''):'<div class="empty">No football matches yet.</div>')+'</section>';syncHeaderLive();syncBalance();startTimers()}
  function openMatch(id){activeMatchId=id;render();try{window.dispatchEvent(new CustomEvent('vexa-football-detail-change',{detail:{open:true}}))}catch(e){}}
  function backToMatches(){if(!activeMatchId)return false;activeMatchId='';render();try{window.dispatchEvent(new CustomEvent('vexa-football-detail-change',{detail:{open:false}}))}catch(e){}return true}
  function selectPick(btn){if(btn.disabled)return;var view=btn&&btn.closest('[data-football-detail-view]');if(!view)return;view.querySelectorAll('[data-football-pick]').forEach(function(n){n.classList.toggle('selected',n===btn)});var submit=view.querySelector('[data-football-submit]');if(submit){submit.disabled=false;submit.textContent='Confirm prediction'}}
  function submitPick(btn){if(busy)return;var view=btn&&btn.closest('[data-football-detail-view]');if(!view)return;var m=findMatch(view.getAttribute('data-football-match-id')||activeMatchId),pick=view.querySelector('[data-football-pick].selected'),status=view.querySelector('[data-football-status]');if(!m||!isOpen(m)){if(status)status.textContent='This match is locked.';return}if(!pick){if(status)status.textContent='Choose a result first.';return}var amount=prompt('Stake TON amount','1');if(amount===null)return;amount=Number(amount);if(!amount||amount<=0){if(status)status.textContent='Enter a valid TON amount.';return}var id=uid();if(!id){if(status)status.textContent='Telegram user was not detected.';return}busy=1;btn.textContent='Placing...';btn.disabled=true;fetch('/app/api/football-bet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:id,matchId:m.id,pick:pick.getAttribute('data-football-pick'),stakeTon:amount})}).then(function(r){return r.json().then(function(j){return {ok:r.ok,json:j}})}).then(function(x){if(!x.ok||!x.json||x.json.ok===false)throw new Error((x.json&&x.json.error)||'Could not place prediction');if(status)status.textContent='Prediction selected for this match.';syncBalance();return loadMatches()}).catch(function(e){if(status)status.textContent=e&&e.message?e.message:'Could not place prediction';btn.disabled=false;btn.textContent='Confirm prediction'}).finally(function(){busy=0})}
  function formatLeft(ms){var s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
  function tickTimers(){var r=root();if(!r)return;r.querySelectorAll('[data-football-countdown]').forEach(function(el){var end=Number(el.getAttribute('data-football-deadline')||0);if(!end)return;var left=end-Date.now();if(left<=0){end=Date.now()+600000;el.setAttribute('data-football-deadline',String(end));left=end-Date.now()}var text=formatLeft(left);if(el.textContent!==text){el.classList.add('is-ticking');el.textContent=text;setTimeout(function(){el.classList.remove('is-ticking')},120)}})}
  function startTimers(){if(timerId)return;tickTimers();timerId=setInterval(tickTimers,1000)}
  function syncBalance(){try{if(window.VexaTonBalance&&window.VexaTonBalance.render)window.VexaTonBalance.render();if(window.VexaUploadedImages&&window.VexaUploadedImages.load)window.VexaUploadedImages.load()}catch(e){}}
  function show(){var r=root();if(!r)return;loadMatches();render();r.classList.add('football-predict-open');var grid=r.querySelector('[data-vexa-predict-group-grid]');if(grid)grid.style.display='none';var card=r.querySelector('[data-predict-card]');if(card)card.classList.add('predict-detail-hidden');var menu=r.querySelector('.predict-zone-category-menu');if(menu)menu.querySelectorAll('.predict-zone-category-card').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-vexa-predict-market')==='football')});var toolbar=r.querySelector('.predict-toolbar-row');if(toolbar)toolbar.style.display='none'}
  function hide(){var r=root();if(r){r.classList.remove('football-predict-open','football-match-detail-open')}activeMatchId='';syncHeaderLive()}
  async function loadTeams(){try{var res=await fetch('/app/api/football-teams',{cache:'no-store'});var json=await res.json();(json.teams||[]).forEach(function(t){teams[t.id]=t});render()}catch(e){}}
  async function loadMatches(){try{var res=await fetch('/app/api/football-matches?userId='+encodeURIComponent(uid()),{cache:'no-store'});var json=await res.json();matches=json.matches||[];render()}catch(e){}}
  function mount(){var r=root();if(!r||r.dataset.footballPredictReady==='1')return;r.dataset.footballPredictReady='1';window.VexaFootballPredictBack=backToMatches;loadTeams().then(loadMatches);document.addEventListener('click',function(e){var p=e.target&&e.target.closest&&e.target.closest('[data-view="playzone"]');if(p&&r.classList.contains('active')&&r.classList.contains('football-match-detail-open')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();backToMatches();return}},true);r.addEventListener('click',function(e){var submit=e.target&&e.target.closest&&e.target.closest('[data-football-submit]');if(submit){e.preventDefault();e.stopPropagation();submitPick(submit);return}var pick=e.target&&e.target.closest&&e.target.closest('[data-football-pick]');if(pick){e.preventDefault();e.stopPropagation();selectPick(pick);return}var match=e.target&&e.target.closest&&e.target.closest('[data-football-match]');if(match){e.preventDefault();e.stopPropagation();openMatch(match.getAttribute('data-football-match')||'');return}},true);var menu=r.querySelector('.predict-zone-category-menu');if(menu){menu.addEventListener('click',function(e){var fb=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-market="football"]');if(fb){e.preventDefault();e.stopImmediatePropagation();show();return}var other=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-group],[data-vexa-predict-market]');if(other&&!fb)hide()},true)}document.addEventListener('click',function(e){var tab=e.target&&e.target.closest&&e.target.closest('[data-view="predictzone"]');if(tab)setTimeout(function(){loadTeams();loadMatches()},200)},true);setInterval(function(){var r=root();if(r&&r.classList.contains('football-predict-open'))loadMatches()},15000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
</script>`;
