export const FOOTBALL_PREDICT_SCRIPT = `<script>
(function(){
  var matches=[],teams={},activeMatchId='',timerId=0,autoStartTimerId=0,smartRefreshTimerId=0,busy=0;
  function root(){return document.getElementById('predictzone')}
  function esc(v){return String(v==null?'':v).replace(/[&<>]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[s]||s})}
  function uid(){var tg=window.Telegram&&window.Telegram.WebApp,u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;return String((u&&u.id)||localStorage.getItem('ownerId')||'').trim()}
  function team(id){id=String(id||'');return teams[id]||{id:id,name:id.charAt(0).toUpperCase()+id.slice(1).replace(/-/g,' '),logoUrl:''}}
  function logo(id,cls){var t=team(id),style=t.logoUrl?' style="background-image:url('+String(t.logoUrl).replace(/"/g,'')+')"':'';return '<span class="football-team-logo '+(cls||'')+' '+(t.logoUrl?'has-logo':'')+'"'+style+'></span>'}
  function findMatch(id){for(var i=0;i<matches.length;i++){if(matches[i].id===id)return matches[i]}return matches[0]||null}
  function injectPolishStyles(){if(document.getElementById('vexa-football-predict-polish'))return;var s=document.createElement('style');s.id='vexa-football-predict-polish';s.textContent='#predictzone.football-match-detail-open .football-predict-view{margin-top:-8px!important}body:has(#predictzone.active.football-match-detail-open) #predictzone .football-detail-page{padding-top:0!important;gap:12px!important;min-height:auto!important}#predictzone .football-detail-page>.football-match-head{display:none!important}#predictzone .football-user-history{display:grid;gap:9px;margin-top:-2px}#predictzone .football-user-history-head{display:flex;align-items:center;justify-content:space-between;padding:0 4px;color:#fff}#predictzone .football-user-history-head strong{font-size:18px;font-weight:950;letter-spacing:-.055em}#predictzone .football-user-history-head span{font-size:11px;font-weight:850;color:rgba(255,255,255,.45)}#predictzone .football-user-history .predict-zone-history-track{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding:1px 2px 3px}#predictzone .football-user-history .predict-zone-history-track::-webkit-scrollbar{display:none}#predictzone .football-history-empty{min-height:44px;display:grid;place-items:center;border-radius:22px;background:rgba(255,255,255,.035);box-shadow:inset 0 1px 0 rgba(255,255,255,.08);color:rgba(255,255,255,.42);font-size:12px;font-weight:850}#predictzone .football-button-success{position:relative!important;color:transparent!important;pointer-events:none!important}#predictzone .football-button-success>*:not(.football-button-success-icon){opacity:0!important}#predictzone .football-button-success .football-button-success-icon{position:absolute;left:50%;top:50%;width:34px;height:34px;display:block;overflow:visible;transform:translate(-50%,-50%);opacity:1!important}#predictzone .football-button-success-ring{fill:none;stroke:rgba(34,197,94,.68);stroke-width:4;stroke-dasharray:170;stroke-dashoffset:170;animation:footballButtonRing .58s ease-out .05s both}#predictzone .football-button-success-check{fill:none;stroke:#22c55e;stroke-width:6;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:56;stroke-dashoffset:56;filter:none!important;animation:footballButtonCheck .42s ease-out .28s both}@keyframes footballButtonRing{to{stroke-dashoffset:0}}@keyframes footballButtonCheck{to{stroke-dashoffset:0}}';document.head.appendChild(s)}
  function liveBadge(cls){return '<span class="football-live-badge '+(cls||'')+'"><i class="football-live-dot"></i>LIVE</span>'}
  function liveOverlay(m){return isLive(m)?'<div class="football-live-overlay" aria-label="Live match">'+liveBadge('football-live-overlay-badge')+'<span>'+matchMinute(m)+'′</span></div>':''}
  function startMs(m){var t=Date.parse((m&&m.startsAt)||'');if(!t)return 0;var d=new Date(t);d.setSeconds(0,0);return d.getTime()}
  function started(m){var t=startMs(m);return !!(m&&t&&Date.now()>=t)}
  function isLive(m){return !!(m&&(m.isLive||((String(m.status||'').toLowerCase()==='locked'||m.locked)&&started(m))))}
  function hasLiveMatches(){for(var i=0;i<matches.length;i++){if(isLive(matches[i]))return true}return false}
  function matchMinute(m){var server=Number((m&&m.matchMinute)||0),t=startMs(m);var local=isLive(m)&&t?Math.max(1,Math.floor((Date.now()-t)/60000)+1):0;return Math.max(server,local)}
  function scoreHtml(m,side){var n=Number(side==='a'?(m.teamAGoals!=null?m.teamAGoals:m.scoreA):(m.teamBGoals!=null?m.teamBGoals:m.scoreB));if(!isFinite(n)||n<0)n=0;return '<span class="football-team-goals">'+Math.floor(n)+' goals</span>'}
  function matchStatus(m){return String((m&&m.status)||'open').toLowerCase()}
  function isOpen(m){return m&&!m.locked&&matchStatus(m)==='open'}
  function pickLabel(m,p){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b);return p==='draw'?'Draw':p==='team_b'?b.name:a.name}
  function ton(v){var n=Number(v||0);return (isFinite(n)?n:0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:4})}
  function headHtml(m,detail){var live=isLive(m);return '<div class="football-match-head"><span class="football-match-left"><span class="football-match-tag">'+esc(m.stage||'Match')+'</span>'+(live?liveBadge():'')+(detail&&live?'<span class="football-minute-pill">'+matchMinute(m)+'′</span>':'')+'</span>'+(detail?'':'<span class="football-match-time">'+esc(m.time||'')+'</span>')+'</div>'}
  function matchHtml(m){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b);return '<article class="football-match-card '+(isLive(m)?'is-live':'')+'" data-football-match="'+esc(m.id)+'">'+liveOverlay(m)+headHtml(m,false)+'<div class="football-teams"><div class="football-team">'+logo(a.id)+'<b>'+esc(a.name)+'</b>'+scoreHtml(m,'a')+'</div><div class="football-vs">VS</div><div class="football-team">'+logo(b.id)+'<b>'+esc(b.name)+'</b>'+scoreHtml(m,'b')+'</div></div><div class="football-pick-row"><button type="button">'+esc(a.name)+'</button><button type="button">Draw</button><button type="button">'+esc(b.name)+'</button></div></article>'}
  function liveQuestion(q){var answered=q.userBet&&q.userBet.pick;return '<div class="football-live-question-row" data-football-live-question="'+esc(q.id)+'"><span>'+esc(q.question||'Live question')+'</span><b data-football-countdown="'+esc(q.id)+'" data-football-deadline="'+(Date.now()+Math.max(0,Number(q.remainingMs||0)))+'">'+formatLeft(q.remainingMs||0)+'</b><div class="football-live-actions"><button type="button" data-football-live-pick="yes" '+(answered?'disabled':'')+'>'+(answered==='yes'?'Yes ✓':'Yes')+'</button><button type="button" data-football-live-pick="no" '+(answered?'disabled':'')+'>'+(answered==='no'?'No ✓':'No')+'</button></div></div>'}
  function liveQuestionCard(m,q){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b),answered=q.userBet&&q.userBet.pick;return '<article class="football-match-card football-live-question-card" data-football-live-card="" data-football-live-question="'+esc(q.id)+'">'+headHtml(m,false)+'<div class="football-teams"><div class="football-team">'+logo(a.id)+'<b>'+esc(a.name)+'</b>'+scoreHtml(m,'a')+'</div><div class="football-vs">VS</div><div class="football-team">'+logo(b.id)+'<b>'+esc(b.name)+'</b>'+scoreHtml(m,'b')+'</div></div><div class="football-live-card-question"><strong>'+esc(q.question||'Live question')+'</strong><b data-football-countdown="'+esc(q.id)+'" data-football-deadline="'+(Date.now()+Math.max(0,Number(q.remainingMs||0)))+'">'+formatLeft(q.remainingMs||0)+'</b></div><div class="football-live-card-actions"><button type="button" data-football-live-pick="yes" '+(answered?'disabled':'')+'>'+(answered==='yes'?'Yes ✓':'Yes')+'</button><button type="button" data-football-live-pick="no" '+(answered?'disabled':'')+'>'+(answered==='no'?'No ✓':'No')+'</button></div><p class="football-pick-status" data-football-status>'+(answered?('Your answer: '+(answered==='yes'?'Yes':'No')):'')+'</p></article>'}
  function liveQuestionCards(){var cards=[];matches.forEach(function(m){(m.liveQuestions||[]).forEach(function(q){cards.push(liveQuestionCard(m,q))})});return cards.join('')}
  function sortedMatches(){return matches.slice().sort(function(a,b){var al=isLive(a)?1:0,bl=isLive(b)?1:0;if(al!==bl)return bl-al;var af=a&&a.featured?1:0,bf=b&&b.featured?1:0;if(af!==bf)return bf-af;return (Date.parse((a&&a.startsAt)||'')||0)-(Date.parse((b&&b.startsAt)||'')||0)})}
  function scheduleAutoStart(){if(autoStartTimerId){clearTimeout(autoStartTimerId);autoStartTimerId=0}var now=Date.now(),next=0;matches.forEach(function(m){var t=startMs(m);if(m&&String(m.status||'').toLowerCase()==='open'&&t&&t>now&&(!next||t<next))next=t});if(!next)return;autoStartTimerId=setTimeout(function(){autoStartTimerId=0;matches.forEach(function(m){if(m&&!isLive(m)&&started(m)){m.isLive=true;m.locked=true;m.status='locked'}});render();loadMatches()},Math.max(0,Math.min(next-now+80,2147483000)))}
  function stopSmartRefresh(){if(smartRefreshTimerId){clearTimeout(smartRefreshTimerId);smartRefreshTimerId=0}}
  function scheduleSmartRefresh(){stopSmartRefresh();var r=root();if(!r||!r.classList.contains('football-predict-open')||document.hidden)return;var hasUpcoming=false,now=Date.now();matches.forEach(function(m){var t=startMs(m);if(m&&String(m.status||'').toLowerCase()==='open'&&t&&t-now<90000)hasUpcoming=true});if(!hasLiveMatches()&&!hasUpcoming)return;smartRefreshTimerId=setTimeout(function(){smartRefreshTimerId=0;var rr=root();if(rr&&rr.classList.contains('football-predict-open')&&!document.hidden)loadMatches()},hasLiveMatches()?8000:3000)}
  function historyHtml(m){var bets=(m.userBets||[]).slice(0,20);var h='<section class="football-user-history"><div class="football-user-history-head"><strong>Your history</strong><span>'+bets.length+' picks</span></div>';if(!bets.length)return h+'<div class="football-history-empty">No prediction yet</div></section>';h+='<div class="predict-zone-history-track">';bets.forEach(function(b){var st=String(b.status||''),kind=st==='won'?'win':st==='lost'?'loss':st==='refunded'?'refund':'active',stake=Number(b.stakeTon||0),pay=Number(b.payoutTon||0),amount=st==='won'?('+'+ton(pay)):st==='lost'?('-'+ton(stake)):ton(pay||stake);h+='<span class="predict-zone-history-card '+kind+'">'+esc(pickLabel(m,b.pick))+' '+amount+'</span>'});return h+'</div></section>'}
  function detailHtml(m){var a=team(m.teamAId||m.a),b=team(m.teamBId||m.b),ub=(m.userBets||[])[0],locked=!isOpen(m);return '<section class="football-detail-page '+(isLive(m)?'is-live':'')+'" data-football-detail-view="" data-football-match-id="'+esc(m.id)+'">'+liveOverlay(m)+'<div class="football-detail-scoreboard"><div class="football-detail-side">'+logo(a.id,'football-detail-logo')+'<b>'+esc(a.name)+'</b>'+scoreHtml(m,'a')+'</div><div class="football-detail-vs">VS</div><div class="football-detail-side">'+logo(b.id,'football-detail-logo')+'<b>'+esc(b.name)+'</b>'+scoreHtml(m,'b')+'</div></div><div class="football-detail-question"><strong>Who wins this match?</strong><span>'+(locked?'Match locked':ub?'Prediction placed':'Pick one result')+'</span></div><div class="football-detail-picks"><button type="button" class="football-detail-pick" data-football-pick="team_a" '+(locked||ub?'disabled':'')+'><span>'+esc(a.name)+'</span><b>Win</b></button><button type="button" class="football-detail-pick" data-football-pick="draw" '+(locked||ub?'disabled':'')+'><span>Draw</span><b>No winner</b></button><button type="button" class="football-detail-pick" data-football-pick="team_b" '+(locked||ub?'disabled':'')+'><span>'+esc(b.name)+'</span><b>Win</b></button></div><button type="button" class="football-confirm-pick" data-football-submit '+(locked||ub?'disabled':'')+'>'+(ub?'Prediction selected':locked?'Locked':'Choose prediction')+'</button><p class="football-pick-status" data-football-status>'+(ub?('Your pick: '+esc(pickLabel(m,ub.pick))):'')+'</p>'+historyHtml(m)+'<section class="football-live-questions"><div class="football-live-questions-head"><strong>Live questions</strong><span>Live now</span></div>'+((m.liveQuestions&&m.liveQuestions.length)?m.liveQuestions.map(liveQuestion).join(''):'')+'</section></section>'}
  function headerLiveBadge(){return '<span data-football-header-live="1" class="football-live-badge football-header-live-badge"><i class="football-live-dot"></i>LIVE</span>'}
  function syncHeaderLive(){var title=document.getElementById('brandTitle');if(!title)return;var badge=title.querySelector('[data-football-header-live]');var m=activeMatchId?findMatch(activeMatchId):null;if(activeMatchId&&isLive(m)){if(!badge)title.insertAdjacentHTML('beforeend',headerLiveBadge())}else if(badge){badge.remove()}}
  function render(){injectPolishStyles();var r=root();if(!r)return;var shell=r.querySelector('.predict-zone-simple-shell');if(!shell)return;var view=r.querySelector('[data-football-predict-view]');if(!view){view=document.createElement('div');view.className='football-predict-view';view.setAttribute('data-football-predict-view','');shell.appendChild(view)}r.classList.toggle('football-match-detail-open',!!activeMatchId);var m=activeMatchId?findMatch(activeMatchId):null;view.innerHTML=activeMatchId&&m?detailHtml(m):'<section class="football-match-list">'+(matches.length?(liveQuestionCards()+sortedMatches().map(matchHtml).join('')):'<div class="empty">No football matches yet.</div>')+'</section>';syncHeaderLive();syncBalance();startTimers();scheduleAutoStart();scheduleSmartRefresh()}
  function openMatch(id){activeMatchId=id;render();loadMatches();try{window.dispatchEvent(new CustomEvent('vexa-football-detail-change',{detail:{open:true}}))}catch(e){}}
  function backToMatches(){if(!activeMatchId)return false;activeMatchId='';render();try{window.dispatchEvent(new CustomEvent('vexa-football-detail-change',{detail:{open:false}}))}catch(e){}return true}
  function selectPick(btn){if(btn.disabled)return;var view=btn&&btn.closest('[data-football-detail-view]');if(!view)return;view.querySelectorAll('[data-football-pick]').forEach(function(n){n.classList.toggle('selected',n===btn)});var submit=view.querySelector('[data-football-submit]');if(submit){submit.disabled=false;submit.textContent='Confirm prediction'}}
  function showButtonSuccess(btn){try{if(!btn)return;injectPolishStyles();var original=btn.getAttribute('data-football-original-html');if(original==null){btn.setAttribute('data-football-original-html',btn.innerHTML)}btn.innerHTML='<svg class="football-button-success-icon" viewBox="0 0 72 72" aria-hidden="true"><circle class="football-button-success-ring" cx="36" cy="36" r="27"></circle><path class="football-button-success-check" d="M22 37.5 31.5 47 51 25"></path></svg>';btn.classList.add('football-button-success');btn.disabled=true;setTimeout(function(){try{btn.classList.remove('football-button-success');var html=btn.getAttribute('data-football-original-html');if(html!=null)btn.innerHTML=html;btn.removeAttribute('data-football-original-html')}catch(e){}},3000)}catch(e){}}
  function restoreButton(btn,fallback){try{if(!btn)return;btn.classList.remove('football-button-success');var html=btn.getAttribute('data-football-original-html');btn.removeAttribute('data-football-original-html');btn.innerHTML=html||fallback||'';btn.disabled=false}catch(e){}}
  function submitLivePick(btn){if(busy||btn.disabled)return;var row=btn.closest('[data-football-live-question]'),view=btn.closest('[data-football-detail-view]')||btn.closest('[data-football-live-card]'),status=view&&view.querySelector('[data-football-status]');if(!row)return;var amount=prompt('Stake TON amount','1');if(amount===null)return;amount=Number(amount);if(!amount||amount<=0){if(status)status.textContent='Enter a valid TON amount.';return}var id=uid();if(!id){if(status)status.textContent='Telegram user was not detected.';return}busy=1;showButtonSuccess(btn);fetch('/app/api/football-live-question-bet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:id,questionId:row.getAttribute('data-football-live-question'),pick:btn.getAttribute('data-football-live-pick'),stakeTon:amount})}).then(function(r){return r.json().then(function(j){return {ok:r.ok,json:j}})}).then(function(x){if(!x.ok||!x.json||x.json.ok===false)throw new Error((x.json&&x.json.error)||'Could not answer live question');if(status)status.textContent='Live answer selected.';syncBalance();setTimeout(loadMatches,3000)}).catch(function(e){if(status)status.textContent=e&&e.message?e.message:'Could not answer live question';restoreButton(btn,btn.getAttribute('data-football-live-pick')==='yes'?'Yes':'No')}).finally(function(){busy=0})}
  function submitPick(btn){if(busy)return;var view=btn&&btn.closest('[data-football-detail-view]');if(!view)return;var m=findMatch(view.getAttribute('data-football-match-id')||activeMatchId),pick=view.querySelector('[data-football-pick].selected'),status=view.querySelector('[data-football-status]');if(!m||!isOpen(m)){if(status)status.textContent='This match is locked.';return}if(!pick){if(status)status.textContent='Choose a result first.';return}var amount=prompt('Stake TON amount','1');if(amount===null)return;amount=Number(amount);if(!amount||amount<=0){if(status)status.textContent='Enter a valid TON amount.';return}var id=uid();if(!id){if(status)status.textContent='Telegram user was not detected.';return}busy=1;showButtonSuccess(btn);fetch('/app/api/football-bet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:id,matchId:m.id,pick:pick.getAttribute('data-football-pick'),stakeTon:amount})}).then(function(r){return r.json().then(function(j){return {ok:r.ok,json:j}})}).then(function(x){if(!x.ok||!x.json||x.json.ok===false)throw new Error((x.json&&x.json.error)||'Could not place prediction');if(status)status.textContent='Prediction selected for this match.';syncBalance();setTimeout(loadMatches,3000)}).catch(function(e){if(status)status.textContent=e&&e.message?e.message:'Could not place prediction';restoreButton(btn,'Confirm prediction')}).finally(function(){busy=0})}
  function formatLeft(ms){var s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
  function tickTimers(){var r=root();if(!r)return;if(r.classList.contains('football-predict-open')){var changed=false;matches.forEach(function(m){if(m&&!m.isLive&&started(m)){m.isLive=true;m.locked=true;m.status='locked';changed=true}});if(changed){render();return}r.querySelectorAll('.football-minute-pill').forEach(function(el){var m=findMatch(activeMatchId);if(m)el.textContent=matchMinute(m)+'′'});r.querySelectorAll('[data-football-match]').forEach(function(card){var m=findMatch(card.getAttribute('data-football-match')||'');var n=card.querySelector('.football-live-overlay>span:not(.football-live-badge)');if(m&&n)n.textContent=matchMinute(m)+'′'})}r.querySelectorAll('[data-football-countdown]').forEach(function(el){var end=Number(el.getAttribute('data-football-deadline')||0);if(!end)return;var left=end-Date.now();if(left<=0){var row=el.closest&&el.closest('[data-football-live-question]');if(row)row.remove();return}var text=formatLeft(left);if(el.textContent!==text){el.classList.add('is-ticking');el.textContent=text;setTimeout(function(){el.classList.remove('is-ticking')},120)}})}
  function startTimers(){if(timerId)return;tickTimers();timerId=setInterval(tickTimers,1000)}
  function syncBalance(){try{if(window.VexaTonBalance&&window.VexaTonBalance.render)window.VexaTonBalance.render();if(window.VexaUploadedImages&&window.VexaUploadedImages.load)window.VexaUploadedImages.load()}catch(e){}}
  function show(){var r=root();if(!r)return;injectPolishStyles();loadMatches();render();r.classList.add('football-predict-open');var grid=r.querySelector('[data-vexa-predict-group-grid]');if(grid)grid.style.display='none';var card=r.querySelector('[data-predict-card]');if(card)card.classList.add('predict-detail-hidden');var menu=r.querySelector('.predict-zone-category-menu');if(menu)menu.querySelectorAll('.predict-zone-category-card').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-vexa-predict-market')==='football')});var toolbar=r.querySelector('.predict-toolbar-row');if(toolbar)toolbar.style.display='none';scheduleSmartRefresh()}
  function hide(){var r=root();if(r){r.classList.remove('football-predict-open','football-match-detail-open')}activeMatchId='';syncHeaderLive();stopSmartRefresh()}
  async function loadTeams(){try{var res=await fetch('/app/api/football-teams',{cache:'no-store'});var json=await res.json();(json.teams||[]).forEach(function(t){teams[t.id]=t});render()}catch(e){}}
  async function loadMatches(){try{var res=await fetch('/app/api/football-matches?userId='+encodeURIComponent(uid()),{cache:'no-store'});var json=await res.json();matches=json.matches||[];render();scheduleAutoStart();scheduleSmartRefresh()}catch(e){scheduleSmartRefresh()}}
  function mount(){var r=root();if(!r||r.dataset.footballPredictReady==='1')return;r.dataset.footballPredictReady='1';injectPolishStyles();window.VexaFootballPredictBack=backToMatches;loadTeams().then(loadMatches);document.addEventListener('visibilitychange',function(){var rr=root();if(document.hidden){stopSmartRefresh();return}if(rr&&rr.classList.contains('football-predict-open'))loadMatches()},false);document.addEventListener('click',function(e){var p=e.target&&e.target.closest&&e.target.closest('[data-view="playzone"]');if(p&&r.classList.contains('active')&&r.classList.contains('football-match-detail-open')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();backToMatches();return}},true);r.addEventListener('click',function(e){var live=e.target&&e.target.closest&&e.target.closest('[data-football-live-pick]');if(live){e.preventDefault();e.stopPropagation();submitLivePick(live);return}var submit=e.target&&e.target.closest&&e.target.closest('[data-football-submit]');if(submit){e.preventDefault();e.stopPropagation();submitPick(submit);return}var pick=e.target&&e.target.closest&&e.target.closest('[data-football-pick]');if(pick){e.preventDefault();e.stopPropagation();selectPick(pick);return}var match=e.target&&e.target.closest&&e.target.closest('[data-football-match]');if(match){e.preventDefault();e.stopPropagation();openMatch(match.getAttribute('data-football-match')||'');return}},true);var menu=r.querySelector('.predict-zone-category-menu');if(menu){menu.addEventListener('click',function(e){var fb=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-market="football"]');if(fb){e.preventDefault();e.stopImmediatePropagation();show();return}var other=e.target&&e.target.closest&&e.target.closest('[data-vexa-predict-group],[data-vexa-predict-market]');if(other&&!fb)hide()},true)}document.addEventListener('click',function(e){var tab=e.target&&e.target.closest&&e.target.closest('[data-view="predictzone"]');if(tab)setTimeout(function(){loadTeams();loadMatches()},200)},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
</script>`;
