export const HOME_BLANK_CARDS_SCRIPT = `
(function(){
  var LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ',ROW_HEIGHT=48;
  function q(s,r){return (r||document).querySelector(s)}
  function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
  function cleanHome(){qa('#home .home-finance-split').forEach(function(n){n.outerHTML=''})}
  function css(){
    var old=q('#homeLuckyCodeStyle');if(old)old.outerHTML='';
    var st=document.createElement('style');st.id='homeLuckyCodeStyle';
    st.textContent=[
      '#home .home-intro-card{display:grid!important;pointer-events:none!important;margin:0 0 14px!important}',
      '#homeLuckyCodeSection{display:block!important;padding:0 0 14px!important;margin:0!important}',
      'body:has(#home.active) #home{overflow:hidden!important}',
      '.home-lucky-card{background:none!important;border:0!important;box-shadow:none!important;padding:0!important}',
      '.home-lucky-head{display:none!important}',
      '.home-lucky-titlebox{display:grid!important;gap:5px!important}.home-lucky-titlebox strong{color:#fff!important;font-size:19px!important;font-weight:950!important}.home-lucky-titlebox span{color:rgba(255,255,255,.5)!important;font-size:11px!important;font-weight:760!important}',
      '.home-lucky-machine{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:9px!important;background:none!important;box-shadow:none!important;perspective:760px!important}',
      '.home-lucky-reel{height:48px!important;border-radius:18px!important;overflow:hidden!important;position:relative!important;background:linear-gradient(145deg,rgba(255,255,255,.13),rgba(255,255,255,.035) 42%,rgba(255,255,255,.018))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.22),inset 0 -1px 0 rgba(255,255,255,.075),inset 0 -18px 26px rgba(0,0,0,.22),0 16px 34px rgba(0,0,0,.20)!important;backdrop-filter:blur(12px) saturate(1.26)!important;-webkit-backdrop-filter:blur(12px) saturate(1.26)!important;transform:translateZ(0)!important}',
      '.home-lucky-reel:before{content:""!important;position:absolute!important;left:0!important;right:0!important;top:0!important;height:17px!important;background:linear-gradient(180deg,rgba(0,0,0,.62),rgba(0,0,0,.18),transparent)!important;z-index:3!important;pointer-events:none!important}.home-lucky-reel:after{content:""!important;position:absolute!important;left:0!important;right:0!important;bottom:0!important;height:17px!important;border-radius:0!important;background:linear-gradient(0deg,rgba(0,0,0,.58),rgba(0,0,0,.16),transparent)!important;z-index:3!important;pointer-events:none!important}.home-lucky-strip{will-change:transform!important;transform:translate3d(0,0,0);backface-visibility:hidden!important;filter:none!important}.home-lucky-reel.is-spinning{box-shadow:inset 0 1px 0 rgba(255,255,255,.15),inset 0 -1px 0 rgba(255,255,255,.07),inset 0 -14px 22px rgba(0,0,0,.22),0 14px 26px rgba(0,0,0,.18)!important}.home-lucky-reel.is-spinning .home-lucky-strip{filter:none!important}.home-lucky-letter{height:48px!important;display:grid!important;place-items:center!important;color:#fff!important;font-size:23px!important;font-weight:950!important;text-shadow:0 8px 18px rgba(0,0,0,.54)!important;transform:translateZ(0)!important}',
      '.home-lucky-code{height:42px!important;margin:13px 0!important;border-radius:18px!important;position:relative!important;display:grid!important;grid-template-columns:minmax(0,1fr) 30px 48px!important;align-items:center!important;gap:7px!important;padding:5px!important;background:rgba(255,255,255,.035)!important;color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:800!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.045),inset 0 -1px 0 rgba(255,255,255,.035)!important}.home-lucky-code b{color:#fff!important;letter-spacing:.16em!important;text-align:center!important}.home-code-spin,.home-ticket-mini-button{height:30px!important;border:0!important;border-radius:12px!important;background:rgba(255,255,255,.09)!important;color:#fff!important;font-size:14px!important;font-weight:950!important;display:grid!important;place-items:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 8px 18px rgba(0,0,0,.2)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}.home-code-spin{width:30px!important}.home-ticket-mini-button{width:48px!important}.home-ticket-mini-button svg{width:25px!important;height:25px!important;display:block!important;filter:drop-shadow(0 7px 13px rgba(255,255,255,.08))!important}.home-code-spin:disabled{opacity:.55!important}',
      '.home-ticket-layout{margin-top:14px!important;display:grid!important;grid-template-columns:1fr!important;gap:12px!important;align-items:stretch!important}',
      '.home-ticket-card{margin:0!important;border-radius:28px!important;padding:14px!important;min-height:154px!important;background:rgba(13,13,13,.54)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;gap:10px!important;align-content:space-between!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}',
      '.home-ticket-card-head{display:flex!important;align-items:flex-start!important;justify-content:flex-start!important;gap:10px!important}.home-ticket-card-head strong{color:#fff!important;font-size:16px!important;font-weight:950!important}.home-ticket-count{height:44px!important;width:100%!important;border-radius:18px!important;background:rgba(0,0,0,.22)!important;color:#fff!important;font-size:20px!important;font-weight:950!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06),inset 0 -1px 0 rgba(255,255,255,.04)!important}',
      '.home-ticket-stepper{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important}.home-ticket-step{height:40px!important;border:0!important;border-radius:16px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:20px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important}',
      '.home-ticket-button{width:100%!important;height:42px!important;border-radius:17px!important;border:0!important;background:rgba(255,255,255,.12)!important;color:#fff!important;font-size:13px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 12px 24px rgba(0,0,0,.2)!important}.home-ticket-button.is-ready{background:rgba(255,255,255,.18)!important}',
      '.home-ticket-finance-visual{min-height:132px!important;height:132px!important;position:relative!important;display:grid!important;place-items:center!important;background:transparent!important;box-shadow:none!important;overflow:visible!important;pointer-events:none!important}.home-ticket-finance-visual img{width:100%!important;height:100%!important;margin-top:4px!important;object-fit:contain!important;display:block!important;filter:drop-shadow(0 18px 34px rgba(0,0,0,.26))!important;animation:homeFinanceFloat 3.8s ease-in-out infinite!important;pointer-events:none!important}',
      '.home-ticket-image-button{position:absolute!important;right:0!important;top:0!important;z-index:4!important;height:34px!important;min-width:76px!important;padding:0 12px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:12px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 14px 30px rgba(0,0,0,.24)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}',
      '.home-ticket-drawer-backdrop{position:fixed!important;inset:0!important;z-index:94!important;background:transparent!important;display:none!important}.home-ticket-drawer-backdrop.is-open{display:block!important}',
      '.home-ticket-drawer{position:fixed!important;left:0!important;top:calc(120px + env(safe-area-inset-top))!important;bottom:calc(88px + env(safe-area-inset-bottom))!important;width:min(44vw,210px)!important;max-width:210px!important;z-index:95!important;padding:24px 14px 14px!important;border-radius:0 30px 30px 0!important;background:rgba(255,255,255,.018)!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.07),inset 0 -1px 0 rgba(255,255,255,.04),0 24px 54px rgba(0,0,0,.36)!important;backdrop-filter:blur(6px) saturate(1.04)!important;-webkit-backdrop-filter:blur(6px) saturate(1.04)!important;transform:translate3d(-104%,0,0)!important;transition:transform .36s cubic-bezier(.18,.88,.24,1)!important;display:grid!important;grid-template-rows:auto auto minmax(0,1fr)!important;gap:14px!important;overflow:hidden!important}.home-ticket-drawer.is-open{transform:translate3d(0,0,0)!important}',
      '.home-ticket-drawer-head{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:8px!important}.home-ticket-drawer-head strong{font-size:16px!important;font-weight:950!important}.home-ticket-drawer-close{width:32px!important;height:32px!important;border-radius:13px!important;border:0!important;background:rgba(255,255,255,.07)!important;color:#fff!important;font-size:18px!important}',
      '.home-ticket-drawer-count{height:54px!important;border-radius:20px!important;background:rgba(0,0,0,.16)!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;font-size:20px!important;font-weight:950!important}.home-ticket-list{min-height:0!important;display:grid!important;align-content:start!important;gap:8px!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;scrollbar-width:none!important;padding:0 0 8px!important}.home-ticket-list::-webkit-scrollbar{display:none!important}.home-ticket-list-item{height:38px!important;border-radius:16px!important;background:rgba(255,255,255,.045)!important;color:#fff!important;display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 10px!important;font-size:12px!important;font-weight:850!important}.home-ticket-list-item span{color:rgba(255,255,255,.54)!important;font-size:11px!important}',
      '.home-live-winners{margin:14px 0 0!important;display:grid!important;grid-template-rows:auto minmax(0,1fr)!important;gap:10px!important;min-height:0!important;border-radius:30px!important;padding:13px!important;background:rgba(255,255,255,.026)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 18px 44px rgba(0,0,0,.24)!important;backdrop-filter:blur(3px) saturate(1.14)!important;-webkit-backdrop-filter:blur(3px) saturate(1.14)!important;overflow:hidden!important}',
      '.home-live-winners-head{display:flex!important;align-items:end!important;justify-content:space-between!important;gap:10px!important}.home-live-winners-title{display:grid!important;gap:3px!important}.home-live-winners-title strong{color:#fff!important;font-size:18px!important;font-weight:950!important;letter-spacing:-.04em!important}.home-live-winners-title span{color:rgba(255,255,255,.48)!important;font-size:11px!important;font-weight:760!important}.home-live-winners-live{color:rgba(255,255,255,.68)!important;font-size:10px!important;font-weight:900!important;letter-spacing:.11em!important;text-transform:uppercase!important}',
      '.home-live-winners-list{max-height:238px!important;min-height:0!important;display:grid!important;align-content:start!important;gap:8px!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;scrollbar-width:none!important;padding:1px 2px 2px!important}.home-live-winners-list::-webkit-scrollbar{display:none!important}',
      '.home-live-winner-card{height:54px!important;border:1px solid rgba(255,255,255,.075)!important;outline:0!important;border-radius:21px!important;background:linear-gradient(135deg,rgba(255,255,255,.07),rgba(255,255,255,.022) 48%,rgba(0,0,0,.11))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.095),0 10px 24px rgba(0,0,0,.13)!important;display:grid!important;grid-template-columns:38px minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;padding:8px!important;backdrop-filter:blur(3px) saturate(1.06)!important;-webkit-backdrop-filter:blur(3px) saturate(1.06)!important}',
      '.home-live-winner-avatar{width:38px!important;height:38px!important;border-radius:50%!important;object-fit:cover!important;display:block!important;background:transparent!important;box-shadow:none!important}.home-live-winner-user{min-width:0!important;display:grid!important;gap:3px!important}.home-live-winner-user strong{display:block!important;color:#fff!important;font-size:13px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.home-live-winner-user span{display:block!important;color:rgba(255,255,255,.48)!important;font-size:10px!important;font-weight:750!important}.home-live-winner-amount{color:#fff!important;font-size:13px!important;font-weight:950!important;white-space:nowrap!important}',
      '@keyframes homeCodeSpin{0%{transform:translate3d(0,0,0)}100%{transform:translate3d(0,-1248px,0)}}@keyframes homeFinanceFloat{0%,100%{transform:translate3d(0,-5px,0)}50%{transform:translate3d(0,7px,0)}}@media(prefers-reduced-motion:reduce){.home-ticket-finance-visual img{animation:none!important;transform:none!important}}'
    ].join('');
    document.head.appendChild(st);
  }

  var WINNERS=['NikaWin','ParsaFlow','MinaLucky','AriTon','LunaVault','KianLuck','VeraSpin','NoahDrop','TaraMoon','DaniJet','RayanX','MilaCoin','ArvinBet','SofiaRay','NiloWin','LeoMint','ZaraCode','IlyaTon','NoraGem','AmirPay','EvaNode','DaryaX','SamLuck','RimaFlow','YunaStar','OmidWin','LianFox','MayaTon','KaroLux','SaraVex'];
  var AVATARS=['telegram','durov','TelegramTips'];
  function winnersHtml(){var html='';for(var i=0;i<30;i++){var amount=(0.18+((i*37)%148)/100).toFixed(2);html+='<article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/'+AVATARS[i%AVATARS.length]+'.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@'+WINNERS[i]+'</strong><span>Lucky Zone</span></div><div class="home-live-winner-amount">+'+amount+' TON</div></article>'}return html}
  function ticketIcon(){return '<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M13 23c4.1 0 7.5-3.4 7.5-7.5h23A7.5 7.5 0 0 0 51 23v18a7.5 7.5 0 0 0-7.5 7.5h-23A7.5 7.5 0 0 0 13 41V23Z" stroke="currentColor" stroke-width="4" stroke-linejoin="round"/><path d="M27 18v28" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-dasharray="3 6" opacity=".55"/><path d="M34 27h9M34 36h7" stroke="currentColor" stroke-width="3.4" stroke-linecap="round"/></svg>'}
  function reel(){var h='';for(var r=0;r<24;r++){for(var i=0;i<LETTERS.length;i++)h+='<div class="home-lucky-letter">'+LETTERS[i]+'</div>'}return h}
  function count(){try{return Math.max(0,Math.floor(Number(localStorage.getItem('vexaFreeTickets')||'0')))}catch(e){return 0}}
  function ready(){try{return localStorage.getItem('vexaTicketReady')==='1'}catch(e){return false}}
  function setReady(v){try{localStorage.setItem('vexaTicketReady',v?'1':'0')}catch(e){}sync()}
  function setCount(v){v=Math.max(0,Math.floor(Number(v)||0));try{localStorage.setItem('vexaFreeTickets',String(v))}catch(e){}sync()}
  function listHtml(c){var html='';for(var i=0;i<c;i++)html+='<div class="home-ticket-list-item"><b>Ticket '+String(i+1).padStart(2,'0')+'</b><span>ready</span></div>';if(!c)html='<div class="home-ticket-list-item"><b>No tickets</b><span>empty</span></div>';return html}
  function sync(){var c=count();qa('[data-ticket-count]').forEach(function(n){n.textContent=c+' ticket'+(c===1?'':'s')});var btn=q('#homeTicketButton');if(btn){btn.classList.toggle('is-ready',ready());btn.textContent=ready()?'Get Ticket ✓':'Get Ticket'}var d=q('#homeTicketList');if(d)d.innerHTML=listHtml(c)}
  function change(delta){setCount(count()+delta)}
  function markReady(){if(count()<=0)return;setReady(true)}
  function placeSection(home,sec){var intro=q('.home-intro-card',home);if(intro&&intro.nextSibling!==sec)intro.parentNode.insertBefore(sec,intro.nextSibling);else if(!intro&&home.firstChild!==sec)home.insertBefore(sec,home.firstChild)}
  function setDrawer(open,sec){var drawer=q('#homeTicketDrawer',sec),backdrop=q('#homeTicketDrawerBackdrop',sec);if(drawer)drawer.classList.toggle('is-open',!!open);if(backdrop)backdrop.classList.toggle('is-open',!!open)}
  function randomCode(){var out='';for(var i=0;i<6;i++)out+=LETTERS[Math.floor(Math.random()*LETTERS.length)];return out}
  function spinSlots(sec){
    var spin=q('#homeCodeSpinButton',sec);
    if(spin&&spin.disabled)return;
    var code=randomCode();
    var strips=qa('.home-lucky-strip',sec);
    var reels=qa('.home-lucky-reel',sec);
    var codeBox=q('#homeLuckyCode',sec);
    if(spin)spin.disabled=true;
    if(codeBox)codeBox.textContent='------';
    strips.forEach(function(s,i){
      if(reels[i])reels[i].classList.add('is-spinning');
      s.style.transition='none';
      s.style.animation='none';
      s.style.filter='none';
      s.style.transform='translate3d(0,0,0)';
      s.offsetHeight;
      s.style.animation='homeCodeSpin .38s linear infinite';
    });
    strips.forEach(function(s,i){
      setTimeout(function(){
        var idx=LETTERS.indexOf(code.charAt(i));
        var target=(LETTERS.length+idx)*ROW_HEIGHT;
        s.style.animation='none';
        s.style.filter='none';
        s.style.transition='transform .72s cubic-bezier(.18,.88,.24,1)';
        s.style.transform='translate3d(0,-'+target+'px,0)';
        setTimeout(function(){
          s.style.transition='none';
          s.style.transform='translate3d(0,-'+target+'px,0)';
          if(reels[i])reels[i].classList.remove('is-spinning');
          if(codeBox)codeBox.textContent=code.slice(0,i+1)+'-'.repeat(5-i);
          if(i===strips.length-1&&spin)spin.disabled=false;
        },760);
      },6000+(i*3000));
    });
  }
  function build(){var home=q('#home');if(!home)return null;cleanHome();var sec=q('#homeLuckyCodeSection',home);if(!sec){sec=document.createElement('section');sec.id='homeLuckyCodeSection';sec.innerHTML='<div class="home-ticket-drawer-backdrop" id="homeTicketDrawerBackdrop"></div><div class="home-ticket-drawer" id="homeTicketDrawer"><div class="home-ticket-drawer-head"><strong>My Tickets</strong><button class="home-ticket-drawer-close" id="homeTicketDrawerClose" type="button">×</button></div><div class="home-ticket-drawer-count" data-ticket-count>0 tickets</div><div class="home-ticket-list" id="homeTicketList"></div></div><div class="home-lucky-card"><div class="home-lucky-head" aria-hidden="true"></div><div class="home-lucky-machine">'+Array(5).fill(0).map(function(){return '<div class="home-lucky-reel"><div class="home-lucky-strip">'+reel()+'</div></div>'}).join('')+'</div><div class="home-lucky-code"><b id="homeLuckyCode">------</b><button class="home-code-spin" id="homeCodeSpinButton" type="button" aria-label="Spin current code">↻</button><button class="home-ticket-mini-button" id="homeTicketImageButton" type="button" aria-label="My Tickets">'+ticketIcon()+'</button></div><div class="home-ticket-layout"><div class="home-ticket-finance-visual" aria-hidden="true"><img src="/app/api/home-finance-image.png" alt="" decoding="async"/></div></div><section class="home-live-winners" aria-label="Live Winners"><div class="home-live-winners-head"><div class="home-live-winners-title"><strong>Live Winners</strong><span>Latest lucky rewards</span></div><span class="home-live-winners-live">Live</span></div><div class="home-live-winners-list">'+winnersHtml()+'</div></section></div>'}placeSection(home,sec);sync();return sec}
  function bind(sec){if(sec.dataset.ticketUiBound==='1')return;sec.dataset.ticketUiBound='1';sec.addEventListener('click',function(e){var t=e.target;if(t.closest&&t.closest('[data-ticket-plus]')){e.preventDefault();change(1);return}if(t.closest&&t.closest('[data-ticket-minus]')){e.preventDefault();change(-1);return}if(t.closest&&t.closest('#homeTicketButton')){e.preventDefault();markReady();return}if(t.closest&&t.closest('#homeCodeSpinButton')){e.preventDefault();spinSlots(sec);return}if(t.closest&&t.closest('#homeTicketImageButton')){e.preventDefault();setDrawer(true,sec);return}if(t.closest&&t.closest('#homeTicketDrawerClose')||t.id==='homeTicketDrawerBackdrop'){e.preventDefault();setDrawer(false,sec);return}},true)}
  function init(){cleanHome();css();var sec=build();if(sec)bind(sec);setTimeout(function(){var s=build();if(s)bind(s)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
`;