export const HOME_IMAGE_VERSION_SCRIPT = `
(function(){
  var css = '#home #homeLuckyCodeSection .home-lottery-slot-card,#home .home-lucky-card .home-lottery-slot-card{height:88px!important;min-height:88px!important;max-height:88px!important;margin:0 0 10px!important;border-radius:22px!important;overflow:hidden!important}#home #homeLuckyCodeSection .home-lottery-slot-image,#home .home-lucky-card .home-lottery-slot-image{height:100%!important;object-fit:cover!important;object-position:center!important;border-radius:22px!important}#home #homeLuckyCodeSection .home-live-winners-list,#home .home-lucky-card .home-live-winners-list{max-height:520px!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;padding:0 2px 26px!important;scroll-padding-bottom:26px!important;box-sizing:border-box!important}#home #homeLuckyCodeSection .home-live-winner-card,#home .home-lucky-card .home-live-winner-card{position:relative!important;overflow:visible!important;padding-left:14px!important}#home #homeLuckyCodeSection .home-live-winner-card:before,#home .home-lucky-card .home-live-winner-card:before,#home #homeLuckyCodeSection .home-live-winner-user strong:after,#home .home-lucky-card .home-live-winner-user strong:after{display:none!important;content:none!important}#home #homeLuckyCodeSection .home-live-winner-card:first-child:after,#home .home-lucky-card .home-live-winner-card:first-child:after{content:"★ ★ ★"!important;position:absolute!important;right:14px!important;bottom:-11px!important;z-index:4!important;width:auto!important;height:22px!important;padding:0 10px!important;border-radius:999px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:3px!important;color:rgba(255,225,235,.88)!important;font-size:11px!important;font-weight:900!important;letter-spacing:.02em!important;background:radial-gradient(circle at 50% 50%,rgba(92,10,35,.40),rgba(28,3,12,.24) 58%,rgba(8,0,4,.02) 100%)!important;box-shadow:0 10px 28px rgba(92,10,35,.32),0 4px 16px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.08)!important;text-shadow:0 0 9px rgba(255,210,225,.38),0 5px 12px rgba(0,0,0,.62)!important;filter:drop-shadow(0 0 6px rgba(92,10,35,.32))!important;animation:vexaPremiumStars 2.9s ease-in-out infinite!important;pointer-events:none!important}#home #homeLuckyCodeSection .home-live-winner-card:first-child .home-live-winner-amount,#home .home-lucky-card .home-live-winner-card:first-child .home-live-winner-amount{padding-right:0!important}@keyframes vexaPremiumStars{0%,100%{opacity:.72;transform:translate3d(0,0,0) scale(.96)}50%{opacity:1;transform:translate3d(0,-2px,0) scale(1.04)}}';
  var style = document.createElement('style');
  style.id = 'home-lottery-slot-size-fix';
  style.textContent = css;
  document.head.appendChild(style);
})();
`;
