export const HOME_IMAGE_VERSION_SCRIPT = `
(function(){
  var latest='',loading=false,homeSpinTimer=null,homeSpinning=false;
  var css=[
    '#home #homeLuckyCodeSection .home-lottery-slot-card,#home .home-lucky-card .home-lottery-slot-card{width:100%!important;height:88px!important;min-height:88px!important;max-height:88px!important;margin:0 0 10px!important;border:0!important;outline:0!important;border-radius:22px!important;overflow:hidden!important;padding:0!important;position:relative!important;box-sizing:border-box!important}',
    '#home #homeLuckyCodeSection .home-lottery-slot-image,#home .home-lucky-card .home-lottery-slot-image{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;display:block!important;object-fit:cover!important;object-position:center!important;border:0!important;outline:0!important;border-radius:22px!important;background:transparent!important;box-shadow:none!important}',
    '#home #homeLuckyCodeSection .home-lottery-slot-image[src*="v=home-lottery"],#home .home-lucky-card .home-lottery-slot-image[src*="v=home-lottery"]{opacity:0!important}',
    '#home .vexa-home-slot-reels{position:absolute!important;inset:0!important;z-index:3!important;pointer-events:none!important;overflow:hidden!important;border-radius:22px!important}',
    '#home .vexa-home-slot-num{position:absolute!important;top:50%!important;transform:translate(-50%,-50%)!important;width:44px!important;height:44px!important;display:grid!important;place-items:center!important;color:rgba(255,238,246,.98)!important;font-size:27px!important;font-weight:950!important;line-height:1!important;text-shadow:0 2px 10px rgba(0,0,0,.78),0 0 14px rgba(255,210,225,.34)!important;font-variant-numeric:tabular-nums!important}',
    '#home .vexa-home-slot-num:nth-child(1){left:14.8%!important}#home .vexa-home-slot-num:nth-child(2){left:32.4%!important}#home .vexa-home-slot-num:nth-child(3){left:50%!important}#home .vexa-home-slot-num:nth-child(4){left:67.6%!important}#home .vexa-home-slot-num:nth-child(5){left:85.2%!important}',
    '#home .vexa-home-spin-button{position:absolute!important;right:90px!important;top:0!important;z-index:5!important;height:34px!important;min-width:58px!important;padding:0 12px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:12px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 14px 30px rgba(0,0,0,.24)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}',
    '#home .vexa-home-spin-button.is-spinning{opacity:.72!important;transform:scale(.98)!important}',
    '#home #homeLuckyCodeSection .home-live-winners-list,#home .home-lucky-card .home-live-winners-list{max-height:520px!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;padding:0 2px 16px!important;scroll-padding-bottom:16px!important;box-sizing:border-box!important}',
    '#home #homeLuckyCodeSection .home-live-winner-card,#home .home-lucky-card .home-live-winner-card{position:relative!important;overflow:hidden!important}',
    '#home #homeLuckyCodeSection .home-live-winner-card:before,#home .home-lucky-card .home-live-winner-card:before,#home #homeLuckyCodeSection .home-live-winner-card:after,#home .home-lucky-card .home-live-winner-card:after,#home #homeLuckyCodeSection .home-live-winner-user strong:after,#home .home-lucky-card .home-live-winner-user strong:after{display:none!important;content:none!important}',
    '#home #homeLuckyCodeSection .home-live-winner-card:nth-child(-n+3)>:not(.vexa-premium-corner),#home .home-lucky-card .home-live-winner-card:nth-child(-n+3)>:not(.vexa-premium-corner){position:relative!important;z-index:3!important}',
    '#home .vexa-premium-corner{position:absolute!important;inset:0!important;z-index:4!important;pointer-events:none!important;overflow:hidden!important;border-radius:28px!important;display:block!important}',
    '#home .vexa-premium-corner:before{content:""!important;position:absolute!important;right:-38px!important;bottom:-36px!important;width:188px!important;height:118px!important;border-radius:999px!important;background:radial-gradient(circle at 82% 82%,rgba(92,10,35,.64),rgba(42,4,16,.34) 34%,rgba(42,4,16,.16) 50%,rgba(8,0,4,.05) 64%,rgba(8,0,4,0) 82%)!important;box-shadow:0 0 42px rgba(92,10,35,.34),inset 0 -20px 34px rgba(92,10,35,.18)!important}',
    '#home .vexa-premium-corner.is-blue:before{background:radial-gradient(circle at 82% 82%,rgba(8,26,112,.68),rgba(4,12,58,.38) 34%,rgba(4,12,58,.18) 50%,rgba(0,3,18,.06) 64%,rgba(0,3,18,0) 82%)!important;box-shadow:0 0 42px rgba(8,26,112,.38),inset 0 -20px 34px rgba(8,26,112,.20)!important}',
    '#home .vexa-premium-corner.is-bronze:before{background:radial-gradient(circle at 82% 82%,rgba(106,63,8,.68),rgba(62,34,4,.38) 34%,rgba(62,34,4,.18) 50%,rgba(18,9,0,.06) 64%,rgba(18,9,0,0) 82%)!important;box-shadow:0 0 42px rgba(106,63,8,.38),inset 0 -20px 34px rgba(106,63,8,.20)!important}',
    '#home .vexa-premium-star{position:absolute!important;z-index:5!important;color:rgba(255,225,235,.86)!important;font-size:10px!important;line-height:1!important;text-shadow:0 0 9px rgba(255,210,225,.35),0 5px 12px rgba(0,0,0,.62)!important;filter:drop-shadow(0 0 5px rgba(92,10,35,.36))!important;animation:none!important}',
    '#home .vexa-premium-corner.is-blue .vexa-premium-star{color:rgba(220,232,255,.88)!important;text-shadow:0 0 9px rgba(160,190,255,.38),0 5px 12px rgba(0,0,0,.62)!important;filter:drop-shadow(0 0 5px rgba(8,26,112,.42))!important}',
    '#home .vexa-premium-corner.is-bronze .vexa-premium-star{color:rgba(255,231,190,.88)!important;text-shadow:0 0 9px rgba(255,190,90,.34),0 5px 12px rgba(0,0,0,.62)!important;filter:drop-shadow(0 0 5px rgba(106,63,8,.42))!important}',
    '#home .vexa-premium-star:nth-child(1){right:14px!important;bottom:10px!important;font-size:12px!important}#home .vexa-premium-star:nth-child(2){right:50px!important;bottom:8px!important;font-size:9px!important}#home .vexa-premium-star:nth-child(3){right:30px!important;bottom:34px!important;font-size:10px!important}#home .vexa-premium-star:nth-child(4){right:92px!important;bottom:13px!important;font-size:8px!important}#home .vexa-premium-star:nth-child(5){right:66px!important;bottom:48px!important;font-size:9px!important}',
    '#home #homeLuckyCodeSection .home-live-winner-card:nth-child(-n+3) .home-live-winner-amount,#home .home-lucky-card .home-live-winner-card:nth-child(-n+3) .home-live-winner-amount{padding-right:28px!important}'
  ].join('');
  function rnd(){return Math.floor(Math.random()*10)}
  function style(){var s=document.getElementById('home-lottery-slot-size-fix');if(!s){s=document.createElement('style');s.id='home-lottery-slot-size-fix';document.head.appendChild(s)}s.textContent=css}
  function old(){document.querySelectorAll('#home #homeLuckyCodeSection .home-lottery-slot-image,#home .home-lucky-card .home-lottery-slot-image').forEach(function(i){if((i.getAttribute('src')||'').indexOf('v=home-lottery')>-1)i.removeAttribute('src')})}
  function setImg(u){if(!u)return;latest=u;document.querySelectorAll('#home #homeLuckyCodeSection .home-lottery-slot-image,#home .home-lucky-card .home-lottery-slot-image').forEach(function(i){if(i.getAttribute('src')!==u)i.setAttribute('src',u);i.style.removeProperty('opacity')})}
  function meta(){if(loading)return;loading=true;fetch('/app/api/home-lottery-slot-meta?ts='+Date.now(),{credentials:'same-origin',cache:'no-store'}).then(function(r){return r.ok?r.json():null}).then(function(j){if(j&&j.url)setImg(j.url)}).finally(function(){loading=false})}
  function reels(){document.querySelectorAll('#home #homeLuckyCodeSection .home-lottery-slot-card,#home .home-lucky-card .home-lottery-slot-card').forEach(function(card){if(card.querySelector('.vexa-home-slot-reels'))return;var box=document.createElement('div');box.className='vexa-home-slot-reels';for(var i=0;i<5;i++){var n=document.createElement('span');n.className='vexa-home-slot-num';n.textContent=String(rnd());box.appendChild(n)}card.appendChild(box)})}
  function spin(){if(homeSpinning)return;homeSpinning=true;var btn=document.getElementById('homeSlotSpinButton');if(btn)btn.classList.add('is-spinning');var ticks=0;if(homeSpinTimer)clearInterval(homeSpinTimer);homeSpinTimer=setInterval(function(){document.querySelectorAll('#home .vexa-home-slot-num').forEach(function(n){n.textContent=String(rnd())});ticks++;if(ticks>22){clearInterval(homeSpinTimer);homeSpinTimer=null;homeSpinning=false;if(btn)btn.classList.remove('is-spinning')}},70)}
  function spinButton(){var wrap=document.querySelector('#home .home-ticket-finance-visual');if(!wrap||document.getElementById('homeSlotSpinButton'))return;var b=document.createElement('button');b.id='homeSlotSpinButton';b.className='vexa-home-spin-button';b.type='button';b.textContent='Spin';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();spin()});wrap.appendChild(b)}
  function stars(card,tone){if(!card)return;var b=card.querySelector('.vexa-premium-corner');if(!b){b=document.createElement('div');b.className='vexa-premium-corner';for(var i=0;i<5;i++){var x=document.createElement('span');x.className='vexa-premium-star';x.textContent='★';b.appendChild(x)}card.appendChild(b)}b.classList.toggle('is-blue',tone==='blue');b.classList.toggle('is-bronze',tone==='bronze')}
  function apply(){style();old();reels();spinButton();var r=document.querySelector('#home #homeLuckyCodeSection')||document.querySelector('#home .home-lucky-card');if(r){stars(r.querySelector('.home-live-winner-card:nth-child(1)'),'red');stars(r.querySelector('.home-live-winner-card:nth-child(2)'),'blue');stars(r.querySelector('.home-live-winner-card:nth-child(3)'),'bronze')}setImg(latest);meta()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
  var n=0,t=setInterval(function(){apply();if(++n>12)clearInterval(t)},250);
  try{new MutationObserver(apply).observe(document.body,{childList:true,subtree:true})}catch(e){}
})();
`;
