export const HOME_BLANK_CARDS_SCRIPT = `
(function(){
  function q(s,r){return (r||document).querySelector(s)}
  function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
  function cleanHome(){qa('#home .home-finance-split,#home .home-live-winners-card').forEach(function(n){n.outerHTML=''})}
  function css(){
    var old=q('#homeLuckyCodeStyle');if(old)old.outerHTML='';
    var st=document.createElement('style');st.id='homeLuckyCodeStyle';
    st.textContent=[
      '#home{overflow-y:auto!important;overflow-x:hidden!important;padding-bottom:calc(98px + env(safe-area-inset-bottom))!important;background:transparent!important;-webkit-overflow-scrolling:touch!important;scrollbar-width:none!important}',
      '#home .home-intro-card{display:grid!important;pointer-events:none!important;margin:0 0 14px!important}',
      '#homeLuckyCodeSection{display:block!important;padding:0!important;margin:0!important;background:transparent!important;box-shadow:none!important;overflow:visible!important}',
      'body:has(#home.active) #home{overflow-y:auto!important;overflow-x:hidden!important}',
      '.home-lucky-card{background:none!important;border:0!important;box-shadow:none!important;padding:0!important;overflow:visible!important}',
      '.home-lucky-head{display:none!important}',
      '#home .home-lottery-slot-card{width:100%!important;height:72px!important;min-height:72px!important;max-height:72px!important;margin:0 0 12px!important;border:0!important;outline:0!important;border-radius:20px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;box-shadow:none!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important;padding:0!important;position:relative!important;box-sizing:border-box!important}',
      '#home .home-lottery-slot-card:before,#home .home-lottery-slot-card:after{display:none!important;content:none!important}',
      '#home .home-lottery-slot-image{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;display:block!important;object-fit:cover!important;object-position:center!important;border:0!important;outline:0!important;border-radius:20px!important;background:transparent!important;box-shadow:none!important;opacity:1!important}',
      '#home .home-slot-number-grid{position:absolute!important;inset:0!important;z-index:2!important;display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:8px!important;padding:7px 8px!important;box-sizing:border-box!important;pointer-events:none!important}',
      '#home .home-slot-number-reel{position:relative!important;display:block!important;border-radius:17px!important;overflow:hidden!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}',
      '#home .home-slot-number-reel:before{display:none!important;content:none!important}',
      '#home .home-slot-number-strip{position:absolute!important;left:0!important;right:0!important;top:50%!important;display:grid!important;grid-auto-rows:40px!important;will-change:transform!important;transition:none!important}',
      '#home .home-slot-number-reel.is-spinning .home-slot-number-strip{filter:blur(1.2px)!important}',
      '#home .home-slot-number-digit{height:40px!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;font-size:34px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.065em!important;text-shadow:0 1px 0 rgba(255,255,255,.32),0 0 16px rgba(255,86,137,.54),0 12px 26px rgba(0,0,0,.54)!important;font-variant-numeric:tabular-nums!important;background:linear-gradient(180deg,#fff 0%,#ffe9f1 42%,#d85a7a 100%)!important;-webkit-background-clip:text!important;background-clip:text!important;color:transparent!important}',
      '.home-ticket-layout{margin-top:14px!important;display:grid!important;grid-template-columns:minmax(0,1fr) minmax(0,1fr)!important;gap:12px!important;align-items:stretch!important}',
      '.home-ticket-card{margin:0!important;border-radius:28px!important;padding:14px!important;min-height:154px!important;background:rgba(13,13,13,.54)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;gap:10px!important;align-content:space-between!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}',
      '.home-ticket-card-head{display:flex!important;align-items:flex-start!important;justify-content:flex-start!important;gap:10px!important}.home-ticket-card-head strong{color:#fff!important;font-size:16px!important;font-weight:950!important}.home-ticket-count{height:44px!important;width:100%!important;border-radius:18px!important;background:rgba(0,0,0,.22)!important;color:#fff!important;font-size:20px!important;font-weight:950!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06),inset 0 -1px 0 rgba(255,255,255,.04)!important}',
      '.home-ticket-stepper{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important}.home-ticket-step{height:40px!important;border:0!important;border-radius:16px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:20px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important}',
      '.home-ticket-button{width:100%!important;height:42px!important;border-radius:17px!important;border:0!important;background:rgba(255,255,255,.12)!important;color:#fff!important;font-size:13px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 12px 24px rgba(0,0,0,.2)!important}.home-ticket-button.is-ready{background:rgba(255,255,255,.18)!important}',
      '.home-ticket-finance-visual{min-height:154px!important;height:100%!important;position:relative!important;display:grid!important;place-items:center!important;background:transparent!important;box-shadow:none!important;overflow:visible!important;pointer-events:auto!important}.home-ticket-finance-visual img{width:100%!important;height:100%!important;margin-top:4px!important;object-fit:contain!important;display:block!important;filter:drop-shadow(0 18px 34px rgba(0,0,0,.26))!important;animation:homeFinanceFloat 3.8s ease-in-out infinite!important;pointer-events:none!important}',
      '.home-ticket-actions{position:absolute!important;right:0!important;top:0!important;z-index:4!important;display:flex!important;align-items:center!important;gap:7px!important}.home-ticket-image-button,.home-slot-spin-button{height:34px!important;min-width:76px!important;padding:0 12px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:12px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 14px 30px rgba(0,0,0,.24)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}.home-slot-spin-button{min-width:52px!important;padding:0 11px!important}.home-slot-spin-button.is-spinning{pointer-events:none!important;opacity:.72!important}',
      '.home-ticket-drawer-backdrop{position:fixed!important;inset:0!important;z-index:99994!important;background:transparent!important;display:none!important}.home-ticket-drawer-backdrop.is-open{display:block!important}',
      '.home-ticket-drawer{position:fixed!important;left:0!important;top:calc(120px + env(safe-area-inset-top))!important;bottom:calc(88px + env(safe-area-inset-bottom))!important;width:min(44vw,210px)!important;max-width:210px!important;z-index:99995!important;padding:24px 14px 14px!important;border-radius:0 30px 30px 0!important;background:rgba(255,255,255,.018)!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.07),inset 0 -1px 0 rgba(255,255,255,.04),0 24px 54px rgba(0,0,0,.36)!important;backdrop-filter:blur(6px) saturate(1.04)!important;-webkit-backdrop-filter:blur(6px) saturate(1.04)!important;transform:translate3d(-104%,0,0)!important;transition:transform .36s cubic-bezier(.18,.88,.24,1)!important;display:grid!important;grid-template-rows:auto auto minmax(0,1fr)!important;gap:14px!important;overflow:hidden!important}.home-ticket-drawer.is-open{transform:translate3d(0,0,0)!important}',
      '.home-ticket-drawer-head{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:8px!important}.home-ticket-drawer-head strong{font-size:16px!important;font-weight:950!important}.home-ticket-drawer-close{width:32px!important;height:32px!important;border-radius:13px!important;border:0!important;background:rgba(255,255,255,.07)!important;color:#fff!important;font-size:18px!important}',
      '.home-ticket-drawer-count{height:54px!important;border-radius:20px!important;background:rgba(0,0,0,.16)!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;font-size:20px!important;font-weight:950!important}.home-ticket-list{min-height:0!important;display:grid!important;align-content:start!important;gap:8px!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;scrollbar-width:none!important;padding:0 0 8px!important}.home-ticket-list::-webkit-scrollbar{display:none!important}.home-ticket-list-item{height:38px!important;border-radius:16px!important;background:rgba(255,255,255,.045)!important;color:#fff!important;display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 10px!important;font-size:12px!important;font-weight:850!important}.home-ticket-list-item span{color:rgba(255,255,255,.54)!important;font-size:11px!important}',
      '@keyframes homeFinanceFloat{0%,100%{transform:translate3d(0,-5px,0)}50%{transform:translate3d(0,7px,0)}}@media(prefers-reduced-motion:reduce){.home-ticket-finance-visual img{animation:none!important;transform:none!important}}'
    ].join('');
    document.head.appendChild(st);
  }
  function reelY(index){return 'translate3d(0,-'+((index*40)+20)+'px,0)'}
  function reelDigitsHtml(){var html='';for(var cycle=0;cycle<4;cycle++)for(var n=0;n<10;n++)html+='<span class="home-slot-number-digit">'+n+'</span>';return html}
  function slotsHtml(){var html='';for(var i=0;i<5;i++){var v=(i+1)%10;html+='<div class="home-slot-number-reel" data-slot-index="'+i+'" data-slot-value="'+v+'"><div class="home-slot-number-strip" data-slot-strip style="transform:'+reelY(20+v)+'">'+reelDigitsHtml()+'</div></div>'}return '<div class="home-slot-number-grid" aria-hidden="true">'+html+'</div>'}
  function count(){try{return Math.max(0,Math.floor(Number(localStorage.getItem('vexaFreeTickets')||'0')))}catch(e){return 0}}
  function ready(){try{return localStorage.getItem('vexaTicketReady')==='1'}catch(e){return false}}
  function setReady(v){try{localStorage.setItem('vexaTicketReady',v?'1':'0')}catch(e){}sync()}
  function setCount(v){v=Math.max(0,Math.floor(Number(v)||0));try{localStorage.setItem('vexaFreeTickets',String(v))}catch(e){}sync()}
  function listHtml(c){var html='';for(var i=0;i<c;i++)html+='<div class="home-ticket-list-item"><b>Ticket '+String(i+1).padStart(2,'0')+'</b><span>ready</span></div>';if(!c)html='<div class="home-ticket-list-item"><b>No tickets</b><span>empty</span></div>';return html}
  function sync(){var c=count();qa('[data-ticket-count]').forEach(function(n){n.textContent=c+' ticket'+(c===1?'':'s')});var btn=q('#homeTicketButton');if(btn){btn.classList.toggle('is-ready',ready());btn.textContent=ready()?'Get Ticket ✓':'Get Ticket'}var d=q('#homeTicketList');if(d)d.innerHTML=listHtml(c)}
  function change(delta){setCount(count()+delta)}
  function markReady(){if(count()<=0)return;setReady(true)}
  function placeSection(home,sec){var intro=q('.home-intro-card',home);if(intro&&intro.nextSibling!==sec)intro.parentNode.insertBefore(sec,intro.nextSibling);else if(!intro&&home.firstChild!==sec)home.insertBefore(sec,home.firstChild)}
  function ensureDrawerPortal(sec){['homeTicketDrawerBackdrop','homeTicketDrawer'].forEach(function(id){var el=q('#'+id,sec);if(el&&el.parentNode!==document.body)document.body.appendChild(el)})}
  function setDrawer(open,sec){ensureDrawerPortal(sec);var drawer=q('#homeTicketDrawer'),backdrop=q('#homeTicketDrawerBackdrop');if(drawer)drawer.classList.toggle('is-open',!!open);if(backdrop)backdrop.classList.toggle('is-open',!!open)}
  function build(){var home=q('#home');if(!home)return null;cleanHome();var sec=q('#homeLuckyCodeSection',home);if(!sec){sec=document.createElement('section');sec.id='homeLuckyCodeSection';sec.innerHTML='<div class="home-ticket-drawer-backdrop" id="homeTicketDrawerBackdrop"></div><div class="home-ticket-drawer" id="homeTicketDrawer"><div class="home-ticket-drawer-head"><strong>My Tickets</strong><button class="home-ticket-drawer-close" id="homeTicketDrawerClose" type="button">×</button></div><div class="home-ticket-drawer-count" data-ticket-count>0 tickets</div><div class="home-ticket-list" id="homeTicketList"></div></div><div class="home-lucky-card"><div class="home-lucky-head" aria-hidden="true"></div><section class="home-lottery-slot-card" aria-label="Lottery slot image"><img class="home-lottery-slot-image" src="/app/api/home-lottery-slot.png?v=home-lottery" alt="" decoding="async" loading="eager"/>'+slotsHtml()+'</section><div class="home-ticket-layout"><div class="home-ticket-card"><div class="home-ticket-card-head"><strong>Get Ticket</strong></div><div class="home-ticket-count" data-ticket-count>0 tickets</div><div class="home-ticket-stepper"><button class="home-ticket-step" type="button" data-ticket-minus>-</button><button class="home-ticket-step" type="button" data-ticket-plus>+</button></div><button class="home-ticket-button" id="homeTicketButton" type="button">Get Ticket</button></div><div class="home-ticket-finance-visual" aria-hidden="true"><div class="home-ticket-actions"><button class="home-slot-spin-button" id="homeSlotSpinButton" type="button">Spin</button><button class="home-ticket-image-button" id="homeTicketImageButton" type="button">My Tickets</button></div><img src="/app/api/home-finance-image.png" alt="" decoding="async"/></div></div></div>'}placeSection(home,sec);ensureDrawerPortal(sec);sync();return sec}
  function bind(sec){if(sec.dataset.ticketUiBound==='1')return;sec.dataset.ticketUiBound='1';sec.addEventListener('click',function(e){var t=e.target;if(t.closest&&t.closest('[data-ticket-plus]')){e.preventDefault();change(1);return}if(t.closest&&t.closest('[data-ticket-minus]')){e.preventDefault();change(-1);return}if(t.id==='homeTicketButton'){e.preventDefault();markReady();return}if(t.id==='homeTicketImageButton'){e.preventDefault();setDrawer(true,sec);return}},true);document.addEventListener('click',function(e){var t=e.target;if(t&&t.id==='homeTicketDrawerClose'){e.preventDefault();setDrawer(false,sec);return}if(t&&t.id==='homeTicketDrawerBackdrop'){e.preventDefault();setDrawer(false,sec);return}},true)}
  function init(){cleanHome();css();var sec=build();if(sec)bind(sec);setTimeout(function(){var s=build();if(s)bind(s)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
`;