export const LIMBO_SECTION = `<section id="limbo" class="view limbo-view">
<style>
.limbo-view{padding:10px 12px calc(112px + env(safe-area-inset-bottom))!important;overflow:hidden!important;background:linear-gradient(180deg,#050b08,#010201)!important}.limbo-game3d{height:calc(100dvh - 156px - env(safe-area-inset-top) - env(safe-area-inset-bottom));min-height:520px;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:10px}.limbo-stage3d{position:relative;overflow:hidden;border-radius:28px;border:1px solid rgba(255,255,255,.12);background:#020403;box-shadow:0 28px 70px rgba(0,0,0,.48),inset 0 1px 0 rgba(255,255,255,.1)}.limbo-stage3d canvas{width:100%!important;height:100%!important;display:block!important}.limbo-hud3d{position:absolute;left:12px;right:12px;top:12px;display:flex;justify-content:space-between;gap:8px;z-index:5;pointer-events:none}.limbo-pill3d{height:34px;padding:0 12px;border-radius:999px;background:rgba(0,0,0,.42);border:1px solid rgba(255,255,255,.13);display:flex;align-items:center;color:#fff;font-size:12px;font-weight:900;-webkit-backdrop-filter:blur(14px);backdrop-filter:blur(14px)}.limbo-aim3d{position:absolute;left:50%;top:50%;width:10px;height:10px;margin:-5px 0 0 -5px;border-radius:50%;border:1px solid rgba(255,255,255,.38);z-index:4;pointer-events:none;box-shadow:0 0 18px rgba(170,255,200,.18)}.limbo-msg3d{position:absolute;left:12px;right:12px;bottom:12px;z-index:5;padding:12px 14px;border-radius:20px;background:rgba(0,0,0,.45);border:1px solid rgba(255,255,255,.13);color:#fff;font-size:13px;font-weight:800;line-height:1.25;-webkit-backdrop-filter:blur(14px);backdrop-filter:blur(14px)}.limbo-controls3d{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.limbo-controls3d button{height:54px;border-radius:18px;border:1px solid rgba(255,255,255,.14);background:linear-gradient(180deg,rgba(255,255,255,.16),rgba(255,255,255,.055));color:#fff;font-size:22px;font-weight:950;box-shadow:0 14px 30px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.22)}.limbo-controls3d button:active{transform:scale(.96)}.limbo-controls3d [data-limbo-action=forward]{grid-column:2}.limbo-controls3d [data-limbo-action=left]{grid-column:1;grid-row:2}.limbo-controls3d [data-limbo-action=back]{grid-column:2;grid-row:2}.limbo-controls3d [data-limbo-action=right]{grid-column:3;grid-row:2}.limbo-controls3d [data-limbo-action=reset]{grid-column:1/4;height:44px;font-size:14px;color:rgba(255,255,255,.76)}
</style>
<div class="limbo-game3d"><div class="limbo-stage3d" data-limbo-stage><div class="limbo-hud3d"><span class="limbo-pill3d" data-limbo-inventory>No lantern</span><span class="limbo-pill3d" data-limbo-state>Forest v4</span></div><span class="limbo-aim3d"></span><div class="limbo-msg3d" data-limbo-message>Loading forest...</div></div><div class="limbo-controls3d"><button type="button" data-limbo-action="forward">↑</button><button type="button" data-limbo-action="left">←</button><button type="button" data-limbo-action="back">↓</button><button type="button" data-limbo-action="right">→</button><button type="button" data-limbo-action="reset">Reset</button></div></div>
<script type="module">
import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';
(function(){
var section=document.getElementById('limbo');
if(!section||section.dataset.limboThree==='1')return;
section.dataset.limboThree='1';
var stage=section.querySelector('[data-limbo-stage]'),msg=section.querySelector('[data-limbo-message]'),inv=section.querySelector('[data-limbo-inventory]'),stateEl=section.querySelector('[data-limbo-state]');
var renderer,scene,camera,player,lanternMesh,gateMesh,lanternLight,flashLight,compassArrow,groundMesh;
var trees=[],rocks=[],fireflies=[],pressed={},hasLantern=false,won=false,yaw=0,targetYaw=0,vel=0,last=performance.now(),walkTime=0,blockedCooldown=0,stepTimer=0,audioCtx=null;
var seed=4421;
function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function say(t){if(msg)msg.textContent=t}
function sync(){if(inv)inv.textContent=hasLantern?'Lantern on':'No lantern';if(stateEl)stateEl.textContent=won?'Escaped':'Forest v4'}
function startAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch(e){}}
function footstep(){if(!audioCtx)return;var o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='triangle';o.frequency.value=70+rnd()*20;f.type='lowpass';f.frequency.value=180;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.08,audioCtx.currentTime+.018);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.connect(f);f.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}
function tex(kind){var c=document.createElement('canvas'),x,y;c.width=c.height=128;var g=c.getContext('2d');if(!g)return null;if(kind==='ground'){g.fillStyle='#132516';g.fillRect(0,0,128,128);for(x=0;x<1150;x++){g.fillStyle=x%5?'rgba(78,96,49,.18)':'rgba(36,18,8,.22)';g.fillRect(rnd()*128,rnd()*128,1+rnd()*4,1+rnd()*5)}}if(kind==='path'){g.fillStyle='#5b4325';g.fillRect(0,0,128,128);for(x=0;x<760;x++){g.fillStyle=x%3?'rgba(145,113,69,.2)':'rgba(35,22,11,.24)';g.fillRect(rnd()*128,rnd()*128,1+rnd()*5,1+rnd()*3)}}if(kind==='bark'){g.fillStyle='#3a2416';g.fillRect(0,0,128,128);for(x=0;x<52;x++){g.strokeStyle=x%2?'rgba(111,70,38,.48)':'rgba(15,8,4,.4)';g.lineWidth=1+rnd()*3;g.beginPath();g.moveTo(rnd()*128,0);for(y=0;y<128;y+=10)g.lineTo(rnd()*128,y);g.stroke()}}if(kind==='leaf'){g.fillStyle='#0a3720';g.fillRect(0,0,128,128);for(x=0;x<860;x++){g.fillStyle=x%3?'rgba(38,125,65,.24)':'rgba(2,18,9,.24)';g.beginPath();g.arc(rnd()*128,rnd()*128,1+rnd()*4,0,Math.PI*2);g.fill()}}if(kind==='skin'){g.fillStyle='#624131';g.fillRect(0,0,128,128);for(x=0;x<180;x++){g.fillStyle='rgba(255,205,165,.08)';g.fillRect(rnd()*128,rnd()*128,1+rnd()*3,1+rnd()*3)}}var t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(kind==='bark'?1:8,kind==='bark'?3:8);t.colorSpace=THREE.SRGBColorSpace;return t}
var groundTex=tex('ground'),pathTex=tex('path'),barkTex=tex('bark'),leafTex=tex('leaf'),skinTex=tex('skin');
function mat(color,rough,map,emissive,ei){return new THREE.MeshStandardMaterial({color:color,roughness:rough||1,map:map||null,emissive:emissive||0x000000,emissiveIntensity:ei||0})}
function init(){
 if(!stage)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x06100b);scene.fog=new THREE.FogExp2(0x06100b,0.043);
 camera=new THREE.PerspectiveCamera(74,1,0.08,100);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(2,window.devicePixelRatio||1));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xb8ffd0,0x071007,0.52));var moon=new THREE.DirectionalLight(0xdcffe8,1.12);moon.position.set(-6,12,5);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);
 lanternLight=new THREE.PointLight(0xffd27a,0,9,1.65);scene.add(lanternLight);flashLight=new THREE.SpotLight(0xffdba0,0,16,Math.PI/6,.55,1.4);scene.add(flashLight);scene.add(flashLight.target);
 var geo=new THREE.PlaneGeometry(86,86,48,48);var pos=geo.attributes.position;for(var i=0;i<pos.count;i++){var x=pos.getX(i),y=pos.getY(i);pos.setZ(i,Math.sin(x*.35)*.12+Math.cos(y*.28)*.11+(rnd()-.5)*.08)}geo.computeVertexNormals();groundMesh=new THREE.Mesh(geo,mat(0x0f2415,1,groundTex));groundMesh.rotation.x=-Math.PI/2;groundMesh.receiveShadow=true;scene.add(groundMesh);
 var pathMaterial=mat(0x6a4c2a,1,pathTex);for(var p=0;p<22;p++){var seg=new THREE.Mesh(new THREE.PlaneGeometry(7.8+rnd()*1.4,4.1),pathMaterial);seg.rotation.x=-Math.PI/2;seg.position.set(Math.sin(p*.55)*1.55,.055,5-p*2.05);seg.rotation.z=Math.sin(p*.6)*.09;seg.receiveShadow=true;scene.add(seg)}
 makeForest();makeDetails();makeLantern();makeGate();makePlayer();bind();resize();say('v4: smoother movement, footsteps, denser fog, better lantern light. Find the lantern, then the gate.');sync();requestAnimationFrame(loop)}
function makePlayer(){player=new THREE.Object3D();player.position.set(0,1.55,4);scene.add(player);player.add(camera);camera.position.set(0,0,0);var skin=mat(0x6b493a,.72,skinTex),sleeve=mat(0x171211,.75,null);function arm(side){var group=new THREE.Group();var fore=new THREE.Mesh(new THREE.CylinderGeometry(.085,.105,.62,14),sleeve);fore.rotation.x=1.08;fore.rotation.z=side*.22;fore.position.set(side*.37,-.38,-.74);fore.castShadow=true;var hand=new THREE.Mesh(new THREE.SphereGeometry(.12,16,10),skin);hand.scale.set(.88,.55,1.18);hand.position.set(side*.42,-.43,-1.04);hand.castShadow=true;group.add(fore,hand);camera.add(group)}arm(-1);arm(1);compassArrow=new THREE.Mesh(new THREE.ConeGeometry(.055,.22,16),mat(0xffd27a,.5,null,0xffb13d,.8));compassArrow.position.set(0,-.28,-.72);compassArrow.rotation.x=-Math.PI/2;camera.add(compassArrow)}
function makeTree(x,z,s,type){var trunkMat=mat(type?0x4b2d18:0x3b2415,1,barkTex),leafMat=mat(type?0x0f5e31:0x0a4325,1,leafTex);var trunk=new THREE.Mesh(new THREE.CylinderGeometry(.1*s,.23*s,1.85*s,9),trunkMat);trunk.position.set(x,.92*s,z);trunk.rotation.z=(rnd()-.5)*.16;trunk.castShadow=true;scene.add(trunk);for(var c=0;c<3;c++){var crown=new THREE.Mesh(new THREE.ConeGeometry((.82-c*.12)*s,(2.05-c*.22)*s,12),leafMat);crown.position.set(x+(rnd()-.5)*.08,(2.18+c*.62)*s,z+(rnd()-.5)*.08);crown.rotation.y=rnd()*6.28;crown.castShadow=true;scene.add(crown)}trees.push({x:x,z:z,r:.62*s})}
function makeForest(){for(var i=0;i<185;i++){var side=i%2===0?-1:1;makeTree(side*(5+rnd()*29),9-rnd()*58,.62+rnd()*1.1,i%5===0)}for(var j=0;j<48;j++){makeTree(-3.8-rnd()*1.8,7-j*1.05,.47+rnd()*.5,j%4===0);makeTree(3.8+rnd()*1.8,7-j*1.05,.47+rnd()*.5,j%3===0)}}
function makeDetails(){var rockMat=mat(0x263028,1,null),grassMat=mat(0x1b6a38,1,null);for(var i=0;i<52;i++){var side=rnd()>.5?-1:1,rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.18+rnd()*.24,0),rockMat);rock.position.set(side*(2.5+rnd()*3.4),.16,6-rnd()*43);rock.rotation.set(rnd()*2,rnd()*3,rnd()*2);rock.castShadow=true;scene.add(rock);rocks.push({x:rock.position.x,z:rock.position.z,r:.34})}for(var g=0;g<170;g++){var blade=new THREE.Mesh(new THREE.ConeGeometry(.035,.42+rnd()*.22,5),grassMat);blade.position.set((rnd()-.5)*12,.22,7-rnd()*47);blade.rotation.z=(rnd()-.5)*.5;scene.add(blade)}for(var f=0;f<26;f++){var bug=new THREE.Mesh(new THREE.SphereGeometry(.035,8,8),mat(0xb8ff9a,.4,null,0xaaff6a,1.25));bug.position.set((rnd()-.5)*8,1.1+rnd()*2.4,4-rnd()*34);bug.userData.base=bug.position.clone();bug.userData.phase=rnd()*6;fireflies.push(bug);scene.add(bug)}}
function makeLantern(){lanternMesh=new THREE.Group();var body=new THREE.Mesh(new THREE.CylinderGeometry(.18,.2,.52,16),mat(0xffd77b,.5,null,0xffb13d,1.35));body.castShadow=true;var ring=new THREE.Mesh(new THREE.TorusGeometry(.18,.025,8,18),mat(0xffd77b,.45,null,0xffb13d,.75));ring.position.y=.34;ring.rotation.x=Math.PI/2;var glass=new THREE.Mesh(new THREE.SphereGeometry(.19,16,12),mat(0xffe3a0,.18,null,0xffbd67,.55));glass.scale.y=.72;var glow=new THREE.PointLight(0xffbd67,1.2,4,1.4);glow.position.y=.16;lanternMesh.add(body,ring,glass,glow);lanternMesh.position.set(-2,.42,-14);scene.add(lanternMesh)}
function makeGate(){gateMesh=new THREE.Group();var gateMat=mat(0x85ffc1,.35,null,0x2cff9b,1.15);var a=new THREE.Mesh(new THREE.BoxGeometry(.38,3.4,.38),gateMat);a.position.set(-1.25,1.7,-27);a.castShadow=true;var b=a.clone();b.position.x=1.25;var top=new THREE.Mesh(new THREE.BoxGeometry(3,.38,.38),gateMat);top.position.set(0,3.25,-27);top.castShadow=true;var gateLight=new THREE.PointLight(0x4cffb2,1.6,8,1.2);gateLight.position.set(0,1.7,-26.4);gateMesh.add(a,b,top,gateLight);scene.add(gateMesh)}
function bind(){section.querySelectorAll('[data-limbo-action]').forEach(function(b){var a=b.getAttribute('data-limbo-action');if(a==='reset'){b.addEventListener('click',function(e){e.preventDefault();reset()});return}b.addEventListener('touchstart',function(e){e.preventDefault();startAudio();pressed[a]=true},{passive:false});b.addEventListener('touchend',function(e){e.preventDefault();pressed[a]=false},{passive:false});b.addEventListener('mousedown',function(){startAudio();pressed[a]=true});b.addEventListener('mouseup',function(){pressed[a]=false});b.addEventListener('mouseleave',function(){pressed[a]=false});b.addEventListener('click',function(e){e.preventDefault();startAudio();tap(a)})})}
function tap(a){pressed[a]=true;setTimeout(function(){pressed[a]=false},120)}
function reset(){hasLantern=false;won=false;yaw=0;targetYaw=0;vel=0;player.position.set(0,1.55,4);player.rotation.y=0;lanternMesh.visible=true;lanternLight.intensity=0;flashLight.intensity=0;scene.fog.density=.043;say('v4: smoother movement, footsteps, denser fog, better lantern light. Find the lantern, then the gate.');sync()}
function collides(nx,nz){if(Math.abs(nx)>32||nz>8||nz<-33)return true;var i,t,dx,dz;for(i=0;i<trees.length;i++){t=trees[i];dx=nx-t.x;dz=nz-t.z;if(dx*dx+dz*dz<(t.r+.36)*(t.r+.36))return true}for(i=0;i<rocks.length;i++){t=rocks[i];dx=nx-t.x;dz=nz-t.z;if(dx*dx+dz*dz<(t.r+.22)*(t.r+.22))return true}return false}
function move(dx,dz){var nx=player.position.x+dx,nz=player.position.z+dz;if(!collides(nx,nz)){player.position.x=nx;player.position.z=nz}else{vel*=.18;if(blockedCooldown<=0){say('A tree blocks your way.');blockedCooldown=.8}}}
function update(dt,now){if(blockedCooldown>0)blockedCooldown-=dt;if(won)return;if(pressed.left)targetYaw+=dt*2.45;if(pressed.right)targetYaw-=dt*2.45;yaw+=(targetYaw-yaw)*Math.min(1,dt*12);player.rotation.y=yaw;var targetSpeed=pressed.forward?4.1:pressed.back?-2.8:0;vel+=(targetSpeed-vel)*Math.min(1,dt*7);if(Math.abs(vel)>.05){move(Math.sin(yaw)*vel*dt,Math.cos(yaw)*vel*dt);walkTime+=dt*(7+Math.abs(vel));stepTimer+=dt*Math.abs(vel);camera.position.y=Math.sin(walkTime)*.052+Math.sin(walkTime*.5)*.018;if(stepTimer>.58){stepTimer=0;footstep()}}else{camera.position.y*=.86}if(lanternMesh.visible){lanternMesh.rotation.y+=dt*1.7;lanternMesh.position.y=.42+Math.sin(now*.002)*.06;if(player.position.distanceTo(lanternMesh.position)<1.35){hasLantern=true;lanternMesh.visible=false;lanternLight.intensity=2.25;flashLight.intensity=.95;scene.fog.density=.024;say('Lantern found. Warm light cuts through the fog. Find the glowing gate.');sync()}}if(hasLantern){lanternLight.position.copy(player.position);lanternLight.position.y=1.25;flashLight.position.copy(player.position);flashLight.position.y=1.35;flashLight.target.position.set(player.position.x-Math.sin(yaw)*8,1.2,player.position.z-Math.cos(yaw)*8)}if(compassArrow){var target=hasLantern?new THREE.Vector3(0,0,-27):lanternMesh.position;var angle=Math.atan2(target.x-player.position.x,target.z-player.position.z)-yaw;compassArrow.rotation.z=angle}for(var i=0;i<fireflies.length;i++){var o=fireflies[i];o.position.x=o.userData.base.x+Math.sin(now*.0015+o.userData.phase)*.35;o.position.y=o.userData.base.y+Math.sin(now*.002+o.userData.phase)*.18}if(player.position.distanceTo(new THREE.Vector3(0,1.5,-27))<2.2){if(hasLantern){won=true;say('You escaped the forest.')}else say('The gate is locked by fog. Find the lantern first.');sync()}}
function resize(){if(!stage||!renderer||!camera)return;var w=stage.clientWidth||300,h=stage.clientHeight||500;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function loop(now){var dt=Math.min(.05,(now-last)/1000);last=now;resize();update(dt,now);if(gateMesh)gateMesh.rotation.y=Math.sin(now*.001)*.035;renderer.render(scene,camera);requestAnimationFrame(loop)}
try{init()}catch(e){say('3D engine could not start.')}
})();
</script>
</section>`;
