const nftPriceIconUrl = '/app/api/nft-price-icon.png';

const marketLayoutStyles = `<style id="marketRealOnlyLayoutStyles">
#market.market-view{height:calc(100vh - 238px)!important;min-height:0!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;padding:6px 0 0!important}
#market .market-segment{flex:0 0 auto!important;position:relative!important;z-index:8!important;margin-bottom:10px!important}
#market .market-filter-bar{flex:0 0 auto!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;margin:0 0 12px!important;position:relative!important;z-index:40!important}
#market .market-collection-wrap,#market .market-sort-wrap{position:relative!important;flex:0 0 auto!important;z-index:60!important}
#market .market-collection-button,#market .market-sort-button{height:38px!important;border:0!important;border-radius:18px!important;background:linear-gradient(180deg,rgba(255,255,255,.065),rgba(255,255,255,.028))!important;color:#fff!important;padding:0 13px!important;display:flex!important;align-items:center!important;gap:7px!important;font-size:12px!important;font-weight:800!important;box-shadow:0 18px 42px rgba(0,0,0,.22)!important;-webkit-backdrop-filter:blur(3px) saturate(1.18)!important;backdrop-filter:blur(3px) saturate(1.18)!important}
#market .market-collection-button svg,#market .market-sort-button svg{width:16px!important;height:16px!important;opacity:.88!important}
#market .market-collection-menu,#market .market-sort-menu{position:absolute!important;top:46px!important;width:208px!important;max-height:284px!important;overflow-y:auto!important;border-radius:24px!important;background:linear-gradient(180deg,rgba(61,28,40,.92),rgba(21,10,16,.88))!important;border:0!important;outline:0!important;box-shadow:0 24px 54px rgba(0,0,0,.45)!important;-webkit-backdrop-filter:blur(3px) saturate(1.16)!important;backdrop-filter:blur(3px) saturate(1.16)!important;padding:8px!important;display:none!important;z-index:99999!important}
#market .market-collection-menu{left:0!important}#market .market-sort-menu{right:0!important}
#market .market-collection-menu:before,#market .market-sort-menu:before{display:none!important}
#market .market-collection-menu.open,#market .market-sort-menu.open{display:block!important}
#market .market-collection-option,#market .market-sort-option{position:relative!important;z-index:1!important;width:100%!important;height:44px!important;border:0!important;outline:0!important;border-radius:16px!important;background:rgba(255,255,255,.045)!important;color:#fff!important;display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 12px!important;font-size:13px!important;font-weight:800!important;text-align:left!important;margin:0 0 6px!important;box-shadow:none!important;-webkit-backdrop-filter:blur(3px)!important;backdrop-filter:blur(3px)!important}
#market .market-collection-option:last-child,#market .market-sort-option:last-child{margin-bottom:0!important}
#market .market-collection-option.active,#market .market-sort-option.active{background:linear-gradient(180deg,rgba(255,255,255,.12),rgba(255,255,255,.06))!important;color:#fff!important;box-shadow:none!important}
#market .market-collection-option i,#market .market-sort-option i{font-style:normal!important;color:#fff!important;font-weight:900!important;opacity:0!important}.market-collection-option.active i,.market-sort-option.active i{opacity:1!important}
#market .market-tab-panel.active{min-height:0!important;flex:1 1 auto!important;overflow:hidden!important;position:relative!important;display:flex!important;flex-direction:column!important}
#market .market-grid-scroll{min-height:0!important;flex:1 1 auto!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;padding-bottom:calc(124px + env(safe-area-inset-bottom))!important}
#market .market-grid{padding-bottom:24px!important}
#market .market-pull-refresh{height:0!important;display:flex!important;align-items:center!important;justify-content:center!important;color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:800!important;overflow:hidden!important;transition:height .18s ease!important}.market-pull-refresh.ready{height:42px!important}.market-pull-refresh.loading{height:48px!important;color:#fff!important}
#market .market-pull-spinner{width:17px!important;height:17px!important;border-radius:999px!important;border:2px solid rgba(255,255,255,.24)!important;border-top-color:#fff!important;margin-right:8px!important;animation:marketSpin .75s linear infinite!important;display:none!important}.market-pull-refresh.loading .market-pull-spinner{display:block!important}@keyframes marketSpin{to{transform:rotate(360deg)}}
#market .market-price-button.vexa-fragment-price{display:flex!important;gap:4px!important;align-items:center!important;justify-content:center!important}
#market .market-price-icon{width:28px!important;height:28px!important;object-fit:contain!important;display:block!important;flex:0 0 auto!important;filter:none!important;margin-right:1px!important}
#market .market-detail-price .market-price-icon{width:36px!important;height:36px!important;margin-right:2px!important}
#market .market-price-button img{filter:none!important;opacity:.98!important}
#market .market-nft-card[data-market-source="telegram"] .market-price-button:not(.vexa-fragment-price){display:none!important}
#market .market-nft-card[data-market-source="telegram"] .vexa-fragment-price + .vexa-fragment-price{display:none!important}
#market .market-price-button b{letter-spacing:-.01em!important;line-height:1!important}
#market .market-detail-price strong{gap:5px!important}
</style>`;

const detailSheet = `<div id="marketDetailSheet" class="market-detail-sheet" aria-hidden="true"><div class="market-detail-backdrop" data-market-detail-close="1"></div><div class="market-detail-card" role="dialog" aria-modal="true" aria-label="NFT details"><div class="market-detail-pad"><div class="market-detail-content" data-market-detail-content><div class="market-detail-titlebar"><div class="market-detail-title-main"><div class="market-detail-thumb" data-market-detail-media></div><div class="market-detail-heading"><span class="market-detail-kicker" data-market-detail-collection>Fragment Gifts</span><h3 data-market-detail-title>NFT</h3></div></div><button class="market-detail-close" type="button" data-market-detail-close="1" aria-label="Close"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2.6" stroke-linecap="round"/></svg></button></div><p class="market-detail-description" data-market-detail-description></p><div class="market-detail-specs" data-market-detail-specs></div><div class="market-detail-price"><span>Price</span><strong><img class="market-price-icon" src="${nftPriceIconUrl}" alt="TON" decoding="async"/><b data-market-detail-price>0</b></strong></div></div></div></div></div>`;

const filterBar = `<div class="market-filter-bar"><div class="market-collection-wrap"><button class="market-collection-button" type="button" data-market-collection-toggle><span data-market-collection-label>Collections</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="market-collection-menu" data-market-collection-menu><button class="market-collection-option active" type="button" data-market-collection="all"><span>All collections</span><i>✓</i></button></div></div><div class="market-sort-wrap"><button class="market-sort-button" type="button" data-market-sort-toggle><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 4v14m0 0 4-4m-4 4-4-4M17 20V6m0 0-4 4m4-4 4 4" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-market-sort-label>Price low to high</span></button><div class="market-sort-menu" data-market-sort-menu><button class="market-sort-option active" type="button" data-market-sort="price_asc"><span>Price low to high</span><i>✓</i></button><button class="market-sort-option" type="button" data-market-sort="price_desc"><span>Price high to low</span><i>✓</i></button></div></div></div>`;

export const MARKET_SECTION = `${marketLayoutStyles}<section id="market" class="view market-view"><div class="market-segment" role="tablist" aria-label="Market tabs"><button class="market-segment-btn active" type="button" data-market-tab="store">Market</button><span class="market-segment-split"><button class="market-segment-btn" type="button" data-market-tab="owned">My NFTs</button><button class="market-segment-btn" type="button" data-market-tab="listed">Listed</button></span></div>${filterBar}<div class="market-tab-panel active" data-market-panel="store"><div class="market-grid-scroll" data-market-scroll="store"><div class="market-pull-refresh" data-market-pull><span class="market-pull-spinner"></span><span data-market-pull-text>Pull to refresh</span></div><div class="market-grid game-grid market-owned-grid" data-market-telegram-grid></div><div class="market-owned-empty" data-market-telegram-empty><div class="market-owned-icon">◆</div><strong>No Telegram Gifts yet</strong><p>Your Telegram Gifts will appear here.</p></div></div></div><div class="market-tab-panel" data-market-panel="owned"><div class="market-grid-scroll" data-market-scroll="owned"><div class="market-grid game-grid market-owned-grid" data-market-owned-grid></div><div class="market-owned-empty" data-market-owned-empty><div class="market-owned-icon">◆</div><strong>No NFTs yet</strong><p>Your purchased NFTs will appear here.</p></div></div></div><div class="market-tab-panel" data-market-panel="listed"><div class="market-grid-scroll"><div class="market-owned-empty"><div class="market-owned-icon">↗</div><strong>No listed NFTs</strong><p>NFTs you put up for sale will appear here.</p></div></div></div>${detailSheet}</section>`;
