const tonLogo = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"%3E%3Cpath fill="white" d="M12 16h40c4.2 0 6.7 4.8 4.2 8.2L36.2 52.4c-2 2.9-6.4 2.9-8.4 0L7.8 24.2C5.3 20.8 7.8 16 12 16Zm4.1 7 13.4 19.3V23H16.1Zm18.4 0v19.3L47.9 23H34.5ZM32 47.2 48.3 23H15.7L32 47.2Z"/%3E%3C/svg%3E';

const marketLayoutStyles = `<style id="marketRealOnlyLayoutStyles">
#market.market-view{height:calc(100vh - 238px)!important;min-height:0!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;padding:6px 0 0!important}
#market .market-segment{flex:0 0 auto!important;position:relative!important;z-index:8!important;margin-bottom:10px!important}
#market .market-filter-bar{flex:0 0 auto!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;margin:0 0 12px!important;position:relative!important;z-index:9!important}
#market .market-filter-title{color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:800!important;letter-spacing:.02em!important;text-transform:uppercase!important}
#market .market-sort-wrap{position:relative!important;flex:0 0 auto!important}
#market .market-sort-button{height:38px!important;border:0!important;border-radius:14px!important;background:rgba(255,255,255,.065)!important;color:#fff!important;padding:0 12px!important;display:flex!important;align-items:center!important;gap:7px!important;font-size:12px!important;font-weight:800!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14),0 14px 34px rgba(0,0,0,.18)!important;-webkit-backdrop-filter:blur(10px) saturate(1.18)!important;backdrop-filter:blur(10px) saturate(1.18)!important}
#market .market-sort-button svg{width:16px!important;height:16px!important;opacity:.8!important}
#market .market-sort-menu{position:absolute!important;right:0!important;top:44px!important;width:190px!important;border-radius:18px!important;background:rgba(24,28,36,.92)!important;border:1px solid rgba(255,255,255,.10)!important;box-shadow:0 24px 70px rgba(0,0,0,.42)!important;-webkit-backdrop-filter:blur(18px) saturate(1.25)!important;backdrop-filter:blur(18px) saturate(1.25)!important;padding:8px!important;display:none!important;z-index:30!important}
#market .market-sort-menu.open{display:block!important}
#market .market-sort-option{width:100%!important;height:42px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#fff!important;display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 10px!important;font-size:13px!important;font-weight:750!important;text-align:left!important}
#market .market-sort-option.active{background:rgba(64,164,255,.16)!important;color:#fff!important}
#market .market-sort-option i{font-style:normal!important;color:#5db7ff!important;font-weight:900!important;opacity:0!important}.market-sort-option.active i{opacity:1!important}
#market .market-tab-panel.active{min-height:0!important;flex:1 1 auto!important;overflow:hidden!important;position:relative!important;display:flex!important;flex-direction:column!important}
#market .market-grid-scroll{min-height:0!important;flex:1 1 auto!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;padding-bottom:calc(124px + env(safe-area-inset-bottom))!important}
#market .market-grid{padding-bottom:24px!important}
#market .market-pull-refresh{height:0!important;display:flex!important;align-items:center!important;justify-content:center!important;color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:800!important;overflow:hidden!important;transition:height .18s ease!important}.market-pull-refresh.ready{height:42px!important}.market-pull-refresh.loading{height:48px!important;color:#fff!important}
#market .market-pull-spinner{width:17px!important;height:17px!important;border-radius:999px!important;border:2px solid rgba(255,255,255,.24)!important;border-top-color:#fff!important;margin-right:8px!important;animation:marketSpin .75s linear infinite!important;display:none!important}.market-pull-refresh.loading .market-pull-spinner{display:block!important}@keyframes marketSpin{to{transform:rotate(360deg)}}
#market .market-price-button img{filter:none!important;opacity:.96!important}#market .market-price-button b{letter-spacing:-.01em!important}
</style>`;

const detailSheet = `<div id="marketDetailSheet" class="market-detail-sheet" aria-hidden="true"><div class="market-detail-backdrop" data-market-detail-close="1"></div><div class="market-detail-card" role="dialog" aria-modal="true" aria-label="NFT details"><div class="market-detail-pad"><div class="market-detail-content" data-market-detail-content><div class="market-detail-titlebar"><div class="market-detail-title-main"><div class="market-detail-thumb" data-market-detail-media></div><div class="market-detail-heading"><span class="market-detail-kicker" data-market-detail-collection>Fragment Gifts</span><h3 data-market-detail-title>NFT</h3></div></div><button class="market-detail-close" type="button" data-market-detail-close="1" aria-label="Close"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2.6" stroke-linecap="round"/></svg></button></div><p class="market-detail-description" data-market-detail-description></p><div class="market-detail-specs" data-market-detail-specs></div><div class="market-detail-price"><span>Price</span><strong><img src="${tonLogo}" alt="TON" decoding="async"/><b data-market-detail-price>0</b></strong></div></div></div></div></div>`;

const filterBar = `<div class="market-filter-bar"><span class="market-filter-title">Fragment Gifts</span><div class="market-sort-wrap"><button class="market-sort-button" type="button" data-market-sort-toggle><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 4v14m0 0 4-4m-4 4-4-4M17 20V6m0 0-4 4m4-4 4 4" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-market-sort-label>Price low to high</span></button><div class="market-sort-menu" data-market-sort-menu><button class="market-sort-option active" type="button" data-market-sort="price_asc"><span>Price low to high</span><i>✓</i></button><button class="market-sort-option" type="button" data-market-sort="price_desc"><span>Price high to low</span><i>✓</i></button></div></div></div>`;

export const MARKET_SECTION = `${marketLayoutStyles}<section id="market" class="view market-view"><div class="market-segment" role="tablist" aria-label="Market tabs"><button class="market-segment-btn active" type="button" data-market-tab="store">Market</button><span class="market-segment-split"><button class="market-segment-btn" type="button" data-market-tab="owned">My NFTs</button><button class="market-segment-btn" type="button" data-market-tab="listed">Listed</button></span></div>${filterBar}<div class="market-tab-panel active" data-market-panel="store"><div class="market-grid-scroll" data-market-scroll="store"><div class="market-pull-refresh" data-market-pull><span class="market-pull-spinner"></span><span data-market-pull-text>Pull to refresh</span></div><div class="market-grid game-grid market-owned-grid" data-market-telegram-grid></div><div class="market-owned-empty" data-market-telegram-empty><div class="market-owned-icon">◆</div><strong>No Telegram Gifts yet</strong><p>Your Telegram Gifts will appear here.</p></div></div></div><div class="market-tab-panel" data-market-panel="owned"><div class="market-grid-scroll" data-market-scroll="owned"><div class="market-grid game-grid market-owned-grid" data-market-owned-grid></div><div class="market-owned-empty" data-market-owned-empty><div class="market-owned-icon">◆</div><strong>No NFTs yet</strong><p>Your purchased NFTs will appear here.</p></div></div></div><div class="market-tab-panel" data-market-panel="listed"><div class="market-grid-scroll"><div class="market-owned-empty"><div class="market-owned-icon">↗</div><strong>No listed NFTs</strong><p>NFTs you put up for sale will appear here.</p></div></div></div>${detailSheet}</section>`;
