export const MINES_SCRIPT = `
(function(){
  var size=25;
  var NANO=1000000000;
  var audioCtx=null;
  var toastTimer=null;
  var lastMultiplierText='1.00x';
  var tileImages={safe:'/app/api/uploaded-image/mines-safe.png',bomb:'/app/api/uploaded-image/mines-bomb.png'};
  var state={active:false,ended:false,amountNano:10000000,mines:3,revealed:0,bombs:{},safe:{},multiplier:1};
  function q(id){return document.getElementById(id)}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
  function toNano(value){return Math.max(0,Math.floor((Number(String(value||'').replace(',','.'))||0)*NANO))}
  function fromNano(value){var ton=Math.max(0,Math.floor(Number(value)||0))/NANO;return ton.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
  function preload(url){if(!url)return;var img=new Image();img.decoding='async';img.src=url}
  function imageEl(kind){var img=document.createElement('img');img.decoding='async';img.loading='eager';img.alt=kind==='bomb'?'Mine':'Safe';img.src=kind==='bomb'?tileImages.bomb:tileImages.safe;img.onerror=function(){img.remove()};return img}
  function loadImages(){fetch('/app/api/uploaded-images',{cache:'no-store'}).then(function(r){return r.json()}).then(function(data){if(data&&data.minesSafeUrl)tileImages.safe=data.minesSafeUrl;if(data&&data.minesBombUrl)tileImages.bomb=data.minesBombUrl;preload(tileImages.safe);preload(tileImages.bomb);primeBoardImages()}).catch(function(){preload(tileImages.safe);preload(tileImages.bomb);primeBoardImages()})}
  function tone(freq,duration,type,gain){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();var osc=audioCtx.createOscillator();var vol=audioCtx.createGain();osc.type=type||'sine';osc.frequency.value=freq;vol.gain.value=0.0001;osc.connect(vol);vol.connect(audioCtx.destination);var now=audioCtx.currentTime;vol.gain.exponentialRampToValueAtTime(gain||0.035,now+0.012);vol.gain.exponentialRampToValueAtTime(0.0001,now+duration);osc.start(now);osc.stop(now+duration+0.02)}catch(e){}}
  function sound(name){if(name==='start'){tone(240,.09,'sine',.026);setTimeout(function(){tone(360,.11,'sine',.026)},55)}else if(name==='safe'){tone(520,.075,'triangle',.022);setTimeout(function(){tone(720,.08,'triangle',.018)},38)}else if(name==='mine'){tone(120,.18,'sawtooth',.026);setTimeout(function(){tone(72,.24,'sine',.022)},70)}else if(name==='cash'){tone(620,.08,'triangle',.025);setTimeout(function(){tone(880,.1,'triangle',.022)},55);setTimeout(function(){tone(1180,.12,'sine',.018)},120)}}
  function readTonBalance(){return window.VexaTonBalance?Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0)):0}
  function addTonDelta(deltaNano){if(window.VexaTonBalance)window.VexaTonBalance.add(Math.floor(Number(deltaNano)||0));else window.dispatchEvent(new CustomEvent('vexa-ton-balance-game-change',{detail:{deltaNano:Math.floor(Number(deltaNano)||0)}}))}
  function calcMultiplier(){var safeLeft=size-state.mines-state.revealed;var totalLeft=size-state.revealed;if(totalLeft<=0||safeLeft<=0)return state.multiplier;var edge=.96;var chance=safeLeft/totalLeft;state.multiplier=Math.max(1,state.multiplier*(1/chance)*edge);return state.multiplier}
  function setStatus(text){var el=q('minesToast');if(!el||!text)return;el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.classList.remove('show')},4200)}
  function setMultiplierText(){var mx=q('minesMultiplier');if(!mx)return;var next=state.multiplier.toFixed(2)+'x';if(mx.textContent!==next&&lastMultiplierText!==next){mx.classList.remove('bump');void mx.offsetWidth;mx.classList.add('bump')}mx.textContent=next;lastMultiplierText=next;var view=q('mines');if(view)view.classList.toggle('playing',state.active)}
  function refresh(){var amount=q('minesBet');var count=q('minesCount');state.amountNano=clamp(toNano(amount&&amount.value),1,999999999999999);state.mines=clamp(Math.floor(Number(count&&count.value)||3),1,20);if(amount)amount.value=fromNano(state.amountNano);setMultiplierText();var start=q('minesStart');if(start)start.textContent=state.active?'Playing':'Start Game';var cash=q('minesCashout');if(cash)cash.disabled=!state.active||state.revealed<1}
  function tileKind(i){return state.active||state.ended?state.bombs[i]?'bomb':'safe':'safe'}
  function setTileBack(tile,kind){var back=tile&&tile.querySelector&&tile.querySelector('.mine-tile-back');if(!back)return;back.textContent='';back.appendChild(imageEl(kind))}
  function primeBoardImages(){document.querySelectorAll('[data-mine-cell]').forEach(function(tile){var i=Number(tile.getAttribute('data-mine-cell'));setTileBack(tile,tileKind(i))})}
  function buildBoard(){var board=q('minesBoard');if(!board)return;board.innerHTML='';for(var i=0;i<size;i++){var b=document.createElement('button');var card=document.createElement('span');var front=document.createElement('span');var back=document.createElement('span');b.type='button';b.className='mine-tile';b.setAttribute('data-mine-cell',String(i));b.setAttribute('aria-label','Hidden tile');card.className='mine-tile-card';front.className='mine-tile-face mine-tile-front';back.className='mine-tile-face mine-tile-back';card.appendChild(front);card.appendChild(back);b.appendChild(card);board.appendChild(b);setTileBack(b,tileKind(i))}}
  function placeBombs(){state.bombs={};var picked=0;while(picked<state.mines){var n=Math.floor(Math.random()*size);if(!state.bombs[n]){state.bombs[n]=true;picked++}}}
  function revealTile(tile,kind){if(!tile||tile.classList.contains('revealed'))return;setTileBack(tile,kind);tile.disabled=true;tile.setAttribute('aria-label',kind==='bomb'?'Mine tile':'Safe tile');tile.classList.add('revealed',kind==='bomb'?'bomb':'safe')}
  function revealAll(){document.querySelectorAll('[data-mine-cell]').forEach(function(tile){var i=Number(tile.getAttribute('data-mine-cell'));revealTile(tile,state.bombs[i]?'bomb':'safe')})}
  function start(){refresh();if(state.active)return;var balance=readTonBalance();if(balance<state.amountNano){setStatus('Not enough TON balance.');return}sound('start');state.active=true;state.ended=false;state.revealed=0;state.bombs={};state.safe={};state.multiplier=1;addTonDelta(-state.amountNano);placeBombs();buildBoard();setStatus('Choose a safe tile.');refresh()}
  function cashout(){if(!state.active||state.revealed<1)return;var resultNano=Math.max(0,Math.floor(state.amountNano*state.multiplier));sound('cash');state.active=false;state.ended=true;addTonDelta(resultNano);revealAll();setStatus('Result +' + fromNano(resultNano) + ' TON.');refresh()}
  function hit(cell){if(!state.active||state.ended)return;var i=Number(cell.getAttribute('data-mine-cell'));if(!Number.isFinite(i)||state.safe[i]||cell.classList.contains('revealed'))return;if(state.bombs[i]){sound('mine');revealTile(cell,'bomb');state.active=false;state.ended=true;setTimeout(revealAll,180);setStatus('Mine hit.');refresh();return}sound('safe');state.safe[i]=true;state.revealed++;revealTile(cell,'safe');calcMultiplier();setStatus('Safe hit. Multiplier ' + state.multiplier.toFixed(2) + 'x');if(state.revealed>=size-state.mines){cashout();return}refresh()}
  function bind(){loadImages();buildBoard();refresh();window.addEventListener('vexa-ton-balance-sync',refresh);window.addEventListener('vexa-mines-images-sync',function(ev){if(!ev||!ev.detail)return;if(ev.detail.safeUrl)tileImages.safe=ev.detail.safeUrl;if(ev.detail.bombUrl)tileImages.bomb=ev.detail.bombUrl;preload(tileImages.safe);preload(tileImages.bomb);primeBoardImages()});var amount=q('minesBet');var count=q('minesCount');if(amount)amount.addEventListener('input',refresh);if(count)count.addEventListener('change',refresh);document.addEventListener('click',function(ev){var step=ev.target&&ev.target.closest&&ev.target.closest('[data-mines-bet]');if(step){tone(260,.045,'sine',.014);var input=q('minesBet');if(input){var next=Number(input.value||0)+Number(step.getAttribute('data-mines-bet'));input.value=String(Math.max(.0001,next));refresh()}return}var startBtn=ev.target&&ev.target.closest&&ev.target.closest('#minesStart');if(startBtn){start();return}var cash=ev.target&&ev.target.closest&&ev.target.closest('#minesCashout');if(cash){cashout();return}var tile=ev.target&&ev.target.closest&&ev.target.closest('[data-mine-cell]');if(tile)hit(tile)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;
