export const MINES_SCRIPT = `
(function(){
  var size=25;
  var audioCtx=null;
  var toastTimer=null;
  var state={active:false,ended:false,bet:10,mines:3,revealed:0,bombs:{},safe:{},multiplier:1};
  function q(id){return document.getElementById(id)}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
  function money(v){return String(Math.max(0,Math.floor(Number(v)||0)))}
  function tone(freq,duration,type,gain){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();var osc=audioCtx.createOscillator();var vol=audioCtx.createGain();osc.type=type||'sine';osc.frequency.value=freq;vol.gain.value=0.0001;osc.connect(vol);vol.connect(audioCtx.destination);var now=audioCtx.currentTime;vol.gain.exponentialRampToValueAtTime(gain||0.035,now+0.012);vol.gain.exponentialRampToValueAtTime(0.0001,now+duration);osc.start(now);osc.stop(now+duration+0.02)}catch(e){}}
  function sound(name){if(name==='start'){tone(240,.09,'sine',.026);setTimeout(function(){tone(360,.11,'sine',.026)},55)}else if(name==='safe'){tone(520,.075,'triangle',.022);setTimeout(function(){tone(720,.08,'triangle',.018)},38)}else if(name==='mine'){tone(120,.18,'sawtooth',.026);setTimeout(function(){tone(72,.24,'sine',.022)},70)}else if(name==='cash'){tone(620,.08,'triangle',.025);setTimeout(function(){tone(880,.1,'triangle',.022)},55);setTimeout(function(){tone(1180,.12,'sine',.018)},120)}}
  function readCredit(){var el=q('plinkoCredit')||q('creditCount')||q('plinkoCreditHeader');return Math.max(0,Math.floor(Number(el&&el.textContent)||0))}
  function setCredit(value,delta){var credit=Math.max(0,Math.floor(Number(value)||0));['plinkoCredit','creditCount','plinkoCreditHeader'].forEach(function(id){var el=q(id);if(el)el.textContent=String(credit)});try{window.dispatchEvent(new CustomEvent('vexa-credit-game-change',{detail:{credit:credit,delta:Math.floor(Number(delta)||0)}}))}catch(e){}}
  function calcMultiplier(){var safeLeft=size-state.mines-state.revealed;var totalLeft=size-state.revealed;if(totalLeft<=0||safeLeft<=0)return state.multiplier;var edge=.96;var chance=safeLeft/totalLeft;state.multiplier=Math.max(1, state.multiplier*(1/chance)*edge);return state.multiplier}
  function setStatus(text){var el=q('minesToast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.classList.remove('show')},5600)}
  function refresh(){var bet=q('minesBet');var count=q('minesCount');state.bet=clamp(Math.floor(Number(bet&&bet.value)||10),1,999999);state.mines=clamp(Math.floor(Number(count&&count.value)||3),1,20);if(bet)bet.value=String(state.bet);var mx=q('minesMultiplier');if(mx)mx.textContent=state.multiplier.toFixed(2)+'x';var start=q('minesStart');if(start)start.textContent=state.active?'Playing':'Start Game';var cash=q('minesCashout');if(cash)cash.disabled=!state.active||state.revealed<1}
  function buildBoard(){var board=q('minesBoard');if(!board)return;board.innerHTML='';for(var i=0;i<size;i++){var b=document.createElement('button');b.type='button';b.className='mine-tile';b.setAttribute('data-mine-cell',String(i));b.textContent='';board.appendChild(b)}}
  function placeBombs(){state.bombs={};var picked=0;while(picked<state.mines){var n=Math.floor(Math.random()*size);if(!state.bombs[n]){state.bombs[n]=true;picked++}}}
  function revealAll(){document.querySelectorAll('[data-mine-cell]').forEach(function(tile){var i=Number(tile.getAttribute('data-mine-cell'));tile.disabled=true;if(state.bombs[i]){tile.classList.add('bomb');tile.textContent='✕'}else if(!state.safe[i]){tile.textContent=''}})}
  function start(){refresh();if(state.active)return;var credit=readCredit();if(credit<state.bet){setStatus('Not enough credit.');return}sound('start');state.active=true;state.ended=false;state.revealed=0;state.bombs={};state.safe={};state.multiplier=1;setCredit(credit-state.bet,-state.bet);placeBombs();buildBoard();setStatus('Game started. Pick a safe tile.');refresh()}
  function cashout(){if(!state.active||state.revealed<1)return;var win=Math.floor(state.bet*state.multiplier);sound('cash');state.active=false;state.ended=true;setCredit(readCredit()+win,win);revealAll();setStatus('Cashed out +' + money(win) + ' credits.');refresh()}
  function hit(cell){if(!state.active||state.ended)return;var i=Number(cell.getAttribute('data-mine-cell'));if(!Number.isFinite(i)||state.safe[i])return;if(state.bombs[i]){sound('mine');cell.classList.add('bomb');cell.textContent='✕';state.active=false;state.ended=true;revealAll();setStatus('Mine hit. Bet lost.');refresh();return}sound('safe');state.safe[i]=true;state.revealed++;cell.classList.add('safe');cell.textContent='✓';cell.disabled=true;calcMultiplier();if(state.revealed>=size-state.mines){cashout();return}setStatus('Safe tile. Multiplier increased.');refresh()}
  function bind(){buildBoard();refresh();var bet=q('minesBet');var count=q('minesCount');if(bet)bet.addEventListener('input',refresh);if(count)count.addEventListener('change',refresh);document.addEventListener('click',function(ev){var step=ev.target&&ev.target.closest&&ev.target.closest('[data-mines-bet]');if(step){tone(260,.045,'sine',.014);var input=q('minesBet');if(input){input.value=String(clamp((Number(input.value)||10)+Number(step.getAttribute('data-mines-bet')),1,999999));refresh()}return}var startBtn=ev.target&&ev.target.closest&&ev.target.closest('#minesStart');if(startBtn){start();return}var cash=ev.target&&ev.target.closest&&ev.target.closest('#minesCashout');if(cash){cashout();return}var tile=ev.target&&ev.target.closest&&ev.target.closest('[data-mine-cell]');if(tile)hit(tile)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;
