export const PLAY_ZONE_SHOWCASE_OVERRIDES = `
.play-zone-stage{gap:10px!important}
.play-zone-plinko-showcase{display:none!important}
#playzone .play-zone-nft-strip{display:none!important}
#playzone .game-card-shell{width:100%!important;max-width:none!important;display:block!important;position:relative!important;margin:0!important;padding:0!important;transform:none!important;animation:none!important;box-shadow:none!important;background:transparent!important;border:0!important;overflow:visible!important}
#playzone .game-card-live{width:100%!important;max-width:none!important;height:calc((100vw - 8px) / 3 + 8px)!important;min-height:126px!important;max-height:178px!important;position:relative!important;display:block!important;background:rgba(255,255,255,.035)!important;background-image:none!important;border:1px solid rgba(255,255,255,.14)!important;box-shadow:0 16px 36px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.12)!important;outline:0!important;padding:4px!important;margin:0!important;border-radius:22px!important;overflow:hidden!important;filter:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important;transform-origin:center!important}
#playzone .game-card-live:before,#playzone .game-card-live:after{content:none!important;display:none!important;background:none!important;box-shadow:none!important;border:0!important}
#playzone .game-card-live .game-image{position:absolute!important;inset:4px!important;display:block!important;width:auto!important;height:auto!important;aspect-ratio:3/1!important;padding:0!important;margin:0!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:14px!important;background:rgba(255,255,255,.025)!important;background-image:none!important;box-shadow:none!important;outline:0!important;overflow:hidden!important;z-index:1!important}
#playzone .game-card-live .game-image:before{content:none!important;display:none!important}
#playzone .game-card-live .game-image:after{content:''!important;position:absolute!important;inset:0!important;border-radius:inherit!important;background:linear-gradient(180deg,rgba(0,0,0,0) 62%,rgba(0,0,0,.14) 100%)!important;pointer-events:none!important;z-index:2!important}
#playzone .game-card-live .game-image img{position:absolute!important;inset:0!important;display:block!important;width:100%!important;height:100%!important;aspect-ratio:3/1!important;object-fit:fill!important;object-position:center!important;border:0!important;border-radius:12px!important;background:transparent!important;box-shadow:none!important;outline:0!important;image-rendering:auto!important;transform:translateZ(0)!important;backface-visibility:hidden!important}
#playzone .game-card-shell>.game-footer-live{position:absolute!important;left:18px!important;right:18px!important;bottom:12px!important;z-index:4!important;display:flex!important;justify-content:center!important;align-items:center!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important;margin:0!important;outline:0!important;pointer-events:none!important}
#playzone .game-card-shell>.game-footer-live:before,#playzone .game-card-shell>.game-footer-live:after{content:none!important;display:none!important}
#playzone .game-card-shell>.game-footer-live .game-players{background:rgba(0,0,0,.22)!important;border:1px solid rgba(255,255,255,.13)!important;border-radius:999px!important;box-shadow:0 10px 24px rgba(0,0,0,.18),inset 0 1px 0 rgba(255,255,255,.08)!important;padding:5px 10px!important;margin:0!important;-webkit-backdrop-filter:blur(10px) saturate(160%)!important;backdrop-filter:blur(10px) saturate(160%)!important}
#playzone .game-card-live.is-soft-entering{transform:scale(.985)!important;opacity:.72!important;filter:brightness(1.05) saturate(1.08)!important}
body.soft-game-entering #playzone{opacity:.96!important;transition:opacity .18s ease!important}
@media(max-width:380px){#playzone .game-card-live{height:calc((100vw - 8px) / 3 + 8px)!important;min-height:118px!important;max-height:150px!important;border-radius:20px!important;padding:4px!important}#playzone .game-card-live .game-image{inset:4px!important;border-radius:12px!important;aspect-ratio:3/1!important}#playzone .game-card-live .game-image img{border-radius:10px!important;object-fit:fill!important;aspect-ratio:3/1!important;height:100%!important}}
`;
