export const PLAY_ZONE_ROW_IMAGE_FIX = `
#playzone .game-grid{row-gap:12px!important}
#playzone .play-zone-row-ad{grid-column:1/-1!important;display:grid!important;align-items:center!important;justify-content:stretch!important;gap:8px!important;height:118px!important;min-height:118px!important;margin:0 0 4px!important;overflow:visible!important;pointer-events:none!important}
#playzone .play-zone-row-ad--right{grid-template-columns:minmax(0,34%) minmax(0,66%)!important;grid-template-areas:"copy image"!important}
#playzone .play-zone-row-ad--left{grid-template-columns:minmax(0,64%) minmax(0,36%)!important;grid-template-areas:"image copy"!important}
#playzone .play-zone-row-ad__copy{grid-area:copy!important;max-width:none!important;min-height:74px!important;margin:0!important;padding:10px 9px!important;border-radius:20px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(255,255,255,.11)!important;box-shadow:0 14px 30px rgba(0,0,0,.16),inset 0 1px 0 rgba(255,255,255,.14)!important;backdrop-filter:blur(4px) saturate(1.12)!important;-webkit-backdrop-filter:blur(4px) saturate(1.12)!important;color:rgba(255,255,255,.82)!important;font-size:12.4px!important;font-weight:850!important;line-height:1.28!important;letter-spacing:-.035em!important;text-align:center!important;display:flex!important;align-items:center!important;justify-content:center!important;align-self:center!important;position:relative!important;z-index:2!important;text-shadow:0 8px 20px rgba(0,0,0,.42)!important}
#playzone .play-zone-row-ad img{grid-area:image!important;width:100%!important;height:118px!important;max-width:none!important;max-height:118px!important;min-width:0!important;display:block!important;object-fit:contain!important;object-position:center!important;align-self:center!important;justify-self:center!important;background:transparent!important;border:0!important;box-shadow:none!important}
#playzone .play-zone-row-ad--right img{width:100%!important;height:118px!important}
#playzone .play-zone-row-ad--left img{width:100%!important;height:118px!important}
#playzone .play-zone-row-ad.is-empty{display:none!important}
@media(max-width:380px){#playzone .game-grid{row-gap:10px!important}#playzone .play-zone-row-ad{height:110px!important;min-height:110px!important;margin:0 0 3px!important;gap:7px!important}#playzone .play-zone-row-ad--right{grid-template-columns:minmax(0,35%) minmax(0,65%)!important}#playzone .play-zone-row-ad--left{grid-template-columns:minmax(0,63%) minmax(0,37%)!important}#playzone .play-zone-row-ad__copy{min-height:68px!important;padding:9px 8px!important;border-radius:18px!important;font-size:10.8px!important;line-height:1.24!important}#playzone .play-zone-row-ad img,#playzone .play-zone-row-ad--right img,#playzone .play-zone-row-ad--left img{height:110px!important;max-height:110px!important;object-fit:contain!important}}
`;
