export const PLAY_ZONE_ROW_IMAGE_FIX = `
#playzone .game-grid{row-gap:9px!important}
#playzone .play-zone-row-ad{grid-column:1/-1!important;display:grid!important;align-items:center!important;justify-content:stretch!important;gap:6px!important;height:130px!important;min-height:130px!important;margin:-2px 0 2px!important;overflow:visible!important;pointer-events:none!important}
#playzone .play-zone-row-ad--right{grid-template-columns:minmax(0,30%) minmax(0,70%)!important;grid-template-areas:"copy image"!important}
#playzone .play-zone-row-ad--left{grid-template-columns:minmax(0,70%) minmax(0,30%)!important;grid-template-areas:"image copy"!important}
#playzone .play-zone-row-ad__copy{grid-area:copy!important;max-width:none!important;min-height:78px!important;margin:0!important;padding:10px 8px!important;border-radius:20px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(255,255,255,.11)!important;box-shadow:0 14px 30px rgba(0,0,0,.16),inset 0 1px 0 rgba(255,255,255,.14)!important;backdrop-filter:blur(4px) saturate(1.12)!important;-webkit-backdrop-filter:blur(4px) saturate(1.12)!important;color:rgba(255,255,255,.84)!important;font-size:12.2px!important;font-weight:850!important;line-height:1.28!important;letter-spacing:-.035em!important;text-align:center!important;display:flex!important;align-items:center!important;justify-content:center!important;align-self:center!important;justify-self:center!important;position:relative!important;z-index:2!important;text-shadow:0 8px 20px rgba(0,0,0,.42)!important;transform:translateX(0)!important}
#playzone .play-zone-row-ad img{grid-area:image!important;width:108%!important;height:130px!important;max-width:none!important;max-height:130px!important;min-width:0!important;display:block!important;object-fit:contain!important;object-position:center!important;align-self:center!important;justify-self:center!important;background:transparent!important;border:0!important;box-shadow:none!important;transform:scale(1.08)!important;transform-origin:center!important}
#playzone .play-zone-row-ad--right img{width:108%!important;height:130px!important}
#playzone .play-zone-row-ad--left img{width:108%!important;height:130px!important}
#playzone .play-zone-row-ad.is-empty{display:none!important}
@media(max-width:380px){#playzone .game-grid{row-gap:8px!important}#playzone .play-zone-row-ad{height:120px!important;min-height:120px!important;margin:-2px 0 2px!important;gap:5px!important}#playzone .play-zone-row-ad--right{grid-template-columns:minmax(0,31%) minmax(0,69%)!important}#playzone .play-zone-row-ad--left{grid-template-columns:minmax(0,69%) minmax(0,31%)!important}#playzone .play-zone-row-ad__copy{min-height:72px!important;padding:9px 7px!important;border-radius:18px!important;font-size:10.6px!important;line-height:1.23!important}#playzone .play-zone-row-ad img,#playzone .play-zone-row-ad--right img,#playzone .play-zone-row-ad--left img{width:110%!important;height:120px!important;max-height:120px!important;object-fit:contain!important;transform:scale(1.1)!important}}
`;
