export const PLAY_ZONE_SHOWCASE_OVERRIDES = `
.play-zone-stage{--play-card-gap:6px;gap:10px!important}
.play-zone-plinko-showcase,#playzone .play-zone-nft-strip{display:none!important}
#playzone .game-card-shell{width:100%!important;max-width:none!important;display:block!important;position:relative!important;margin:0!important;padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important;overflow:visible!important;transform:none!important;animation:none!important}
#playzone .game-card-live{width:100%!important;height:auto!important;min-height:0!important;max-height:none!important;display:block!important;position:relative!important;margin:0!important;padding:0!important;border:0!important;border-radius:22px!important;background:rgba(255,255,255,.06)!important;box-shadow:none!important;overflow:hidden!important;-webkit-backdrop-filter:blur(3px)!important;backdrop-filter:blur(3px)!important}
#playzone .game-card-live:before,#playzone .game-card-live:after{content:none!important;display:none!important}
#playzone .game-card-live .game-image{display:block!important;position:relative!important;inset:auto!important;width:auto!important;height:auto!important;margin:var(--play-card-gap)!important;aspect-ratio:3/1!important;border:0!important;outline:0!important;border-radius:16px!important;background:transparent!important;box-shadow:none!important;overflow:hidden!important;padding:0!important}
#playzone .game-card-live .game-image:before,#playzone .game-card-live .game-image:after{content:none!important;display:none!important}
#playzone .game-card-live .game-image img{display:block!important;position:static!important;width:100%!important;height:auto!important;aspect-ratio:3/1!important;object-fit:fill!important;object-position:center!important;border:0!important;outline:0!important;border-radius:16px!important;background:transparent!important;box-shadow:none!important}
#playzone .game-card-shell>.game-footer-live{position:absolute!important;left:18px!important;right:18px!important;bottom:12px!important;z-index:4!important;display:flex!important;justify-content:center!important;align-items:center!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important;margin:0!important;pointer-events:none!important}
#playzone .game-card-shell>.game-footer-live:before,#playzone .game-card-shell>.game-footer-live:after{content:none!important;display:none!important}
#playzone .game-card-shell>.game-footer-live .game-players{background:rgba(0,0,0,.22)!important;border:0!important;border-radius:999px!important;box-shadow:none!important;padding:5px 10px!important;margin:0!important;-webkit-backdrop-filter:blur(3px)!important;backdrop-filter:blur(3px)!important}
#playzone .game-card-live.is-soft-entering{transform:scale(.985)!important;opacity:.72!important;filter:brightness(1.05) saturate(1.08)!important}
body.soft-game-entering #playzone{opacity:.96!important;transition:opacity .18s ease!important}
@media(max-width:380px){.play-zone-stage{--play-card-gap:6px}#playzone .game-card-live{height:auto!important;min-height:0!important;max-height:none!important;border-radius:20px!important}#playzone .game-card-live .game-image{margin:var(--play-card-gap)!important;border-radius:14px!important}#playzone .game-card-live .game-image img{border-radius:14px!important}}
`;
