export const PLINKO_CONTROLS_MODERN_STYLES = `
#plinko .plinko-controls{width:min(94%,374px)!important;display:grid!important;gap:12px!important;margin-top:2px!important;padding:14px!important;border-radius:32px!important;border:1px solid rgba(255,255,255,.10)!important;background:#050505!important;background-image:none!important;box-shadow:0 24px 74px rgba(0,0,0,.58),inset 0 1px 0 rgba(255,255,255,.08)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important;position:relative!important;z-index:2!important;flex:0 0 auto!important}
#plinko .plinko-control-grid{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:9px!important}
#plinko .plinko-field{min-height:84px!important;border-radius:18px!important;background:#030303!important;border:1px solid rgba(255,255,255,.10)!important;padding:12px 11px!important;text-align:left!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important;display:block!important}
#plinko .plinko-field small{display:block!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:850!important;letter-spacing:-.02em!important;white-space:nowrap!important;line-height:1!important}
#plinko .plinko-field b{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:7px!important;margin-top:14px!important;font-size:22px!important;font-weight:760!important;letter-spacing:-.04em!important;font-variant-numeric:tabular-nums lining-nums!important;white-space:nowrap!important;line-height:1!important}
#plinko .plinko-field i{font-style:normal!important;font-size:18px!important;color:rgba(255,255,255,.72)!important;font-weight:800!important}
#plinko .plinko-bet{display:grid!important;grid-template-columns:.74fr 1.52fr .74fr!important;gap:8px!important}
#plinko .plinko-bet button,#plinko .plinko-drop{height:46px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.12)!important;background:rgba(255,255,255,.075)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;text-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;transition:transform .18s ease,background .18s ease,border-color .18s ease,opacity .18s ease!important}
#plinko .plinko-bet button:active,#plinko .plinko-drop:enabled:active{transform:scale(.975)!important;background:rgba(255,255,255,.16)!important}
#plinko .plinko-bet-main{font-size:17px!important;background:rgba(255,255,255,.14)!important;border-color:rgba(255,255,255,.20)!important}
#plinko .plinko-bet-main.active{background:rgba(255,255,255,.18)!important;border-color:rgba(255,255,255,.24)!important}
#plinko .plinko-bet-value{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;left:-9999px!important}
#plinko .plinko-drop,#plinko .plinko-drop:enabled,#plinko .plinko-drop:disabled,#plinko .plinko-drop[disabled]{width:100%!important;height:46px!important;display:flex!important;align-items:center!important;justify-content:center!important;opacity:1!important}
#plinko .plinko-drop:disabled,#plinko .plinko-drop[disabled]{opacity:.58!important;filter:none!important;transform:scale(.985)!important}
#plinko .plinko-stats{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:8px!important}
#plinko .plinko-stat{min-width:0;border-radius:17px!important;background:#030303!important;border:1px solid rgba(255,255,255,.10)!important;padding:10px 8px!important;text-align:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important}
#plinko .plinko-stat small{display:block!important;color:rgba(255,255,255,.42)!important;font-size:10px!important;font-weight:850!important;letter-spacing:.02em!important;white-space:nowrap!important}
#plinko .plinko-stat b{display:block!important;margin-top:6px!important;color:#fff!important;font-size:15px!important;font-weight:850!important;letter-spacing:-.035em!important;font-variant-numeric:tabular-nums lining-nums!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}
#plinko .plinko-bet-editor{position:fixed!important;inset:0!important;z-index:50!important;display:block!important;padding:0!important;background:rgba(0,0,0,.18)!important;opacity:0!important;pointer-events:none!important;transition:opacity .18s ease!important;overflow:hidden!important}
#plinko .plinko-bet-editor.active{opacity:1!important;pointer-events:auto!important}
#plinko .plinko-bet-box{position:absolute!important;left:50%!important;top:var(--plinko-editor-top,42vh)!important;width:min(330px,86vw)!important;border-radius:28px!important;background:rgba(255,255,255,.035)!important;border:0!important;box-shadow:0 28px 90px rgba(0,0,0,.55),inset 0 1px 0 rgba(255,255,255,.12)!important;padding:18px!important;transform:translate(-50%,calc(-50% + 18px)) scale(.96)!important;opacity:.8!important;transition:transform .22s cubic-bezier(.2,.8,.2,1),opacity .22s ease!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important}
#plinko .plinko-bet-editor.active .plinko-bet-box{transform:translate(-50%,-50%) scale(1)!important;opacity:1!important}
#plinko .plinko-bet-box small{display:block!important;text-align:center!important;color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:850!important;letter-spacing:.12em!important;text-transform:uppercase!important}
#plinko .plinko-bet-input{width:100%!important;height:74px!important;margin:12px 0 14px!important;border-radius:22px!important;border:1px solid rgba(255,255,255,.16)!important;background:rgba(255,255,255,.035)!important;color:#fff!important;text-align:center!important;font-size:34px!important;font-weight:900!important;letter-spacing:-.04em!important;outline:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important;box-sizing:border-box!important}
#plinko .plinko-bet-done{width:100%!important;height:50px!important;border-radius:999px!important;border:1px solid rgba(255,255,255,.16)!important;background:rgba(255,255,255,.10)!important;color:#fff!important;font-size:15px!important;font-weight:900!important}
@media(max-width:420px){#plinko .plinko-controls{width:min(94%,374px)!important;border-radius:30px!important;gap:12px!important;padding:14px!important}#plinko .plinko-control-grid{gap:7px!important}#plinko .plinko-field{min-height:80px!important;padding:11px 9px!important}#plinko .plinko-field small{font-size:12px!important}#plinko .plinko-field b{font-size:19px!important}#plinko .plinko-bet{grid-template-columns:.68fr 1.64fr .68fr!important}}
`;
