export const PLINKO_GLASS_BALL_SCRIPT = `
(function(){
  var GLASS_BALL_URL='data:image/svg+xml;utf8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><defs><radialGradient id="g" cx="34%" cy="24%" r="72%"><stop offset="0" stop-color="#ffffff" stop-opacity=".98"/><stop offset=".18" stop-color="#eff8ff" stop-opacity=".78"/><stop offset=".42" stop-color="#aeb9c8" stop-opacity=".28"/><stop offset=".68" stop-color="#11141a" stop-opacity=".38"/><stop offset="1" stop-color="#020204" stop-opacity=".86"/></radialGradient><radialGradient id="c" cx="50%" cy="50%" r="56%"><stop offset="0" stop-color="#ffffff" stop-opacity="0"/><stop offset=".56" stop-color="#ffffff" stop-opacity="0"/><stop offset=".82" stop-color="#ffffff" stop-opacity=".34"/><stop offset="1" stop-color="#ffffff" stop-opacity=".86"/></radialGradient><linearGradient id="s" x1="20" y1="14" x2="104" y2="116"><stop offset="0" stop-color="#fff" stop-opacity=".88"/><stop offset=".42" stop-color="#dcecff" stop-opacity=".12"/><stop offset="1" stop-color="#050508" stop-opacity=".62"/></linearGradient><filter id="shadow" x="-40%" y="-40%" width="180%" height="180%"><feDropShadow dx="0" dy="10" stdDeviation="10" flood-color="#000" flood-opacity=".55"/><feDropShadow dx="0" dy="0" stdDeviation="5" flood-color="#fff" flood-opacity=".28"/></filter></defs><circle cx="64" cy="64" r="45" fill="url(#g)" filter="url(#shadow)"/><circle cx="64" cy="64" r="45" fill="url(#c)"/><path d="M33 51c8-22 29-32 49-26" fill="none" stroke="#fff" stroke-width="7" stroke-linecap="round" opacity=".64"/><ellipse cx="45" cy="37" rx="12" ry="8" fill="#fff" opacity=".88" transform="rotate(-28 45 37)"/><ellipse cx="78" cy="83" rx="16" ry="7" fill="#000" opacity=".30" transform="rotate(-24 78 83)"/><circle cx="64" cy="64" r="45" fill="none" stroke="url(#s)" stroke-width="3"/><circle cx="64" cy="64" r="34" fill="none" stroke="#fff" stroke-opacity=".18" stroke-width="2"/></svg>');
  function apply(){
    try{window.dispatchEvent(new CustomEvent('vexa-credit-icon-sync',{detail:{url:GLASS_BALL_URL,source:'plinko-glass-ball'}}))}catch(e){}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(apply,80);setTimeout(apply,700)});else{setTimeout(apply,80);setTimeout(apply,700)}
  setInterval(function(){var active=document.getElementById('plinko');if(active&&active.classList.contains('active'))apply()},3000);
})();
`;
