export const PLINKO_PANEL_SCRIPT = `
(function(){
  var NANO=1000000000;
  function q(id){return document.getElementById(id)}
  function tonToNano(value){return Math.max(0,Math.floor((Number(String(value||'').replace(',','.'))||0)*NANO))}
  function readBalanceNano(){if(window.VexaTonBalance&&typeof window.VexaTonBalance.read==='function')return Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0));var source=q('plinkoTonBalance')||q('topTonBalance')||q('plinkoCredit');return tonToNano(source&&source.textContent)}
  function isPlinkoActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='plinko')}
  function roundCurrency(value){var next=Math.round((Math.max(0,Number(value)||0)+Number.EPSILON)*100)/100;return next}
  function money(value){var next=roundCurrency(value);return next.toFixed(2).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1')}
  function syncHiddenInput(){var input=q('plinkoBet'),open=document.querySelector('[data-plinko-bet-input-open]');if(input&&open&&document.activeElement!==input)input.value=money(open.textContent||input.value||1)}
  function currentBet(){var input=q('plinkoBet');var value=Number(String(input&&input.value||'').replace(',','.'));return Number.isFinite(value)&&value>=1?roundCurrency(value):1}
  function setBet(value){var input=q('plinkoBet'),open=document.querySelector('[data-plinko-bet-input-open]'),editorInput=document.querySelector('[data-plinko-bet-input]');var next=roundCurrency(value);if(!Number.isFinite(next)||next<1)next=1;var balance=readBalanceNano()/NANO;if(balance>=1&&next>balance)next=roundCurrency(balance);var display=money(next);if(input)input.value=display;if(open)open.textContent=display;if(editorInput&&document.activeElement!==editorInput)editorInput.value=display;renderStats()}
  function multiplyBet(multiplier){var value=currentBet();setBet(multiplier===.5?Math.max(1,value/2):value*2)}
  function renderStats(){var bet=currentBet(),balance=readBalanceNano()/NANO;var current=document.querySelector('[data-plinko-current]'),balanceEl=document.querySelector('[data-plinko-balance]');if(current)current.textContent=money(bet);if(balanceEl)balanceEl.textContent=money(balance);syncHiddenInput()}
  function placeNativeInput(input,anchor){var rect=anchor&&anchor.getBoundingClientRect?anchor.getBoundingClientRect():null;if(!input||!rect)return;input.style.position='fixed';input.style.left=rect.left+'px';input.style.top=rect.top+'px';input.style.width=rect.width+'px';input.style.height=rect.height+'px';input.style.zIndex='9999';input.style.opacity='1';input.style.background='transparent';input.style.border='0';input.style.outline='0';input.style.boxShadow='none';input.style.color='transparent';input.style.webkitTextFillColor='transparent';input.style.caretColor='#fff';input.style.textAlign='center';input.style.fontSize='22px';input.style.fontWeight='900';input.style.lineHeight=rect.height+'px';input.style.padding='0';input.style.margin='0';input.style.pointerEvents='auto';input.style.transform='none';input.style.appearance='none'}
  function clearNativeInput(input){if(!input)return;['position','left','top','width','height','zIndex','opacity','background','border','outline','boxShadow','color','webkitTextFillColor','caretColor','textAlign','fontSize','fontWeight','lineHeight','padding','margin','pointerEvents','transform','appearance'].forEach(function(prop){try{input.style[prop]=''}catch(e){}})}
  function focusAmountInput(anchor){var editor=document.querySelector('[data-plinko-bet-editor]'),editorInput=document.querySelector('[data-plinko-bet-input]'),input=q('plinkoBet');if(editor)editor.classList.remove('active');if(editorInput)editorInput.value=money(currentBet());if(!input)return;input.removeAttribute('aria-hidden');input.removeAttribute('tabindex');input.setAttribute('inputmode','decimal');input.setAttribute('autocomplete','off');input.setAttribute('enterkeyhint','done');input.value=money(currentBet());placeNativeInput(input,anchor);try{input.focus({preventScroll:true});input.setSelectionRange(String(input.value).length,String(input.value).length)}catch(e){try{input.focus();input.select()}catch(_){}}}
  function closeEditor(save){var editor=document.querySelector('[data-plinko-bet-editor]'),input=document.querySelector('[data-plinko-bet-input]');if(save&&input)setBet(input.value);if(editor)editor.classList.remove('active')}
  function syncHeaderCredit(){var source=q('plinkoTonBalance')||q('topTonBalance')||q('plinkoCredit');var header=q('plinkoCreditHeader');if(source&&header)header.textContent=source.textContent||'0';renderStats()}
  function setLastWin(value){var win=document.querySelector('[data-plinko-win]');if(win)win.textContent=money(value)}
  function smoothPress(el){if(!el)return;if(el.__plinkoSmoothFrame)cancelAnimationFrame(el.__plinkoSmoothFrame);el.classList.add('plinko-drop-press');el.__plinkoSmoothFrame=requestAnimationFrame(function(){el.classList.add('plinko-drop-tap');clearTimeout(el.__plinkoSmoothTimer);el.__plinkoSmoothTimer=setTimeout(function(){el.classList.remove('plinko-drop-tap');el.classList.remove('plinko-drop-press')},220)})}
  function smoothRelease(el){if(el)el.classList.remove('plinko-drop-press')}
  function dropAssetFromEvent(ev){var btn=ev&&ev.target&&ev.target.closest?ev.target.closest('[data-action="drop-plinko-ball"]'):null;if(!btn)return null;return btn.closest('.plinko-drop-asset')||btn}
  document.addEventListener('pointerdown',function(ev){var el=dropAssetFromEvent(ev);if(el)smoothPress(el)},{capture:true,passive:true});
  document.addEventListener('pointerup',function(ev){smoothRelease(dropAssetFromEvent(ev))},{capture:true,passive:true});
  document.addEventListener('pointercancel',function(ev){smoothRelease(dropAssetFromEvent(ev))},{capture:true,passive:true});
  document.addEventListener('click',function(ev){var button=ev.target&&ev.target.closest&&ev.target.closest('button');if(!button)return;if(button.hasAttribute('data-plinko-bet-input-open')){ev.preventDefault();focusAmountInput(button);return}if(button.hasAttribute('data-plinko-bet-done')){ev.preventDefault();closeEditor(true);return}var action=button.getAttribute('data-action');if(action==='plinko-bet-half'){ev.preventDefault();multiplyBet(.5);return}if(action==='plinko-bet-double'){ev.preventDefault();multiplyBet(2);return}},true);
  document.addEventListener('click',function(ev){var editor=document.querySelector('[data-plinko-bet-editor]');if(editor&&editor.classList.contains('active')&&ev.target===editor)closeEditor(true)});
  document.addEventListener('keydown',function(ev){var input=q('plinkoBet');if(input&&document.activeElement===input){if(ev.key==='Enter'){ev.preventDefault();input.blur();setBet(input.value)}if(ev.key==='Escape'){ev.preventDefault();input.blur();return}return}var editor=document.querySelector('[data-plinko-bet-editor]');if(!editor||!editor.classList.contains('active'))return;if(ev.key==='Escape')closeEditor(false);if(ev.key==='Enter')closeEditor(true)});
  document.addEventListener('input',function(ev){if(ev.target&&ev.target.id==='plinkoBet'){var open=document.querySelector('[data-plinko-bet-input-open]');if(open)open.textContent=money(ev.target.value);renderStats()}if(ev.target&&ev.target.hasAttribute&&ev.target.hasAttribute('data-plinko-bet-input')){var input=q('plinkoBet'),open2=document.querySelector('[data-plinko-bet-input-open]');if(input)input.value=ev.target.value;if(open2)open2.textContent=money(ev.target.value);renderStats()}});
  document.addEventListener('focusout',function(ev){if(ev.target&&ev.target.id==='plinkoBet'){setBet(ev.target.value);clearNativeInput(ev.target);ev.target.setAttribute('aria-hidden','true');ev.target.setAttribute('tabindex','-1')}if(ev.target&&ev.target.hasAttribute&&ev.target.hasAttribute('data-plinko-bet-input'))setBet(ev.target.value)});
  document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')syncHeaderCredit()});
  window.addEventListener('focus',syncHeaderCredit);window.addEventListener('vexa-ton-balance-sync',syncHeaderCredit);window.addEventListener('vexa-credit-sync',syncHeaderCredit);window.addEventListener('vexa-credit-game-change',syncHeaderCredit);
  window.addEventListener('vexa-plinko-last-win',function(ev){setLastWin(ev&&ev.detail?ev.detail.total:0);renderStats()});
  if(window.MutationObserver){var root=q('plinko');if(root)new MutationObserver(function(){if(isPlinkoActive())syncHeaderCredit()}).observe(root,{attributes:true,attributeFilter:['class']})}
  var start=function(){setBet(currentBet());syncHeaderCredit()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
`;