export const PLINKO_SCRIPT = `
(function(){
  var state=null,risk='medium',rows=7;
  var credit=Number((document.getElementById('plinkoCredit')||{}).textContent||'1000')||1000;
  var creditIconUrl='/app/api/uploaded-image/credit-icon.png';
  var plinkoControl=null,lastPlinkoControlStamp='',lastPlinkoControlLoadAt=0,syncing=false,syncQueued=false;
  var audioContext=null,lastPegSoundAt=0,pegToneIndex=0;
  var MAX_ACTIVE_BALLS=24;
  var multiplierTable={
    7:{low:[2,1.4,1.1,.9,.9,1.1,1.4,2],medium:[5,2,1.2,.5,.5,1.2,2,5],high:[12,4,1.5,.2,.2,1.5,4,12]},
    9:{low:[3,1.6,1.3,1.1,.8,.8,1.1,1.3,1.6,3],medium:[8,3,1.6,1.1,.4,.4,1.1,1.6,3,8],high:[25,8,3,1.3,.2,.2,1.3,3,8,25]},
    11:{low:[4,1.8,1.5,1.2,1,.85,.85,1,1.2,1.5,1.8,4],medium:[14,4,2.2,1.5,1,.5,.5,1,1.5,2.2,4,14],high:[60,14,6,2.5,1.2,.25,.25,1.2,2.5,6,14,60]}
  };

  function q(id){return document.getElementById(id)}
  function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
  function toast(message){var n=q('toast');if(!n)return;n.textContent=message;n.style.display='block';setTimeout(function(){n.style.display='none'},2500)}
  function renderCredit(){var value=Math.max(0,Math.round(credit));['plinkoCredit','creditCount','plinkoCreditHeader'].forEach(function(id){var el=q(id);if(el)el.textContent=String(value)});return value}
  function reportGameCredit(delta){var value=renderCredit();try{window.dispatchEvent(new CustomEvent('vexa-credit-game-change',{detail:{credit:value,delta:delta}}))}catch(e){}}
  function forceCredit(next){var value=Math.max(0,Math.floor(Number(next)||0));if(value===Math.max(0,Math.round(credit)))return;credit=value;renderCredit();var input=q('plinkoBet');if(input&&Number(input.value)>credit)input.value=String(Math.max(1,Math.floor(credit)))}
  window.addEventListener('vexa-credit-sync',function(ev){if(ev&&ev.detail)forceCredit(ev.detail.credit)});
  window.addEventListener('vexa-credit-icon-sync',function(ev){if(ev&&ev.detail&&ev.detail.url)updateTokenImage(ev.detail.url)});
  function getBet(){var input=q('plinkoBet');var value=Math.floor(Number(input&&input.value)||0);if(value<1)value=1;if(value>credit)value=Math.floor(credit);if(input)input.value=String(value);return value}
  function fmt(n){return Number.isInteger(n)?String(n):String(n).replace(/^0/,'0')}
  function houseCount(){return rows+1}
  function controlItem(){var rk=String(rows);return plinkoControl&&plinkoControl.enabled!==false&&plinkoControl.rows&&plinkoControl.rows[rk]&&plinkoControl.rows[rk][risk]?plinkoControl.rows[rk][risk]:null}
  function currentMultipliers(){var item=controlItem();return item&&Array.isArray(item.multipliers)&&item.multipliers.length===houseCount()?item.multipliers:multiplierTable[rows][risk]}
  function currentWeights(){var item=controlItem();if(item&&Array.isArray(item.weights)&&item.weights.length===houseCount())return item.weights.map(function(v){return Math.max(0,Number(v)||0)});return Array(houseCount()).fill(1)}
  function hasPositiveChance(){return currentWeights().some(function(v){return v>0})}
  // Fair-physics mode: keep multiplier overrides, but never steer a ball toward weighted target houses.
  function isControlled(){return false}
  function chooseWeightedIndex(){var weights=currentWeights(),sum=weights.reduce(function(a,b){return a+b},0);if(sum<=0)return Math.floor(weights.length/2);var r=Math.random()*sum;for(var i=0;i<weights.length;i++){r-=weights[i];if(r<=0&&weights[i]>0)return i}return Math.floor(weights.length/2)}
  function chooseChanceIndex(){var multipliers=currentMultipliers(),forced=window.VexaGameChance&&typeof window.VexaGameChance.decideWin==='function'?window.VexaGameChance.decideWin():null;if(forced===null||forced===undefined)return Math.floor(Math.random()*houseCount());var wantWin=!!forced,candidates=[];for(var i=0;i<multipliers.length;i++){var mult=Number(multipliers[i])||0;if(wantWin?mult>=1:mult<1)candidates.push(i)}if(!candidates.length){for(var j=0;j<multipliers.length;j++)candidates.push(j)}return candidates[Math.floor(Math.random()*candidates.length)]}
  function resolveLandingIndex(index){if(!isControlled())return index;var weights=currentWeights(),idx=clamp(Math.floor(Number(index)||0),0,weights.length-1);if(weights[idx]>0)return idx;var best=-1,bestDistance=Infinity;for(var i=0;i<weights.length;i++){if(weights[i]>0){var d=Math.abs(i-idx);if(d<bestDistance){best=i;bestDistance=d}}}return best>=0?best:Math.floor(weights.length/2)}
  function pegRadius(){return rows===7?5.25:rows===9?4.6:3.48}
  function pegVisualRadius(){return rows===7?7.1:rows===9?6.6:4.35}
  function ballRadius(){return rows===7?8.4:rows===9?7.6:6.75}
  function binTextSize(count){return count>=13?6.8:count>=12?7.1:count>=11?7.6:8.4}
  function targetCenterX(index,bins,left,right){var idx=resolveLandingIndex(index);return left+(idx+.5)*((right-left)/bins.length)}
  function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function updateTokenImage(url){creditIconUrl=url||creditIconUrl;if(state&&state.tokenImg&&state.tokenImg.src!==creditIconUrl)state.tokenImg.src=creditIconUrl}
  function getAudioContext(){var Ctor=window.AudioContext||window.webkitAudioContext;if(!Ctor)return null;if(!audioContext)audioContext=new Ctor();return audioContext}
  function primeAudio(){var c=getAudioContext();if(c&&c.resume)c.resume().catch(function(){})}
  function playPegHitSound(){var nowMs=performance.now();if(nowMs-lastPegSoundAt<130)return;lastPegSoundAt=nowMs;var context=getAudioContext();if(!context||context.state==='suspended')return;var now=context.currentTime,osc=context.createOscillator(),gain=context.createGain(),tone=[520,620,720,820][pegToneIndex++%4];osc.type='triangle';osc.frequency.setValueAtTime(tone,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.006);gain.gain.exponentialRampToValueAtTime(.0001,now+.075);osc.connect(gain).connect(context.destination);osc.start(now);osc.stop(now+.08)}

  function isPlinkoActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='plinko')}
  function loadPlinkoControl(){return fetch('/app/api/plinko-control',{cache:'no-store'}).then(function(r){return r.json()}).then(function(data){if(data&&data.rows){var stamp=String(data.updatedAt||JSON.stringify(data.rows));var changed=stamp!==lastPlinkoControlStamp;plinkoControl=data;lastPlinkoControlStamp=stamp;retargetControlledBalls(changed);rebuildBoard(hasActiveBalls())}}).catch(function(){})}
  function requestSync(force){var now=Date.now();if(!force&&!isPlinkoActive())return Promise.resolve();if(!force&&now-lastPlinkoControlLoadAt<1200)return Promise.resolve();if(syncing){syncQueued=Boolean(force||syncQueued);return Promise.resolve()}syncing=true;lastPlinkoControlLoadAt=now;return loadPlinkoControl().finally(function(){syncing=false;if(syncQueued){syncQueued=false;requestSync(true)}})}
  function retargetControlledBalls(force){if(!state||!state.balls||!isControlled())return;var bins=state.bins,left=bins[0].x,right=bins[bins.length-1].x+bins[bins.length-1].w;state.balls.forEach(function(ball){if(!ball||ball.sinking)return;ball.targetIndex=force?chooseWeightedIndex():resolveLandingIndex(Number.isFinite(ball.targetIndex)?ball.targetIndex:chooseWeightedIndex());ball.settleX=targetCenterX(ball.targetIndex,bins,left,right)})}
  function spawnPegImpact(x,y){if(!state)return;playPegHitSound();if(state.impactRings.length<48)state.impactRings.push({x:x,y:y,r:5,life:14,max:14})}
  function drawGlassEffects(ctx){if(!state)return;for(var r=state.impactRings.length-1;r>=0;r--){var ring=state.impactRings[r];ring.life-=1;var ra=Math.max(0,ring.life/ring.max);ctx.save();if(ring.bin){var bin=ring.bin;ctx.globalAlpha=ra;roundRect(ctx,bin.x,bin.y,bin.w,bin.h,Math.min(10,Math.max(5,bin.w*.28)));ctx.fillStyle='rgba(255,255,255,.18)';ctx.fill();ctx.strokeStyle='rgba(220,250,255,.92)';ctx.lineWidth=1.4;ctx.stroke();ctx.restore();if(ring.life<=0)state.impactRings.splice(r,1);continue}ring.r+=1.25;ctx.globalAlpha=ra*.75;ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(ring.x,ring.y,ring.r,0,Math.PI*2);ctx.stroke();ctx.restore();if(ring.life<=0)state.impactRings.splice(r,1)}}
  function drawGlassPeg(ctx,x,y,r,hit){ctx.save();if(hit>0){ctx.beginPath();ctx.arc(x,y,r*1.9,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.10)';ctx.fill()}ctx.shadowColor='rgba(255,255,255,'+(hit>0?'.46':'.22')+')';ctx.shadowBlur=Math.max(hit>0?9:5,r*(hit>0?1.55:.9));ctx.beginPath();ctx.arc(x,y,r*1.04,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.10)';ctx.fill();ctx.shadowBlur=0;var edge=ctx.createRadialGradient(x-r*.36,y-r*.42,r*.06,x,y,r*1.08);edge.addColorStop(0,'rgba(255,255,255,1)');edge.addColorStop(.24,'rgba(255,255,255,.88)');edge.addColorStop(.58,'rgba(255,255,255,.42)');edge.addColorStop(1,'rgba(255,255,255,.12)');ctx.beginPath();ctx.arc(x,y,r+(hit>0?1.1:0),0,Math.PI*2);ctx.fillStyle=edge;ctx.fill();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=Math.max(.75,r*.11);ctx.stroke();ctx.restore()}
  function drawGlassBin(ctx,bin){var r=Math.min(10,Math.max(5,bin.w*.28));ctx.save();ctx.shadowColor='rgba(255,255,255,.12)';ctx.shadowBlur=6;roundRect(ctx,bin.x,bin.y,bin.w,bin.h,r);var fill=ctx.createLinearGradient(bin.x,bin.y,bin.x,bin.y+bin.h);fill.addColorStop(0,'rgba(255,255,255,.22)');fill.addColorStop(.5,'rgba(255,255,255,.07)');fill.addColorStop(1,'rgba(255,255,255,.016)');ctx.fillStyle=fill;ctx.fill();ctx.shadowBlur=0;roundRect(ctx,bin.x+.8,bin.y+.8,bin.w-1.6,bin.h-1.6,Math.max(2,r-1));ctx.strokeStyle='rgba(255,255,255,.44)';ctx.lineWidth=1;ctx.stroke();ctx.restore()}

  function hasActiveBalls(){return !!(state&&state.balls&&state.balls.some(function(ball){return ball&&!ball.sinking}))}
  function hasAnimatedEffects(){return !!(state&&state.impactRings&&state.impactRings.length)}
  function hasMovingBalls(){return !!(state&&state.balls&&state.balls.length)}
  function scheduleFrame(delay){if(!state||state.raf||state.timer)return;var start=function(){if(!state)return;state.timer=0;if(!state.raf)state.raf=requestAnimationFrame(tick)};if(delay&&delay>0)state.timer=setTimeout(start,delay);else start()}
  function markStaticDirty(){if(state)state.staticDirty=true}
  function setRisk(next){requestSync(false);if(hasActiveBalls()){toast('Wait for current balls to finish');return false}risk=next||'medium';document.querySelectorAll('[data-risk]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-risk')===risk)});rebuildBoard(false);return true}
  function setRows(next){requestSync(false);if(hasActiveBalls()){toast('Wait for current balls to finish');return false}rows=Number(next)||7;var el=q('plinkoRowsValue');if(el)el.textContent=String(rows);rebuildBoard(false);return true}
  function rebuildBoard(preserveBalls){if(!state)return init(true);var oldBalls=preserveBalls&&state.balls?state.balls:[];state.pegs=makePegs();state.bins=makeBins();state.balls=oldBalls;state.impactRings=state.impactRings||[];markStaticDirty();draw();if(hasMovingBalls()||hasAnimatedEffects())scheduleFrame(0)}
  function makePegs(){var pegs=[],top=32,bottom=rows===11?238:rows===9?235:230,rowGap=(bottom-top)/Math.max(1,rows-1),slotCount=houseCount(),slotLeft=12,slotWidth=296,slotGap=slotWidth/slotCount,r=pegRadius(),vr=pegVisualRadius();for(var row=0;row<rows;row++){var count=row+3,start=slotLeft+((slotCount-(count-1))*slotGap)/2,y=top+row*rowGap;for(var i=0;i<count;i++)pegs.push({key:row+':'+i,x:start+i*slotGap,y:y,r:r,vr:vr,lastImpactAt:0})}return pegs}
  function makeBins(){var multipliers=currentMultipliers(),count=houseCount(),bins=[],left=12,top=256,width=296,height=34,gutter=3,binW=width/count;for(var j=0;j<count;j++)bins.push({x:left+j*binW+gutter/2,y:top,w:binW-gutter,h:height,label:fmt(multipliers[j]),mult:Number(multipliers[j])||0});return bins}
  function init(force){var canvas=q('plinkoCanvasV2');if(!canvas)return;if(state&&state.canvas===canvas&&!force){draw();return}var dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=320*dpr;canvas.height=326*dpr;var ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';var previous=state,img=new Image();img.onload=function(){draw()};img.src=creditIconUrl;state={canvas:canvas,ctx:ctx,dpr:dpr,pegs:makePegs(),bins:makeBins(),balls:[],impactRings:[],last:0,raf:previous&&previous.raf||0,timer:previous&&previous.timer||0,staticDirty:true,tokenImg:img};renderCredit();document.querySelectorAll('[data-risk]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-risk')===risk)});var rowsEl=q('plinkoRowsValue');if(rowsEl)rowsEl.textContent=String(rows);draw();scheduleFrame(0)}
  function drop(){requestSync(false);init();primeAudio();if(!state)return;if(state.balls&&state.balls.length>=MAX_ACTIVE_BALLS){toast('Please wait for a few balls to finish');return}var bet=getBet();if(!bet||credit<bet){toast('Not enough credit');return}credit-=bet;reportGameCredit(-bet);var target=isControlled()?chooseWeightedIndex():chooseChanceIndex();target=resolveLandingIndex(target);var bins=state.bins,left=bins[0].x,right=bins[bins.length-1].x+bins[bins.length-1].w;state.balls.push({x:160,y:-8,r:ballRadius(),bet:bet,targetIndex:target,start:performance.now(),duration:1450+Math.random()*180,hitPegKeys:{},sinking:false,sink:0,paid:false,settleX:targetCenterX(target,bins,left,right)});scheduleFrame(0)}
  function settle(ball,bin){if(ball.paid)return;ball.paid=true;if(state)state.impactRings.push({bin:bin,life:34,max:34});var payout=Math.max(0,Math.round(ball.bet*bin.mult));credit+=payout;reportGameCredit(payout)}
  function ballPath(ball,time,bins,left,right){var p=clamp((time-ball.start)/ball.duration,0,1),ease=p*p*(3-2*p),target=targetCenterX(ball.targetIndex,bins,left,right),swing=Math.sin(p*Math.PI*(rows+1)+ball.targetIndex)*Math.max(0,1-p)*Math.min(13,(right-left)/bins.length*.28);ball.x=160+(target-160)*ease+swing;ball.y=-8+(bins[0].y+18)*ease;return p}
  function tick(time){if(!state)return;var balls=state.balls,bins=state.bins,left=bins[0].x,right=bins[bins.length-1].x+bins[bins.length-1].w;for(var b=balls.length-1;b>=0;b--){var ball=balls[b];if(ball.sinking){ball.sink+=1;if(Number.isFinite(ball.settleX))ball.x+=(ball.settleX-ball.x)*.2;ball.y+=.46;ball.r*=.978;if(ball.sink>42||ball.r<1.2)balls.splice(b,1);continue}var progress=ballPath(ball,time,bins,left,right);for(var p=0;p<state.pegs.length;p++){var peg=state.pegs[p],dx=ball.x-peg.x,dy=ball.y-peg.y;if(!ball.hitPegKeys[peg.key]&&dx*dx+dy*dy<(ball.r+peg.r+7)*(ball.r+peg.r+7)){ball.hitPegKeys[peg.key]=1;peg.hit=9;peg.lastImpactAt=time;spawnPegImpact(peg.x,peg.y)}}if(progress>=1){var idx=resolveLandingIndex(ball.targetIndex),bin=bins[idx];ball.sinking=true;ball.sink=0;ball.settleX=bin.x+bin.w/2;settle(ball,bin)}}draw();state.raf=0;if(hasMovingBalls()||hasAnimatedEffects())scheduleFrame(0)}
  function drawStatic(ctx){for(var p=0;p<state.pegs.length;p++){var peg=state.pegs[p];drawGlassPeg(ctx,peg.x,peg.y,peg.vr,peg.hit||0);if(peg.hit>0)peg.hit-=1}var bins=state.bins;ctx.font='900 '+binTextSize(bins.length)+'px Inter,system-ui,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';for(var i=0;i<bins.length;i++){var bin=bins[i];drawGlassBin(ctx,bin);ctx.fillStyle='rgba(255,255,255,.86)';ctx.fillText(bin.label,bin.x+bin.w/2,bin.y+bin.h-12)}}
  function draw(){if(!state)return;var ctx=state.ctx,dpr=state.dpr||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,320,326);drawStatic(ctx);drawGlassEffects(ctx);for(var b=0;b<state.balls.length;b++){var ball=state.balls[b],img=state.tokenImg,alpha=ball.sinking?Math.max(0,1-ball.sink/34):1;ctx.save();ctx.globalAlpha=alpha;if(img&&img.complete&&img.naturalWidth>0){var size=ball.r*2.45;ctx.drawImage(img,ball.x-size/2,ball.y-size/2,size,size)}else{ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}ctx.restore()}}
  window.dropPlinko=drop;window.setPlinkoRisk=setRisk;window.setPlinkoRows=setRows;window.plinkoInit=init;window.plinkoHasActiveBalls=hasActiveBalls;window.plinkoReloadControl=function(){requestSync(true)};document.addEventListener('click',function(ev){var button=ev.target&&ev.target.closest&&ev.target.closest('button');if(button&&(button.getAttribute('data-view')==='plinko'||button.getAttribute('data-game-view')==='plinko'))setTimeout(function(){requestSync(true)},0)},true);document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'&&isPlinkoActive())requestSync(true)});window.addEventListener('focus',function(){requestSync(false)});if(isPlinkoActive())requestSync(true);setTimeout(function(){init()},50);
})();
`;