export const PLINKO_SCRIPT = `
(function(){
  var state=null;
  var rows=13;
  var risk='low';
  var NANO=1000000000;
  var credit=readPoints();
  var iconUrl='/app/api/uploaded-image/credit-icon.png';
  var control=null;
  var lastStamp='';
  var lastLoadAt=0;
  var syncing=false;
  var syncQueued=false;
  var audioCtx=null;
  var lastSoundAt=0;
  var BOARD_W=360;
  var BOARD_H=326;
  var CENTER_X=180;
  var multipliers={13:{low:[5,2.4,1.8,1.35,1.15,1,.85,.85,1,1.15,1.35,1.8,2.4,5]}};

  function q(id){return document.getElementById(id)}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
  function active(){var view=document.querySelector('.view.active');return !!(view&&view.id==='plinko')}
  function show(text){var n=q('toast');if(!n)return;n.textContent=text;n.style.display='flex';clearTimeout(n.__p);n.__p=setTimeout(function(){n.style.display='none'},2200)}
  function fmtTon(v){var n=Math.max(0,Number(v)||0);return n.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
  function readPoints(){if(window.VexaTonBalance&&typeof window.VexaTonBalance.read==='function')return Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0))/NANO;return Math.max(0,Number((q('plinkoCredit')||{}).textContent||'1000')||1000)}
  function renderPoints(){credit=readPoints();var display=fmtTon(credit);['plinkoCredit','creditCount','plinkoCreditHeader'].forEach(function(id){var el=q(id);if(el)el.textContent=display});return credit}
  function changePoints(delta){var nano=Math.trunc((Number(delta)||0)*NANO);if(window.VexaTonBalance&&typeof window.VexaTonBalance.add==='function'){window.VexaTonBalance.add(nano);credit=readPoints();return}credit=Math.max(0,credit+(Number(delta)||0));renderPoints();try{window.dispatchEvent(new CustomEvent('vexa-credit-game-change',{detail:{credit:credit,delta:delta}}))}catch(e){}}
  function forcePoints(next){var value=Number(next)||0;if(arguments.length&&typeof next==='object')value=Number(next.tonBalanceNano||0)/NANO||Number(next.credit)||0;credit=Math.max(0,value);renderPoints();var input=q('plinkoBet');if(input&&Number(input.value)>credit)input.value=fmtTon(Math.max(.01,credit))}
  function amount(){var input=q('plinkoBet');credit=readPoints();var value=Number(String(input&&input.value||'').replace(',','.'))||0;if(value<.01)value=.01;if(value>credit)value=credit;if(input)input.value=fmtTon(value);return value}
  function label(n){return Number.isInteger(n)?String(n):String(n).replace(/^0/,'0')}
  function houseCount(){return rows+1}
  function controlItem(){var rk=String(rows);return control&&control.enabled!==false&&control.rows&&control.rows[rk]&&control.rows[rk].low?control.rows[rk].low:null}
  function currentMultipliers(){var item=controlItem();return item&&Array.isArray(item.multipliers)&&item.multipliers.length===houseCount()?item.multipliers:multipliers[13].low}
  function pegRadius(){return 2.65}
  function pegVisualRadius(){return 3.65}
  function ballRadius(){return 6.45}
  function binTextSize(count){return count>=14?6.45:6.8}
  function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function updateIcon(url){iconUrl=url||iconUrl;if(state&&state.tokenImg&&state.tokenImg.src!==iconUrl)state.tokenImg.src=iconUrl}
  function primeAudio(){var Ctor=window.AudioContext||window.webkitAudioContext;if(!Ctor)return;if(!audioCtx)audioCtx=new Ctor();if(audioCtx&&audioCtx.resume)audioCtx.resume().catch(function(){})}
  function pegSound(){var nowMs=performance.now();if(nowMs-lastSoundAt<160)return;lastSoundAt=nowMs;try{primeAudio();if(!audioCtx||audioCtx.state==='suspended')return;var now=audioCtx.currentTime;var osc=audioCtx.createOscillator();var gain=audioCtx.createGain();osc.type='triangle';osc.frequency.setValueAtTime(560+Math.random()*90,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.035,now+.008);gain.gain.exponentialRampToValueAtTime(.0001,now+.07);osc.connect(gain).connect(audioCtx.destination);osc.start(now);osc.stop(now+.08)}catch(e){}}
  function loadControl(){return fetch('/app/api/plinko-control',{cache:'no-store'}).then(function(r){return r.json()}).then(function(data){if(data&&data.rows){var stamp=String(data.updatedAt||JSON.stringify(data.rows));var changed=stamp!==lastStamp;control=data;lastStamp=stamp;if(changed)rebuildBoard(hasBalls())}}).catch(function(){})}
  function requestSync(force){var now=Date.now();if(!force&&!active())return Promise.resolve();if(!force&&now-lastLoadAt<1200)return Promise.resolve();if(syncing){syncQueued=Boolean(force||syncQueued);return Promise.resolve()}syncing=true;lastLoadAt=now;return loadControl().finally(function(){syncing=false;if(syncQueued){syncQueued=false;requestSync(true)}})}
  function smartLoadPlinkoControl(force){return requestSync(force)}
  function hitPeg(x,y){if(!state)return;pegSound()}
  function drawPeg(ctx,x,y,r,hit){ctx.save();ctx.shadowColor='rgba(255,255,255,.20)';ctx.shadowBlur=Math.max(4,r*.8);ctx.beginPath();ctx.arc(x,y,r*1.04,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.10)';ctx.fill();ctx.shadowBlur=0;var edge=ctx.createRadialGradient(x-r*.36,y-r*.42,r*.06,x,y,r*1.08);edge.addColorStop(0,'rgba(255,255,255,1)');edge.addColorStop(.24,'rgba(255,255,255,.88)');edge.addColorStop(.58,'rgba(255,255,255,.42)');edge.addColorStop(1,'rgba(255,255,255,.12)');ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=edge;ctx.fill();ctx.beginPath();ctx.arc(x-r*.28,y-r*.34,Math.max(1,r*.23),0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.88)';ctx.fill();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=Math.max(.55,r*.1);ctx.stroke();ctx.restore()}
  function drawBin(ctx,bin){var r=Math.min(9,Math.max(5,bin.w*.24));ctx.save();ctx.shadowColor='rgba(255,255,255,.10)';ctx.shadowBlur=5;roundRect(ctx,bin.x,bin.y,bin.w,bin.h,r);ctx.strokeStyle='rgba(255,255,255,.34)';ctx.lineWidth=.9;ctx.stroke();ctx.shadowBlur=0;roundRect(ctx,bin.x+1.6,bin.y+1.6,bin.w-3.2,bin.h-3.2,Math.max(3,r-1.6));ctx.strokeStyle='rgba(255,255,255,.13)';ctx.lineWidth=.55;ctx.stroke();ctx.beginPath();ctx.moveTo(bin.x+Math.min(5,bin.w*.18),bin.y+3.2);ctx.lineTo(bin.x+bin.w-Math.min(5,bin.w*.18),bin.y+3.2);ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=.7;ctx.lineCap='round';ctx.stroke();ctx.restore()}
  function hasBalls(){return !!(state&&state.balls&&state.balls.length)}
  function hasEffects(){return !!(state&&state.effects&&state.effects.length)}
  function scheduleFrame(delay){if(!state||state.raf||state.timer)return;var start=function(){if(!state)return;state.timer=0;if(!state.raf)state.raf=requestAnimationFrame(tick)};if(delay&&delay>0)state.timer=setTimeout(start,delay);else start()}
  function dirty(){if(state)state.staticDirty=true}
  function rebuildBoard(preserveBalls){if(!state)return init(true);var oldBalls=preserveBalls&&state.balls?state.balls:[];state.pegs=makePegs();state.bins=makeBins();state.balls=oldBalls;state.effects=state.effects||[];dirty();draw();if(hasBalls()||hasEffects())scheduleFrame(0)}
  function makePegs(){var pegs=[];var top=20,bottom=248,pegRows=13,rowGap=(bottom-top)/Math.max(1,pegRows-1);var slotCount=houseCount();var slotLeft=4,slotWidth=352,slotGap=slotWidth/slotCount;var r=pegRadius(),vr=pegVisualRadius();for(var row=0;row<pegRows;row++){var count=row+3;var start=slotLeft+((slotCount-(count-1))*slotGap)/2;var y=top+row*rowGap;var pr=row===pegRows-1?r*.7:r;for(var i=0;i<count;i++)pegs.push({key:row+':'+i,x:start+i*slotGap,y:y,r:pr,vr:vr,hit:0})}return pegs}
  function makeBins(){var mult=currentMultipliers();var count=houseCount();var bins=[];var left=4,top=260,width=352,height=28,gutter=2;var binW=width/count;for(var j=0;j<count;j++)bins.push({x:left+j*binW+gutter/2,y:top,w:binW-gutter,h:height,label:label(mult[j]),mult:Number(mult[j])||0});return bins}
  function binIndexFromX(x,bins,left,right){return clamp(Math.floor((x-left)/((right-left)/bins.length)),0,bins.length-1)}
  function init(force){var canvas=q('plinkoCanvasV2');if(!canvas)return;if(state&&state.canvas===canvas&&!force){draw();return}var dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=BOARD_W*dpr;canvas.height=BOARD_H*dpr;var ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';var prev=state;var img=new Image();img.onload=function(){draw()};img.src=iconUrl;state={canvas:canvas,ctx:ctx,dpr:dpr,pegs:makePegs(),bins:makeBins(),balls:[],effects:[],last:0,raf:prev&&prev.raf||0,timer:prev&&prev.timer||0,staticCanvas:prev&&prev.staticCanvas||null,staticCtx:prev&&prev.staticCtx||null,staticDpr:0,staticDirty:true,tokenImg:img};renderPoints();var rowsEl=q('plinkoRowsValue');if(rowsEl)rowsEl.textContent='13';draw();scheduleFrame(0)}
  function drop(){smartLoadPlinkoControl(false);init();primeAudio();if(!state)return;if(state.balls&&state.balls.length>=24){show('Please wait for a few balls to finish');return}var value=amount();if(!value||credit<value){show('Not enough points');return}changePoints(-value);var activeTop=state.balls.filter(function(ball){return ball&&!ball.sinking&&ball.y<28}).length;var spread=[0,-6,6,-12,12,-3,3,-9,9];var startX=CENTER_X+(spread[activeTop%spread.length]||0)+(Math.random()*2-1);var vx=(Math.random()*.14-.07);state.balls.push({x:startX,y:-8,vx:vx,vy:.055,r:ballRadius(),amount:value,pathPhase:Math.random()*2,age:0,hitPegKeys:{},sinking:false,sink:0,settled:false,settleX:null});scheduleFrame(0)}
  function settle(ball,bin){if(ball.settled)return;ball.settled=true;if(state)state.effects.push({bin:bin,life:28,max:28});changePoints(Math.max(0,ball.amount*bin.mult))}
  function collide(ball,peg,left,right,prevX,prevY){var dx=ball.x-peg.x,dy=ball.y-peg.y,min=ball.r+peg.r+.95;if(Math.abs(dx)>min+2&&Math.abs(ball.x-(prevX!==undefined?prevX:ball.x))<min)return;if(Math.abs(dy)>min+2&&Math.abs(ball.y-(prevY!==undefined?prevY:ball.y))<min)return;var dist=Math.sqrt(dx*dx+dy*dy)||1;if(dist>=min&&prevX!==undefined&&prevY!==undefined){var sx=ball.x-prevX,sy=ball.y-prevY,len2=sx*sx+sy*sy;if(len2>0){var t=((peg.x-prevX)*sx+(peg.y-prevY)*sy)/len2;t=clamp(t,0,1);var cx=prevX+sx*t,cy=prevY+sy*t,cdx=cx-peg.x,cdy=cy-peg.y,cd=Math.sqrt(cdx*cdx+cdy*cdy)||1;if(cd<min){dx=cdx;dy=cdy;dist=cd;ball.x=cx;ball.y=cy}else{return}}else{return}}else if(dist>=min){return}var key=peg.key;var speed=Math.sqrt(ball.vx*ball.vx+ball.vy*ball.vy);if(!ball.hitPegKeys[key]&&speed>=.13){ball.hitPegKeys[key]=1;hitPeg(peg.x,peg.y)}var nx=dx/dist,ny=dy/dist;var overlap=min-dist;ball.x+=nx*(overlap+.04);ball.y+=ny*(overlap+.04);var vn=ball.vx*nx+ball.vy*ny;if(vn<0){ball.vx-=(1+.38)*vn*nx;ball.vy-=(1+.38)*vn*ny;var tx=-ny,ty=nx;var vt=ball.vx*tx+ball.vy*ty;ball.vx-=vt*.05*tx;ball.vy-=vt*.05*ty;ball.vx+=(Math.random()-.5)*.018}ball.vx*=.988;ball.vy*=.988;if(ball.vy<-0.38)ball.vy=-0.38;if(ball.vy>1.85)ball.vy=1.85;if(ball.x<left+ball.r){ball.x=left+ball.r;ball.vx=Math.abs(ball.vx)*.34}if(ball.x>right-ball.r){ball.x=right-ball.r;ball.vx=-Math.abs(ball.vx)*.34}}
  function tick(time){if(!state)return;var raw=(time-(state.last||time))||16;var dt=Math.min(18,raw)/16.67;state.last=time;var balls=state.balls,bins=state.bins;var left=bins[0].x,right=bins[bins.length-1].x+bins[bins.length-1].w,binTop=bins[0].y,binBottom=bins[0].y+bins[0].h;for(var b=balls.length-1;b>=0;b--){var ball=balls[b];ball.age=(ball.age||0)+dt;if(ball.sinking){ball.sink+=dt;if(Number.isFinite(ball.settleX))ball.x+=clamp(ball.settleX-ball.x,-.85,.85)*dt;ball.y+=.34*dt;ball.r*=.982;if(ball.sink>48||ball.r<1.2)balls.splice(b,1);continue}ball.vy+=.108*dt;ball.vx*=.992;if(ball.vy>1.85)ball.vy=1.85;if(ball.vy<-0.38)ball.vy=-0.38;ball.vx+=(Math.random()-.5)*.008*dt;var prevX=ball.x,prevY=ball.y;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<left+ball.r){ball.x=left+ball.r;ball.vx=Math.abs(ball.vx)*.36}if(ball.x>right-ball.r){ball.x=right-ball.r;ball.vx=-Math.abs(ball.vx)*.36}for(var pass=0;pass<2;pass++){for(var p=0;p<state.pegs.length;p++)collide(ball,state.pegs[p],left,right,pass===0?prevX:undefined,pass===0?prevY:undefined)}if(ball.y+ball.r>binTop+5){var physicalIdx=binIndexFromX(ball.x,bins,left,right);var bin=bins[physicalIdx];for(var s=1;s<bins.length;s++){var wall=left+s*(right-left)/bins.length;if(Math.abs(ball.x-wall)<ball.r&&ball.y>binTop-6&&ball.y<binBottom){if(ball.x<wall){ball.x=wall-ball.r;ball.vx=-Math.abs(ball.vx)*.36}else{ball.x=wall+ball.r;ball.vx=Math.abs(ball.vx)*.36}ball.vy*=.74}}if(ball.y+ball.r>bin.y+bin.h*.62){ball.settleX=clamp(ball.x,bin.x+ball.r,bin.x+bin.w-ball.r);ball.vx*=.16;ball.vy*=.16;settle(ball,bin);ball.sinking=true;ball.sink=0}}if(ball.y>316){if(!ball.settled){var fallback=binIndexFromX(ball.x,bins,left,right);settle(ball,bins[fallback])}balls.splice(b,1)}}draw();state.raf=0;if(hasBalls()||hasEffects())scheduleFrame(0)}
  function staticBoard(){if(!state)return null;var dpr=state.dpr||1;if(!state.staticCanvas||state.staticDpr!==dpr){state.staticCanvas=document.createElement('canvas');state.staticCanvas.width=BOARD_W*dpr;state.staticCanvas.height=BOARD_H*dpr;state.staticCtx=state.staticCanvas.getContext('2d');state.staticDpr=dpr;state.staticDirty=true}if(!state.staticDirty)return state.staticCanvas;var ctx=state.staticCtx;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,BOARD_W,BOARD_H);for(var p=0;p<state.pegs.length;p++){var peg=state.pegs[p];drawPeg(ctx,peg.x,peg.y,peg.vr||peg.r,0)}var bins=state.bins;var size=binTextSize(bins.length);ctx.font='800 '+size+'px Inter, system-ui, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';for(var i=0;i<bins.length;i++){var bin=bins[i];drawBin(ctx,bin);ctx.fillStyle='rgba(255,255,255,.94)';ctx.fillText(bin.label,bin.x+bin.w/2,bin.y+bin.h/2)}state.staticDirty=false;return state.staticCanvas}
  function drawEffects(ctx){if(!state)return;for(var r=state.effects.length-1;r>=0;r--){var ring=state.effects[r];ring.life-=1;var a=Math.max(0,ring.life/ring.max);ctx.save();if(ring.bin){var bin=ring.bin;ctx.globalAlpha=a;var glow=ctx.createLinearGradient(bin.x,bin.y,bin.x,bin.y+bin.h);glow.addColorStop(0,'rgba(255,255,255,.07)');glow.addColorStop(.55,'rgba(255,255,255,.17)');glow.addColorStop(1,'rgba(255,255,255,.04)');ctx.fillStyle=glow;ctx.fillRect(bin.x+3,bin.y+4,Math.max(1,bin.w-6),Math.max(1,bin.h-7));ctx.restore();if(ring.life<=0)state.effects.splice(r,1);continue}ctx.restore();state.effects.splice(r,1)}}
  function draw(){if(!state)return;var ctx=state.ctx,dpr=state.dpr||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,BOARD_W,BOARD_H);var base=staticBoard();if(base)ctx.drawImage(base,0,0,BOARD_W,BOARD_H);for(var p=0;p<state.pegs.length;p++){var peg=state.pegs[p];drawPeg(ctx,peg.x,peg.y,peg.vr||peg.r,0)}drawEffects(ctx);for(var b=0;b<state.balls.length;b++){var ball=state.balls[b],img=state.tokenImg,alpha=ball.sinking?Math.max(0,1-ball.sink/40):1;ctx.save();ctx.globalAlpha=alpha;if(img&&img.complete&&img.naturalWidth>0){var size=ball.r*2.45;ctx.drawImage(img,ball.x-size/2,ball.y-size/2,size,size)}else{ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}ctx.restore()}}
  document.addEventListener('pointerdown',primeAudio,{passive:true});
  document.addEventListener('touchstart',primeAudio,{passive:true});
  document.addEventListener('click',function(ev){var button=ev.target&&ev.target.closest&&ev.target.closest('button');primeAudio();if(!button)return;if(button.getAttribute('data-view')==='plinko'||button.getAttribute('data-game-view')==='plinko'){setTimeout(function(){smartLoadPlinkoControl(true);init(true)},0)}var action=button.getAttribute('data-action');if(action==='drop-plinko-ball'){ev.preventDefault();ev.stopPropagation();drop()}},true);
  document.addEventListener('input',function(ev){if(ev.target&&ev.target.id==='plinkoBet')amount()});
  document.addEventListener('visibilitychange',function(){if(!document.hidden&&active())smartLoadPlinkoControl(true)});
  window.addEventListener('focus',function(){if(active())smartLoadPlinkoControl(true)});
  window.addEventListener('vexa-credit-sync',function(ev){if(ev&&ev.detail)forcePoints(ev.detail)});
  window.addEventListener('vexa-ton-balance-sync',function(ev){if(ev&&ev.detail)forcePoints(ev.detail)});
  window.addEventListener('vexa-credit-icon-sync',function(ev){if(ev&&ev.detail&&ev.detail.url)updateIcon(ev.detail.url)});
  window.plinkoReloadControl=function(){smartLoadPlinkoControl(true)};
  if(q('plinkoCanvasV2'))init(true);if(active())smartLoadPlinkoControl(true);
})();
`;