export const PLINKO_CONTROLS_MODERN_STYLES = `
#plinko .plinko-controls{width:min(94%,374px)!important;display:grid!important;gap:12px!important;margin-top:2px!important;padding:14px!important;border-radius:32px!important;border:1px solid rgba(255,255,255,.10)!important;background:#050505!important;background-image:none!important;box-shadow:0 24px 74px rgba(0,0,0,.58),inset 0 1px 0 rgba(255,255,255,.08)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important}
#plinko .plinko-control-row{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:9px!important;align-items:stretch!important}
#plinko .plinko-field{display:grid!important;gap:7px!important;color:#fff!important;background:#030303!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:18px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important;padding:12px 11px!important;text-align:left!important}
#plinko .plinko-label{display:block!important;color:rgba(255,255,255,.50)!important;font-size:13px!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;line-height:1!important;white-space:nowrap!important;padding-left:0!important}
#plinko .risk-segment,#plinko .rows-select,#plinko .autoplay-row{border-radius:18px!important;border:1px solid rgba(255,255,255,.10)!important;background:#030303!important;background-image:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important;color:#fff!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .risk-segment{height:84px!important;padding:12px 11px!important;gap:7px!important;display:grid!important;grid-template-columns:repeat(2,1fr)!important;align-items:end!important}
#plinko .risk-segment button{height:46px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.12)!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;transition:transform .18s ease,background .18s ease,border-color .18s ease!important}
#plinko .risk-segment button.active{background:rgba(255,255,255,.18)!important;color:#fff!important;border-color:rgba(255,255,255,.24)!important;box-shadow:none!important}
#plinko .risk-segment button:active{transform:scale(.975)!important}
#plinko .rows-select{height:84px!important;width:100%!important;padding:12px 11px!important;background:#030303!important;display:flex!important;align-items:flex-end!important;justify-content:space-between!important}
#plinko .rows-select strong{font-size:22px!important;font-weight:760!important;letter-spacing:-.04em!important;font-variant-numeric:tabular-nums lining-nums!important;color:#fff!important;line-height:1!important}
#plinko .rows-select svg{opacity:.72!important;color:rgba(255,255,255,.72)!important}
#plinko .bet-amount{height:46px!important;display:grid!important;grid-template-columns:.74fr 1.52fr .74fr!important;align-items:center!important;gap:8px!important;padding:0!important;border:0!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .bet-amount input{order:2!important;min-width:0!important;width:100%!important;height:46px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.20)!important;background:rgba(255,255,255,.14)!important;color:#fff!important;font-size:17px!important;font-weight:900!important;text-align:center!important;letter-spacing:-.025em!important;box-shadow:none!important;font-variant-numeric:tabular-nums lining-nums!important;padding:0 8px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .bet-quick{display:contents!important}
#plinko .bet-quick button{height:46px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.12)!important;background:rgba(255,255,255,.075)!important;color:#fff!important;font-size:15px!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;transition:transform .18s ease,background .18s ease,border-color .18s ease!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .bet-quick button:first-child{order:1!important}
#plinko .bet-quick button:last-child{order:3!important}
#plinko .bet-quick button:active{transform:scale(.975)!important;background:rgba(255,255,255,.16)!important}
#plinko .plinko-drop,#plinko .plinko-drop:enabled,#plinko .plinko-drop:disabled,#plinko .plinko-drop[disabled]{width:100%!important;height:62px!important;border-radius:999px!important;background:#fff!important;background-image:none!important;color:#050506!important;-webkit-text-fill-color:#050506!important;font-size:18px!important;font-weight:900!important;letter-spacing:-.025em!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:0 14px 28px rgba(0,0,0,.58)!important;border:1px solid #fff!important;text-shadow:none!important;opacity:1!important;transition:transform .18s ease,opacity .18s ease!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .plinko-drop:enabled:active{transform:scale(.975)!important}
#plinko .plinko-drop:disabled,#plinko .plinko-drop[disabled]{opacity:.58!important;filter:none!important;transform:scale(.985)!important}
#plinko .autoplay-row{height:46px!important;padding:0 11px!important;background:rgba(255,255,255,.075)!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.12)!important}
#plinko .autoplay-label{font-size:13px!important;font-weight:900!important;color:#fff!important;letter-spacing:-.025em!important}
#plinko .autoplay-icon{width:24px!important;height:24px!important;background:transparent!important;border:1px solid rgba(255,255,255,.12)!important;color:rgba(255,255,255,.72)!important;box-shadow:none!important}
#plinko .autoplay-toggle{background:rgba(255,255,255,.075)!important;border:1px solid rgba(255,255,255,.12)!important}
#plinko .autoplay-toggle.active{background:rgba(255,255,255,.18)!important;border-color:rgba(255,255,255,.24)!important}
#plinko .autoplay-toggle span{box-shadow:none!important}
@media(max-width:420px){#plinko .plinko-controls{width:min(94%,374px)!important;border-radius:30px!important;gap:12px!important;padding:14px!important}#plinko .plinko-control-row{gap:8px!important;grid-template-columns:repeat(3,1fr)!important}#plinko .plinko-label{font-size:12px!important}#plinko .rows-select strong{font-size:19px!important}#plinko .bet-amount{grid-template-columns:.68fr 1.64fr .68fr!important;gap:8px!important}#plinko .plinko-field{padding:11px 9px!important}#plinko .risk-segment,#plinko .rows-select{height:80px!important;padding:11px 9px!important}}
/* dice-control-copy-plinko */
`;
