export const PLINKO_CONTROLS_MODERN_STYLES = `
#plinko .plinko-controls{--plinko-input-width:clamp(160px,54.5vw,196px);width:100vw!important;max-width:520px!important;display:flex!important;flex-direction:column!important;align-items:center!important;gap:10px!important;margin-top:-4px!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;position:relative!important;z-index:20!important}
#plinko .plinko-controls::before,#plinko .plinko-controls::after,#plinko .plinko-image-controls::before,#plinko .plinko-image-controls::after,#plinko .plinko-control-asset::before,#plinko .plinko-control-asset::after,#plinko .plinko-drop::before,#plinko .plinko-drop::after,#plinko .plinko-bet-asset::before,#plinko .plinko-bet-asset::after{display:none!important;content:none!important;background:none!important;background-image:none!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;opacity:0!important}
#plinko .plinko-image-controls{display:flex!important;flex-direction:column!important;align-items:center!important;background:transparent!important;background-image:none!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
#plinko .plinko-control-grid,#plinko .plinko-field,#plinko .plinko-bet,#plinko .plinko-stats,#plinko .plinko-stat{display:none!important}
#plinko .plinko-control-asset{position:relative!important;display:block!important;border:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;padding:0!important;margin:0!important;overflow:visible!important;filter:none!important;line-height:1!important;opacity:1!important}
#plinko .plinko-bet-asset{order:1!important;z-index:120!important;width:calc(var(--plinko-input-width) + 128px)!important;height:58px!important;margin-top:0!important;border-radius:0!important;display:grid!important;grid-template-columns:56px var(--plinko-input-width) 56px!important;align-items:center!important;justify-content:center!important;gap:8px!important;padding:7px 0!important;background:transparent!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;pointer-events:auto!important}
#plinko .plinko-drop-asset{order:2!important;z-index:60!important;width:var(--plinko-input-width)!important;height:44px!important;margin-top:0!important;margin-bottom:0!important;border-radius:999px!important;display:flex!important;align-items:center!important;justify-content:center!important;background-color:transparent!important;background-image:url('/assets/plinko-glass/drop-button.webp')!important;background-position:center!important;background-size:100% 100%!important;background-repeat:no-repeat!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;color:rgba(255,255,255,.96)!important;-webkit-text-fill-color:rgba(255,255,255,.96)!important;font-size:15px!important;font-weight:950!important;letter-spacing:-.035em!important;text-shadow:0 1px 12px rgba(0,0,0,.42)!important;transition:transform .14s ease,filter .14s ease!important;will-change:transform!important;cursor:pointer!important;touch-action:manipulation!important}
#plinko .plinko-drop-asset.plinko-drop-tap,#plinko .plinko-drop-asset.plinko-drop-press,#plinko .plinko-drop-asset:active{transform:translateY(2px) scale(.985)!important;filter:brightness(1.14)!important}
#plinko .plinko-control-asset img,#plinko .plinko-bet-image,#plinko .plinko-drop-image{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#plinko .plinko-drop,#plinko .plinko-drop:enabled,#plinko .plinko-drop:disabled,#plinko .plinko-drop[disabled]{min-height:0!important;outline:0!important;opacity:1!important;filter:none!important;overflow:visible!important;-webkit-tap-highlight-color:transparent!important}
#plinko .plinko-drop span{position:relative!important;width:auto!important;height:auto!important;overflow:visible!important;clip-path:none!important;white-space:nowrap!important;display:block!important;color:inherit!important;-webkit-text-fill-color:inherit!important}
#plinko .plinko-asset-hit{position:static!important;height:44px!important;border:0!important;border-radius:999px!important;background:transparent!important;background-image:none!important;color:rgba(255,255,255,.84)!important;-webkit-text-fill-color:rgba(255,255,255,.84)!important;font-size:15px!important;font-weight:950!important;box-shadow:none!important;padding:0!important;margin:0!important;opacity:1!important;touch-action:manipulation!important;cursor:pointer!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;z-index:3!important;pointer-events:auto!important;-webkit-tap-highlight-color:transparent!important;display:flex!important;align-items:center!important;justify-content:center!important;text-shadow:0 1px 10px rgba(0,0,0,.34)!important}
#plinko .plinko-asset-hit:active{transform:scale(.96)!important;background:transparent!important}
#plinko .plinko-asset-half{grid-column:1!important;width:56px!important;background:url('/assets/plinko-glass/half-button.webp') center/100% 100% no-repeat!important}
#plinko .plinko-asset-input{grid-column:2!important;width:var(--plinko-input-width)!important;height:44px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:3px!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:19px!important;font-weight:1000!important;letter-spacing:-.03em!important;text-align:center!important;text-shadow:0 2px 12px rgba(0,0,0,.55)!important;line-height:1!important;z-index:4!important;transform:none!important;background:url('/assets/plinko-glass/bet-input.webp') center/100% 100% no-repeat!important}
#plinko .plinko-asset-input::before{content:""!important;display:block!important;width:26px!important;height:26px!important;flex:0 0 26px!important;margin-right:-1px!important;border-radius:50%!important;background:url('/app/api/nft-price-icon.png') center/contain no-repeat!important;opacity:.98!important;filter:drop-shadow(0 2px 8px rgba(0,0,0,.34))!important;pointer-events:none!important}
#plinko .plinko-asset-double{grid-column:3!important;width:56px!important;background:url('/assets/plinko-glass/double-button.webp') center/100% 100% no-repeat!important}
#plinko .plinko-bet-value,#plinko .plinko-hidden-status{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;left:-9999px!important}
#plinko .plinko-stage{overflow:visible!important;background:transparent!important;background-image:none!important;box-shadow:none!important;border:0!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .plinko-canvas{clip-path:none!important;background:transparent!important;background-image:none!important}
#plinko .plinko-stage::before,#plinko .plinko-stage::after{display:none!important;content:none!important;background:none!important;background-image:none!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .plinko-house-image{display:none!important}
#plinko .plinko-bet-editor,#plinko .plinko-bet-editor.active,#plinko .plinko-bet-box,#plinko .plinko-bet-box small,#plinko .plinko-bet-done{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important;background:transparent!important;background-image:none!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#plinko .plinko-bet-input{position:fixed!important;left:-9999px!important;top:0!important;width:1px!important;height:1px!important;opacity:.01!important;border:0!important;background:transparent!important;color:#fff!important;text-align:center!important;font-size:22px!important;font-weight:900!important;outline:none!important;box-sizing:border-box!important;pointer-events:auto!important;z-index:-1!important;inputmode:decimal!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
@media(max-width:420px){#plinko .plinko-controls{width:100vw!important;max-width:none!important;gap:10px!important;margin-top:-4px!important}#plinko .plinko-bet-asset{width:calc(var(--plinko-input-width) + 128px)!important;height:58px!important;margin-top:0!important;order:1!important}#plinko .plinko-drop-asset{width:var(--plinko-input-width)!important;height:44px!important;margin-top:0!important;order:2!important;background-image:url('/assets/plinko-glass/drop-button.webp')!important}#plinko .plinko-house-image{display:none!important}}
`;
