export const PREDICT_EXTRA_MARKETS_SCRIPT = `
(function(){
function R(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f):f()}
R(function(){
var root=document.getElementById('predictzone');if(!root||root.dataset.extraMarketsReady==='1')return;root.dataset.extraMarketsReady='1';
var menu=root.querySelector('.predict-zone-category-menu'),card=root.querySelector('[data-predict-card]');if(!menu||!card)return;
var M={bitcoin:['Bitcoin','Bitcoin up or down?','btcusdt@miniTicker',0,5,20,0],ethereum:['Ethereum','Ethereum up or down?','ethusdt@miniTicker',2,.5,5,0],solana:['Solana','Solana up or down?','solusdt@miniTicker',2,.05,.5,0],gold:['Gold','Gold up or down?','paxgusdt@miniTicker',2,.5,5,0],oil:['Oil','Oil up or down?','clusdt@ticker',2,.05,.7,1]};
var oilStreams=['clusdt@ticker','bzusdt@ticker'];
menu.innerHTML='<button type="button" class="predict-zone-category-card active" data-vexa-predict-market="bitcoin"><span>Bitcoin</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="ethereum"><span>Ethereum</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="solana"><span>Solana</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="gold"><span>Gold</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="oil"><span>Oil</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="football"><span>Football</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="politics"><span>Politics</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="fun"><span>Fun</span></button>';
var c=card.querySelector('[data-predict-chart]'),ln=c&&c.querySelector('.predict-zone-chart-line'),fl=c&&c.querySelector('.predict-zone-chart-fill'),dot=c&&c.querySelector('.predict-zone-chart-dot'),pg=c&&c.querySelector('.predict-zone-price-guide'),ax=c?c.querySelectorAll('[data-price-axis]'):[],gl=c?c.querySelectorAll('[data-chart-grid-line]'):[],q=card.querySelector('[data-predict-question]'),qi=card.querySelector('[data-predict-question-image]'),cd=card.querySelector('[data-predict-countdown]'),live=card.querySelector('.predict-zone-live-price'),start=card.querySelector('.predict-zone-start-price'),res=card.querySelector('[data-predict-result]'),lb=card.querySelector('[data-predict-live-bets]'),sg=c&&c.querySelector('[data-predict-start-guide]');
var k='bitcoin',ws=null,raf=0,a=[],cur=0,last=0,ok=0,cen=0,slot=Math.floor(Date.now()/300000)*300000,entry=0,W=360,H=220,L=14,RR=78,P=24,imgs={},seq=0,retry=0,failTimer=0,lastSync=0,cache={};
function m(){return M[k]||M.bitcoin}function on(){return root.classList.contains('active')&&document.visibilityState!=='hidden'}function f(v){var x=m(),n=+v;return !isFinite(n)||n<=0?'—':'$'+n.toLocaleString('en-US',{minimumFractionDigits:x[3],maximumFractionDigits:x[3]})}function y(v,s){return Math.max(P,Math.min(H-P,P+((s.max-v)/(s.max-s.min))*(H-P*2)))}function t(ms){var s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function save(){if(ok&&cur>0)cache[k]={a:a.slice(),cur:cur,last:last,cen:cen,entry:entry,slot:slot,ok:ok}}
function restore(){var d=cache[k];if(!d)return false;a=d.a.slice();cur=d.cur;last=d.last;cen=d.cen;entry=d.entry||0;slot=d.slot||slot;ok=1;if(c)c.classList.add('ready');showPrices(true);if(start)start.textContent=entry?f(entry):f(cur);draw(0);return true}
function showPrices(show){if(live)live.style.visibility='';if(start)start.style.visibility='';if(dot)dot.style.visibility=show?'':'hidden';if(pg)pg.style.visibility=show?'':'hidden';ax.forEach(function(el){el.style.visibility=''});if(!show){if(live)live.textContent='—';if(start)start.textContent='—';ax.forEach(function(el){el.textContent='—'})}}
function close(){seq++;if(failTimer){clearTimeout(failTimer);failTimer=0}if(ws){try{ws.onmessage=null;ws.onclose=null;ws.onerror=null;ws.close()}catch(e){}ws=null}}
function img(){if(!qi)return;var u=imgs[k]||'';qi.style.backgroundImage=u?'url("'+u.replace(/"/g,'')+'")':'';qi.classList.toggle('has-image',!!u)}
fetch('/app/api/predict-markets',{cache:'no-store'}).then(r=>r.json()).then(d=>{var x=d&&d.markets||{};Object.keys(x).forEach(n=>{if(x[n]&&x[n].imageUrl)imgs[n]=x[n].imageUrl});img()}).catch(()=>{});
function con(){close();var my=seq,x=m(),stream=k==='oil'?oilStreams[retry%oilStreams.length]:x[2];if(!on())return;try{ws=new WebSocket((x[6]?('wss://f'+'stream.binance.com/ws/'):'wss://stream.binance.com:9443/ws/')+stream);if(k==='oil')failTimer=setTimeout(function(){if(my===seq&&!ok&&k==='oil'){retry++;con()}},3500);ws.onmessage=e=>{if(my!==seq||x!==m())return;try{var j=JSON.parse(e.data),p=+(j.c||j.p);if(!p||!isFinite(p))return;if(failTimer){clearTimeout(failTimer);failTimer=0}last=p;if(!ok){ok=1;showPrices(true);c&&c.classList.add('ready');seed(p);draw(0)}save()}catch(_){}};ws.onclose=()=>{if(my!==seq)return;ws=null;if(on())setTimeout(con,6000)};ws.onerror=()=>{if(my!==seq)return;try{ws.close()}catch(e){}}}catch(e){if(k==='oil'){retry++;setTimeout(con,1200)}}}
function seed(p){a=[];var st=p>1000?1.8:p>100?.18:.006,w=p>1000?5:p>100?.5:.018;for(var i=0;i<22;i++)a.push(p-st*12+i*st+Math.sin(i/2.8)*w);cur=p;last=p;cen=Math.round(p/m()[4])*m()[4];if(start&&!entry)start.textContent=f(p);sync();save()}
function path(p){if(!p.length)return'';var d='M'+p[0].x.toFixed(1)+' '+p[0].y.toFixed(1);for(var i=0;i<p.length-1;i++){var A=p[i],B=p[i+1],mx=(A.x+B.x)/2;d+=' C '+mx.toFixed(1)+' '+A.y.toFixed(1)+' '+mx.toFixed(1)+' '+B.y.toFixed(1)+' '+B.x.toFixed(1)+' '+B.y.toFixed(1)}return d}
function draw(pr){if(!ok||!a.length||!ln||!fl)return;var r=m()[5],target=Math.round(cur/m()[4])*m()[4];cen+=(target-cen)*.08;var s={min:cen-r/2,max:cen+r/2},right=W-RR,step=(W-L-RR)/(Math.max(22,a.length+1)-1),p=a.map((v,i)=>({x:right-((a.length-i)+pr)*step,y:y(v,s),v:v}));p.push({x:right,y:y(cur,s),v:cur});var v=p.filter(z=>z.x>=0&&z.x<=right);if(v.length<2)v=p.slice(-2);var d=path(v),F=v[0],Z=v[v.length-1],xp=Z.x/W*100,yp=Z.y/H*100;ln.setAttribute('d',d);fl.setAttribute('d',d+' L '+Z.x.toFixed(1)+' '+H+' L '+F.x.toFixed(1)+' '+H+' Z');if(dot){dot.style.left=xp+'%';dot.style.top=yp+'%'}if(pg)pg.style.top=yp+'%';ax.forEach((el,i)=>{var rr=ax.length>1?i/(ax.length-1):0,pv=s.max-rr*(s.max-s.min),top=y(pv,s)/H*100+'%';el.style.top=top;el.textContent=f(pv);if(gl[i])gl[i].style.top=top});if(sg&&entry){sg.style.top=y(entry,s)/H*100+'%';sg.classList.add('show')}if(start&&entry)start.textContent=f(entry);if(live)live.textContent=f(Z.v);save()}
function loop(n){if(!on()){stop();return}if(ok){cur+=(last-cur)*.12;var e=n%3000;if(e<60){a.push(cur);if(a.length>23)a.shift()}if(n-lastSync>12000){lastSync=n;sync()}draw(e/3000)}tick();raf=requestAnimationFrame(loop)}
function tick(){if(cd)cd.textContent=t(300000-((Date.now()-slot)%300000))}function sync(){fetch('/app/api/predict-round?market='+k,{cache:'no-store'}).then(r=>r.json()).then(d=>{var R=d&&d.round;if(!R)return;if(R.startPrice){entry=+R.startPrice;if(ok&&start)start.textContent=f(entry)}if(R.startsAt)slot=Date.parse(R.startsAt)||slot;if(R.remainingMs&&cd)cd.textContent=t(R.remainingMs);save()}).catch(()=>{})}
function stop(){save();close();if(raf)cancelAnimationFrame(raf),raf=0}
function reset(){a=[];cur=0;last=0;cen=0;ok=0;entry=0;retry=0;lastSync=0;if(dot){dot.style.left='';dot.style.top=''}if(pg)pg.style.top='';if(sg)sg.classList.remove('show');showPrices(false)}
function go(n){if(!M[n])return;save();k=n;menu.querySelectorAll('[data-vexa-predict-market]').forEach(b=>b.classList.toggle('active',b.getAttribute('data-vexa-predict-market')===n));if(q)q.textContent=m()[1];img();if(res)res.innerHTML='';if(lb)lb.innerHTML='';slot=Math.floor(Date.now()/300000)*300000;stop();reset();if(!restore()){if(ln)ln.setAttribute('d','');if(fl)fl.setAttribute('d','');ax.forEach((el,i)=>{el.textContent='—';if(gl[i])gl[i].style.top=''})}con();if(!raf)raf=requestAnimationFrame(loop);sync()}
menu.addEventListener('click',e=>{var b=e.target.closest&&e.target.closest('[data-vexa-predict-market]');if(!b)return;var n=b.getAttribute('data-vexa-predict-market');if(!M[n])return;e.preventDefault();e.stopPropagation();go(n)},true);
document.addEventListener('visibilitychange',()=>{document.visibilityState==='visible'?go(k):stop()});document.addEventListener('click',()=>setTimeout(()=>{if(!raf)go(k)},70),true);go('bitcoin');
});
})();
`;
