export const PREDICT_EXTRA_MARKETS_SCRIPT = `
(function(){
  function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
  ready(function(){
    var root=document.getElementById('predictzone');
    if(!root||root.dataset.extraMarketsReady==='1')return;
    root.dataset.extraMarketsReady='1';
    var menu=root.querySelector('.predict-zone-category-menu');
    var card=root.querySelector('[data-predict-card]');
    if(!menu||!card)return;
    var markets={
      bitcoin:{label:'Bitcoin',question:'Bitcoin up or down?',stream:'btcusdt@miniTicker',decimals:0,axisStep:5,axisRange:20,seed:102400,imageUrl:''},
      ethereum:{label:'Ethereum',question:'Ethereum up or down?',stream:'ethusdt@miniTicker',decimals:2,axisStep:.5,axisRange:5,seed:3600,imageUrl:''},
      solana:{label:'Solana',question:'Solana up or down?',stream:'solusdt@miniTicker',decimals:2,axisStep:.05,axisRange:.5,seed:160,imageUrl:''},
      gold:{label:'Gold',question:'Gold up or down?',stream:'paxgusdt@miniTicker',decimals:2,axisStep:.5,axisRange:5,seed:3300,imageUrl:''},
      ton:{label:'TON',question:'TON up or down?',stream:'tonusdt@miniTicker',decimals:4,axisStep:.005,axisRange:.02,seed:2.85,imageUrl:''}
    };
    menu.innerHTML='<button type="button" class="predict-zone-category-card active" data-vexa-predict-market="bitcoin"><span>Bitcoin</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="ethereum"><span>Ethereum</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="solana"><span>Solana</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="gold"><span>Gold</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="ton"><span>TON</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="football"><span>Football</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="politics"><span>Politics</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="fun"><span>Fun</span></button>';
    var tg=window.Telegram&&window.Telegram.WebApp;
    var tgUser=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};
    var chart=card.querySelector('[data-predict-chart]'),line=chart&&chart.querySelector('.predict-zone-chart-line'),fill=chart&&chart.querySelector('.predict-zone-chart-fill'),dot=chart&&chart.querySelector('.predict-zone-chart-dot'),priceGuide=chart&&chart.querySelector('.predict-zone-price-guide'),axisLabels=chart?chart.querySelectorAll('[data-price-axis]'):[],gridLines=chart?chart.querySelectorAll('[data-chart-grid-line]'):[],question=card.querySelector('[data-predict-question]'),questionImage=card.querySelector('[data-predict-question-image]'),countdown=card.querySelector('[data-predict-countdown]'),live=card.querySelector('.predict-zone-live-price'),start=card.querySelector('.predict-zone-start-price'),resultBox=card.querySelector('[data-predict-result]'),liveBetBox=card.querySelector('[data-predict-live-bets]'),startGuide=chart&&chart.querySelector('[data-predict-start-guide]'),startTarget=chart&&chart.querySelector('[data-predict-start-target]');
    var activeMarket='bitcoin',ws=null,raf=0,timer=0,liveBetTimer=0,prices=[],currentPrice=0,lastRealPrice=0,realReady=false,axisCenter=0,axisTarget=0,lastRender=0,lastPoint=0,roundStartedAt=Math.floor(Date.now()/300000)*300000,roundStartPrice=0,currentRound=null,width=360,height=220,padLeft=14,padRight=78,padY=24;
    function m(){return markets[activeMarket]||markets.bitcoin}function uid(){return String((tgUser&&tgUser.id)||localStorage.getItem('ownerId')||'').trim()}function active(){return root.classList.contains('active')&&document.visibilityState!=='hidden'}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function roundStep(v,s){return Math.round(v/s)*s}function fmt(v){var mm=m(),n=Number(v);return !Number.isFinite(n)||n<=0?'Loading':'$'+n.toLocaleString('en-US',{minimumFractionDigits:mm.decimals,maximumFractionDigits:mm.decimals})}function time(ms){var s=Math.max(0,Math.ceil(ms/1000)),a=Math.floor(s/60),b=s%60;return String(a).padStart(2,'0')+':'+String(b).padStart(2,'0')}
    function closeWs(){if(ws){try{ws.onclose=null;ws.onerror=null;ws.onmessage=null;ws.close()}catch(e){}ws=null}}
    function applyImage(){var mm=m();if(!questionImage)return;if(mm.imageUrl){questionImage.style.backgroundImage='url("'+String(mm.imageUrl).replace(/"/g,'')+'")';questionImage.classList.add('has-image')}else{questionImage.style.backgroundImage='';questionImage.classList.remove('has-image')}}
    function loadImages(){fetch('/app/api/predict-markets',{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){var x=d&&d.markets?d.markets:{};Object.keys(x).forEach(function(k){if(markets[k]&&x[k]&&x[k].imageUrl)markets[k].imageUrl=x[k].imageUrl});applyImage()}).catch(function(){})}
    function connect(){closeWs();var mm=m();if(!active()||!mm.stream||!('WebSocket'in window))return;try{ws=new WebSocket('wss://stream.binance.com:9443/ws/'+mm.stream);ws.onmessage=function(e){try{var p=Number(JSON.parse(e.data).c);if(!p||!isFinite(p))return;lastRealPrice=p;if(!realReady){realReady=true;if(chart)chart.classList.add('ready');seed(p);render(0,16)}}catch(x){}};ws.onclose=function(){ws=null;if(active())setTimeout(connect,6000)};ws.onerror=function(){try{ws.close()}catch(e){}}}catch(e){}}
    function clearChart(){prices=[];currentPrice=0;lastRealPrice=0;realReady=false;axisCenter=0;axisTarget=0;if(chart)chart.classList.remove('ready');if(line)line.setAttribute('d','');if(fill)fill.setAttribute('d','');axisLabels.forEach(function(x,i){x.textContent='';x.style.top='';if(gridLines[i])gridLines[i].style.top=''});if(startGuide)startGuide.classList.remove('show');if(startTarget){startTarget.classList.remove('show','above','below');startTarget.textContent=''}}
    function seed(p){prices=[];var step=p>1000?1.8:p>100?.18:.006,wave=p>1000?5:p>100?.5:.018;for(var i=0;i<22;i++)prices.push(p-step*12+i*step+Math.sin(i/2.8)*wave);currentPrice=p;lastPoint=performance.now();axisCenter=roundStep(p,m().axisStep||1);axisTarget=axisCenter;syncRound()}
    function scale(delta){var mm=m(),range=mm.axisRange||50;if(!axisCenter)axisCenter=roundStep(currentPrice||mm.seed,mm.axisStep||1);axisTarget=roundStep(currentPrice||mm.seed,mm.axisStep||1);axisCenter+=(axisTarget-axisCenter)*Math.min(.26,(delta||16)/900);return{min:axisCenter-range/2,max:axisCenter+range/2}}
    function y(price,s){return clamp(padY+((s.max-price)/(s.max-s.min))*(height-padY*2),padY,height-padY)}
    function path(points){if(!points.length)return'';var d='M'+points[0].x.toFixed(1)+' '+points[0].y.toFixed(1);for(var i=0;i<points.length-1;i++){var a=points[i],b=points[i+1],mx=(a.x+b.x)/2;d+=' C '+mx.toFixed(1)+' '+a.y.toFixed(1)+' '+mx.toFixed(1)+' '+b.y.toFixed(1)+' '+b.x.toFixed(1)+' '+b.y.toFixed(1)}return d}
    function updateEntry(s){if(!startGuide||!startTarget||!roundStartPrice){if(startGuide)startGuide.classList.remove('show');return}if(roundStartPrice<=s.max&&roundStartPrice>=s.min){startGuide.style.top=(y(roundStartPrice,s)/height*100)+'%';startGuide.classList.add('show');startTarget.classList.remove('show','above','below');startTarget.textContent=''}else{startGuide.classList.remove('show');startTarget.classList.add('show');if(roundStartPrice>s.max){startTarget.classList.add('above');startTarget.classList.remove('below');startTarget.textContent='Entry ↑'}else{startTarget.classList.add('below');startTarget.classList.remove('above');startTarget.textContent='Entry ↓'}}}
    function render(progress,delta){if(!prices.length||!line||!fill)return;var s=scale(delta),right=width-padRight,plot=width-padLeft-padRight,slots=Math.max(22,prices.length+1),step=plot/(slots-1),pts=prices.map(function(v,i){return{x:right-((prices.length-i)+progress)*step,y:y(v,s),value:v}});pts.push({x:right,y:y(currentPrice,s),value:currentPrice});var vis=pts.filter(function(p){return p.x>=0&&p.x<=right});if(vis.length<2)vis=pts.slice(-2);var d=path(vis),first=vis[0],last=vis[vis.length-1],xp=last.x/width*100,yp=last.y/height*100;line.setAttribute('d',d);fill.setAttribute('d',d+' L '+last.x.toFixed(1)+' '+height+' L '+first.x.toFixed(1)+' '+height+' Z');if(dot){dot.style.left=xp+'%';dot.style.top=yp+'%'}if(priceGuide)priceGuide.style.top=yp+'%';axisLabels.forEach(function(l,i){var r=axisLabels.length>1?i/(axisLabels.length-1):0,p=s.max-r*(s.max-s.min),top=(y(p,s)/height*100)+'%';l.style.top=top;l.textContent=fmt(p);if(gridLines[i])gridLines[i].style.top=top});updateEntry(s);if(live)live.textContent=fmt(last.value)}
    function frame(now){if(!active()){stop();return}if(!lastRender)lastRender=now;if(now-lastRender<50){raf=requestAnimationFrame(frame);return}var delta=Math.min(120,now-lastRender);lastRender=now;updateCountdown();if(realReady){currentPrice=currentPrice+(lastRealPrice-currentPrice)*(1-Math.pow(.945,delta/100));var elapsed=now-lastPoint;while(elapsed>=3000){prices.push(currentPrice);if(prices.length>23)prices.shift();lastPoint+=3000;elapsed=now-lastPoint}render(clamp(elapsed/3000,0,1),delta)}raf=requestAnimationFrame(frame)}
    function startEngine(){if(!active())return;startTimer();if(!raf){lastRender=0;raf=requestAnimationFrame(frame)}if(!ws)connect()}function stop(){if(liveBetTimer){clearInterval(liveBetTimer);liveBetTimer=0}closeWs();if(raf){cancelAnimationFrame(raf);raf=0}}
    function updateCountdown(){if(!countdown)return;countdown.textContent=time(300000-((Date.now()-roundStartedAt)%300000))}function startTimer(){if(timer)return;syncRound();timer=setInterval(function(){var slot=Math.floor(Date.now()/300000)*300000;if(slot!==roundStartedAt){roundStartedAt=slot;syncRound()}updateCountdown()},1000)}
    function syncRound(){fetch('/app/api/predict-round?market='+encodeURIComponent(activeMarket)+'&userId='+encodeURIComponent(uid()),{cache:'no-store'}).then(function(r){return r.json()}).then(function(data){var round=data&&data.round;if(!round)return;currentRound=round;if(round.startPrice){roundStartPrice=Number(round.startPrice);if(start)start.textContent=fmt(roundStartPrice)}if(round.remainingMs&&countdown)countdown.textContent=time(round.remainingMs);if(round.startsAt)roundStartedAt=Date.parse(round.startsAt)||roundStartedAt}).catch(function(){})}
    function setMarket(key){if(!markets[key])return;if(activeMarket===key&&realReady)return;activeMarket=key;menu.querySelectorAll('[data-vexa-predict-market]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-vexa-predict-market')===key)});if(question)question.textContent=m().question;applyImage();if(start)start.textContent='Loading';if(live)live.textContent='Loading';if(countdown)countdown.textContent='--:--';if(resultBox){resultBox.className='predict-zone-result-strip';resultBox.innerHTML=''}if(liveBetBox)liveBetBox.innerHTML='';roundStartPrice=0;currentRound=null;roundStartedAt=Math.floor(Date.now()/300000)*300000;clearChart();stop();startEngine()}
    menu.addEventListener('click',function(ev){var btn=ev.target.closest&&ev.target.closest('[data-vexa-predict-market]');if(!btn)return;var key=btn.getAttribute('data-vexa-predict-market');if(!markets[key])return;ev.preventDefault();ev.stopPropagation();setMarket(key)},true);
    document.addEventListener('visibilitychange',function(){document.visibilityState==='visible'?(syncRound(),startEngine()):stop()});
    document.addEventListener('click',function(){setTimeout(startEngine,70)},true);
    if(window.MutationObserver)new MutationObserver(function(){active()?startEngine():stop()}).observe(root,{attributes:true,attributeFilter:['class']});
    loadImages();setMarket('bitcoin');
  });
})();
`;
