export const PREDICT_ZONE_LOADER_POLISH_STYLES = `
#predictzone .predict-zone-chart-loader{background:linear-gradient(180deg,rgba(0,0,0,.04),rgba(0,0,0,.22))!important;-webkit-backdrop-filter:blur(2px);backdrop-filter:blur(2px);opacity:1!important;transition:opacity .28s ease,visibility 0s linear 0s!important}
#predictzone .predict-zone-chart-preview.ready .predict-zone-chart-loader{opacity:0!important;visibility:hidden;transition:opacity .28s ease,visibility 0s linear .28s!important}
#predictzone .predict-zone-loader-core{position:relative!important;width:68px!important;height:68px!important;border-radius:999px!important;display:grid!important;place-items:center!important;background:rgba(255,255,255,.032)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.075),0 18px 38px rgba(0,0,0,.24)!important;filter:none!important;overflow:visible!important}
#predictzone .predict-zone-loader-core:before{content:""!important;position:absolute!important;inset:0!important;border:0!important;border-radius:999px!important;background:conic-gradient(from 0deg,rgba(255,255,255,.08),rgba(255,255,255,.82),rgba(92,10,31,.42),rgba(255,255,255,.08))!important;box-shadow:none!important;-webkit-mask:radial-gradient(circle,transparent 59%,#000 61%);mask:radial-gradient(circle,transparent 59%,#000 61%);animation:predictLoaderCircle 1.05s linear infinite!important}
#predictzone .predict-zone-loader-core:after{content:""!important;position:absolute!important;inset:13px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.035)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.07)!important;-webkit-mask:none!important;mask:none!important;opacity:1!important;animation:predictLoaderBreath 1.55s ease-in-out infinite!important}
#predictzone .predict-zone-loader-core span{position:relative!important;z-index:1!important;width:auto!important;height:auto!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;color:rgba(255,255,255,.66)!important;font-size:7.8px!important;font-weight:900!important;letter-spacing:.14em!important;text-transform:uppercase!important;animation:predictLoaderTextSoft 1.4s ease-in-out infinite!important}
#predictzone .predict-zone-loader-core span:before,#predictzone .predict-zone-loader-core span:after{display:none!important;content:none!important}
#predictzone .predict-zone-loader-core span:empty:before{display:block!important;content:"LIVE"!important}
@keyframes predictLoaderCircle{to{transform:rotate(360deg)}}
@keyframes predictLoaderBreath{0%,100%{transform:scale(.94);opacity:.54}50%{transform:scale(1.03);opacity:.95}}
@keyframes predictLoaderTextSoft{0%,100%{opacity:.48}50%{opacity:.86}}
`;
