export const PREDICT_ZONE_NAV_HIDE_STYLES = `
body:has(#predictzone.active) .top{display:none!important}
body:has(#predictzone.active) .tabs{display:none!important}
body:has(#predictzone.active) .app{padding-top:calc(14px + env(safe-area-inset-top))!important;padding-bottom:calc(18px + env(safe-area-inset-bottom))!important}
body:has(#predictzone.active) .content{width:calc(100% + 32px)!important;height:calc(100dvh - 32px - env(safe-area-inset-top) - env(safe-area-inset-bottom))!important;margin-left:-16px!important;margin-right:-16px!important;padding:0 0 calc(18px + env(safe-area-inset-bottom))!important;overflow:hidden!important}
body:has(#predictzone.active) .app:before,body:has(#predictzone.active) .app:after{display:none!important}
body:has(#predictzone.active) #predictzone.active{padding-left:16px!important;padding-right:16px!important}
body:has(#predictzone.active) #predictzone .predict-zone-simple-shell{position:relative!important;min-height:calc(100vh - 56px - env(safe-area-inset-top) - env(safe-area-inset-bottom))!important;display:block!important;padding:94px 0 120px!important;overflow:visible!important;background:transparent!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu:before{display:none!important;content:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu{position:fixed!important;top:calc(44px + env(safe-area-inset-top))!important;left:0!important;z-index:70!important;width:100vw!important;max-width:100vw!important;margin:0!important;padding:0 16px 10px!important;overflow-x:auto!important;overflow-y:visible!important;scroll-snap-type:none!important;box-sizing:border-box!important;background:transparent!important;transform:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card{background:rgba(255,255,255,.035)!important;color:rgba(255,255,255,.58)!important;box-shadow:0 12px 26px rgba(0,0,0,.14),inset 0 1px 0 rgba(255,255,255,.10),inset 0 -1px 0 rgba(255,255,255,.03)!important;-webkit-backdrop-filter:blur(2px)!important;backdrop-filter:blur(2px)!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card span{color:rgba(255,255,255,.58)!important;font-weight:680!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card.active{background:rgba(255,255,255,.055)!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card.active span{color:#fff!important;font-weight:740!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu:after{flex-basis:48px!important}
body:has(#predictzone.active) #predictzone .predict-zone-glass-card{width:100%!important;min-height:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important;overflow:visible!important;color:#fff!important}
body:has(#predictzone.active) #predictzone .predict-zone-glass-card:before{display:none!important;content:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-card-top{position:absolute!important;top:3px!important;right:0!important;z-index:6!important;margin:0!important;display:block!important}
body:has(#predictzone.active) #predictzone .predict-zone-card-top small.predict-zone-countdown{font-size:23px!important;font-weight:680!important;line-height:1!important;color:rgba(255,255,255,.42)!important;letter-spacing:-.065em!important;text-shadow:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-question-row{display:flex!important;align-items:center!important;gap:5px!important;min-height:0!important;margin:0 0 15px!important;padding:0 96px 0 0!important;transform:none!important;color:#fff!important;font-size:27px!important;font-weight:720!important;line-height:.99!important;letter-spacing:-.06em!important;text-align:left!important;text-shadow:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-question-image{flex:0 0 56px!important;width:56px!important;height:56px!important;transform:none!important;margin:0 -1px 0 0!important;background-size:contain!important;background-position:center!important;background-repeat:no-repeat!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta{display:grid!important;grid-template-columns:1fr 1px 1fr!important;gap:16px!important;align-items:center!important;margin:0 0 14px!important;position:relative!important;z-index:2!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta:before{content:""!important;grid-column:2!important;grid-row:1!important;width:1px!important;height:34px!important;background:rgba(255,255,255,.12)!important;border-radius:999px!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div{height:auto!important;min-height:49px!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;display:grid!important;align-content:center!important;gap:5px!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div:first-child{grid-column:1!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div:last-child{grid-column:3!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta span{font-size:9.5px!important;font-weight:660!important;letter-spacing:.15em!important;color:rgba(255,255,255,.38)!important;text-transform:uppercase!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta strong{font-size:25px!important;font-weight:700!important;line-height:1!important;letter-spacing:-.045em!important;color:#fff!important;font-family:var(--font-num)!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-preview{height:285px!important;width:calc(100% + 12px)!important;margin:0 -6px 17px!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important;overflow:visible!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-grid{inset:0 72px 0 0!important;background-size:50px 100%!important;opacity:.54!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-preview svg{overflow:visible!important;filter:drop-shadow(0 10px 16px rgba(255,255,255,.08))!important}
body:has(#predictzone.active) #predictzone .predict-zone-price-axis span{font-size:13px!important;font-weight:620!important;color:rgba(255,255,255,.42)!important}
body:has(#predictzone.active) #predictzone .predict-zone-actions{gap:11px!important;margin:0 0 12px!important}
body:has(#predictzone.active) #predictzone .predict-zone-choice{height:49px!important;font-size:15px!important;font-weight:700!important;background:rgba(255,255,255,.04)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.10),0 14px 26px rgba(0,0,0,.12)!important}
body:has(#predictzone.active) #predictzone .predict-zone-result-strip{margin:0 -2px!important}
@media(max-width:380px){body:has(#predictzone.active) .app{padding-top:calc(12px + env(safe-area-inset-top))!important}body:has(#predictzone.active) #predictzone .predict-zone-simple-shell{padding-top:87px!important}body:has(#predictzone.active) #predictzone .predict-zone-category-menu{top:calc(38px + env(safe-area-inset-top))!important;left:0!important;width:100vw!important;max-width:100vw!important;margin:0!important;padding:0 16px 10px!important}body:has(#predictzone.active) #predictzone .predict-zone-question-row{font-size:23px!important;padding-right:82px!important;margin-bottom:13px!important;gap:4px!important}body:has(#predictzone.active) #predictzone .predict-zone-question-image{flex-basis:50px!important;width:50px!important;height:50px!important}body:has(#predictzone.active) #predictzone .predict-zone-card-top small.predict-zone-countdown{font-size:20px!important}body:has(#predictzone.active) #predictzone .predict-zone-live-meta{gap:12px!important;margin-bottom:12px!important}body:has(#predictzone.active) #predictzone .predict-zone-live-meta strong{font-size:21px!important}body:has(#predictzone.active) #predictzone .predict-zone-chart-preview{height:260px!important;margin-bottom:15px!important}body:has(#predictzone.active) #predictzone .predict-zone-choice{height:46px!important;font-size:14px!important}}
`;