export const PREDICT_CANDLE_SCRIPT = `
(function(){
  function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
  ready(function(){
    var root=document.getElementById('predictzone');
    if(!root||root.dataset.predictCandleReady==='1')return;
    root.dataset.predictCandleReady='1';
    var HOUR=3600000,LOCK=1800000,ws=null,market='',candles=[],side='up',busy=false,round=null,timer=0,ui=0,lastSlot=0,lastHistory='';
    function css(){
      var t='#predictzone.predict-candle-mode .predict-zone-chart-line,#predictzone.predict-candle-mode .predict-zone-chart-fill,#predictzone.predict-candle-mode .predict-zone-chart-dot,#predictzone.predict-candle-mode .predict-zone-price-guide,#predictzone.predict-candle-mode .predict-zone-start-guide,#predictzone.predict-candle-mode .predict-zone-start-target,#predictzone.predict-candle-mode .predict-zone-live-bets{display:none!important}#predictzone .predict-candle-layer{position:absolute;inset:0;z-index:4;pointer-events:none;opacity:0;transition:opacity .18s ease}#predictzone.predict-candle-mode .predict-candle-layer{opacity:1}#predictzone .predict-candle-layer svg{width:100%;height:100%;display:block;overflow:visible}#predictzone .predict-candle-up{fill:rgba(58,255,150,.82);stroke:rgba(58,255,150,.95)}#predictzone .predict-candle-down{fill:rgba(255,92,118,.82);stroke:rgba(255,92,118,.95)}#predictzone .predict-candle-wick{stroke-width:1.4;stroke-linecap:round}#predictzone .predict-candle-caption{position:absolute;left:12px;top:10px;z-index:5;height:24px;display:none;align-items:center;padding:0 9px;border-radius:999px;background:rgba(255,255,255,.06);box-shadow:inset 0 1px 0 rgba(255,255,255,.10);color:rgba(255,255,255,.74);font-size:10px;font-weight:850;letter-spacing:.04em}#predictzone.predict-candle-mode .predict-candle-caption{display:inline-flex}#predictzone .predict-candle-lock-icon{display:inline-block;width:22px;height:22px;margin-right:1px;vertical-align:-5px;color:rgba(255,255,255,.92);filter:drop-shadow(0 2px 8px rgba(255,255,255,.18)) drop-shadow(0 6px 12px rgba(0,0,0,.38))}#predictzone.predict-candle-locked [data-predict-choice]{opacity:.46!important;filter:saturate(.7)!important}#predictzone .predict-candle-countdown{display:none}#predictzone.predict-candle-mode [data-predict-countdown]{display:none!important}#predictzone.predict-candle-mode .predict-candle-countdown{display:inline-flex!important;align-items:center!important;gap:0!important}#predictzone .predict-candle-result-strip{display:none;position:relative;margin:10px -2px 0;overflow:hidden;border-radius:20px}#predictzone.predict-candle-mode [data-predict-result]{display:none!important}#predictzone.predict-candle-mode .predict-candle-result-strip.show{display:block}#predictzone .predict-candle-result-strip:before,#predictzone .predict-candle-result-strip:after{content:"";position:absolute;top:0;bottom:0;width:28px;z-index:2;pointer-events:none}#predictzone .predict-candle-result-strip:before{left:0;background:linear-gradient(90deg,rgba(10,3,5,.86),rgba(10,3,5,0))}#predictzone .predict-candle-result-strip:after{right:0;background:linear-gradient(270deg,rgba(10,3,5,.86),rgba(10,3,5,0))}';
      var s=document.getElementById('predictCandleStyles');if(!s){s=document.createElement('style');s.id='predictCandleStyles';document.head.appendChild(s)}s.textContent=t;
    }
    function q(s){return root.querySelector(s)}
    function mkt(){var b=q('.predict-zone-category-menu [data-vexa-predict-market].active,.predict-zone-category-menu [data-predict-market].active');return b?(b.getAttribute('data-vexa-predict-market')||b.getAttribute('data-predict-market')||'bitcoin'):'bitcoin'}
    function uid(){var tg=window.Telegram&&window.Telegram.WebApp,u=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};return String(u.id||localStorage.getItem('ownerId')||'').trim()}
    function label(m){return m==='bitcoin'?'Bitcoin':m==='ethereum'?'Ethereum':m==='solana'?'Solana':m==='gold'?'Gold':m==='ton'?'TON':m.charAt(0).toUpperCase()+m.slice(1)}
    function sym(m){return m==='bitcoin'?'btcusdt':m==='ethereum'?'ethusdt':m==='solana'?'solusdt':m==='gold'?'paxgusdt':m==='ton'?'tonusdt':''}
    function dec(){return mkt()==='bitcoin'?0:mkt()==='ton'?4:2}
    function price(v){v=Number(v);return !isFinite(v)||v<=0?'Loading':'$'+v.toLocaleString('en-US',{minimumFractionDigits:dec(),maximumFractionDigits:dec()})}
    function ton(v){return Number(v||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:4})}
    function slot(n){n=Number(n||Date.now());var st=Math.floor(n/HOUR)*HOUR;return{start:st,lock:st+LOCK,end:st+HOUR}}
    function time(ms){var s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
    function lockSvg(){return '<svg class="predict-candle-lock-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7.5 10V8.1C7.5 5.7 9.4 4 12 4s4.5 1.7 4.5 4.1V10" stroke="currentColor" stroke-width="2.25" stroke-linecap="round"/><rect x="5" y="10" width="14" height="10" rx="3" stroke="currentColor" stroke-width="2.25"/><path d="M12 14.1v2.2" stroke="currentColor" stroke-width="2.25" stroke-linecap="round"/></svg>'}
    function locked(){var s=slot(Date.now());return Date.now()>=s.lock&&Date.now()<s.end}
    function candleCountdown(){var old=q('[data-predict-countdown]');if(!old)return null;var el=q('.predict-candle-countdown');if(!el){el=document.createElement('small');el.className='predict-zone-countdown predict-candle-countdown';old.insertAdjacentElement('afterend',el)}return el}
    function candleResult(){var old=q('[data-predict-result]');if(!old)return null;var el=q('.predict-candle-result-strip');if(!el){el=document.createElement('div');el.className='predict-candle-result-strip';old.insertAdjacentElement('afterend',el)}return el}
    function setStatus(t,k){var e=q('[data-predict-bet-status]');if(!e)return;e.textContent=t||'';e.classList.toggle('bad',k==='bad');e.classList.toggle('good',k==='good')}
    function setBalance(p){var c=p&&p.userControls;if(!c||c.tonBalanceNano===undefined)return;var b=Number(c.tonBalanceNano);if(!isFinite(b))return;if(window.VexaTonBalance&&window.VexaTonBalance.write)window.VexaTonBalance.write(b,0,false);else try{window.dispatchEvent(new CustomEvent('vexa-ton-balance-game-change',{detail:{tonBalanceNano:b}}))}catch(e){}}
    function setLocked(v){root.classList.toggle('predict-candle-locked',!!v);root.querySelectorAll('[data-predict-choice]').forEach(function(b){b.disabled=!!v});var s=q('[data-predict-bet-submit]');if(s&&root.dataset.predictMode==='candle')s.disabled=!!v||busy}
    function tick(){if(root.dataset.predictMode!=='candle')return;var el=candleCountdown();if(!el)return;var n=Date.now(),s=slot(n),l=n>=s.lock&&n<s.end;if(lastSlot&&lastSlot!==s.start){lastHistory='';var box=candleResult();if(box){box.className='predict-candle-result-strip';box.innerHTML=''}round=null;loadRound();start()}lastSlot=s.start;el.innerHTML=(l?lockSvg():'')+time(s.end-n);setLocked(l)}
    function startTimer(){if(timer)clearTimeout(timer);tick();timer=setTimeout(function loop(){timer=0;tick();if(root.dataset.predictMode==='candle'&&document.visibilityState!=='hidden')timer=setTimeout(loop,1000)},1000)}
    function stopTimer(){if(timer){clearTimeout(timer);timer=0}}
    function layer(){var c=q('[data-predict-chart]');if(!c)return null;var l=c.querySelector('.predict-candle-layer');if(!l){l=document.createElement('div');l.className='predict-candle-layer';l.innerHTML='<span class="predict-candle-caption">1H candle • guess close</span><svg viewBox="0 0 360 220" preserveAspectRatio="none" aria-hidden="true"></svg>';c.appendChild(l)}return l}
    function header(){if(root.dataset.predictMode!=='candle')return;var m=mkt(),last=candles[candles.length-1],qq=q('[data-predict-question]');if(qq)qq.textContent=label(m)+' candle close?';if(last){var st=q('.predict-zone-start-price'),lv=q('.predict-zone-live-price');if(st)st.textContent=price(last.o);if(lv)lv.textContent=price(last.c)}}
    function yy(v,min,max){return 24+((max-v)/(max-min||1))*172}
    function render(){var l=layer();if(!l)return;var svg=l.querySelector('svg');if(!svg)return;if(!candles.length){svg.innerHTML='';header();return}var d=candles.slice(-18),hi=Math.max.apply(null,d.map(function(x){return x.h})),lo=Math.min.apply(null,d.map(function(x){return x.l})),pad=(hi-lo)*.12||1;hi+=pad;lo-=pad;var left=16,right=282,step=(right-left)/Math.max(1,d.length),body=Math.max(5,Math.min(10,step*.48)),html='';d.forEach(function(x,i){var xx=left+i*step+step*.5,yo=yy(x.o,lo,hi),yc=yy(x.c,lo,hi),yh=yy(x.h,lo,hi),yl=yy(x.l,lo,hi),up=x.c>=x.o,cls=up?'predict-candle-up':'predict-candle-down',top=Math.min(yo,yc),h=Math.max(2,Math.abs(yc-yo));html+='<line class="predict-candle-wick '+cls+'" x1="'+xx.toFixed(1)+'" x2="'+xx.toFixed(1)+'" y1="'+yh.toFixed(1)+'" y2="'+yl.toFixed(1)+'"/><rect class="'+cls+'" x="'+(xx-body/2).toFixed(1)+'" y="'+top.toFixed(1)+'" width="'+body.toFixed(1)+'" height="'+h.toFixed(1)+'" rx="2"/>'});svg.innerHTML=html;header()}
    function close(){if(ws){try{ws.onmessage=null;ws.onclose=null;ws.onerror=null;ws.close()}catch(e){}ws=null}}
    function start(){var s=sym(mkt());if(!s){close();candles=[];render();return}if(market===s&&ws&&ws.readyState===1){header();loadRound();return}market=s;close();candles=[];render();loadRound();fetch('https://api.binance.com/api/v3/klines?symbol='+s.toUpperCase()+'&interval=1h&limit=18',{cache:'default'}).then(function(r){return r.json()}).then(function(d){if(Array.isArray(d)){candles=d.map(function(k){return{o:+k[1],h:+k[2],l:+k[3],c:+k[4]}}).filter(function(x){return x.o&&x.h&&x.l&&x.c});render()}}).catch(function(){});try{ws=new WebSocket('wss://stream.binance.com:9443/ws/'+s+'@kline_1h');ws.onmessage=function(e){try{var j=JSON.parse(e.data),k=j.k;if(!k)return;var it={o:+k.o,h:+k.h,l:+k.l,c:+k.c};if(!it.o||!it.h||!it.l||!it.c)return;if(k.x&&candles.length)candles.push(it);else if(candles.length)candles[candles.length-1]=it;else candles=[it];if(candles.length>18)candles=candles.slice(-18);render()}catch(_){}}}catch(e){}}
    function renderHistory(r){var box=candleResult();if(!box||!r)return;var all=[];(r.userBets||[]).forEach(function(b){all.push(b)});(r.recentUserBets||[]).forEach(function(b){if(!all.some(function(x){return x.id===b.id}))all.push(b)});var done=all.filter(function(b){return b&&b.status}).slice(0,20);box.className='predict-candle-result-strip';if(!done.length){if(lastHistory){box.innerHTML=lastHistory;box.className='predict-candle-result-strip show'}return}var html='<div class="predict-zone-history-track">';done.forEach(function(b){var sd=String(b.side||'').toLowerCase()==='down'?'Red':'Green',stake=Number(b.stakeTon||0),pay=Number(b.payoutTon||0),st=String(b.status||''),kind=st==='won'?'win':st==='lost'?'loss':st==='refunded'?'refund':'active',amount=st==='won'?('+'+ton(pay)):st==='lost'?('-'+ton(stake)):ton(pay||stake);html+='<span class="predict-zone-history-card '+kind+'">'+sd+' '+amount+'</span>'});html+='</div>';lastHistory=html;box.innerHTML=html;box.className='predict-candle-result-strip show'}
    function loadRound(){if(root.dataset.predictMode!=='candle')return Promise.resolve(null);return fetch('/app/api/predict-round?mode=candle&market='+encodeURIComponent(mkt())+'&userId='+encodeURIComponent(uid()),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){setBalance(d);round=d&&d.round;if(round)renderHistory(round);return d}).catch(function(){return null})}
    function paint(mode){var up=q('[data-predict-choice="up"]'),dn=q('[data-predict-choice="down"]'),title=q('[data-predict-bet-title]'),qq=q('[data-predict-bet-question]');function setChoiceText(btn,text){if(!btn)return;var label=btn.querySelector&&btn.querySelector('.predict-zone-choice-label');if(label)label.textContent=text;else btn.textContent=text}if(up){setChoiceText(up,mode==='candle'?'Green':'Up');up.disabled=mode==='candle'&&locked()}if(dn){setChoiceText(dn,mode==='candle'?'Red':'Down');dn.disabled=mode==='candle'&&locked()}if(title){if(mode==='candle')title.textContent=side==='down'?'Red':'Green';else if(title.textContent==='Green')title.textContent='Up';else if(title.textContent==='Red')title.textContent='Down'}if(qq&&mode==='candle')qq.textContent=label(mkt())+' candle close?'}
    function submit(){if(busy)return;if(locked()){setStatus('This candle is locked. Wait for the next candle.','bad');return}var input=q('[data-predict-bet-input]'),btn=q('[data-predict-bet-submit]'),amount=Number(input&&input.value||0);if(!amount||!isFinite(amount)||amount<=0){setStatus('Enter a valid TON amount','bad');return}busy=true;if(btn)btn.disabled=true;setStatus('Placing candle guess...','');fetch('/app/api/predict-bet',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'candle',market:mkt(),side:side==='down'?'red':'green',userId:uid(),stakeTon:amount})}).then(function(r){return r.json().then(function(d){if(!r.ok||d.ok===false)throw new Error(d.error||'Could not place candle guess');return d})}).then(function(d){setBalance(d);if(d&&d.round){round=d.round;renderHistory(d.round)}setStatus('Candle guess placed','good');var sh=q('[data-predict-bet-sheet]');if(sh){sh.classList.remove('open');sh.setAttribute('aria-hidden','true')}if(input)input.value='';return loadRound()}).catch(function(e){setStatus(e&&e.message?e.message:'Could not place candle guess','bad');loadRound()}).finally(function(){busy=false;setLocked(locked())})}
    function setMode(mode){mode=mode==='candle'?'candle':'updown';if(root.dataset.predictMode===mode)return;css();candleCountdown();candleResult();root.dataset.predictMode=mode;root.classList.toggle('predict-candle-mode',mode==='candle');root.classList.remove('predict-candle-locked');paint(mode);if(mode==='candle'){lastSlot=0;start();startTimer();startUi()}else{close();stopTimer();stopUi();setLocked(false)}}
    function startUi(){if(ui)return;function f(){ui=0;if(root.dataset.predictMode!=='candle'||document.visibilityState==='hidden'){stopUi();return}header();ui=setTimeout(f,1000)}f()}
    function stopUi(){if(ui){clearTimeout(ui);ui=0}}
    window.addEventListener('vexa-predict-mode-change',function(e){setMode((e&&e.detail&&e.detail.mode)==='candle'?'candle':'updown')});
    document.addEventListener('click',function(e){var sub=e.target&&e.target.closest?e.target.closest('#predictzone [data-predict-bet-submit]'):null;if(sub&&root.dataset.predictMode==='candle'){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();submit();return}var ch=e.target&&e.target.closest?e.target.closest('#predictzone [data-predict-choice]'):null;if(ch&&root.dataset.predictMode==='candle'){if(locked()){e.preventDefault();e.stopPropagation();setStatus('This candle is locked. Wait for the next candle.','bad');return}side=ch.getAttribute('data-predict-choice')==='down'?'down':'up';setTimeout(function(){paint('candle')},20)}var mb=e.target&&e.target.closest?e.target.closest('#predictzone [data-vexa-predict-market],#predictzone [data-predict-market]'):null;if(mb&&root.dataset.predictMode==='candle')setTimeout(function(){start();header()},160)},true);
    document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden'){close();stopTimer();stopUi()}else if(root.dataset.predictMode==='candle')setTimeout(function(){start();startTimer();startUi()},160)});
    setMode('updown');
  });
})();
`;