import { PREDICT_OIL_HOTFIX_SCRIPT } from './predict-oil-hotfix-script';

export const PREDICT_EXTRA_MARKETS_SCRIPT = `
(function(){
if(!window.__vexaPredictFetchGuard){window.__vexaPredictFetchGuard=1;(function(){var nativeFetch=window.fetch&&window.fetch.bind(window),cache={};if(!nativeFetch)return;function keyOf(input){var url=String((input&&input.url)||input||'');if(url.indexOf('/app/api/predict-markets')>=0)return 'markets';if(url.indexOf('/app/api/predict-oil-price')>=0)return 'oil:'+Math.floor(Date.now()/300000);if(url.indexOf('/app/api/predict-round')>=0){try{var u=new URL(url,location.href),m=u.searchParams.get('market')||'';return 'round:'+m+':'+Math.floor(Date.now()/300000)}catch(e){return 'round:'+Math.floor(Date.now()/300000)}}return ''}window.fetch=function(input,init){var k=keyOf(input);if(!k)return nativeFetch(input,init);var now=Date.now(),hit=cache[k],ttl=k.indexOf('markets')===0?300000:k.indexOf('oil:')===0?300000:1500;if(hit&&now-hit.t<ttl)return hit.p.then(function(r){return r.clone()});var p=nativeFetch(input,init).then(function(r){cache[k]={t:Date.now(),p:Promise.resolve(r.clone())};return r});cache[k]={t:now,p:p.then(function(r){return r.clone()})};return p}})()}
function R(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f):f()}
R(function(){
var root=document.getElementById('predictzone');if(!root||root.dataset.extraMarketsReady==='1')return;root.dataset.extraMarketsReady='1';
var menu=root.querySelector('.predict-zone-category-menu'),card=root.querySelector('[data-predict-card]'),shell=root.querySelector('.predict-zone-simple-shell');if(!menu||!card||!shell)return;
var M={bitcoin:['Bitcoin','Bitcoin up or down?','btcusdt@miniTicker',0,5,20,0],ethereum:['Ethereum','Ethereum up or down?','ethusdt@miniTicker',2,.5,5,0],solana:['Solana','Solana up or down?','solusdt@miniTicker',2,.05,.5,0],gold:['Gold','Gold up or down?','paxgusdt@miniTicker',2,.5,5,0],oil:['Oil','Oil up or down?','',2,.05,.7,1],football:['Football','Football prediction','',0,1,10,0],politics:['Politics','Politics prediction','',0,1,10,0],fun:['Fun','Fun prediction','',0,1,10,0]};
var GROUPS={crypto:['bitcoin','solana','ethereum'],finance:['gold','oil']};
menu.innerHTML='<button type="button" class="predict-zone-category-card active" data-vexa-predict-group="crypto"><span>Crypto</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-group="finance"><span>Finance</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="football"><span>Football</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="politics"><span>Politics</span></button><button type="button" class="predict-zone-category-card" data-vexa-predict-market="fun"><span>Fun</span></button>';
var grid=document.createElement('div');grid.className='predict-crypto-grid';grid.setAttribute('data-vexa-predict-group-grid','');shell.insertBefore(grid,card);card.classList.add('predict-detail-hidden');
function refresh(sel){var n=card.querySelector(sel);if(n)n.outerHTML=n.outerHTML}
refresh('[data-predict-countdown]');refresh('.predict-zone-live-meta');refresh('[data-predict-chart]');
var c=card.querySelector('[data-predict-chart]'),ln=c&&c.querySelector('.predict-zone-chart-line'),fl=c&&c.querySelector('.predict-zone-chart-fill'),dot=c&&c.querySelector('.predict-zone-chart-dot'),pg=c&&c.querySelector('.predict-zone-price-guide'),ax=c?c.querySelectorAll('[data-price-axis]'):[],gl=c?c.querySelectorAll('[data-chart-grid-line]'):[],q=card.querySelector('[data-predict-question]'),qi=card.querySelector('[data-predict-question-image]'),cd=card.querySelector('[data-predict-countdown]'),live=card.querySelector('.predict-zone-live-price'),start=card.querySelector('.predict-zone-start-price'),res=card.querySelector('[data-predict-result]'),lb=card.querySelector('[data-predict-live-bets]'),sg=c&&c.querySelector('[data-predict-start-guide]'),st=c&&c.querySelector('[data-predict-start-target]');
var k='bitcoin',ws=null,raf=0,a=[],cur=0,last=0,ok=0,cen=0,slot=Math.floor(Date.now()/300000)*300000,entry=0,W=360,H=220,L=14,RR=78,P=24,imgs={},cardImgs={},seq=0,retry=0,failTimer=0,lastSync=0,lastDraw=0,cache={},listMode=true,currentGroup='crypto';
var imageCacheKey='vexaPredictMarketImages:v1',cardImageCacheKey='vexaPredictCryptoCardImages:v1',imagesLocked=false,cardImagesLocked=false;
function m(){return M[k]||M.bitcoin}function on(){return root.classList.contains('active')&&document.visibilityState!=='hidden'}function activeMarket(){var b=menu.querySelector('[data-vexa-predict-market].active');return b&&M[b.getAttribute('data-vexa-predict-market')]?b.getAttribute('data-vexa-predict-market'):''}function f(v){var x=m(),n=+v;return !isFinite(n)||n<=0?'—':'$'+n.toLocaleString('en-US',{minimumFractionDigits:x[3],maximumFractionDigits:x[3]})}function y(v,s){return Math.max(P,Math.min(H-P,P+((s.max-v)/(s.max-s.min))*(H-P*2)))}function t(ms){var s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function save(){if(ok&&cur>0)cache[k]={a:a.slice(),cur:cur,last:last,cen:cen,entry:entry,slot:slot,ok:ok}}
function setDetailMode(on){root.classList.toggle('predict-market-detail-mode',!!on);try{window.dispatchEvent(new CustomEvent('vexa-predict-detail-change',{detail:{open:!!on,market:on?k:''}}))}catch(e){}}
function backToPredictMain(){if(!root.classList.contains('predict-market-detail-mode'))return false;showGroup(currentGroup||'crypto');return true}
window.VexaPredictBack=backToPredictMain;
function showPrices(show){if(live)live.style.visibility='';if(start)start.style.visibility='';if(dot)dot.style.visibility=show?'':'hidden';if(pg)pg.style.visibility=show?'':'hidden';ax.forEach(function(el){el.style.visibility=''});if(!show){if(live)live.textContent='Loading';if(start)start.textContent='Loading';ax.forEach(function(el){el.textContent='Loading'})}}
function loadingChart(){var d='M14 134 C 52 112 88 146 126 124 C 164 102 198 138 236 118 C 252 110 268 116 282 108';if(c)c.classList.remove('ready');if(ln)ln.setAttribute('d',d);if(fl)fl.setAttribute('d',d+' L 282 220 L 14 220 Z');ax.forEach(function(el,i){el.style.top=(18+i*16)+'%';el.textContent='Loading';if(gl[i])gl[i].style.top=(18+i*16)+'%'})}
function close(){seq++;if(failTimer){clearTimeout(failTimer);failTimer=0}if(ws){try{ws.onmessage=null;ws.onclose=null;ws.onerror=null;ws.close()}catch(e){}ws=null}}
function img(){if(!qi)return;var u=imgs[k]||'';qi.style.backgroundImage=u?'url("'+u.replace(/"/g,'')+'")':'';qi.classList.toggle('has-image',!!u)}
function preloadImage(url){if(!url)return;try{var im=new Image();im.decoding='async';im.loading='eager';im.src=url}catch(e){}}
function hasImages(map){return !!(map&&Object.keys(map).some(function(n){return !!map[n]}))}
function applyImageMap(map,saveLocal){if(!map)return;var changed=false;Object.keys(map).forEach(function(n){var u=map[n];if(u&&imgs[n]!==u){imgs[n]=u;changed=true;preloadImage(u)}});if(changed&&saveLocal){try{localStorage.setItem(imageCacheKey,JSON.stringify({images:imgs,updatedAt:Date.now(),locked:true}))}catch(e){}}img();paintGroupImages()}
function applyCardImageMap(map,saveLocal){if(!map)return;var changed=false;Object.keys(map).forEach(function(n){var u=map[n];if(u&&cardImgs[n]!==u){cardImgs[n]=u;changed=true;preloadImage(u)}});if(changed&&saveLocal){try{localStorage.setItem(cardImageCacheKey,JSON.stringify({images:cardImgs,updatedAt:Date.now(),locked:true}))}catch(e){}}paintGroupImages()}
try{var saved=JSON.parse(localStorage.getItem(imageCacheKey)||'null');if(saved&&hasImages(saved.images)){applyImageMap(saved.images,false);imagesLocked=true}}catch(e){}
try{var savedCards=JSON.parse(localStorage.getItem(cardImageCacheKey)||'null');if(savedCards&&hasImages(savedCards.images)){applyCardImageMap(savedCards.images,false);cardImagesLocked=true}}catch(e){}
if(!imagesLocked){fetch('/app/api/predict-markets',{cache:'force-cache'}).then(r=>r.json()).then(d=>{var x=d&&d.markets||{},next={};Object.keys(x).forEach(n=>{if(x[n]&&x[n].imageUrl)next[n]=x[n].imageUrl});applyImageMap(next,true)}).catch(()=>{});}
if(!cardImagesLocked){fetch('/app/api/predict-crypto-card-images',{cache:'force-cache'}).then(r=>r.json()).then(d=>{var x=d&&d.images||{},next={};Object.keys(x).forEach(n=>{if(x[n]&&x[n].imageUrl)next[n]=x[n].imageUrl});applyCardImageMap(next,true)}).catch(()=>{});}
function priceText(id){var x=M[id]||M.bitcoin;if(!x[2]&&id!=='oil')return 'Soon';var d=cache[id];return d&&d.cur?('$'+Number(d.cur).toLocaleString('en-US',{minimumFractionDigits:x[3],maximumFractionDigits:x[3]})):'Loading'}
function groupCard(id){var x=M[id]||M.bitcoin,isCrypto=GROUPS.crypto.indexOf(id)>=0;return '<button type="button" class="predict-crypto-card '+(isCrypto?'predict-crypto-card-empty':'')+'" data-vexa-predict-open="'+id+'"><span class="predict-crypto-card-upload" data-vexa-predict-upload-img="'+id+'"></span><span class="predict-crypto-image" data-vexa-predict-card-img="'+id+'"></span><span class="predict-crypto-copy"><b>'+x[0]+'</b><small>'+x[1]+'</small></span><span class="predict-crypto-price" data-vexa-predict-card-price="'+id+'">'+priceText(id)+'</span></button>'}
function paintGroupImages(){grid.querySelectorAll('[data-vexa-predict-card-img]').forEach(function(el){var id=el.getAttribute('data-vexa-predict-card-img'),u=imgs[id]||'';el.style.backgroundImage=u?'url("'+u.replace(/"/g,'')+'")':'';el.classList.toggle('has-image',!!u)});grid.querySelectorAll('[data-vexa-predict-upload-img]').forEach(function(el){var id=el.getAttribute('data-vexa-predict-upload-img'),u=cardImgs[id]||'';el.style.backgroundImage=u?'url("'+u.replace(/"/g,'')+'")':'';el.classList.toggle('has-image',!!u)})}
function updateGroupPrices(){grid.querySelectorAll('[data-vexa-predict-card-price]').forEach(function(el){el.textContent=priceText(el.getAttribute('data-vexa-predict-card-price')||'bitcoin')})}
function showGroup(g){g=GROUPS[g]?g:'crypto';currentGroup=g;listMode=true;setDetailMode(false);save();stop();var ids=GROUPS[g]||GROUPS.crypto;card.classList.add('predict-detail-hidden');grid.style.display='grid';grid.innerHTML=ids.map(groupCard).join('');paintGroupImages();updateGroupPrices();menu.querySelectorAll('[data-vexa-predict-group],[data-vexa-predict-market]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-vexa-predict-group')===g)});grid.querySelectorAll('[data-vexa-predict-open]').forEach(function(b){b.onclick=function(){go(b.getAttribute('data-vexa-predict-open')||'bitcoin')}})}
function con(){close();var my=seq,x=m(),stream=x[2];if(!on()||!stream)return;try{ws=new WebSocket((x[6]?('wss://f'+'stream.binance.com/ws/'):'wss://stream.binance.com:9443/ws/')+stream);ws.onmessage=e=>{if(my!==seq||x!==m())return;try{var j=JSON.parse(e.data),p=+(j.c||j.p);if(!p||!isFinite(p))return;last=p;if(!ok){ok=1;showPrices(true);c&&c.classList.add('ready');seed(p);draw(0)}cache[k]=cache[k]||{};cache[k].cur=p;updateGroupPrices();save()}catch(_){}};ws.onclose=()=>{if(my!==seq)return;ws=null;if(on())setTimeout(con,6000)};ws.onerror=()=>{if(my!==seq)return;try{ws.close()}catch(e){}}}catch(e){}}
function seed(p){a=[];var stp=p>1000?1.8:p>100?.18:.006,w=p>1000?5:p>100?.5:.018;for(var i=0;i<22;i++)a.push(p-stp*12+i*stp+Math.sin(i/2.8)*w);cur=p;last=p;cen=Math.round(p/m()[4])*m()[4];if(start&&!entry)start.textContent=f(p);save()}
function path(p){if(!p.length)return'';var d='M'+p[0].x.toFixed(1)+' '+p[0].y.toFixed(1);for(var i=0;i<p.length-1;i++){var A=p[i],B=p[i+1],mx=(A.x+B.x)/2;d+=' C '+mx.toFixed(1)+' '+A.y.toFixed(1)+' '+mx.toFixed(1)+' '+B.y.toFixed(1)+' '+B.x.toFixed(1)+' '+B.y.toFixed(1)}return d}
function draw(pr){if(!ok||!a.length||!ln||!fl)return;var r=m()[5],target=Math.round(cur/m()[4])*m()[4];cen+=(target-cen)*.08;var s={min:cen-r/2,max:cen+r/2},right=W-RR,step=(W-L-RR)/(Math.max(22,a.length+1)-1),p=a.map((v,i)=>({x:right-((a.length-i)+pr)*step,y:y(v,s),v:v}));p.push({x:right,y:y(cur,s),v:cur});var v=p.filter(z=>z.x>=0&&z.x<=right);if(v.length<2)v=p.slice(-2);var d=path(v),F=v[0],Z=v[v.length-1],xp=Z.x/W*100,yp=Z.y/H*100;ln.setAttribute('d',d);fl.setAttribute('d',d+' L '+Z.x.toFixed(1)+' '+H+' L '+F.x.toFixed(1)+' '+H+' Z');if(dot){dot.style.left=xp+'%';dot.style.top=yp+'%'}if(pg)pg.style.top=yp+'%';ax.forEach((el,i)=>{var rr=ax.length>1?i/(ax.length-1):0,pv=s.max-rr*(s.max-s.min),top=y(pv,s)/H*100+'%';el.style.top=top;el.textContent=f(pv);if(gl[i])gl[i].style.top=top});if(sg)sg.classList.remove('show');if(st){st.classList.remove('show','above','below');st.textContent=''}if(entry){if(entry<=s.max&&entry>=s.min){if(sg){sg.style.top=y(entry,s)/H*100+'%';sg.classList.add('show')}}else if(st){st.classList.add('show');if(entry>s.max){st.classList.add('above');st.textContent='Entry ↑'}else{st.classList.add('below');st.textContent='Entry ↓'}}}if(start&&entry)start.textContent=f(entry);if(live)live.textContent=f(Z.v)}
function loop(n){if(!on()){stop();return}tick();if(ok){cur+=(last-cur)*.12;var e=n%3000;if(e<70){a.push(cur);if(a.length>23)a.shift()}if(n-lastDraw>66){lastDraw=n;draw(e/3000)}}raf=requestAnimationFrame(loop)}
function tick(){if(!cd)return;var now=Date.now(),nextSlot=Math.floor(now/300000)*300000;if(nextSlot!==slot){slot=nextSlot;entry=0;sync()}cd.textContent=t(300000-((now-slot)%300000))}function sync(){lastSync=Date.now();var api=(k==='gold'||k==='oil'||k==='football'||k==='politics'||k==='fun')?'bitcoin':k;fetch('/app/api/predict-round?market='+api,{cache:'no-store'}).then(r=>r.json()).then(d=>{var R=d&&d.round;if(!R)return;if(R.startPrice){entry=+R.startPrice;if(ok&&start)start.textContent=f(entry)}if(R.startsAt)slot=Date.parse(R.startsAt)||slot;if(R.remainingMs&&cd)cd.textContent=t(R.remainingMs);save()}).catch(()=>{})}
function stop(){save();close();if(raf)cancelAnimationFrame(raf),raf=0}
function reset(){a=[];cur=0;last=0;cen=0;ok=0;entry=0;retry=0;lastSync=0;lastDraw=0;if(dot){dot.style.left='';dot.style.top=''}if(pg)pg.style.top='';if(sg)sg.classList.remove('show');if(st){st.classList.remove('show','above','below');st.textContent=''}showPrices(false);loadingChart()}
function go(n){if(!M[n])return;listMode=false;save();stop();k=n;setDetailMode(true);grid.style.display='none';card.classList.remove('predict-detail-hidden');menu.querySelectorAll('[data-vexa-predict-group],[data-vexa-predict-market]').forEach(b=>b.classList.toggle('active',b.getAttribute('data-vexa-predict-market')===n));if(q)q.textContent=m()[1];img();if(res)res.innerHTML='';if(lb)lb.innerHTML='';slot=Math.floor(Date.now()/300000)*300000;reset();con();if(!raf)raf=requestAnimationFrame(loop);sync()}
function boot(){if(listMode)return;if(on()&&!raf){var n=activeMarket();if(n)go(n)}}function resume(force){if(!on()||listMode)return;var n=activeMarket();if(!n)return;var needsStream=!!M[n][2],deadStream=needsStream&&(!ws||ws.readyState!==1);if(force||!raf||!ok||deadStream)go(n)}function resumeSoon(){setTimeout(()=>resume(true),120);setTimeout(()=>resume(true),700);setTimeout(()=>resume(true),1600)}
menu.addEventListener('click',e=>{var g=e.target.closest&&e.target.closest('[data-vexa-predict-group]');if(g){e.preventDefault();e.stopPropagation();showGroup(g.getAttribute('data-vexa-predict-group')||'crypto');return}var b=e.target.closest&&e.target.closest('[data-vexa-predict-market]');if(!b)return;var n=b.getAttribute('data-vexa-predict-market');if(!M[n])return;e.preventDefault();e.stopPropagation();go(n)},true);
document.addEventListener('visibilitychange',()=>{document.visibilityState==='visible'?resumeSoon():stop()});window.addEventListener('focus',resumeSoon);window.addEventListener('pageshow',resumeSoon);document.addEventListener('click',()=>setTimeout(boot,120),true);if(window.MutationObserver)new MutationObserver(resumeSoon).observe(root,{attributes:true,attributeFilter:['class']});showGroup('crypto');
});
})();
${PREDICT_OIL_HOTFIX_SCRIPT}
`;