export const PREDICT_ZONE_LOADER_POLISH_STYLES = `
#predictzone .predict-zone-chart-loader{background:linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.26))!important;-webkit-backdrop-filter:blur(2px);backdrop-filter:blur(2px);opacity:1!important;transition:opacity .28s ease,visibility 0s linear 0s!important}
#predictzone .predict-zone-chart-preview.ready .predict-zone-chart-loader{opacity:0!important;visibility:hidden;transition:opacity .28s ease,visibility 0s linear .28s!important}
#predictzone .predict-zone-loader-core{position:relative!important;width:104px!important;height:34px!important;border-radius:999px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:rgba(255,255,255,.045)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 16px 34px rgba(0,0,0,.22)!important;filter:none!important;overflow:hidden!important}
#predictzone .predict-zone-loader-core:before{content:""!important;position:absolute!important;left:8px!important;right:8px!important;top:50%!important;height:2px!important;margin-top:-1px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.10)!important;box-shadow:none!important;animation:none!important}
#predictzone .predict-zone-loader-core:after{content:""!important;position:absolute!important;left:8px!important;top:50%!important;width:28px!important;height:2px!important;margin-top:-1px!important;border:0!important;border-radius:999px!important;background:rgba(255,255,255,.78)!important;box-shadow:0 0 14px rgba(255,255,255,.20)!important;-webkit-mask:none!important;mask:none!important;opacity:1!important;animation:predictLoaderLine 1.08s ease-in-out infinite!important}
#predictzone .predict-zone-loader-core span{position:relative!important;z-index:1!important;width:auto!important;height:auto!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;color:rgba(255,255,255,.64)!important;font-size:8.5px!important;font-weight:850!important;letter-spacing:.16em!important;text-transform:uppercase!important;animation:predictLoaderText 1.35s ease-in-out infinite!important}
#predictzone .predict-zone-loader-core span:before,#predictzone .predict-zone-loader-core span:after{display:none!important;content:none!important}
#predictzone .predict-zone-loader-core span:empty:before{display:block!important;content:"LIVE"!important}
@keyframes predictLoaderLine{0%{transform:translateX(0);opacity:.42}50%{transform:translateX(60px);opacity:1}100%{transform:translateX(0);opacity:.42}}
@keyframes predictLoaderText{0%,100%{opacity:.44}50%{opacity:.78}}
`;
