export const PREDICT_ZONE_NAV_HIDE_STYLES = `
body:has(#predictzone.active) .top{display:none!important}
body:has(#predictzone.active) .tabs{display:none!important}
body:has(#predictzone.active) .app{padding-top:calc(14px + env(safe-area-inset-top))!important;padding-bottom:calc(18px + env(safe-area-inset-bottom))!important}
body:has(#predictzone.active) .content{width:calc(100% + 32px)!important;height:calc(100dvh - 32px - env(safe-area-inset-top) - env(safe-area-inset-bottom))!important;margin-left:-16px!important;margin-right:-16px!important;padding:0 0 calc(18px + env(safe-area-inset-bottom))!important;overflow:hidden!important}
body:has(#predictzone.active) .app:before,body:has(#predictzone.active) .app:after{display:none!important}
body:has(#predictzone.active) #predictzone.active{padding-left:16px!important;padding-right:16px!important}
body:has(#predictzone.active) #predictzone .predict-zone-simple-shell{position:relative!important;min-height:calc(100vh - 56px - env(safe-area-inset-top) - env(safe-area-inset-bottom))!important;display:block!important;padding:94px 0 120px!important;overflow:visible!important;background:transparent!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu:before{display:none!important;content:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu{position:fixed!important;top:calc(44px + env(safe-area-inset-top))!important;left:0!important;right:auto!important;z-index:70!important;width:100vw!important;max-width:100vw!important;margin:0!important;padding:0 16px 10px!important;overflow-x:auto!important;overflow-y:visible!important;scroll-snap-type:none!important;box-sizing:border-box!important;background:transparent!important;transform:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card{background:rgba(255,255,255,.035)!important;color:rgba(255,255,255,.58)!important;box-shadow:0 12px 26px rgba(0,0,0,.14),inset 0 1px 0 rgba(255,255,255,.10),inset 0 -1px 0 rgba(255,255,255,.03)!important;-webkit-backdrop-filter:blur(2px)!important;backdrop-filter:blur(2px)!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card span{color:rgba(255,255,255,.58)!important;font-weight:760!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card.active{background:rgba(255,255,255,.055)!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-card.active span{color:#fff!important;font-weight:820!important}
body:has(#predictzone.active) #predictzone .predict-zone-category-menu:after{flex-basis:48px!important}
body:has(#predictzone.active) #predictzone .predict-zone-glass-card{width:100%!important;min-height:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important;overflow:visible!important;color:#fff!important}
body:has(#predictzone.active) #predictzone .predict-zone-glass-card:before{display:none!important;content:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-card-top{position:absolute!important;top:3px!important;right:0!important;z-index:6!important;margin:0!important;display:block!important}
body:has(#predictzone.active) #predictzone .predict-zone-card-top small.predict-zone-countdown{font-size:25px!important;font-weight:820!important;line-height:1!important;color:rgba(255,255,255,.46)!important;letter-spacing:-.07em!important;text-shadow:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-question-row{display:flex!important;align-items:flex-start!important;gap:8px!important;min-height:0!important;margin:0 0 18px!important;padding:0 104px 0 0!important;transform:none!important;color:#fff!important;font-size:29px!important;font-weight:840!important;line-height:.98!important;letter-spacing:-.07em!important;text-align:left!important;text-shadow:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-question-image{flex:0 0 44px!important;width:44px!important;height:44px!important;transform:translateY(1px)!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta{display:grid!important;grid-template-columns:1fr 1px 1fr!important;gap:18px!important;align-items:center!important;margin:0 0 16px!important;position:relative!important;z-index:2!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta:before{content:""!important;grid-column:2!important;grid-row:1!important;width:1px!important;height:38px!important;background:rgba(255,255,255,.12)!important;border-radius:999px!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div{height:auto!important;min-height:54px!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;display:grid!important;align-content:center!important;gap:6px!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div:first-child{grid-column:1!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta div:last-child{grid-column:3!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta span{font-size:10px!important;font-weight:820!important;letter-spacing:.15em!important;color:rgba(255,255,255,.42)!important;text-transform:uppercase!important}
body:has(#predictzone.active) #predictzone .predict-zone-live-meta strong{font-size:27px!important;font-weight:860!important;line-height:1!important;letter-spacing:-.055em!important;color:#fff!important;font-family:var(--font-num)!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-preview{height:305px!important;width:calc(100% + 16px)!important;margin:0 -8px 20px!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important;overflow:visible!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-grid{inset:0 72px 0 0!important;background-size:50px 100%!important;opacity:.54!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-preview svg{overflow:visible!important;filter:drop-shadow(0 10px 16px rgba(255,255,255,.08))!important}
body:has(#predictzone.active) #predictzone .predict-zone-chart-line{stroke-width:5.2!important}
body:has(#predictzone.active) #predictzone .predict-zone-price-axis span{font-size:14px!important;font-weight:760!important;color:rgba(255,255,255,.46)!important}
body:has(#predictzone.active) #predictzone .predict-zone-actions{gap:12px!important;margin:0 0 14px!important}
body:has(#predictzone.active) #predictzone .predict-zone-choice{height:52px!important;font-size:16px!important;font-weight:820!important;background:rgba(255,255,255,.04)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.10),0 14px 26px rgba(0,0,0,.12)!important}
body:has(#predictzone.active) #predictzone .predict-zone-result-strip{margin:0 -2px!important}
@media(max-width:380px){body:has(#predictzone.active) .app{padding-top:calc(12px + env(safe-area-inset-top))!important}body:has(#predictzone.active) #predictzone .predict-zone-simple-shell{padding-top:87px!important}body:has(#predictzone.active) #predictzone .predict-zone-category-menu{top:calc(38px + env(safe-area-inset-top))!important;left:0!important;width:100vw!important;max-width:100vw!important;margin:0!important;padding:0 16px 10px!important}body:has(#predictzone.active) #predictzone .predict-zone-question-row{font-size:25px!important;padding-right:88px!important;margin-bottom:15px!important}body:has(#predictzone.active) #predictzone .predict-zone-card-top small.predict-zone-countdown{font-size:22px!important}body:has(#predictzone.active) #predictzone .predict-zone-live-meta{gap:14px!important;margin-bottom:14px!important}body:has(#predictzone.active) #predictzone .predict-zone-live-meta strong{font-size:23px!important}body:has(#predictzone.active) #predictzone .predict-zone-chart-preview{height:280px!important;margin-bottom:18px!important}body:has(#predictzone.active) #predictzone .predict-zone-choice{height:49px!important}}
`;