export const REWARDS_LIVE_WINNERS_EFFECTS = `
<style id="vexa-rewards-live-winners-effects">
#home[data-home-variant="one"] .home-ticket-finance-visual.home-ticket-card{min-height:154px!important;height:var(--home-lottery-winners-height,154px)!important;align-self:start!important;place-items:stretch!important;pointer-events:auto!important}
#home[data-home-variant="one"] .home-ticket-finance-visual>.home-lottery-winners{width:100%!important;height:100%!important;min-height:0!important;display:grid!important;grid-template-rows:minmax(0,1fr)!important;gap:0!important;align-content:stretch!important;min-width:0!important;background:transparent!important;box-shadow:none!important;border:0!important;padding:0!important}
#home[data-home-variant="one"] .home-lottery-winners-list{position:relative!important;display:grid!important;grid-auto-rows:32px!important;align-content:start!important;gap:6px!important;min-height:0!important;height:100%!important;overflow-y:auto!important;overflow-x:hidden!important;padding:0 2px!important;box-sizing:border-box!important;background:transparent!important;box-shadow:none!important;scrollbar-width:none!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;touch-action:pan-y!important;mask-image:none!important;-webkit-mask-image:none!important}
#home[data-home-variant="one"] .home-lottery-winners-list::-webkit-scrollbar{display:none!important}
#home[data-home-variant="one"] .home-lottery-winners-list.has-overflow:not(.is-scrolled){mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 18px),transparent 100%)!important;-webkit-mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 18px),transparent 100%)!important}
#home[data-home-variant="one"] .home-lottery-winners-list.has-overflow.is-scrolled:not(.is-at-bottom){mask-image:linear-gradient(to bottom,transparent 0,#000 18px,#000 calc(100% - 18px),transparent 100%)!important;-webkit-mask-image:linear-gradient(to bottom,transparent 0,#000 18px,#000 calc(100% - 18px),transparent 100%)!important}
#home[data-home-variant="one"] .home-lottery-winners-list.has-overflow.is-at-bottom{mask-image:linear-gradient(to bottom,transparent 0,#000 18px,#000 100%)!important;-webkit-mask-image:linear-gradient(to bottom,transparent 0,#000 18px,#000 100%)!important}
#home[data-home-variant="one"] .home-lottery-winner-row{position:relative!important;overflow:hidden!important;height:32px!important;min-height:32px!important;border:0!important;outline:0!important;border-radius:14px!important;background:#000!important;box-shadow:0 8px 18px rgba(0,0,0,.28)!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:8px!important;padding:0 10px!important;box-sizing:border-box!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;isolation:isolate!important}
#home[data-home-variant="one"] .home-lottery-winner-copy{min-width:0!important;display:flex!important;align-items:center!important;overflow:hidden!important}
#home[data-home-variant="one"] .home-lottery-winner-name{min-width:0!important;max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;color:#fff!important;font-size:9.5px!important;font-weight:900!important;line-height:1.08!important}
#home[data-home-variant="one"] .home-lottery-winner-amount{align-self:center!important;color:rgba(255,255,255,.34)!important;font-size:7.5px!important;font-weight:800!important;white-space:nowrap!important;margin-left:2px!important}
#home[data-home-variant="one"] .home-lottery-winners-empty{height:100%!important;display:grid!important;place-items:center!important;text-align:center!important;color:rgba(255,255,255,.34)!important;font-size:9px!important;font-weight:760!important;line-height:1.3!important;padding:0 12px!important;box-sizing:border-box!important}
</style>
<script id="vexa-rewards-live-winners-scroll-script">
(function(){
  var loading=false,lastRequestAt=0,phaseTimer=0,retryTimer=0,retryDelay=1000;
  var heightObserver=null,observedTicket=null;
  function q(s,r){return (r||document).querySelector(s)}
  function homeOne(){var home=document.getElementById('home');return home&&home.getAttribute('data-home-variant')==='one'?home:null}
  function host(){var home=homeOne();return home?q('.home-ticket-finance-visual',home):null}
  function initData(){var tg=window.Telegram&&window.Telegram.WebApp;return String(tg&&tg.initData||'')}
  function gram(nano){var value=Math.max(0,Number(nano)||0)/1000000000;if(value>=1000)return value.toLocaleString('en-US',{maximumFractionDigits:1});if(value>=10)return value.toFixed(1).replace(/\\.0$/,'');return value.toFixed(2).replace(/0+$/,'').replace(/\\.$/,'')}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':'&quot;'})}
  function cleanCount(value){var count=Math.floor(Number(value)||0);return Math.max(0,Math.min(50,count))}
  function winnerMap(winners,count){var map={},limit=cleanCount(count);(Array.isArray(winners)?winners:[]).forEach(function(item){var rank=Math.floor(Number(item&&item.rank)||0);if(rank>=1&&rank<=limit)map[rank]=item});return map}
  function displayName(item){var name=String(item&&item.displayName||'').trim();return esc(name||'Player')}
  function row(rank,item,waiting){var name,amount;if(waiting){name='Waiting for draw';amount='—'}else if(!item){name='No result this round';amount='—'}else{name=displayName(item);amount='+'+gram(item.prizeNano)+' GRAM'}return '<article class="home-lottery-winner-row"><div class="home-lottery-winner-copy"><div class="home-lottery-winner-name">'+name+'</div></div><div class="home-lottery-winner-amount">'+esc(amount)+'</div></article>'}
  function syncHeight(){var card=host(),ticket=q('#home .home-ticket-layout>.home-ticket-card:not(.home-ticket-finance-visual)');if(!card||!ticket)return;var h=Math.ceil(ticket.getBoundingClientRect().height||0);if(h>0)card.style.setProperty('--home-lottery-winners-height',Math.max(154,h)+'px')}
  function watchHeight(){var ticket=q('#home .home-ticket-layout>.home-ticket-card:not(.home-ticket-finance-visual)');if(!ticket)return;if(observedTicket===ticket){syncHeight();return}if(heightObserver){heightObserver.disconnect();heightObserver=null}observedTicket=ticket;syncHeight();if(window.ResizeObserver){heightObserver=new ResizeObserver(function(){syncHeight()});heightObserver.observe(ticket)}}
  function updateFade(list){if(!list)return;var max=Math.max(0,list.scrollHeight-list.clientHeight),overflow=max>2;list.classList.toggle('has-overflow',overflow);list.classList.toggle('is-scrolled',overflow&&list.scrollTop>2);list.classList.toggle('is-at-bottom',overflow&&list.scrollTop>=max-2)}
  function ensureSurface(){var home=homeOne(),card=host();if(!home||!card)return null;card.removeAttribute('aria-hidden');card.classList.add('home-ticket-card');var surface=q(':scope>.home-lottery-winners',card);if(!surface){card.innerHTML='<section class="home-lottery-winners" aria-label="Lottery results"><div class="home-lottery-winners-list"></div></section>';surface=q(':scope>.home-lottery-winners',card)}var list=surface&&q('.home-lottery-winners-list',surface);if(list&&list.dataset.winnersScrollBound!=='1'){list.dataset.winnersScrollBound='1';list.addEventListener('scroll',function(){updateFade(list)},{passive:true})}watchHeight();return list}
  function render(winners,waiting,count){var list=ensureSurface();if(!list)return;var limit=cleanCount(count),map=winnerMap(winners,limit),html='';for(var rank=1;rank<=limit;rank++)html+=row(rank,map[rank],!!waiting);list.innerHTML=html;(window.requestAnimationFrame||function(cb){return setTimeout(cb,0)})(function(){updateFade(list)})}
  function clearRetry(){if(retryTimer){clearTimeout(retryTimer);retryTimer=0}}
  function scheduleRetry(){var home=homeOne();if(retryTimer||!home||!home.classList.contains('active')||document.hidden)return;var delay=retryDelay;retryDelay=Math.min(15000,Math.round(retryDelay*1.8));retryTimer=setTimeout(function(){retryTimer=0;load(true)},delay)}
  function schedulePhaseRefresh(payload){if(phaseTimer){clearTimeout(phaseTimer);phaseTimer=0}var next=Number(payload&&payload.nextDisplayChangeAtMs),serverNow=Number(payload&&payload.serverNowMs);if(!Number.isFinite(next)||!Number.isFinite(serverNow)||next<=serverNow)return;phaseTimer=setTimeout(function(){phaseTimer=0;load(true)},Math.max(80,next-serverNow+80))}
  async function load(force){var home=homeOne(),list=ensureSurface(),data=initData();if(!home||!home.classList.contains('active')||!list||!data||loading)return false;var now=Date.now();if(!force&&now-lastRequestAt<500)return false;loading=true;lastRequestAt=now;try{var response=await fetch('/app/api/lottery/winners',{cache:'no-store',headers:{'accept':'application/json','x-telegram-init-data':data}});var payload=await response.json().catch(function(){return null});if(!response.ok||!payload)throw new Error('Could not load lottery results');clearRetry();retryDelay=1000;render(payload.winners||[],!!payload.waitingForWinner,payload.winnerCount);schedulePhaseRefresh(payload);return true}catch(e){scheduleRetry();return false}finally{loading=false}}
  function bind(){var home=homeOne(),list=ensureSurface();if(!home||!list)return;updateFade(list);if(home.classList.contains('active'))load(false)}
  function refreshWhenVisible(){var home=homeOne();if(!document.hidden&&home&&home.classList.contains('active'))load(false)}
  document.addEventListener('click',function(ev){var target=ev.target&&ev.target.closest&&ev.target.closest('[data-view="home"]');if(target)setTimeout(bind,60)},true);
  window.addEventListener('vexa:section-mounted',bind);
  window.addEventListener('resize',function(){syncHeight();updateFade(ensureSurface())},{passive:true});
  window.addEventListener('focus',refreshWhenVisible);
  document.addEventListener('visibilitychange',refreshWhenVisible);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
</script>`;