export const REWARDS_SECTION = `<section id="rewards" class="view rewards-view">
  <style>
    #rewards{overflow-y:auto!important;overflow-x:hidden!important;padding:0 3px 120px!important;-webkit-overflow-scrolling:touch;scrollbar-width:none;box-sizing:border-box!important}
    #rewards::-webkit-scrollbar{display:none}
    #rewards .rewards-home-intro-card{--rewards-intro-bg:url('/app/api/home-intro-image.png');width:100%!important;min-height:0!important;display:block!important;position:relative!important;padding:0!important;overflow:visible!important;box-sizing:border-box!important;background:transparent!important;background-image:none!important;border-radius:0!important;margin:8px 0 12px!important;aspect-ratio:var(--rewards-intro-aspect,12/5)!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;isolation:isolate!important}
    #rewards .rewards-home-intro-card:before{content:""!important;position:absolute!important;z-index:0!important;inset:-22px!important;border-radius:46px!important;background-image:linear-gradient(rgba(0,0,0,.50),rgba(0,0,0,.50)),var(--rewards-intro-bg)!important;background-size:100% 100%!important;background-position:center!important;background-repeat:no-repeat!important;filter:blur(30px) saturate(.82)!important;transform:scale(1.08)!important;opacity:.78!important;pointer-events:none!important;-webkit-mask-image:radial-gradient(ellipse at center,#000 0 48%,rgba(0,0,0,.70) 62%,rgba(0,0,0,.24) 78%,transparent 100%)!important;mask-image:radial-gradient(ellipse at center,#000 0 48%,rgba(0,0,0,.70) 62%,rgba(0,0,0,.24) 78%,transparent 100%)!important}
    #rewards .rewards-home-intro-card:after{content:""!important;position:absolute!important;z-index:0!important;inset:-38px!important;border-radius:62px!important;background:radial-gradient(ellipse at center,rgba(0,0,0,.28) 0%,rgba(0,0,0,.16) 42%,rgba(0,0,0,.06) 66%,transparent 100%)!important;filter:blur(34px)!important;opacity:.82!important;pointer-events:none!important}
    #rewards .rewards-home-intro-image-frame{position:relative!important;z-index:1!important;width:100%!important;height:100%!important;min-height:0!important;display:block!important;overflow:hidden!important;border:0!important;border-radius:30px!important;aspect-ratio:var(--rewards-intro-aspect,12/5)!important;background-image:url('/app/api/home-intro-image.png')!important;background-size:100% 100%!important;background-position:center center!important;background-repeat:no-repeat!important;box-shadow:none!important;filter:none!important;box-sizing:border-box!important}
    #rewards .rewards-live-winners{margin:0!important;display:block!important;min-height:0!important;background:transparent!important;box-shadow:none!important;overflow:visible!important}
    #rewards .home-live-winners-list{height:auto!important;max-height:none!important;min-height:0!important;display:grid!important;align-content:start!important;gap:10px!important;overflow:visible!important;overscroll-behavior:auto!important;scrollbar-width:none!important;padding:0 2px 16px!important;background:transparent!important;box-shadow:none!important}
    #rewards .home-live-winners-list::-webkit-scrollbar{display:none!important}
    #rewards .home-live-winner-card{position:relative!important;overflow:hidden!important;min-height:64px!important;border:0!important;outline:0!important;border-radius:28px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;grid-template-columns:42px minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;padding:11px 14px!important;backdrop-filter:blur(3px) saturate(1.04)!important;-webkit-backdrop-filter:blur(3px) saturate(1.04)!important}
    #rewards .home-live-winner-avatar{width:42px!important;height:42px!important;border-radius:50%!important;object-fit:cover!important;display:block!important;background:transparent!important;box-shadow:none!important}
    #rewards .home-live-winner-user{min-width:0!important;display:grid!important;gap:3px!important}
    #rewards .home-live-winner-user strong{display:block!important;color:#fff!important;font-size:13px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
    #rewards .home-live-winner-user span{display:block!important;color:rgba(255,255,255,.48)!important;font-size:10px!important;font-weight:750!important}
    #rewards .home-live-winner-amount{color:#fff!important;font-size:13px!important;font-weight:950!important;white-space:nowrap!important}
    #rewards .home-live-winner-card .vexa-premium-corner,#rewards .home-live-winner-card .vexa-bonus-premium,#rewards .home-live-winner-card .vexa-premium-star,#rewards .home-live-winner-card .vexa-bonus-star{display:none!important;content:none!important}

    @keyframes rewardsHeroFloat{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(0,-8px,0)}}
    @media(prefers-reduced-motion:reduce){#rewards .rewards-hero-image-wrap{animation:none}}
    @media(max-width:380px){#rewards{padding-left:3px!important;padding-right:3px!important}#rewards .rewards-home-intro-card{margin-top:8px!important;min-height:0!important}#rewards .rewards-home-intro-image-frame{min-height:0!important}#rewards .rewards-hero-image-wrap{width:min(42vw,155px);height:clamp(58px,18vw,92px);margin-top:26px!important}#rewards .rewards-mission-list{width:100%!important;max-width:none!important;margin-top:10px!important}#rewards .rewards-mission-card{min-height:110px!important;border-radius:22px!important;padding:10px!important}#rewards .rewards-mission-info{font-size:11px!important;height:30px!important}}
  </style>
  <div class="rewards-home-intro-card" aria-hidden="true"><div class="rewards-home-intro-image-frame"></div></div>
  <section class="rewards-live-winners" aria-label="Live Winners">
    <div class="home-live-winners-list">
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@NikaWin</strong><span>Level 8</span></div><div class="home-live-winner-amount">+1.25 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ParsaFlow</strong><span>Level 9</span></div><div class="home-live-winner-amount">+0.84 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MinaLucky</strong><span>Level 10</span></div><div class="home-live-winner-amount">+0.47 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ArianTon</strong><span>Level 11</span></div><div class="home-live-winner-amount">+2.10 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@SabaPlay</strong><span>Level 12</span></div><div class="home-live-winner-amount">+0.66 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@RezaMax</strong><span>Level 13</span></div><div class="home-live-winner-amount">+1.72 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@LunaSpin</strong><span>Level 14</span></div><div class="home-live-winner-amount">+0.93 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@KianStar</strong><span>Level 15</span></div><div class="home-live-winner-amount">+1.38 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@TaraTON</strong><span>Level 16</span></div><div class="home-live-winner-amount">+0.52 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@OmidJet</strong><span>Level 17</span></div><div class="home-live-winner-amount">+2.44 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@NoraWin</strong><span>Level 18</span></div><div class="home-live-winner-amount">+0.79 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ArmanX</strong><span>Level 19</span></div><div class="home-live-winner-amount">+1.06 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@DinaLuck</strong><span>Level 20</span></div><div class="home-live-winner-amount">+0.31 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@YaraBet</strong><span>Level 21</span></div><div class="home-live-winner-amount">+1.89 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@NavidGo</strong><span>Level 22</span></div><div class="home-live-winner-amount">+0.58 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@SaraMoon</strong><span>Level 23</span></div><div class="home-live-winner-amount">+2.75 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@RayanPay</strong><span>Level 24</span></div><div class="home-live-winner-amount">+0.64 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MahanUp</strong><span>Level 25</span></div><div class="home-live-winner-amount">+1.21 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@LiliFox</strong><span>Level 26</span></div><div class="home-live-winner-amount">+0.97 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@PouyaMax</strong><span>Level 27</span></div><div class="home-live-winner-amount">+0.43 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@Shayan7</strong><span>Level 28</span></div><div class="home-live-winner-amount">+1.57 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@AvaGold</strong><span>Level 29</span></div><div class="home-live-winner-amount">+0.88 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@TinaWin</strong><span>Level 30</span></div><div class="home-live-winner-amount">+2.03 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@KasraTon</strong><span>Level 31</span></div><div class="home-live-winner-amount">+0.69 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MitraPlay</strong><span>Level 32</span></div><div class="home-live-winner-amount">+1.34 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@RahaLuck</strong><span>Level 33</span></div><div class="home-live-winner-amount">+0.56 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@SinaFlow</strong><span>Level 34</span></div><div class="home-live-winner-amount">+2.18 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@NeginBet</strong><span>Level 35</span></div><div class="home-live-winner-amount">+0.74 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@AmirJet</strong><span>Level 36</span></div><div class="home-live-winner-amount">+1.11 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@HanaMoon</strong><span>Level 37</span></div><div class="home-live-winner-amount">+0.49 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MehradX</strong><span>Level 38</span></div><div class="home-live-winner-amount">+1.68 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@Setareh</strong><span>Level 39</span></div><div class="home-live-winner-amount">+0.91 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@BaranWin</strong><span>Level 40</span></div><div class="home-live-winner-amount">+0.37 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@NimaTon</strong><span>Level 41</span></div><div class="home-live-winner-amount">+2.62 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ElinaPay</strong><span>Level 42</span></div><div class="home-live-winner-amount">+0.82 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@DarioBet</strong><span>Level 43</span></div><div class="home-live-winner-amount">+1.46 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ZaraLuck</strong><span>Level 44</span></div><div class="home-live-winner-amount">+0.53 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@RoxanaX</strong><span>Level 45</span></div><div class="home-live-winner-amount">+1.95 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@Kourosh</strong><span>Level 46</span></div><div class="home-live-winner-amount">+0.71 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MonaStar</strong><span>Level 47</span></div><div class="home-live-winner-amount">+1.28 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@AriaMoon</strong><span>Level 48</span></div><div class="home-live-winner-amount">+0.45 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@TahaWin</strong><span>Level 49</span></div><div class="home-live-winner-amount">+2.31 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@HeliaTon</strong><span>Level 50</span></div><div class="home-live-winner-amount">+0.86 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@SamBet</strong><span>Level 51</span></div><div class="home-live-winner-amount">+1.03 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@LeilaGo</strong><span>Level 52</span></div><div class="home-live-winner-amount">+0.62 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@BardiaX</strong><span>Level 53</span></div><div class="home-live-winner-amount">+1.77 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@AnisaPay</strong><span>Level 54</span></div><div class="home-live-winner-amount">+0.94 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/TelegramTips.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@ParsaJet</strong><span>Level 55</span></div><div class="home-live-winner-amount">+0.39 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/telegram.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@MahsaWin</strong><span>Level 56</span></div><div class="home-live-winner-amount">+2.06 TON</div></article>
      <article class="home-live-winner-card"><img class="home-live-winner-avatar" src="https://t.me/i/userpic/320/durov.jpg" alt="" decoding="async"/><div class="home-live-winner-user"><strong>@RadinTon</strong><span>Level 57</span></div><div class="home-live-winner-amount">+0.67 TON</div></article>
    </div>
  </section>
</section>`;
