export const REWARDS_SECTION = `<section id="rewards" class="view rewards-view">
  <style>
    html:has(#rewards.active),body:has(#rewards.active){background:#000!important;background-color:#000!important;background-image:none!important}
    body:has(#rewards.active):before,body:has(#rewards.active):after,body:has(#rewards.active) .app:before,body:has(#rewards.active) .app:after{display:none!important;content:none!important;background:none!important;background-image:none!important}
    body:has(#rewards.active) .app,body:has(#rewards.active) main.app,body:has(#rewards.active) .content,body:has(#rewards.active) .view.active,body:has(#rewards.active) .top,body:has(#rewards.active) header.top{background:#000!important;background-color:#000!important;background-image:none!important}
    body:has(#rewards.active) .content:before,body:has(#rewards.active) .content:after,body:has(#rewards.active) #rewards:before,body:has(#rewards.active) #rewards:after{display:none!important;content:none!important;background:none!important;background-image:none!important}
    #rewards{overflow-y:auto!important;overflow-x:hidden!important;padding:0 0 120px!important;-webkit-overflow-scrolling:touch;scrollbar-width:none;box-sizing:border-box!important;background:#000!important;background-color:#000!important;background-image:none!important}
    #rewards::-webkit-scrollbar{display:none}
    #rewards .rewards-home-intro-card{--rewards-intro-bg:url('/app/api/home-intro-image.png');width:97%!important;max-width:430px!important;min-height:0!important;display:block!important;position:relative!important;left:48%!important;transform:translateX(-50%)!important;padding:0!important;overflow:visible!important;box-sizing:border-box!important;background:transparent!important;background-image:none!important;border:0!important;border-radius:0!important;margin:0 0 14px!important;aspect-ratio:var(--rewards-intro-aspect,12/5)!important;box-shadow:none!important;filter:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;isolation:isolate!important}
    #rewards .rewards-home-intro-card:before{display:none!important;content:none!important}
    #rewards .rewards-home-intro-card:after{display:none!important;content:none!important}
    #rewards .rewards-home-intro-image-frame{position:relative!important;z-index:1!important;width:100%!important;height:100%!important;min-height:0!important;display:block!important;overflow:visible!important;border:0!important;border-radius:0!important;aspect-ratio:var(--rewards-intro-aspect,12/5)!important;background:transparent url('/app/api/home-intro-image.png') center center/100% 100% no-repeat!important;box-shadow:none!important;filter:none!important;box-sizing:border-box!important}
    :is(#rewards,#home[data-home-variant="one"]) .rewards-live-winners{margin:0!important;display:block!important;min-height:0!important;background:transparent!important;box-shadow:none!important;overflow:visible!important}
    :is(#rewards,#home[data-home-variant="one"]) .rewards-winners-state-title{margin:0 8px 10px!important;color:rgba(255,255,255,.72)!important;font-size:13px!important;font-weight:850!important;line-height:1.2!important;letter-spacing:-.01em!important;transition:opacity .16s ease,transform .16s ease!important}:is(#rewards,#home[data-home-variant="one"]).rewards-winners-scrolled .rewards-winners-state-title{opacity:0!important;transform:translateY(-5px)!important;pointer-events:none!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winners-list{height:auto!important;max-height:none!important;min-height:0!important;display:grid!important;align-content:start!important;gap:10px!important;overflow:visible!important;overscroll-behavior:auto!important;scrollbar-width:none!important;padding:0 2px 16px!important;background:transparent!important;box-shadow:none!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winners-list::-webkit-scrollbar{display:none!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-card{position:relative!important;overflow:hidden!important;min-height:64px!important;border:0!important;outline:0!important;border-radius:28px!important;background:transparent!important;background-color:transparent!important;background-image:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;grid-template-columns:42px minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;padding:11px 14px!important;backdrop-filter:blur(3px) saturate(1.04)!important;-webkit-backdrop-filter:blur(3px) saturate(1.04)!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-avatar{width:42px!important;height:42px!important;border-radius:50%!important;object-fit:cover!important;display:block!important;background:transparent!important;box-shadow:none!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-user{min-width:0!important;display:grid!important;gap:3px!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-user strong{display:block!important;color:#fff!important;font-size:13px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-user span{display:block!important;color:rgba(255,255,255,.48)!important;font-size:10px!important;font-weight:750!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-amount{color:#fff!important;font-size:13px!important;font-weight:950!important;white-space:nowrap!important}
    :is(#rewards,#home[data-home-variant="one"]) .home-live-winner-card .vexa-premium-corner,:is(#rewards,#home[data-home-variant="one"]) .home-live-winner-card .vexa-bonus-premium,:is(#rewards,#home[data-home-variant="one"]) .home-live-winner-card .vexa-premium-star,:is(#rewards,#home[data-home-variant="one"]) .home-live-winner-card .vexa-bonus-star{display:none!important;content:none!important}
    @keyframes rewardsHeroFloat{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(0,-8px,0)}}
    @media(prefers-reduced-motion:reduce){#rewards .rewards-hero-image-wrap{animation:none}}
    @media(max-width:380px){#rewards{padding-left:3px!important;padding-right:3px!important}#rewards .rewards-home-intro-card{margin-top:8px!important;min-height:0!important}#rewards .rewards-home-intro-image-frame{min-height:0!important}#rewards .rewards-hero-image-wrap{width:min(42vw,155px);height:clamp(58px,18vw,92px);margin-top:26px!important}}
  </style>
  <div class="rewards-home-intro-card" aria-hidden="true"><div class="rewards-home-intro-image-frame"></div></div>
  <section class="rewards-live-winners" aria-label="Lottery Winners">
    <div class="rewards-winners-state-title" id="lotteryRewardsStateTitle">Waiting for Winner</div>
    <div class="home-live-winners-list" id="lotteryRewardsWinnersList"></div>
  </section>
</section>`;