export const REWARDS_LIVE_WINNERS_EFFECTS = `
<style id="vexa-rewards-live-winners-effects">
#home[data-home-variant="one"] .home-winners-host>.home-live-activity{display:none!important}
#home[data-home-variant="one"] .home-winners-host>.rewards-live-winners{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;min-height:0!important;margin:0!important;padding:0!important;display:block!important;overflow:hidden!important;background:transparent!important;box-shadow:none!important}
#home[data-home-variant="one"] .home-winners-host .rewards-winners-state-title{display:none!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winners-list{position:relative!important;display:grid!important;grid-auto-rows:32px!important;align-content:start!important;gap:6px!important;min-height:0!important;height:100%!important;overflow-y:auto!important;overflow-x:hidden!important;padding:0 2px!important;box-sizing:border-box!important;background:transparent!important;box-shadow:none!important;scrollbar-width:none!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;touch-action:pan-y!important;mask-image:none!important;-webkit-mask-image:none!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winners-list::-webkit-scrollbar{display:none!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winners-list.has-overflow:not(.is-scrolled){mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 10px),transparent 100%)!important;-webkit-mask-image:linear-gradient(to bottom,#000 0,#000 calc(100% - 10px),transparent 100%)!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winners-list.has-overflow.is-scrolled:not(.is-at-bottom){mask-image:linear-gradient(to bottom,transparent 0,#000 10px,#000 calc(100% - 10px),transparent 100%)!important;-webkit-mask-image:linear-gradient(to bottom,transparent 0,#000 10px,#000 calc(100% - 10px),transparent 100%)!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winners-list.has-overflow.is-at-bottom{mask-image:linear-gradient(to bottom,transparent 0,#000 10px,#000 100%)!important;-webkit-mask-image:linear-gradient(to bottom,transparent 0,#000 10px,#000 100%)!important}

/* Same row styling as the original Live Activity card. */
#home[data-home-variant="one"] .home-winners-host .home-live-winner-card{position:relative!important;overflow:hidden!important;height:32px!important;min-height:32px!important;border:0!important;outline:0!important;border-radius:28px!important;background:radial-gradient(34px 34px at 0 0,rgba(186,53,87,.16) 0%,rgba(146,35,66,.07) 42%,rgba(104,18,44,0) 76%),radial-gradient(36px 36px at 100% 100%,rgba(172,46,79,.15) 0%,rgba(133,30,60,.065) 43%,rgba(94,16,39,0) 78%),radial-gradient(118% 76% at 10% -16%,rgba(255,255,255,.12) 0%,rgba(255,255,255,.032) 30%,rgba(255,255,255,0) 58%),radial-gradient(96% 72% at 102% 108%,rgba(255,255,255,.052) 0%,rgba(255,255,255,.010) 34%,rgba(255,255,255,0) 62%),radial-gradient(92% 78% at 88% 112%,rgba(72,5,27,.11) 0%,rgba(42,3,16,0) 60%)!important;box-shadow:0 12px 30px rgba(31,1,10,.32),0 0 18px rgba(69,5,26,.15),inset 3px 3px .5px -3.5px rgba(255,255,255,.10),inset -3px -3px .5px -3.5px rgba(156,38,70,.48),inset 1px 1px 1px -.5px rgba(140,29,61,.30),inset -1px -1px 1px -.5px rgba(124,22,53,.24),inset 0 0 6px 6px rgba(255,255,255,.055),inset 0 0 2px 2px rgba(255,255,255,.035),inset 0 1px 0 rgba(112,18,49,.065),inset 0 -1px 0 rgba(88,12,37,.15)!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:8px!important;padding:0 10px!important;box-sizing:border-box!important;backdrop-filter:blur(22px) saturate(1.40) brightness(1.05) contrast(1.04)!important;-webkit-backdrop-filter:blur(22px) saturate(1.40) brightness(1.05) contrast(1.04)!important;isolation:isolate!important;opacity:1!important;transform:none!important;filter:none!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-avatar,#home[data-home-variant="one"] .home-winners-host .rewards-winner-avatar-fallback{display:none!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-user{min-width:0!important;display:flex!important;align-items:center!important;gap:5px!important;overflow:hidden!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-user strong{flex:0 1 auto!important;min-width:0!important;max-width:46%!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;color:#fff!important;font-size:9.5px!important;font-weight:900!important;line-height:1.08!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-user span{flex:1 1 auto!important;min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;color:rgba(255,255,255,.48)!important;font-size:8px!important;font-weight:750!important;line-height:1.08!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-amount{align-self:center!important;color:rgba(255,255,255,.34)!important;font-size:7.5px!important;font-weight:800!important;white-space:nowrap!important;margin-left:2px!important}
#home[data-home-variant="one"] .home-winners-host .home-live-winner-card:after{display:none!important;content:none!important}
</style>
<script id="vexa-rewards-live-winners-scroll-script">
(function(){
  var loading=false,lastRequestAt=0,phaseTimer=0,retryTimer=0,retryDelay=1000;
  function q(s,r){return (r||document).querySelector(s)}
  function homeOne(){var home=document.getElementById('home');return home&&home.getAttribute('data-home-variant')==='one'?home:null}
  function host(){var home=homeOne();return home?q('.home-ticket-finance-visual',home):null}
  function initData(){var tg=window.Telegram&&window.Telegram.WebApp;return String(tg&&tg.initData||'')}
  function gram(nano){var value=Math.max(0,Number(nano)||0)/1000000000;return value.toFixed(2).replace(/\\.00$/,'').replace(/(\\.\\d)0$/,'$1')}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return ch==='&'?'&amp;':ch==='<'?'&lt;':ch==='>'?'&gt;':ch==='"'?'&quot;':'&#39;'})}
  function winnerMap(winners){var map={};(Array.isArray(winners)?winners:[]).forEach(function(item){var rank=Math.floor(Number(item&&item.rank)||0);if(rank>=1&&rank<=15)map[rank]=item});return map}
  function maskedName(item){var username=String(item&&item.username||'').replace(/^@+/,'').trim();if(!username)return esc(item&&item.displayName||'Player');if(username.length===1)return '@'+esc(username);if(username.length===2)return '@'+esc(username.charAt(0)+'*');if(username.length<=4)return '@'+esc(username.charAt(0)+'**'+username.charAt(username.length-1));return '@'+esc(username.slice(0,2)+'***'+username.slice(-2))}
  function row(rank,item,waiting){var rankText=String(rank).padStart(2,'0');if(waiting)return '<article class="home-live-winner-card"><div class="home-live-winner-user"><strong>Waiting for draw</strong><span>Rank #'+rankText+'</span></div><div class="home-live-winner-amount">—</div></article>';if(!item)return '<article class="home-live-winner-card"><div class="home-live-winner-user"><strong>No result this round</strong><span>Rank #'+rankText+'</span></div><div class="home-live-winner-amount">—</div></article>';var level=Math.max(1,Math.floor(Number(item.level)||1));return '<article class="home-live-winner-card"><div class="home-live-winner-user"><strong>'+maskedName(item)+'</strong><span>Level '+level+'</span></div><div class="home-live-winner-amount">+'+gram(item.prizeNano)+' GRAM</div></article>'}
  function updateFade(list){if(!list)return;var max=Math.max(0,list.scrollHeight-list.clientHeight),overflow=max>2;list.classList.toggle('has-overflow',overflow);list.classList.toggle('is-scrolled',overflow&&list.scrollTop>2);list.classList.toggle('is-at-bottom',overflow&&list.scrollTop>=max-2)}
  function ensureLocation(){var home=homeOne(),card=host(),section=q('.rewards-live-winners');if(!home||!card||!section)return null;if(section.parentNode!==card)card.appendChild(section);card.classList.add('home-ticket-card','home-winners-host');card.removeAttribute('role');card.removeAttribute('tabindex');card.removeAttribute('aria-label');var list=q('#lotteryRewardsWinnersList',section);if(list&&list.dataset.winnersScrollBound!=='1'){list.dataset.winnersScrollBound='1';list.addEventListener('scroll',function(){updateFade(list)},{passive:true})}return section}
  function render(winners,waiting){var section=ensureLocation(),list=section&&q('#lotteryRewardsWinnersList',section);if(!list)return;var map=winnerMap(winners),html='';for(var rank=1;rank<=15;rank++)html+=row(rank,map[rank],!!waiting);list.innerHTML=html;requestAnimationFrame(function(){updateFade(list)})}
  function clearRetry(){if(retryTimer){clearTimeout(retryTimer);retryTimer=0}}
  function scheduleRetry(){var home=homeOne();if(retryTimer||!home||!home.classList.contains('active')||document.hidden)return;var delay=retryDelay;retryDelay=Math.min(15000,Math.round(retryDelay*1.8));retryTimer=setTimeout(function(){retryTimer=0;load(true)},delay)}
  function schedulePhaseRefresh(payload){if(phaseTimer){clearTimeout(phaseTimer);phaseTimer=0}var next=Number(payload&&payload.nextDisplayChangeAtMs),serverNow=Number(payload&&payload.serverNowMs);if(!Number.isFinite(next)||!Number.isFinite(serverNow)||next<=serverNow)return;phaseTimer=setTimeout(function(){phaseTimer=0;load(true)},Math.max(80,next-serverNow+80))}
  async function load(force){var home=homeOne(),section=ensureLocation(),data=initData();if(!home||!home.classList.contains('active')||!section||!data||loading)return false;var now=Date.now();if(!force&&now-lastRequestAt<500)return false;loading=true;lastRequestAt=now;try{var response=await fetch('/app/api/lottery/winners',{cache:'no-store',headers:{'accept':'application/json','x-telegram-init-data':data}});var payload=await response.json().catch(function(){return null});if(!response.ok||!payload)throw new Error('Could not load lottery results');clearRetry();retryDelay=1000;render(payload.winners||[],!!payload.waitingForWinner);schedulePhaseRefresh(payload);return true}catch(e){scheduleRetry();return false}finally{loading=false}}
  function bind(){var home=homeOne(),section=ensureLocation();if(!home||!section)return;var list=q('#lotteryRewardsWinnersList',section);updateFade(list);if(home.classList.contains('active'))load(false)}
  function refreshWhenVisible(){var home=homeOne();if(!document.hidden&&home&&home.classList.contains('active'))load(false)}
  document.addEventListener('click',function(ev){var target=ev.target&&ev.target.closest&&ev.target.closest('[data-view="home"]');if(target)setTimeout(bind,60)},true);
  window.addEventListener('vexa:section-mounted',bind);
  window.addEventListener('resize',function(){var section=ensureLocation();updateFade(section&&q('#lotteryRewardsWinnersList',section))},{passive:true});
  window.addEventListener('focus',refreshWhenVisible);
  document.addEventListener('visibilitychange',refreshWhenVisible);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
</script>`;
