export const RPS_SECTION = `
<section id="rps" class="view rps-view">
  <style>
    html:has(#rps.active),body:has(#rps.active){background:#000!important;background-color:#000!important;background-image:none!important}
    body:has(#rps.active)::before,body:has(#rps.active)::after,body:has(#rps.active) .app::before,body:has(#rps.active) .app::after{content:none!important;display:none!important;background:none!important;box-shadow:none!important}
    body:has(#rps.active) .tabs{display:none!important}
    body:has(#rps.active) .app,body:has(#rps.active) main.app,body:has(#rps.active) .content,body:has(#rps.active) .view.active,body:has(#rps.active) #rps,body:has(#rps.active) .rps-view,body:has(#rps.active) .top,body:has(#rps.active) header.top{background:#000!important;background-color:#000!important;background-image:none!important;box-shadow:none!important}
    .rps-view{min-height:100%;padding:4px 14px calc(104px + env(safe-area-inset-bottom));color:#fff;background:#000!important;overflow-y:auto!important;overflow-x:hidden;-webkit-overflow-scrolling:touch;box-sizing:border-box;scrollbar-width:none}
    .rps-view::-webkit-scrollbar{display:none}
    .rps-wrap{width:100%;max-width:560px;margin:0 auto;display:grid;gap:10px}
    .rps-title{display:none!important}
    .rps-multipliers{display:flex;gap:8px;overflow-x:auto;overflow-y:hidden;margin:2px -14px 8px;padding:2px 14px 10px;scrollbar-width:none;-webkit-overflow-scrolling:touch;scroll-snap-type:x proximity}
    .rps-multipliers::-webkit-scrollbar{display:none}
    .rps-multiplier{flex:0 0 auto;height:34px;min-width:58px;padding:0 12px;border:0;border-radius:999px;display:grid;place-items:center;color:rgba(255,255,255,.58);font-size:12px;font-weight:950;letter-spacing:-.025em;background:rgba(255,255,255,.035);box-shadow:inset 0 1px 0 rgba(255,255,255,.10),0 10px 24px rgba(0,0,0,.22);-webkit-backdrop-filter:blur(8px) saturate(130%);backdrop-filter:blur(8px) saturate(130%);scroll-snap-align:center;transition:transform .32s cubic-bezier(.2,.9,.18,1),background .22s ease,color .22s ease,box-shadow .22s ease,filter .32s ease}
    .rps-multiplier.is-active{color:#fff;background:linear-gradient(180deg,rgba(255,255,255,.11),rgba(255,255,255,.035));box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 12px 28px rgba(0,0,0,.30);transform:scale(1.04)}
    .rps-multiplier.rps-win{color:rgba(220,255,232,.96);background:linear-gradient(180deg,rgba(8,86,42,.58),rgba(2,32,17,.72));box-shadow:inset 0 1px 0 rgba(149,255,187,.16),0 0 18px rgba(8,92,43,.26),0 12px 28px rgba(0,0,0,.36);transition:transform .2s cubic-bezier(.18,.86,.2,1),background .08s ease,color .08s ease,box-shadow .08s ease,filter .2s ease;animation:rpsMultiplierWin .72s cubic-bezier(.18,.86,.2,1) both}
    .rps-multiplier.rps-loss{color:rgba(255,218,226,.94);background:linear-gradient(180deg,rgba(85,5,28,.64),rgba(31,1,12,.82));box-shadow:inset 0 1px 0 rgba(255,124,151,.14),0 0 18px rgba(92,5,30,.28),0 12px 28px rgba(0,0,0,.38);transition:transform .2s cubic-bezier(.18,.86,.2,1),background .08s ease,color .08s ease,box-shadow .08s ease,filter .2s ease;animation:rpsMultiplierLoss .72s cubic-bezier(.18,.86,.2,1) both}
    .rps-arena{position:relative;min-height:476px;display:grid;grid-template-rows:auto auto auto auto;border:0!important;border-radius:0;background:transparent!important;box-shadow:none!important;overflow:visible!important;padding:4px 0 0}
    .rps-duel{display:grid;grid-template-columns:1fr 64px 1fr;align-items:center;gap:12px;margin:24px 0 14px}
    .rps-hand-card{height:168px;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;display:grid;grid-template-rows:128px 18px;place-items:center;gap:6px;overflow:visible!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}
    .rps-hand-img{display:block;width:116px;height:116px;object-fit:contain;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;filter:drop-shadow(0 18px 28px rgba(0,0,0,.46));pointer-events:none;opacity:0;--rps-hand-angle:90deg;--rps-hand-drop-start:-90deg;--rps-hand-drop-overshoot:5deg;transform:rotate(var(--rps-hand-angle));transform-origin:center;transition:opacity .24s ease,transform 1.15s cubic-bezier(.18,.82,.22,1);will-change:transform,opacity}
    [data-rps-bot-img]{--rps-hand-angle:-90deg;--rps-hand-drop-start:90deg;--rps-hand-drop-overshoot:-5deg}
    .rps-choice .rps-hand-img{width:58px;height:58px;filter:drop-shadow(0 10px 14px rgba(0,0,0,.32));opacity:0}
    .rps-hand-card.has-rps-image .rps-hand-img,.rps-choice.has-rps-image .rps-hand-img{opacity:1}
    .rps-hand-card small,.rps-choice span{color:rgba(255,255,255,.54);font-size:11px;font-weight:900}
    .rps-vs{width:auto!important;height:auto!important;border:0!important;background:transparent!important;box-shadow:none!important;display:grid;place-items:center;font-weight:950;color:#fff;font-size:18px;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}
    .rps-result{min-height:30px;text-align:center;font-family:Inter,-apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif;font-size:17px;font-weight:850;letter-spacing:-.025em;color:rgba(255,255,255,.92);margin-bottom:2px}
    .rps-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-top:-2px}
    .rps-choice{height:92px;border:0!important;border-radius:0!important;outline:0!important;appearance:none!important;-webkit-appearance:none!important;margin:0!important;padding:0!important;color:#fff;background:none!important;background-color:transparent!important;background-image:none!important;box-shadow:none!important;display:grid;grid-template-rows:62px 16px;place-items:center;gap:4px;font-weight:950;overflow:visible!important;transition:transform .18s cubic-bezier(.2,.9,.16,1),opacity .18s ease;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}
    .rps-choice::before,.rps-choice::after{content:none!important;display:none!important;background:none!important;box-shadow:none!important;border:0!important}
    .rps-choice:focus,.rps-choice:focus-visible{outline:0!important;box-shadow:none!important}
    .rps-choice:disabled{opacity:.48;pointer-events:none}
    .rps-choice:active{transform:scale(.96)}
    .rps-choice.is-picked{opacity:1;transform:scale(1.04)}
    .rps-choice:not(.is-picked){opacity:.72}
    .rps-panel{position:relative;display:grid;gap:10px;border:0!important;border-radius:28px;padding:14px;background:linear-gradient(180deg,rgba(255,255,255,.026),rgba(255,255,255,.012));box-shadow:0 0 0 1px rgba(62,4,19,.10),0 0 22px rgba(54,3,17,.15),0 18px 46px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.045);-webkit-backdrop-filter:blur(18px) saturate(138%);backdrop-filter:blur(18px) saturate(138%);overflow:hidden;margin-top:-2px}
    .rps-input-row{display:grid;grid-template-columns:1fr auto auto;gap:8px}
    .rps-input-row input,.rps-input-row button,.rps-stat{border:0!important;background:rgba(255,255,255,.04);box-shadow:inset 0 1px 0 rgba(255,255,255,.07),0 12px 26px rgba(0,0,0,.22);-webkit-backdrop-filter:blur(12px) saturate(135%);backdrop-filter:blur(12px) saturate(135%)}
    .rps-input-row input,.rps-input-row button{height:50px;border-radius:18px;color:#fff;font-weight:950;outline:none}
    .rps-input-row input{padding:0 14px;font-size:18px}.rps-input-row button{min-width:58px;font-size:13px}
    .rps-play{height:60px;border:0;border-radius:999px;background:linear-gradient(180deg,#2b0310,#170107);color:rgba(255,255,255,.94);font-size:18px;font-weight:950;letter-spacing:-.045em;box-shadow:0 0 0 1px rgba(95,8,30,.10),0 0 18px rgba(70,4,22,.20),0 14px 30px rgba(0,0,0,.46),inset 0 1px 0 rgba(255,255,255,.07)}
    .rps-friend-box{display:grid;gap:9px;border-radius:22px;padding:12px;background:rgba(255,255,255,.035);box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 12px 28px rgba(0,0,0,.24)}
    .rps-friend-row{display:flex;gap:8px;align-items:center}.rps-friend-row button,.rps-friend-link{height:40px;border:0;border-radius:15px;background:rgba(255,255,255,.07);color:#fff;font-size:12px;font-weight:950;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}
    .rps-friend-row button{padding:0 12px}.rps-friend-link{min-width:0;flex:1;padding:0 11px;outline:0;color:rgba(255,255,255,.78)}.rps-friend-status{min-height:17px;color:rgba(255,255,255,.66);font-size:12px;font-weight:850;letter-spacing:-.02em}.rps-friend-primary{width:100%;height:44px!important;background:linear-gradient(180deg,rgba(255,255,255,.13),rgba(255,255,255,.055))!important}.rps-view.is-friend-mode .rps-multipliers{opacity:.32}.rps-view.is-friend-mode .rps-input-row,.rps-view.is-friend-mode .rps-play,.rps-view.is-friend-mode .rps-stats{opacity:.38}
    .rps-play:disabled{opacity:.42}
    .rps-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.rps-stat{border-radius:18px;padding:10px;text-align:center}.rps-stat small{display:block;color:rgba(255,255,255,.45);font-size:10px;font-weight:850}.rps-stat b{display:block;margin-top:4px;font-size:14px}.rps-won-amount{color:rgba(58,164,82,.96)!important;text-shadow:0 0 12px rgba(13,80,32,.28)}
    .rps-hand-drop{animation:rpsHandDrop .92s cubic-bezier(.16,.86,.2,1) both}@keyframes rpsHandDrop{0%{opacity:0;transform:translateY(-74px) rotate(calc(var(--rps-hand-angle) + var(--rps-hand-drop-start))) scale(.88)}74%{opacity:1;transform:translateY(4px) rotate(calc(var(--rps-hand-angle) + var(--rps-hand-drop-overshoot))) scale(1.02)}100%{opacity:1;transform:translateY(0) rotate(var(--rps-hand-angle)) scale(1)}}
    @keyframes rpsMultiplierWin{0%{filter:saturate(1);transform:translateY(0) scale(1)}46%{filter:saturate(1.26);transform:translateY(-1px) scale(1.04)}100%{filter:saturate(1);transform:translateY(0) scale(1)}}
    @keyframes rpsMultiplierLoss{0%{filter:saturate(1);transform:translateY(0) scale(1)}46%{filter:saturate(1.22);transform:translateY(1px) scale(.99)}100%{filter:saturate(1);transform:translateY(0) scale(1)}}
    @media(max-width:380px){.rps-arena{min-height:436px}.rps-duel{margin:18px 0 12px}.rps-hand-card{height:148px;grid-template-rows:108px 18px}.rps-hand-img{width:86px;height:86px}.rps-hand-card.has-rps-image .rps-hand-img{width:104px;height:104px}.rps-choice{height:78px;grid-template-rows:54px 16px}.rps-choice .rps-hand-img{width:50px;height:50px}.rps-panel{margin-top:0}}
  </style>
  <div class="rps-wrap">
    <div class="rps-arena">
      <div class="rps-title"><strong>Rock Paper Scissors</strong></div>
      <div class="rps-multipliers" data-rps-multipliers></div>
      <div class="rps-duel">
        <div class="rps-hand-card" data-rps-player-card><img class="rps-hand-img" data-rps-player-img alt=""/><small>You</small></div>
        <div class="rps-vs">VS</div>
        <div class="rps-hand-card" data-rps-bot-card><img class="rps-hand-img" data-rps-bot-img alt=""/><small data-rps-opponent-label>Bot</small></div>
      </div>
      <div class="rps-result" data-rps-result>Pick a hand</div>
      <div class="rps-choices">
        <button class="rps-choice" type="button" data-rps-choice="rock"><img class="rps-hand-img" data-rps-choice-img="rock" alt=""/><span>Rock</span></button>
        <button class="rps-choice" type="button" data-rps-choice="paper"><img class="rps-hand-img" data-rps-choice-img="paper" alt=""/><span>Paper</span></button>
        <button class="rps-choice" type="button" data-rps-choice="scissors"><img class="rps-hand-img" data-rps-choice-img="scissors" alt=""/><span>Scissors</span></button>
      </div>
    </div>
    <div class="rps-panel">
      <div class="rps-input-row"><input data-rps-bet inputmode="decimal" pattern="[0-9.]*" value="0.1"/><button type="button" data-rps-half>1/2</button><button type="button" data-rps-double>2x</button></div>
      <button class="rps-play" type="button" data-rps-play>Cash Out</button>
      <div class="rps-stats"><div class="rps-stat"><small>WINS</small><b data-rps-wins>0</b></div><div class="rps-stat"><small>WON</small><b class="rps-won-amount" data-rps-streak>0.00</b></div><div class="rps-stat"><small>BET</small><b data-rps-bet-label>0.1</b></div></div>
      <div class="rps-friend-box" data-rps-friend-box>
        <button class="rps-friend-primary" type="button" data-rps-friend-start>Play with Friend</button>
        <div class="rps-friend-row"><input class="rps-friend-link" data-rps-friend-link readonly placeholder="Invite link appears here"/><button type="button" data-rps-friend-share>Share</button><button type="button" data-rps-friend-leave>Solo</button></div>
        <div class="rps-friend-status" data-rps-friend-status>Solo with Bot/Rival is active.</div>
      </div>
    </div>
  </div>
  <script>
    (function(){
      var root=document.getElementById('rps');if(!root||root.dataset.readyRps)return;root.dataset.readyRps='1';
      var tg=window.Telegram&&window.Telegram.WebApp;
      var beats={rock:'scissors',paper:'rock',scissors:'paper'};
      var multipliers=[1.2,1.4,1.7,2,2.5,3,4,5,7,10];
      var rpsImages={you:{rock:'/app/api/uploaded-image/rps-you-rock.png',paper:'/app/api/uploaded-image/rps-you-paper.png',scissors:'/app/api/uploaded-image/rps-you-scissors.png'},bot:{rock:'/app/api/uploaded-image/rps-bot-rock.png',paper:'/app/api/uploaded-image/rps-bot-paper.png',scissors:'/app/api/uploaded-image/rps-bot-scissors.png'}};
      var picked='rock',wins=0,streak=0,playing=false,sessionActive=false,betNano=0,currentWinNano=0,rate=1000000000,playerAngle=90,botAngle=-90;
      var friendMode=false,friendState=null,friendBusy=false,friendPoll=null,lastResultId='';
      var playerImg=root.querySelector('[data-rps-player-img]'),botImg=root.querySelector('[data-rps-bot-img]'),resultEl=root.querySelector('[data-rps-result]'),betInput=root.querySelector('[data-rps-bet]'),betLabel=root.querySelector('[data-rps-bet-label]'),winsEl=root.querySelector('[data-rps-wins]'),wonEl=root.querySelector('[data-rps-streak]'),playerCard=root.querySelector('[data-rps-player-card]'),botCard=root.querySelector('[data-rps-bot-card]'),playBtn=root.querySelector('[data-rps-play]'),halfBtn=root.querySelector('[data-rps-half]'),doubleBtn=root.querySelector('[data-rps-double]'),choices=['rock','paper','scissors'];
      var multWrap=root.querySelector('[data-rps-multipliers]'),friendStart=root.querySelector('[data-rps-friend-start]'),friendShare=root.querySelector('[data-rps-friend-share]'),friendLeave=root.querySelector('[data-rps-friend-leave]'),friendLink=root.querySelector('[data-rps-friend-link]'),friendStatus=root.querySelector('[data-rps-friend-status]'),opponentLabel=root.querySelector('[data-rps-opponent-label]');
      function imageFor(side,value){return value&&rpsImages[side]?rpsImages[side][value]||'':''}
      function tone(type){try{var A=window.AudioContext||window.webkitAudioContext;if(!A)return;var ctx=new A();var o=ctx.createOscillator();var g=ctx.createGain();o.type='sine';o.frequency.value=type==='win'?740:type==='lose'?180:420;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(type==='win'?.12:.09,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.24);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.28);setTimeout(function(){try{ctx.close()}catch(e){}},420)}catch(e){}}
      function formatTon(nano){var n=Math.max(0,Number(nano)||0)/rate;return n.toFixed(2).replace(/\.00$/,'.00')}
      function renderMultipliers(){if(!multWrap)return;multWrap.innerHTML=multipliers.map(function(m,i){return '<span class="rps-multiplier '+(i===Math.min(streak,multipliers.length-1)?'is-active':'')+'">'+m+'x</span>'}).join('');var active=multWrap.querySelector('.is-active');if(active)try{active.scrollIntoView({inline:'center',block:'nearest',behavior:'smooth'})}catch(e){}}
      function flashMultiplier(type,index){if(!multWrap)return;var cards=multWrap.querySelectorAll('.rps-multiplier');var card=cards[Math.max(0,Math.min(index,cards.length-1))];if(!card)return;card.classList.remove('rps-win','rps-loss');void card.offsetWidth;card.classList.add(type==='win'?'rps-win':'rps-loss');setTimeout(function(){card.classList.remove('rps-win','rps-loss')},860)}
      function updateStats(){winsEl.textContent=String(wins);wonEl.textContent=formatTon(currentWinNano);betLabel.textContent=betInput.value||'0.1'}
      function friendCanChoose(){if(!friendMode||friendBusy||!friendState||!friendState.room||!friendState.round)return false;if(!friendState.room.hasGuest||friendState.room.status==='finished'||friendState.room.status==='expired')return false;return friendState.round.status==='open'&&!friendState.round.yourChoice}
      function updateControls(){if(friendMode){betInput.disabled=true;if(halfBtn)halfBtn.disabled=true;if(doubleBtn)doubleBtn.disabled=true;playBtn.textContent='Friend Mode';playBtn.disabled=true;root.querySelectorAll('[data-rps-choice]').forEach(function(button){button.disabled=!friendCanChoose()});updateStats();return}var locked=sessionActive||playing;betInput.disabled=locked;if(halfBtn)halfBtn.disabled=locked;if(doubleBtn)doubleBtn.disabled=locked;root.querySelectorAll('[data-rps-choice]').forEach(function(button){button.disabled=playing});playBtn.textContent='Cash Out';playBtn.disabled=playing||!sessionActive||currentWinNano<=0;updateStats()}
      function applyUploadedRpsImages(data){if(!data)return;rpsImages.you.rock=data.rpsYouRockUrl||rpsImages.you.rock;rpsImages.you.paper=data.rpsYouPaperUrl||rpsImages.you.paper;rpsImages.you.scissors=data.rpsYouScissorsUrl||rpsImages.you.scissors;rpsImages.bot.rock=data.rpsBotRockUrl||rpsImages.bot.rock;rpsImages.bot.paper=data.rpsBotPaperUrl||rpsImages.bot.paper;rpsImages.bot.scissors=data.rpsBotScissorsUrl||rpsImages.bot.scissors}
      function replayDrop(target){if(!target)return;target.classList.remove('rps-hand-drop');void target.offsetWidth;target.classList.add('rps-hand-drop')}
      function setHandAngle(image,angle){if(image)image.style.setProperty('--rps-hand-angle',angle+'deg')}
      function bindImage(container,image,url){if(!container||!image)return false;image.decoding='async';image.loading='eager';image.onload=function(){container.classList.add('has-rps-image')};image.onerror=function(){image.removeAttribute('src');container.classList.remove('has-rps-image')};if(url&&image.getAttribute('src')!==url)image.src=url;else if(url)container.classList.add('has-rps-image');return !!url}
      function setCardImage(card,image,side,value,animate){setHandAngle(image,side==='bot'?botAngle:playerAngle);var hasImage=bindImage(card,image,imageFor(side,value));if(animate&&hasImage)replayDrop(image)}
      function paintChoiceImages(){root.querySelectorAll('[data-rps-choice-img]').forEach(function(img){var kind=img.getAttribute('data-rps-choice-img')||'';bindImage(img.closest('[data-rps-choice]'),img,imageFor('you',kind))})}
      function refreshRpsImages(){paintChoiceImages();setCardImage(playerCard,playerImg,'you',picked,false)}
      function betValue(){var next=Math.max(.1,Number(String(betInput.value||'0.1').replace(',','.'))||.1);next=Math.round(next*100)/100;return next}
      function setBet(value){var next=Math.max(.1,Number(value)||.1);next=Math.round(next*100)/100;betInput.value=String(next).replace(/\.0$/,'');betLabel.textContent=betInput.value}
      function setPick(value,animate){picked=value;setCardImage(playerCard,playerImg,'you',value,animate!==false);root.querySelectorAll('[data-rps-choice]').forEach(function(button){button.classList.toggle('is-picked',button.getAttribute('data-rps-choice')===value)})}
      function user(){var u=(tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user)||{};var id=String(u.id||localStorage.getItem('ownerId')||'').replace(/[^0-9A-Za-z_-]/g,'').slice(0,80);if(!id){id=localStorage.getItem('rpsFriendUserId')||('local_'+Math.random().toString(36).slice(2)+Date.now().toString(36));localStorage.setItem('rpsFriendUserId',id)}var name=String(u.first_name||u.username||localStorage.getItem('ownerName')||'Player').replace(/[<>]/g,'').slice(0,80);return{id:id,name:name||'Player'}}
      function api(path,opt){return fetch(path,Object.assign({credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json'}},opt||{})).then(function(r){return r.json().catch(function(){return{error:'Invalid response'}}).then(function(j){if(!r.ok)throw new Error(j.error||'Request failed');return j})})}
      function sanitizeRoomId(roomId){return String(roomId||'').replace(/[^0-9A-Za-z_-]/g,'').slice(0,80)}
      function inviteUrl(roomId){var url=new URL(location.href);url.searchParams.set('rpsRoom',sanitizeRoomId(roomId));url.searchParams.delete('open');return url.toString()}
      function setFriendMessage(v){if(friendStatus)friendStatus.textContent=v;resultEl.textContent=v}
      function enterFriendMode(state){friendMode=true;friendState=state||friendState;root.classList.add('is-friend-mode');if(opponentLabel)opponentLabel.textContent='Friend';if(friendStart)friendStart.textContent='Create New Friend Room';if(botImg)botImg.removeAttribute('src');if(botCard)botCard.classList.remove('has-rps-image');startPolling();renderFriendState(state)}
      function leaveFriendMode(){friendMode=false;friendState=null;friendBusy=false;lastResultId='';root.classList.remove('is-friend-mode');if(opponentLabel)opponentLabel.textContent='Bot';if(friendStart)friendStart.textContent='Play with Friend';if(friendStatus)friendStatus.textContent='Solo with Bot/Rival is active.';if(friendLink)friendLink.value='';stopPolling();setPick('rock',false);resultEl.textContent='Pick a hand';updateControls()}
      function renderFriendState(state){if(!state||!state.room){updateControls();return}friendState=state;var room=state.room,round=state.round||{};if(friendLink)friendLink.value=inviteUrl(room.id);if(opponentLabel)opponentLabel.textContent=room.guestName||'Friend';if(round.yourChoice)setPick(round.yourChoice,false);else setPick(picked||'rock',false);if(round.opponentChoice)setCardImage(botCard,botImg,'bot',round.opponentChoice,true);else{if(botImg)botImg.removeAttribute('src');if(botCard)botCard.classList.remove('has-rps-image')}var msg='Waiting for your choice';if(room.status==='waiting'||!room.hasGuest)msg='Waiting for friend';else if(room.status==='expired')msg='Room expired';else if(room.status==='finished'){var won=round.winnerRole===state.player.role;msg=won?'You won':'Friend won';tone(won?'win':'lose')}else if(state.lastResult&&state.lastResult.id!==lastResultId){lastResultId=state.lastResult.id;if(state.lastResult.isDraw){msg='Draw';tone('draw')}else{var youWon=state.lastResult.winnerRole===state.player.role;msg=youWon?'You won':'Friend won';tone(youWon?'win':'lose')}}else if(room.hasGuest&&!round.yourChoice&&!round.hostPicked&&!round.guestPicked)msg='Friend joined — Waiting for your choice';else if(round.yourChoice&&!round.opponentChoice)msg='Waiting for friend choice';else if(!round.yourChoice)msg='Waiting for your choice';else msg='Friend joined';setFriendMessage(msg);updateControls()}
      function syncFriend(){if(!friendMode||!friendState||!friendState.room||!root.classList.contains('active'))return Promise.resolve();var u=user();return api('/app/api/rps/friend/rooms/'+encodeURIComponent(friendState.room.id)+'?userId='+encodeURIComponent(u.id)).then(renderFriendState).catch(function(e){if(friendStatus)friendStatus.textContent=e.message||'Sync failed'})}
      function startPolling(){stopPolling();friendPoll=setInterval(syncFriend,1000)}
      function stopPolling(){if(friendPoll){clearInterval(friendPoll);friendPoll=null}}
      function createFriendRoom(){if(friendBusy)return;friendBusy=true;setFriendMessage('Creating friend room...');var u=user();api('/app/api/rps/friend/rooms',{method:'POST',body:JSON.stringify({userId:u.id,name:u.name})}).then(function(state){enterFriendMode(state);shareInvite()}).catch(function(e){setFriendMessage(e.message||'Could not create room')}).finally(function(){friendBusy=false;updateControls()})}
      function joinFriendRoom(roomId){if(friendBusy||!roomId)return;friendBusy=true;setFriendMessage('Joining friend room...');var u=user();api('/app/api/rps/friend/rooms/'+encodeURIComponent(roomId)+'/join',{method:'POST',body:JSON.stringify({userId:u.id,name:u.name})}).then(enterFriendMode).catch(function(e){setFriendMessage(e.message||'Could not join room')}).finally(function(){friendBusy=false;updateControls()})}
      function friendChoice(value){if(!friendCanChoose())return;friendBusy=true;setPick(value,true);setFriendMessage('Waiting for friend choice');var u=user();api('/app/api/rps/friend/rooms/'+encodeURIComponent(friendState.room.id)+'/choice',{method:'POST',body:JSON.stringify({userId:u.id,name:u.name,choice:value})}).then(renderFriendState).catch(function(e){setFriendMessage(e.message||'Could not save choice')}).finally(function(){friendBusy=false;updateControls()})}
      function shareInvite(){if(!friendState||!friendState.room)return;var roomId=sanitizeRoomId(friendState.room.id);if(!roomId)return;var link=inviteUrl(roomId);var entry='https://t.me/VexaAppBOT?startapp='+encodeURIComponent('rpsRoom_'+roomId);if(friendLink)friendLink.value=link;var text='🎮 چالش سنگ، کاغذ، قیچی آماده‌ست!\n\nیه دوئل سریع و باحال منتظرته 😎✨\nانتخابتو بزن و ببین کی برنده می‌شه 🪨📄✂️\n\n👇 از دکمه پایین وارد مینی‌اپ شو';var share='https://t.me/share/url?url='+encodeURIComponent(entry)+'&text='+encodeURIComponent(text);try{if(tg&&typeof tg.openTelegramLink==='function'){tg.openTelegramLink(share);return}}catch(e){}try{if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(entry);setFriendMessage('Invite link copied');return}}catch(e){}if(friendLink){friendLink.value=entry;friendLink.select();document.execCommand&&document.execCommand('copy');setFriendMessage('Invite link copied')}}
      function showRpsFromInvite(){document.querySelectorAll('.view').forEach(function(n){n.classList.remove('active')});root.classList.add('active');document.querySelectorAll('.tab').forEach(function(n){n.classList.toggle('active',n.getAttribute('data-view')==='rps')});var title=document.getElementById('brandTitle');if(title)title.textContent='Rock Paper Scissors'}
      function chooseBotHand(){var losingChoice=choices.filter(function(x){return beats[x]===picked})[0];var botPool=[picked,picked,losingChoice,losingChoice,losingChoice,beats[picked]];return botPool[Math.floor(Math.random()*botPool.length)]}
      function balanceRead(){return window.VexaTonBalance&&window.VexaTonBalance.read?Number(window.VexaTonBalance.read()):0}
      function balanceAdd(delta){if(window.VexaTonBalance&&window.VexaTonBalance.add)return window.VexaTonBalance.add(delta);window.dispatchEvent(new CustomEvent('vexa-ton-balance-game-change',{detail:{deltaNano:delta}}));return Promise.resolve(balanceRead()+delta)}
      function startSession(){var bet=betValue();setBet(bet);betNano=Math.round(bet*rate);if(balanceRead()<betNano){resultEl.textContent='Not enough credit';tone('lose');return false}sessionActive=true;streak=0;currentWinNano=0;balanceAdd(-betNano);renderMultipliers();updateControls();return true}
      function cashOut(){if(friendMode||playing||!sessionActive||currentWinNano<=0)return;var paid=currentWinNano;balanceAdd(paid);resultEl.textContent='Cashed out • '+formatTon(paid);sessionActive=false;streak=0;currentWinNano=0;renderMultipliers();updateControls();tone('win')}
      function playChoice(value){if(friendMode){friendChoice(value);return}if(playing)return;setPick(value,true);if(!sessionActive&&!startSession())return;playing=true;updateControls();var roundIndex=Math.min(streak,multipliers.length-1);var bot=chooseBotHand();if(botImg)setHandAngle(botImg,botAngle);resultEl.textContent='Shuffling...';setTimeout(function(){setCardImage(botCard,botImg,'bot',bot,true);if(bot===picked){resultEl.textContent='Draw — pick again';tone('draw')}else if(beats[picked]===bot){var m=multipliers[roundIndex];currentWinNano=Math.round(betNano*m);wins+=1;streak=Math.min(streak+1,multipliers.length-1);resultEl.textContent='Win • '+m+'x or cash out';tone('win');renderMultipliers();flashMultiplier('win',roundIndex)}else{resultEl.textContent='You lose';sessionActive=false;streak=0;currentWinNano=0;tone('lose');renderMultipliers();flashMultiplier('loss',roundIndex)}playing=false;updateControls()},620)}
      root.querySelectorAll('[data-rps-choice]').forEach(function(button){button.onclick=function(){playChoice(button.getAttribute('data-rps-choice')||'rock')}});
      root.querySelector('[data-rps-half]').onclick=function(){if(!friendMode&&!sessionActive&&!playing)setBet(betValue()/2)};root.querySelector('[data-rps-double]').onclick=function(){if(!friendMode&&!sessionActive&&!playing)setBet(betValue()*2)};betInput.oninput=function(){betLabel.textContent=betInput.value||'0.1'};playBtn.onclick=cashOut;if(friendStart)friendStart.onclick=createFriendRoom;if(friendShare)friendShare.onclick=shareInvite;if(friendLeave)friendLeave.onclick=leaveFriendMode;
      window.addEventListener('vexa-rps-images-sync',function(event){applyUploadedRpsImages(event.detail||null);refreshRpsImages()});
      window.addEventListener('beforeunload',stopPolling);if(window.MutationObserver)new MutationObserver(function(){if(friendMode){if(root.classList.contains('active'))startPolling();else stopPolling()}}).observe(root,{attributes:true,attributeFilter:['class']});
      try{if(window.VexaUploadedImages&&window.VexaUploadedImages.read)applyUploadedRpsImages(window.VexaUploadedImages.read());if(window.VexaUploadedImages&&window.VexaUploadedImages.load)window.VexaUploadedImages.load().then(function(data){applyUploadedRpsImages(data);refreshRpsImages()}).catch(function(){})}catch(e){}
      setPick('rock',false);setBet(betInput.value);paintChoiceImages();renderMultipliers();updateControls();
      try{var roomId=new URLSearchParams(location.search).get('rpsRoom');var startParam=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.start_param;if(!roomId&&startParam&&startParam.indexOf('rpsRoom_')===0)roomId=startParam.replace('rpsRoom_','');roomId=sanitizeRoomId(roomId);if(roomId){showRpsFromInvite();setTimeout(function(){joinFriendRoom(roomId)},120)}}catch(e){}
    })();
  </script>
</section>
`;
