export const HOME_SECTION = `<section id="home" class="view active"><div class="hero"><h2>Build bots. Like magic.</h2><p>A premium AI control center for creating Telegram bots from natural language.</p></div><div class="actions"><button class="primary" data-view="connect">Connect</button><button class="secondary" data-view="results">Results</button></div><section class="card" style="margin-top:14px"><div class="pad"><div class="title"><h3>Overview</h3><span>Ready</span></div><div class="stats"><div class="stat"><b id="statBots">0</b><span>Bots</span></div><div class="stat"><b id="statActive">0</b><span>Live</span></div><div class="stat"><b id="statPaused">0</b><span>Paused</span></div></div></div></section></section>`;

export const CONNECT_SECTION = `<section id="connect" class="view"><section class="card"><div class="pad"><div class="title"><h3>Connect BotFather Key</h3><span id="builderStatus">Ready</span></div><div class="field"><label>BotFather Key</label><input id="botKey" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Paste bot token here"/></div><button class="primary" data-action="create-bot">Connect Bot</button><div class="tiny" style="margin-top:10px">Telegram verifies the token securely.</div></div></section><section class="card"><div class="pad"><div class="title"><h3>Your bots</h3><button class="ghost" data-action="refresh">Refresh</button></div><div id="homeBots" class="list"><div class="notice">Loading...</div></div></div></section></section>`;

export const RESULTS_SECTION = `<section id="results" class="view"><section class="card"><div class="pad"><div class="title"><h3>Results</h3><button class="ghost" data-action="refresh">Refresh</button></div><div id="botsList" class="list"><div class="notice">Loading...</div></div></div></section><section class="card"><div class="pad"><div class="title"><h3>Selected bot</h3><span id="activeBotLabel">No bot selected</span></div><div id="botInfo" class="notice">Choose a bot.</div><button class="primary" style="margin-top:12px" data-view="flow">Open TTS</button></div></section></section>`;

export const VOICE_OPTIONS = `<button class="active" data-voice="TX3LPaxmHKxFdv7VOQHJ">Liam</button><button data-voice="1SM7GgM6IMuvQlz2BwM3">Noah</button><button data-voice="tnSpp4vdxKPjI9w0GnoV">Ava</button><button data-voice="BIvP0GN1cAtSRTxNHnWS">Nora</button><button data-voice="GFGuOkimbpNkTEOVDkqX">Alex</button><button data-voice="NZiuR1C6kVMSWHG27sIM">Ella</button><button data-voice="BZgkqPqms7Kj9ulSkVzn">Chloe</button><button data-voice="kdmDKE6EkgrWrrykO9Qt">Alexandra</button><button data-voice="7piC4m7q8WrpEAnMj5xC">Laura</button><button data-voice="0dPqNXnhg2bmxQv1WKDp">Maxon</button><button data-voice="cgSgspJ2msm6clMCkdW9">Jessica</button><button data-voice="Bj9UqZbhQsanLzgalpEG">Austin</button>`;

export const TTS_SECTION = `<section id="flow" class="view"><div class="tts-page"><div class="tts-head"><div class="credit-pill"><img src="/app/api/credit-icon.png" alt=""/><span id="creditCount">1000</span></div><div id="voiceWrap" class="voice-wrap"><button class="voice-btn" data-action="toggle-voice"><span id="voiceLabel">Liam</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="voice-menu">${VOICE_OPTIONS}</div></div></div><div class="tts-area"><div class="tts-label">Text</div><textarea id="ttsText" placeholder="Type something..."></textarea></div><div class="tts-bottom"><div id="wavePlayer" class="wave-player"><button id="wavePlay" class="wave-play" data-action="play-tts">▶</button><svg class="wave-svg" viewBox="0 0 240 44" preserveAspectRatio="none"><rect x="2" y="12" width="4" height="20" rx="2"/><rect x="18" y="5" width="4" height="34" rx="2"/><rect x="34" y="15" width="4" height="14" rx="2"/><rect x="50" y="8" width="4" height="28" rx="2"/><rect x="66" y="3" width="4" height="38" rx="2"/><rect x="82" y="16" width="4" height="12" rx="2"/><rect x="98" y="9" width="4" height="26" rx="2"/><rect x="114" y="2" width="4" height="40" rx="2"/><rect x="130" y="13" width="4" height="18" rx="2"/><rect x="146" y="7" width="4" height="30" rx="2"/><rect x="162" y="17" width="4" height="10" rx="2"/><rect x="178" y="6" width="4" height="32" rx="2"/><rect x="194" y="12" width="4" height="20" rx="2"/><rect x="210" y="4" width="4" height="36" rx="2"/><rect x="226" y="15" width="4" height="14" rx="2"/></svg><span class="wave-time" id="waveTime">0:00</span></div><button class="tts-generate" data-action="generate-tts">Generate Voice</button><audio id="ttsAudio" class="tts-hidden-audio"></audio></div></div></section>`;

export const SETTINGS_SECTION = `<section id="settings" class="view"><section class="card"><div class="pad"><div class="title"><h3>Account</h3><span>Settings</span></div><div class="field"><label>Telegram User ID</label><input id="ownerId"/></div><button class="primary" data-action="save-user">Save User</button></div></section><section class="card"><div class="pad"><div class="title"><h3>Bot Settings</h3><span>Control</span></div><div class="field"><label>Bot</label><select id="botSelect"></select></div><div class="toolbar"><button class="ghost" data-action="publish">Publish</button><button class="ghost" data-action="toggle-pause" id="pauseBtn">Pause</button><button class="danger" data-action="delete">Delete</button></div></div></section></section>`;
