export const TRANSACTIONS_GLOBAL_STYLES = `
body > #transactionsSheet.deposit-sheet,#transactionsSheet.deposit-sheet{position:fixed!important;inset:0!important;z-index:120!important;display:none;align-items:center!important;justify-content:center!important;padding:20px 16px calc(92px + env(safe-area-inset-bottom))!important}
body > #transactionsSheet.deposit-sheet.open,#transactionsSheet.deposit-sheet.open{display:flex!important}
body > #transactionsSheet .deposit-backdrop,#transactionsSheet .deposit-backdrop{position:absolute!important;inset:0!important;background:rgba(0,0,0,.30)!important;backdrop-filter:blur(2px)!important;-webkit-backdrop-filter:blur(2px)!important}
body > #transactionsSheet .deposit-panel,#transactionsSheet .deposit-panel{position:relative!important;left:auto!important;right:auto!important;bottom:auto!important;width:min(100%,528px)!important;max-height:min(82vh,650px)!important;margin:auto!important;border-radius:32px!important;background:rgba(8,8,8,.34)!important;border:0!important;box-shadow:0 22px 62px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.10)!important;backdrop-filter:blur(2px) saturate(1.08)!important;-webkit-backdrop-filter:blur(2px) saturate(1.08)!important;overflow:auto!important;animation:depositCenterIn .34s cubic-bezier(.18,.88,.22,1.08)!important}
body > #transactionsSheet .deposit-panel .pad,#transactionsSheet .deposit-panel .pad{padding:24px 22px 24px!important}
body > #transactionsSheet .deposit-title,#transactionsSheet .deposit-title{display:flex!important;align-items:center!important;justify-content:space-between!important;margin:0 0 14px!important;gap:12px!important}
body > #transactionsSheet .deposit-title-main,#transactionsSheet .deposit-title-main{display:flex!important;align-items:center!important;gap:10px!important;min-width:0!important}
body > #transactionsSheet .transactions-title-icon,#transactionsSheet .transactions-title-icon{width:34px!important;height:34px!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:rgba(255,255,255,.07)!important;color:#fff!important;flex:0 0 auto!important;filter:drop-shadow(0 8px 18px rgba(255,255,255,.12))!important}
body > #transactionsSheet .transactions-title-icon svg,#transactionsSheet .transactions-title-icon svg{width:24px!important;height:24px!important}
body > #transactionsSheet .deposit-title h3,#transactionsSheet .deposit-title h3{font-size:20px!important;line-height:1.05!important;font-weight:900!important;letter-spacing:-.055em!important;white-space:nowrap!important}
body > #transactionsSheet .deposit-close,#transactionsSheet .deposit-close{width:38px!important;height:38px!important;min-width:38px!important;padding:0!important;border:0!important;background:rgba(255,255,255,.035)!important;color:#fff!important;display:grid!important;place-items:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important}
body > #transactionsSheet .deposit-close svg,#transactionsSheet .deposit-close svg{width:20px!important;height:20px!important;display:block!important}
body > #transactionsSheet .deposit-copy,#transactionsSheet .deposit-copy{margin:8px auto 14px!important;max-width:330px!important;text-align:center!important;color:rgba(255,255,255,.76)!important;font-size:16px!important;line-height:1.36!important;font-weight:750!important;letter-spacing:-.035em!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important}
body > #transactionsSheet .transactions-list,#transactionsSheet .transactions-list{display:grid!important;gap:10px!important;max-height:390px!important;overflow:auto!important;padding:2px 2px 4px!important;scrollbar-width:none!important;opacity:0;animation:depositItemIn .42s cubic-bezier(.18,.88,.22,1.08) .29s forwards!important}
body > #transactionsSheet .transactions-list::-webkit-scrollbar,#transactionsSheet .transactions-list::-webkit-scrollbar{display:none!important}
body > #transactionsSheet .transaction-row,#transactionsSheet .transaction-row{display:grid!important;grid-template-columns:42px minmax(0,1fr) auto!important;gap:10px!important;align-items:center!important;border-radius:22px!important;background:rgba(255,255,255,.045)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 12px 28px rgba(0,0,0,.14)!important;backdrop-filter:blur(6px) saturate(1.12)!important;-webkit-backdrop-filter:blur(6px) saturate(1.12)!important;padding:12px 12px!important;animation:depositItemIn .36s ease both!important}
body > #transactionsSheet .transaction-icon,#transactionsSheet .transaction-icon{width:42px!important;height:42px!important;border-radius:17px!important;display:grid!important;place-items:center!important;color:#fff!important;background:rgba(255,255,255,.055)!important}
body > #transactionsSheet .transaction-icon svg,#transactionsSheet .transaction-icon svg{width:24px!important;height:24px!important}
body > #transactionsSheet .transaction-icon.in,#transactionsSheet .transaction-icon.in{color:#42f594!important}
body > #transactionsSheet .transaction-icon.out,#transactionsSheet .transaction-icon.out{color:#ffcf6b!important}
body > #transactionsSheet .transaction-main,#transactionsSheet .transaction-main{min-width:0!important}
body > #transactionsSheet .transaction-main strong,#transactionsSheet .transaction-main strong{display:block!important;font-size:14px!important;font-weight:900!important;letter-spacing:-.035em!important;color:#fff!important}
body > #transactionsSheet .transaction-main span,#transactionsSheet .transaction-main span{display:block!important;margin-top:4px!important;font-size:10px!important;font-weight:700!important;color:rgba(255,255,255,.48)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
body > #transactionsSheet .transaction-side,#transactionsSheet .transaction-side{text-align:right!important;white-space:nowrap!important}
body > #transactionsSheet .transaction-side b,#transactionsSheet .transaction-side b{display:block!important;font-size:13px!important;font-weight:900!important;color:#fff!important}
body > #transactionsSheet .transaction-side em,#transactionsSheet .transaction-side em{display:block!important;margin-top:5px!important;font-size:9px!important;font-style:normal!important;font-weight:850!important;text-transform:uppercase!important;letter-spacing:.04em!important;color:rgba(255,255,255,.55)!important}
body > #transactionsSheet .transaction-side em.completed,#transactionsSheet .transaction-side em.completed{color:#42f594!important}
body > #transactionsSheet .transaction-side em.pending,#transactionsSheet .transaction-side em.pending{color:#ffcf6b!important}
body > #transactionsSheet .transactions-empty,#transactionsSheet .transactions-empty{text-align:center!important;color:rgba(255,255,255,.62)!important;font-size:13px!important;font-weight:750!important;padding:26px 8px!important;border-radius:22px!important;background:rgba(255,255,255,.035)!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important}
`;
