export const VOICE_OPTIONS = `<button class="active" data-voice="TX3LPaxmHKxFdv7VOQHJ">Liam</button><button data-voice="1SM7GgM6IMuvQlz2BwM3">Noah</button><button data-voice="tnSpp4vdxKPjI9w0GnoV">Ava</button><button data-voice="BIvP0GN1cAtSRTxNHnWS">Nora</button><button data-voice="GFGuOkimbpNkTEOVDkqX">Alex</button><button data-voice="NZiuR1C6kVMSWHG27sIM">Ella</button><button data-voice="BZgkqPqms7Kj9ulSkVzn">Chloe</button><button data-voice="kdmDKE6EkgrWrrykO9Qt">Alexandra</button><button data-voice="7piC4m7q8WrpEAnMj5xC">Laura</button><button data-voice="0dPqNXnhg2bmxQv1WKDp">Maxon</button><button data-voice="cgSgspJ2msm6clMCkdW9">Jessica</button><button data-voice="Bj9UqZbhQsanLzgalpEG">Austin</button>`;

export const TTS_WAVE_BARS = Array.from({ length: 31 }, (_, index) => {
  const heights = [14, 24, 11, 30, 18, 34, 12, 28, 20, 36, 15, 26, 32, 13, 23, 38, 23, 13, 32, 26, 15, 36, 20, 28, 12, 34, 18, 30, 11, 24, 14];
  const x = 2 + index * 7.6;
  const h = heights[index];
  const y = 22 - h / 2;
  return `<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="3.2" height="${h}" rx="1.6"/>`;
}).join('');

export const TTS_SECTION = `<section id="flow" class="view"><div class="tts-page"><div class="tts-head"><div></div><div id="voiceWrap" class="voice-wrap"><button class="voice-btn" data-action="toggle-voice"><span id="voiceLabel">Liam</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="voice-menu">${VOICE_OPTIONS}</div></div></div><div class="tts-area"><div class="tts-label">Text</div><textarea id="ttsText" placeholder="Type something"></textarea></div><button class="keyboard-dismiss" data-action="dismiss-keyboard" aria-label="Hide keyboard"><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="tts-bottom"><div id="wavePlayer" class="wave-player"><button id="wavePlay" class="wave-play" data-action="play-tts">▶</button><svg class="wave-svg" viewBox="0 0 240 44" preserveAspectRatio="none">${TTS_WAVE_BARS}</svg><span class="wave-time" id="waveTime">0:00</span></div><div class="tts-generate-row"><button class="tts-generate" data-action="generate-tts">Generate Voice</button><span class="char-count-wrap"><span class="char-count" id="ttsCharCount">0 characters</span><button class="char-warning" id="ttsCharWarning" data-action="open-char-limit" aria-label="Character limit warning">!</button></span></div><audio id="ttsAudio" class="tts-hidden-audio"></audio></div><div class="limit-sheet" id="ttsLimitSheet" aria-hidden="true"><button class="limit-backdrop" data-action="close-char-limit" aria-label="Close"></button><div class="limit-card"><div class="limit-icon">!</div><h3>Character limit</h3><p>You can’t convert more than 1000 characters</p><button class="limit-close" data-action="close-char-limit">Got it</button></div></div></div></section>`;
