export const VEXA_REWARDS_SCRIPT = `
(function(){
  var state=null;
  function q(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/[&<>]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[s]||s})}
  function userId(){var tg=window.Telegram&&window.Telegram.WebApp;var u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;return String((u&&u.id)||localStorage.getItem('ownerId')||'').trim()}
  function claimedIds(){var ids=state&&state.userState&&Array.isArray(state.userState.claimedMissionIds)?state.userState.claimedMissionIds:[];return ids.map(String)}
  function missionId(m,i){return String(m.id||m.templateId||m.title||('reward-mission-'+i)).replace(/[^0-9A-Za-z_-]/g,'_')}
  function fallback(){return {todayMissions:[{id:'daily-checkin',title:'Daily Check-in',description:'Open Vexa once today',vexAmount:20},{id:'play-3-games',title:'Play 3 Games',description:'Complete any three Play Zone rounds',vexAmount:70},{id:'use-ai-chat',title:'Use AI Chat',description:'Send one message to Vexa AI',vexAmount:40},{id:'open-leaderboard',title:'Open Weekly Vex',description:'View the weekly leaderboard',vexAmount:15}],userState:{vex:0,claimedMissionIds:[]}}}
  async function load(){try{var id=userId();var r=await fetch('/app/api/vexa-league'+(id?'?userId='+encodeURIComponent(id):''),{headers:{accept:'application/json'},cache:'no-store'});var j=await r.json().catch(function(){return null});if(r.ok&&j&&j.ok){state=j;return j}}catch(e){}state=fallback();return state}
  function icon(){return '<svg viewBox="0 0 24 24"><path d="M5 12.5l4.2 4.2L19 7"/></svg>'}
  function row(m,i){var id=missionId(m,i);var done=claimedIds().indexOf(id)>-1;return '<div class="mission-row '+(i===0?'primary':'')+'"><div class="mission-icon">'+icon()+'</div><div class="mission-main"><strong>'+esc(m.title||'Daily Mission')+'</strong><span>'+esc(m.description||'Complete this mission')+'</span></div><button class="mission-reward" type="button" data-vexa-reward-claim="'+esc(id)+'" data-vexa-reward-vex="'+esc(m.vexAmount||0)+'" '+(done?'disabled':'')+'>'+(done?'Claimed':'+'+esc(m.vexAmount||0)+' Vex')+'</button></div>'}
  function render(){var page=q('rewardsPage');if(!page||!state)return;var missions=state.todayMissions||state.missions||[];var claimed=claimedIds();var done=missions.filter(function(m,i){return claimed.indexOf(missionId(m,i))>-1}).length;var strip=page.querySelector('.rewards-status-pill');if(strip)strip.textContent=done+' / '+missions.length;var status=page.querySelector('.rewards-status-main span');if(status)status.textContent=done+' missions completed today';var title=page.querySelector('.missions-title span');if(title)title.textContent=done+' / '+missions.length+' done';var list=page.querySelector('.missions-list');if(list)list.innerHTML=missions.length?missions.slice(0,8).map(row).join(''):'<div class="mission-row primary"><div class="mission-icon">'+icon()+'</div><div class="mission-main"><strong>No missions selected</strong><span>Admin will add today missions soon</span></div><div class="mission-reward">Vex</div></div>';var btn=page.querySelector('.reward-today-button');if(btn){btn.disabled=missions.length===0;btn.textContent=done>=missions.length&&missions.length?'Done':'Claim';btn.setAttribute('data-vexa-reward-main','1')}var todayMain=page.querySelector('.reward-today-main span');if(todayMain)todayMain.textContent=missions.length?('Complete '+missions.length+' missions to earn Vex'):'Daily missions will appear here'}
  function toast(msg){try{var t=q('toast');if(t){t.textContent=msg;t.style.display='block';setTimeout(function(){t.style.display='none'},2200)}}catch(e){}}
  async function claim(id,amount,button){var uid=userId();if(!uid){toast('Telegram user not found');return}if(button){button.disabled=true;button.textContent='Claiming...'}try{var r=await fetch('/app/api/vexa-league/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:uid,missionId:id})});var j=await r.json().catch(function(){return null});if(!r.ok||!j||!j.ok)throw new Error((j&&j.error)||'Could not claim');state.userState=j.userState||state.userState;state.seedUsers=j.leaderboard||state.seedUsers;toast('+'+amount+' Vex claimed');render()}catch(e){if(button){button.disabled=false;button.textContent='+'+amount+' Vex'}toast(e.message||'Claim failed')}}
  async function refresh(){await load();render()}
  document.addEventListener('click',function(ev){var page=q('rewardsPage');var claimBtn=ev.target&&ev.target.closest&&ev.target.closest('[data-vexa-reward-claim]');if(claimBtn){ev.preventDefault();ev.stopPropagation();claim(claimBtn.getAttribute('data-vexa-reward-claim'),Number(claimBtn.getAttribute('data-vexa-reward-vex')||0),claimBtn);return}var mainBtn=ev.target&&ev.target.closest&&ev.target.closest('[data-vexa-reward-main]');if(mainBtn&&page){var first=page.querySelector('[data-vexa-reward-claim]:not([disabled])');if(first){ev.preventDefault();ev.stopPropagation();first.click()}}var open=ev.target&&ev.target.closest&&ev.target.closest('[data-action="open-rewards"]');if(open)setTimeout(refresh,80)},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(refresh,800)});else setTimeout(refresh,800);
  window.VexaRewards={refresh:refresh};
})();
`;