export const WALLET_SECTION = `<section id="wallet" class="view wallet-view">
  <style>
    #wallet{overflow-y:auto!important;overflow-x:hidden!important;padding:0 0 126px!important;-webkit-overflow-scrolling:touch;scrollbar-width:none;color:#fff;font-family:var(--font-main)!important}
    #wallet::-webkit-scrollbar{display:none}
    #wallet *{box-sizing:border-box;font-family:var(--font-main)!important}
    .wallet-shell{display:grid;gap:14px;padding:2px 0 8px;position:relative}
    .wallet-orb{position:absolute;right:-52px;top:22px;width:176px;height:176px;border-radius:50%;background:radial-gradient(circle at 35% 35%,rgba(130,18,49,.62),rgba(46,0,13,.18) 48%,transparent 72%);filter:blur(.2px);opacity:.72;animation:walletFloat 6s ease-in-out infinite;pointer-events:none}
    .wallet-orb:after{content:"";position:absolute;inset:38px;border-radius:50%;border:1px solid rgba(255,255,255,.11);box-shadow:0 0 42px rgba(116,18,45,.38),inset 0 0 24px rgba(255,255,255,.05)}
    .wallet-hero,.wallet-glass-card,.wallet-action-card,.wallet-referral-card,.wallet-transactions-card{position:relative;border:0;border-radius:32px;background:linear-gradient(135deg,rgba(255,255,255,.072),rgba(255,255,255,.018));box-shadow:inset 0 1px 0 rgba(255,255,255,.11),0 24px 62px rgba(0,0,0,.30);backdrop-filter:blur(18px) saturate(1.18);-webkit-backdrop-filter:blur(18px) saturate(1.18);overflow:hidden}
    .wallet-hero{min-height:178px;padding:18px;display:grid;align-content:space-between;background:linear-gradient(145deg,rgba(95,13,39,.24),rgba(255,255,255,.022) 48%,rgba(0,0,0,.18))}
    .wallet-hero:before,.wallet-referral-card:before{content:"";position:absolute;inset:-1px;background:linear-gradient(115deg,transparent 0%,rgba(255,255,255,.13) 38%,transparent 52%);transform:translateX(-115%);animation:walletSweep 5.8s cubic-bezier(.16,1,.3,1) infinite;pointer-events:none}
    .wallet-kicker{display:flex;align-items:center;justify-content:space-between;gap:12px;color:rgba(255,255,255,.58);font-size:11px;font-weight:850;text-transform:uppercase;letter-spacing:.08em}
    .wallet-live-dot{width:9px;height:9px;border-radius:50%;background:#7b1534;box-shadow:0 0 0 8px rgba(123,21,52,.12),0 0 28px rgba(150,26,62,.72);animation:walletPulse 1.8s ease-in-out infinite}
    .wallet-balance-line{display:flex;align-items:flex-end;gap:10px;margin-top:28px}.wallet-balance-line strong{font-size:42px;line-height:.9;font-weight:950;letter-spacing:-.075em;color:#fff}.wallet-balance-line span{font-size:13px;font-weight:900;color:rgba(255,255,255,.52);padding-bottom:4px}
    .wallet-balance-sub{margin:12px 0 0;color:rgba(255,255,255,.52);font-size:12px;font-weight:680;line-height:1.35}.wallet-balance-sub b{color:#fff;font-weight:900}
    .wallet-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wallet-action-card{appearance:none;-webkit-appearance:none;min-height:118px;padding:14px;text-align:left;color:#fff;display:grid;align-content:space-between;isolation:isolate}.wallet-action-card:active{transform:scale(.985)}
    .wallet-action-icon{width:42px;height:42px;border-radius:18px;display:grid;place-items:center;background:rgba(255,255,255,.058);box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 16px 32px rgba(0,0,0,.22)}.wallet-action-icon svg{width:28px;height:28px}.wallet-action-card strong{font-size:19px;line-height:1;font-weight:940;letter-spacing:-.055em}.wallet-action-card span:last-child{font-size:11px;font-weight:720;color:rgba(255,255,255,.50);line-height:1.25}
    .wallet-referral-card{padding:15px;display:grid;gap:12px;background:linear-gradient(145deg,rgba(82,9,33,.20),rgba(255,255,255,.025))}.wallet-referral-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.wallet-referral-head strong{font-size:18px;font-weight:940;letter-spacing:-.05em}.wallet-reward-pill{height:32px;border-radius:999px;padding:0 11px;display:flex;align-items:center;background:rgba(99,15,42,.34);box-shadow:inset 0 1px 0 rgba(255,255,255,.1);font-size:11px;font-weight:900;color:#fff}
    .wallet-referral-meter{height:13px;border-radius:999px;background:rgba(0,0,0,.24);box-shadow:inset 0 1px 2px rgba(0,0,0,.36);overflow:hidden}.wallet-referral-meter span{display:block;width:74%;height:100%;border-radius:999px;background:linear-gradient(90deg,rgba(68,8,28,.88),rgba(128,24,55,.95),rgba(255,255,255,.42));box-shadow:0 0 24px rgba(128,24,55,.62);animation:walletMeter 3.2s ease-in-out infinite}
    .wallet-link-row{display:grid;grid-template-columns:minmax(0,1fr) 86px;gap:9px}.wallet-link-box{height:44px;border-radius:18px;background:rgba(0,0,0,.22);box-shadow:inset 0 1px 0 rgba(255,255,255,.06);display:flex;align-items:center;padding:0 12px;color:rgba(255,255,255,.62);font-size:11.5px;font-weight:760;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.wallet-copy-btn{border:0;border-radius:18px;background:rgba(255,255,255,.062);box-shadow:inset 0 1px 0 rgba(255,255,255,.10);color:#fff;font-size:12px;font-weight:900}
    .wallet-transactions-card{padding:15px;display:grid;gap:12px}.wallet-section-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.wallet-section-title strong{font-size:18px;font-weight:940;letter-spacing:-.05em}.wallet-section-title span{font-size:11px;font-weight:780;color:rgba(255,255,255,.42)}#walletTransactionsList{display:grid;gap:10px;max-height:360px;overflow:auto;scrollbar-width:none}#walletTransactionsList::-webkit-scrollbar{display:none}
    #wallet .transaction-row{background:rgba(255,255,255,.04)!important;border-radius:22px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.075)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important}
    @keyframes walletSweep{0%,62%{transform:translateX(-115%)}100%{transform:translateX(115%)}}@keyframes walletPulse{50%{transform:scale(1.22);box-shadow:0 0 0 11px rgba(123,21,52,.06),0 0 34px rgba(150,26,62,.82)}}@keyframes walletFloat{50%{transform:translate3d(-8px,14px,0) scale(1.05)}}@keyframes walletMeter{50%{width:88%;filter:brightness(1.18)}}
  </style>
  <div class="wallet-shell">
    <div class="wallet-orb" aria-hidden="true"></div>
    <section class="wallet-hero">
      <div class="wallet-kicker"><span>Liquid TON Wallet</span><i class="wallet-live-dot" aria-hidden="true"></i></div>
      <div><div class="wallet-balance-line"><strong id="walletTonBalance" data-ton-balance-display>0</strong><span>TON</span></div><p class="wallet-balance-sub">Transparent balance center for <b>deposit</b>, <b>withdraw</b>, referral rewards, and payment history.</p></div>
    </section>
    <section class="wallet-actions">
      <button class="wallet-action-card" type="button" data-action="open-deposit"><span class="wallet-action-icon"><svg viewBox="0 0 48 48" fill="none"><path d="M24 8v24" stroke="currentColor" stroke-width="3.3" stroke-linecap="round"/><path d="M14 22l10 10 10-10" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"/></svg></span><strong>Deposit</strong><span>Add TON with Stars or wallet</span></button>
      <button class="wallet-action-card" type="button" data-action="open-withdraw"><span class="wallet-action-icon"><svg viewBox="0 0 48 48" fill="none"><path d="M24 40V16" stroke="currentColor" stroke-width="3.3" stroke-linecap="round"/><path d="M14 26l10-10 10 10" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"/></svg></span><strong>Withdraw</strong><span>Send TON to your wallet</span></button>
    </section>
    <section class="wallet-referral-card">
      <div class="wallet-referral-head"><strong>Referral Boost</strong><span class="wallet-reward-pill">+0.1 TON / invite</span></div>
      <div class="wallet-referral-meter" aria-hidden="true"><span></span></div>
      <div class="wallet-link-row"><div id="walletReferralLink" class="wallet-link-box">Loading referral link</div><button id="walletReferralCopy" class="wallet-copy-btn" type="button">Copy</button></div>
    </section>
    <section class="wallet-transactions-card">
      <div class="wallet-section-title"><strong>Payment Transactions</strong><span>Deposits & withdrawals</span></div>
      <div id="walletTransactionsList" class="transactions-list"><div class="transactions-empty">Loading transactions</div></div>
    </section>
  </div>
  <script>(function(){var tg=window.Telegram&&window.Telegram.WebApp;function q(id){return document.getElementById(id)}function uid(){return String((tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user&&tg.initDataUnsafe.user.id)||localStorage.getItem('ownerId')||'')}function linkFor(id){return 'https://t.me/VexaAppBOT?startapp=ref_'+encodeURIComponent(id||'')}function sync(){var id=uid();var box=q('walletReferralLink');if(box)box.textContent=id?linkFor(id):'Telegram user not found';if(id)localStorage.setItem('ownerId',id);if(window.__vexaWalletLoadTransactions)window.__vexaWalletLoadTransactions()}window.__vexaWalletSync=sync;document.addEventListener('click',function(ev){if(ev.target&&ev.target.closest&&ev.target.closest('#walletReferralCopy')){ev.preventDefault();var id=uid();var link=linkFor(id);try{navigator.clipboard&&navigator.clipboard.writeText(link)}catch(e){}var b=q('walletReferralCopy');if(b){b.textContent='Copied';setTimeout(function(){b.textContent='Copy'},1200)}}},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(sync,180)});else setTimeout(sync,180);})();</script>
</section>`;
