// Final Dice control polish. One viewport-independent control path; loaded after dice-fixed.ts.
export const DICE_FINAL_TWEAK = `<style id="vexaDiceCrashGlassControls">
#dice.dice-view{filter:none!important}
#dice .dice-panel{position:relative!important;display:grid!important;grid-template-columns:minmax(0,1fr)!important;grid-template-rows:70px 94px auto!important;width:100%!important;max-width:100%!important;min-width:0!important;margin:-8px 0 0!important;padding:16px 18px 18px!important;row-gap:0!important;column-gap:0!important;border-radius:36px!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;overflow:visible!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#dice .dice-panel>.dice-control-grid,#dice .dice-panel>.dice-bet{grid-column:1!important;width:100%!important;max-width:100%!important;min-width:0!important;justify-self:stretch!important;align-self:stretch!important;box-sizing:border-box!important}
#dice .dice-control-grid{height:70px!important;min-height:70px!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;column-gap:11px!important;row-gap:0!important;margin:0!important;padding:0!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
#dice .dice-control-grid .dice-field,#dice .dice-control-grid .dice-field.active,#dice .dice-control-grid .dice-field:hover,#dice .dice-control-grid .dice-field:focus,#dice .dice-control-grid .dice-field:active,#dice .dice-control-grid button.dice-mode-field,#dice .dice-control-grid button.dice-mode-field.active,#dice .dice-control-grid button.dice-mode-field:hover,#dice .dice-control-grid button.dice-mode-field:focus,#dice .dice-control-grid button.dice-mode-field:active{min-width:0!important;min-height:70px!important;height:70px!important;display:grid!important;grid-template-rows:10px 18px!important;align-content:center!important;justify-content:stretch!important;row-gap:4px!important;padding:8px 12px!important;border-radius:22px!important;border:0!important;border-color:transparent!important;outline:0!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14),inset 0 -1px 0 rgba(255,255,255,.025),0 8px 22px rgba(0,0,0,.12)!important;filter:none!important;backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;-webkit-backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;appearance:none!important;-webkit-appearance:none!important;-webkit-tap-highlight-color:transparent!important;overflow:hidden!important}
#dice .dice-control-grid .dice-field::before,#dice .dice-control-grid .dice-field::after,#dice .dice-control-grid button.dice-mode-field::before,#dice .dice-control-grid button.dice-mode-field::after{content:none!important;display:none!important;background:none!important;box-shadow:none!important}
#dice .dice-control-grid .dice-field small,#dice .dice-control-grid button.dice-mode-field small[data-dice-mode-label]{display:flex!important;align-items:center!important;height:10px!important;margin:0!important;font-size:10.5px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important;color:rgba(255,255,255,.58)!important;white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;transform:none!important;background:none!important;box-shadow:none!important}
#dice .dice-control-grid .dice-field b,#dice .dice-control-grid button.dice-mode-field b{display:flex!important;align-items:center!important;justify-content:space-between!important;width:100%!important;height:18px!important;margin:0!important;gap:4px!important;min-width:0!important;font-size:18px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.035em!important;color:#fff!important;white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;transform:none!important}
#dice .dice-control-grid .dice-field b>span,#dice .dice-control-grid button.dice-mode-field b>span{min-width:max-content!important;overflow:visible!important;text-overflow:clip!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#dice .dice-mode-field i{width:20px!important;height:20px!important;flex:0 0 20px!important;border-radius:0!important;display:grid!important;place-items:center!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;box-shadow:none!important;color:rgba(255,255,255,.78)!important;font-size:13px!important;line-height:1!important}
#dice .dice-bet{display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;height:70px!important;min-height:70px!important;margin:12px 0!important;padding:0!important;column-gap:11px!important;row-gap:0!important;align-items:stretch!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;transform:none!important}
#dice .dice-bet button,#dice .dice-bet button:hover,#dice .dice-bet button:focus,#dice .dice-bet button:active,#dice .dice-bet button.active{width:100%!important;min-width:0!important;height:70px!important;border-radius:22px!important;border:0!important;border-color:transparent!important;outline:0!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;display:grid!important;place-items:center!important;padding:0 12px!important;font-size:22px!important;line-height:1!important;font-weight:950!important;letter-spacing:0!important;text-align:center!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14),inset 0 -1px 0 rgba(255,255,255,.025),0 8px 22px rgba(0,0,0,.12)!important;filter:none!important;backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;-webkit-backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;text-shadow:none!important;-webkit-tap-highlight-color:transparent!important;overflow:hidden!important}
#dice .dice-bet [data-dice-bet-half]::before,#dice .dice-bet [data-dice-bet-half]::after,#dice .dice-bet [data-dice-bet-double]::before,#dice .dice-bet [data-dice-bet-double]::after{content:none!important;display:none!important;background:none!important;box-shadow:none!important}
#dice .dice-bet .dice-bet-main,#dice .dice-bet .dice-bet-main.active,#dice .dice-bet .dice-bet-main:hover,#dice .dice-bet .dice-bet-main:focus,#dice .dice-bet .dice-bet-main:active{height:70px!important;border-radius:22px!important;border:0!important;border-color:transparent!important;outline:0!important;background:transparent!important;background-color:rgba(0,0,0,0)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:0!important;padding:0 12px!important;font-size:22px!important;font-weight:950!important;letter-spacing:0!important;text-shadow:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.14),inset 0 -1px 0 rgba(255,255,255,.025),0 8px 22px rgba(0,0,0,.12)!important;filter:none!important;backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;-webkit-backdrop-filter:blur(15px) saturate(1.16) brightness(1.04)!important;transform:none!important}
#dice .dice-bet .dice-bet-main::before{content:''!important;width:37px!important;height:37px!important;flex:0 0 37px!important;display:block!important;margin-right:-5px!important;background-color:transparent!important;background-image:url('/app/api/uploaded-image/ton-icon.png')!important;background-position:center!important;background-size:contain!important;background-repeat:no-repeat!important;border:0!important;box-shadow:none!important;filter:none!important;transform:translateY(2px)!important;pointer-events:none!important}
#dice .dice-bet .dice-bet-main::after{content:none!important;display:none!important;background:none!important;box-shadow:none!important}
#dice .dice-roll-button{grid-column:1/-1!important;justify-self:center!important;width:100%!important;min-width:0!important;height:60px!important;min-height:60px!important;margin:0 auto!important;padding:0!important;border-radius:20px!important;border:0!important;outline:0!important;background-color:rgba(59,7,21,.58)!important;background-image:linear-gradient(145deg,rgba(112,22,48,.62),rgba(59,7,21,.40) 62%,rgba(39,4,13,.48))!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;font-size:17px!important;font-weight:900!important;letter-spacing:-.045em!important;text-transform:none!important;box-shadow:inset 0 1px 0 rgba(255,220,229,.14),inset 0 -1px 0 rgba(255,255,255,.018),0 10px 24px rgba(0,0,0,.20)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;text-shadow:none!important;transition:transform .18s ease,opacity .18s ease,background .18s ease!important;overflow:hidden!important}
#dice .dice-roll-button.is-rolling{background-color:rgba(59,7,21,.58)!important;background-image:linear-gradient(145deg,rgba(112,22,48,.62),rgba(59,7,21,.40) 62%,rgba(39,4,13,.48))!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;transform:none!important}
#dice .dice-roll-button:not(:disabled):active{transform:scale(.975)!important}
#dice .dice-roll-button:disabled{opacity:.62!important;transform:none!important}
</style>`;
