export const CRASH_BREAK_FX_SCRIPT = `
(function(){
  var audioCtx=null, master=null, lastState='idle', crashedLock=false, lastStartKey='';
  function q(id){return document.getElementById(id)}
  function active(){var c=q('crash');return !!(c&&c.classList.contains('active'))}
  function getAudio(){var C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioCtx){audioCtx=new C();master=audioCtx.createGain();master.gain.value=.95;master.connect(audioCtx.destination)}return audioCtx}
  function unlock(){if(!active())return null;var ctx=getAudio();if(!ctx)return null;if(ctx.state==='suspended')ctx.resume().catch(function(){});return ctx}
  function canPlay(){return !!(audioCtx&&audioCtx.state==='running')}
  function bell(freq,when,len,vol,type){var ctx=audioCtx;if(!ctx||!canPlay())return;var o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=type||'triangle';o.frequency.setValueAtTime(freq,when);o.frequency.exponentialRampToValueAtTime(freq*.985,when+len);f.type='bandpass';f.frequency.setValueAtTime(freq*2.15,when);f.Q.value=1.65;g.gain.setValueAtTime(.001,when);g.gain.linearRampToValueAtTime(vol,when+.01);g.gain.exponentialRampToValueAtTime(.001,when+len);o.connect(f);f.connect(g);g.connect(master);o.start(when);o.stop(when+len+.035)}
  function startSound(){var ctx=unlock();if(!ctx||!canPlay())return;var t=ctx.currentTime;bell(587.33,t,.16,.18,'sine');bell(466.16,t+.06,.18,.15,'triangle');bell(293.66,t+.13,.20,.12,'sine')}
  function burst(ctx,delay,dur,gainVal){if(!canPlay())return;var b=ctx.createBuffer(1,Math.floor(ctx.sampleRate*dur),ctx.sampleRate),d=b.getChannelData(0);for(var i=0;i<d.length;i++){var t=i/d.length;d[i]=(Math.random()*2-1)*Math.pow(1-t,3)}var s=ctx.createBufferSource();s.buffer=b;var f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=850+Math.random()*1000;var g=ctx.createGain();g.gain.setValueAtTime(gainVal,ctx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+dur);s.connect(f);f.connect(g);g.connect(master);s.start(ctx.currentTime+delay)}
  function crackSound(){var ctx=unlock();if(!ctx||!canPlay())return;burst(ctx,0,.08,.18);burst(ctx,.04,.06,.11);bell(146.83,ctx.currentTime,.20,.075,'triangle')}
  function explosionSound(){var ctx=unlock();if(!ctx||!canPlay())return;var t=ctx.currentTime;burst(ctx,0,.18,.24);burst(ctx,.035,.27,.16);bell(82.41,t,.34,.105,'sine');bell(123.47,t+.015,.18,.08,'triangle')}
  function ensureExplosionStyle(){var style=q('crashRocketExplosionStyle');if(style)return;style=document.createElement('style');style.id='crashRocketExplosionStyle';style.textContent='#crash .crash-rocket-flame{top:91%!important}#crash .crash-rocket-explosion-layer{position:absolute;inset:0;z-index:8;overflow:visible;pointer-events:none}#crash .crash-rocket-explosion-piece{position:absolute;left:0;top:0;will-change:transform,opacity;pointer-events:none}#crash .crash-rocket-explosion-flash{width:42px;height:42px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,1) 0%,rgba(255,231,205,.98) 18%,rgba(160,23,52,.82) 48%,rgba(50,0,13,0) 78%);filter:blur(.8px);mix-blend-mode:screen}#crash .crash-rocket-explosion-ring{width:34px;height:34px;border-radius:50%;border:2px solid rgba(255,226,214,.76);box-shadow:0 0 18px rgba(154,14,45,.34)}#crash .crash-rocket-explosion-spark{width:4px;height:10px;border-radius:999px;background:linear-gradient(180deg,#fff 0%,#ffd5c9 24%,#9b1239 70%,rgba(72,0,18,0) 100%);transform-origin:50% 100%;filter:drop-shadow(0 0 4px rgba(255,174,158,.38))}#crash .crash-rocket-explosion-debris{width:5px;height:3px;border-radius:1px;background:linear-gradient(180deg,#d8d8d8,#5d5d5d);box-shadow:0 0 4px rgba(255,255,255,.18)}#crash .crash-rocket-explosion-smoke{width:18px;height:18px;border-radius:50%;background:radial-gradient(circle,rgba(110,110,110,.46) 0%,rgba(45,45,45,.26) 52%,rgba(15,15,15,0) 78%);filter:blur(2px)}#crash .crash-rocket-flight.is-exploding{animation:none!important}#crash .crash-rocket-flight.is-exploding .crash-rocket-model,#crash .crash-rocket-flight.is-exploding .crash-rocket-flame,#crash .crash-rocket-flight.is-exploding .crash-rocket-heat{opacity:0!important;transition:opacity .09s linear!important}';document.head.appendChild(style)}
  function explodeRocket(){
    ensureExplosionStyle();var flight=q('crashRocketFlight'),scene=q('crashRocketScene');if(!flight||!scene)return;
    var old=scene.querySelector('.crash-rocket-explosion-layer');if(old)old.remove();
    flight.classList.remove('is-exploding');
    var sr=scene.getBoundingClientRect(),fr=flight.getBoundingClientRect(),cx=fr.left-sr.left+fr.width*.5,cy=fr.top-sr.top+fr.height*.5;
    var layer=document.createElement('div');layer.className='crash-rocket-explosion-layer';scene.appendChild(layer);
    function piece(cls,x,y){var e=document.createElement('span');e.className='crash-rocket-explosion-piece '+cls;e.style.transform='translate3d('+(x||cx)+'px,'+(y||cy)+'px,0) translate(-50%,-50%)';layer.appendChild(e);return e}
    flight.classList.add('is-exploding');
    var flash=piece('crash-rocket-explosion-flash');flash.animate([{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) scale(.18)',opacity:0},{offset:.14,transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) scale(1.18)',opacity:1},{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) scale(2.05)',opacity:0}],{duration:390,easing:'cubic-bezier(.16,.78,.24,1)',fill:'forwards'});
    var ring=piece('crash-rocket-explosion-ring');ring.animate([{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) scale(.22)',opacity:.9},{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) scale(4.1)',opacity:0}],{duration:620,easing:'cubic-bezier(.12,.7,.22,1)',fill:'forwards'});
    for(var i=0;i<16;i++){var a=(Math.PI*2*i/16)+(Math.random()-.5)*.24,dist=36+Math.random()*62,tx=Math.cos(a)*dist,ty=Math.sin(a)*dist,spark=piece('crash-rocket-explosion-spark');spark.animate([{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) rotate('+(a*180/Math.PI+90)+'deg) scaleY(.55)',opacity:0},{offset:.12,opacity:1},{transform:'translate3d('+(cx+tx)+'px,'+(cy+ty)+'px,0) translate(-50%,-50%) rotate('+(a*180/Math.PI+90)+'deg) scaleY(1.18)',opacity:0}],{duration:420+Math.random()*260,delay:Math.random()*45,easing:'cubic-bezier(.15,.72,.2,1)',fill:'forwards'})}
    for(var j=0;j<8;j++){var da=Math.random()*Math.PI*2,dd=24+Math.random()*54,dx=Math.cos(da)*dd,dy=Math.sin(da)*dd+18,debris=piece('crash-rocket-explosion-debris');debris.animate([{transform:'translate3d('+cx+'px,'+cy+'px,0) translate(-50%,-50%) rotate(0deg) scale(1)',opacity:1},{transform:'translate3d('+(cx+dx)+'px,'+(cy+dy)+'px,0) translate(-50%,-50%) rotate('+(180+Math.random()*420)+'deg) scale(.65)',opacity:0}],{duration:560+Math.random()*360,easing:'cubic-bezier(.18,.68,.26,1)',fill:'forwards'})}
    for(var k=0;k<6;k++){var smoke=piece('crash-rocket-explosion-smoke',cx+(Math.random()-.5)*18,cy+(Math.random()-.5)*14),sx=(Math.random()-.5)*40,sy=-18-Math.random()*34,sc=.7+Math.random()*.6;smoke.animate([{transform:smoke.style.transform+' scale(.45)',opacity:0},{offset:.16,opacity:.34},{transform:'translate3d('+(cx+sx)+'px,'+(cy+sy)+'px,0) translate(-50%,-50%) scale('+(2.1*sc)+')',opacity:0}],{duration:850+Math.random()*420,delay:55+Math.random()*90,easing:'cubic-bezier(.18,.64,.28,1)',fill:'forwards'})}
    explosionSound();
    setTimeout(function(){flight.classList.remove('is-exploding');if(layer&&layer.parentNode)layer.parentNode.removeChild(layer)},1350)
  }
  function resetRocketExplosion(){var flight=q('crashRocketFlight'),scene=q('crashRocketScene');if(flight)flight.classList.remove('is-exploding');if(scene){var layer=scene.querySelector('.crash-rocket-explosion-layer');if(layer)layer.remove()}}
  function triggerBreak(){var n=q('crashMultiplier');if(!n)return;n.setAttribute('data-crash-text',n.textContent||'');n.classList.remove('crash-broken');void n.offsetWidth;n.classList.add('crash-broken');crackSound();explodeRocket()}
  function state(){if(!active())return 'inactive';var label=q('crashNextRound'),txt=String((label&&label.textContent)||'');if(/Crashed/i.test(txt))return 'crashed';if(/Round starts/i.test(txt))return 'waiting';return 'running'}
  function roundKey(){var n=q('crashMultiplier');return String((n&&n.textContent)||'')+'|'+String(Date.now()).slice(0,-3)}
  function sync(){var s=state(),n=q('crashMultiplier');if(s==='inactive'){lastState='inactive';crashedLock=false;resetRocketExplosion();return}unlock();if(s==='running'){crashedLock=false;if(n)n.classList.remove('crash-broken');if(lastState!=='running'){var k=roundKey();if(k!==lastStartKey&&canPlay()){lastStartKey=k;startSound()}}}if(s==='crashed'&&!crashedLock){crashedLock=true;triggerBreak()}if(s==='waiting'&&lastState==='crashed')crashedLock=true;if(s==='waiting'&&n)n.classList.remove('crash-broken');lastState=s}
  function unlockAndSync(){if(!active())return;unlock();sync()}
  function scheduleSync(delay){setTimeout(function(){if(!document.hidden)sync()},delay||0)}
  document.addEventListener('pointerdown',unlockAndSync,true);document.addEventListener('touchstart',unlockAndSync,true);document.addEventListener('click',unlockAndSync,true);
  window.addEventListener('vexa-round-ended',function(){scheduleSync(0)});
  window.addEventListener('vexa-crash-visible',function(){scheduleSync(0)});
  document.addEventListener('visibilitychange',function(){if(!document.hidden)scheduleSync(0)});
  if(window.MutationObserver){var label=q('crashNextRound');if(label)new MutationObserver(function(){sync()}).observe(label,{childList:true,characterData:true,subtree:true})}
  ensureExplosionStyle();resetRocketExplosion();scheduleSync(0);
})();
`;