export const CRASH_LIVE_D1_SCRIPT = `
(function(){
  var UNIT=1000000000;
  var ROUND_GAP_MS=10000,CRASH_HOLD_MS=2200;
  var cache=null,lastSyncAt=0,syncing=false,lastRendered='',localSeq=1,eventTimer=0,currentScheduledRound=0,wasCrashActive=false;
  function ton(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
  function betTon(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(2)}
  function phaseOf(j){var s=j&&j.state||{};if(s.running)return 'running';if(s.inCrashHold)return 'ended';return 'betting'}
  function sortLiveBetsForPhase(bets,phase){return bets.slice().sort(function(a,b){if(phase==='betting'){var aa=Number(a&&a.amountNano)||0,bb=Number(b&&b.amountNano)||0;if(aa!==bb)return bb-aa;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}if(phase==='running'){var ar=a&&a.status==='cashout',br=b&&b.status==='cashout';if(ar!==br)return ar?-1:1;if(ar&&br){var am=Number(a&&a.cashoutMultiplier)||0,bm=Number(b&&b.cashoutMultiplier)||0;if(am!==bm)return bm-am}var aa2=Number(a&&a.amountNano)||0,bb2=Number(b&&b.amountNano)||0;if(aa2!==bb2)return bb2-aa2;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}var rank={cashout:0,crashed:1,bet:2};var ra=rank[a&&a.status]??3,rb=rank[b&&b.status]??3;if(ra!==rb)return ra-rb;var am2=Number(a&&a.cashoutMultiplier)||0,bm2=Number(b&&b.cashoutMultiplier)||0;if(am2!==bm2)return bm2-am2;var aa3=Number(a&&a.amountNano)||0,bb3=Number(b&&b.amountNano)||0;return bb3-aa3})}
  function keyOf(roundId,userId){return String(roundId||'')+'::'+String(userId||'')}
  function mergeBet(bet){if(!bet||!bet.userId)return;var rid=Number(bet.roundId)||Number(cache&&cache.roundId)||0;if(!rid)return;bet=Object.assign({},bet,{roundId:rid});var bets=(cache&&cache.bets)?cache.bets.slice():[];var k=keyOf(bet.roundId,bet.userId),found=false;for(var i=0;i<bets.length;i++){if(keyOf(bets[i].roundId,bets[i].userId)===k){bets[i]=Object.assign({},bets[i],bet);found=true;break}}if(!found)bets.unshift(bet);if(!cache)cache={ok:true,roundId:rid,totalNano:0,bets:[],state:null};cache.bets=bets;cache.totalNano=bets.reduce(function(s,b){return s+Number(b&&b.amountNano||0)},0);render(cache)}
  function markRoundCrashed(roundId){if(!cache||!cache.bets||!roundId)return;var changed=false,bets=cache.bets.map(function(b){if(Number(b&&b.roundId)===Number(roundId)&&b.status==='bet'){changed=true;return Object.assign({},b,{status:'crashed',localOrder:Date.now()+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets,state:Object.assign({},cache.state||{},{running:false,waiting:true,inCrashHold:true})});render(cache)}}
  function markDueVirtualCashouts(roundId,currentValue,stop){if(!cache||!cache.bets)return;var now=Date.now(),changed=false,bets=cache.bets.map(function(b){var target=Number(b&&b.targetCashoutMultiplier)||0;if(Number(b&&b.roundId)===Number(roundId)&&b.isVirtual&&b.status==='bet'&&target>0&&target<=currentValue&&target<stop){changed=true;var payout=Math.max(0,Math.floor((Number(b.amountNano)||0)*target));return Object.assign({},b,{status:'cashout',cashoutMultiplier:target,payoutNano:payout,updatedAt:new Date(now).toISOString(),localOrder:now+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets,state:Object.assign({},cache.state||{},{current:currentValue,running:true,inCrashHold:false})});render(cache)}}
  function amountFor(roundId,userId,payout,m){var bets=(cache&&cache.bets)||[],k=keyOf(roundId,userId);for(var i=0;i<bets.length;i++)if(keyOf(bets[i].roundId,bets[i].userId)===k)return Number(bets[i].amountNano)||0;return payout&&m>0?Math.floor(payout/m):0}
  function tgUser(){var tg=window.Telegram&&window.Telegram.WebApp;var u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;var id=String((u&&u.id)||localStorage.getItem('ownerId')||'local').trim();var name=u?String(u.first_name||u.last_name||'User'):'You';return{id:id||'local',name:name||'User'}}
  function telegramInitData(){var tg=window.Telegram&&window.Telegram.WebApp;return tg?String(tg.initData||''):''}
  function cleanText(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function isCrashActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='crash'&&!document.hidden)}
  function multAt(seconds){return 1+seconds*.06+seconds*seconds*.00105}
  function stopTime(target){target=Math.max(1,Number(target)||1);var lo=0,hi=68000;for(var i=0;i<24;i++){var mid=(lo+hi)/2;if(multAt(mid/1000)>=target)hi=mid;else lo=mid}return hi}
  function clearEventTimer(){if(eventTimer){clearTimeout(eventTimer);eventTimer=0}}
  function setEventTimer(delay,fn){clearEventTimer();var ms=Math.max(0,Math.floor(Number(delay)||0));eventTimer=setTimeout(function(){eventTimer=0;fn()},ms)}
  function cacheStillCurrent(){var state=cache&&cache.state;if(!state)return false;var now=Date.now(),start=Number(state.start)||0,runMs=Number(state.runMs)||0;if(!start||!runMs)return false;var endAt=start+runMs;if(state.inCrashHold&&now>=endAt+CRASH_HOLD_MS)return false;return now<endAt+ROUND_GAP_MS}
  function scheduleSmart(j){
    clearEventTimer();if(!j||!j.ok||!isCrashActive())return;
    var state=j.state||{},now=Date.now(),roundId=Number(j.roundId)||0,start=Number(state.start)||0,runMs=Number(state.runMs)||0;
    currentScheduledRound=roundId;if(!roundId||!start||!runMs)return;
    var endAt=start+runMs,nextStart=endAt+ROUND_GAP_MS;
    if(state.running){
      if(now>=endAt){markRoundCrashed(roundId);setEventTimer(Math.max(80,endAt+CRASH_HOLD_MS-now+80),function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)});return}
      var stop=Number(state.stop)||1,currentValue=Math.min(stop,multAt(Math.max(0,now-start)/1000));markDueVirtualCashouts(roundId,currentValue,stop);
      var bets=(cache&&cache.bets)||[],nextTarget=0;
      for(var i=0;i<bets.length;i++){var b=bets[i],target=Number(b&&b.targetCashoutMultiplier)||0;if(!b||!b.isVirtual||b.status!=='bet'||Number(b.roundId)!==roundId||target<=currentValue||target>=stop)continue;if(!nextTarget||target<nextTarget)nextTarget=target}
      if(nextTarget){var targetAt=start+stopTime(nextTarget);setEventTimer(Math.max(40,targetAt-now+20),function(){if(isCrashActive()&&currentScheduledRound===roundId)scheduleSmart(cache)});return}
      setEventTimer(Math.max(80,endAt-now+60),function(){if(!isCrashActive()||currentScheduledRound!==roundId)return;markRoundCrashed(roundId);setEventTimer(CRASH_HOLD_MS+80,function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)})});return
    }
    if(state.inCrashHold){setEventTimer(Math.max(80,endAt+CRASH_HOLD_MS-now+80),function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)});return}
    var nextReveal=Number(j.nextRevealAtMs)||0;
    if(nextReveal>now){setEventTimer(Math.max(40,nextReveal-now+40),function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)});return}
    var nextSync=Number(j.nextSyncMs)||0;
    if(nextSync>0){setEventTimer(Math.max(80,nextSync),function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)});return}
    if(now>=nextStart){requestSync(true);return}
    setEventTimer(Math.max(80,nextStart-now+80),function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)})
  }
  async function post(path,body){try{var payload=Object.assign({},body||{},{initData:telegramInitData()});var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),keepalive:true});return await r.json().catch(function(){return null})}catch(e){return null}}
  function applyServerState(r){if(!r)return false;var authoritative=false;var balance=Number(r.tonBalanceNano);if(Number.isFinite(balance)&&window.VexaTonBalance&&typeof window.VexaTonBalance.write==='function'){window.VexaTonBalance.write(balance,0,false);authoritative=true}if(r.level){try{window.dispatchEvent(new CustomEvent('vexa-initial-user-state',{detail:{level:r.level}}))}catch(e){}}return authoritative}
  function failEvent(name,detail){try{window.dispatchEvent(new CustomEvent(name,{detail:detail||{}}))}catch(e){}}
  async function pull(){try{var j=await fetch('/app/api/crash-live',{cache:'no-store'}).then(function(r){return r.json().catch(function(){return null})});if(j&&j.ok){cache=j;render(j);scheduleSmart(j)}}catch(e){}}
  function requestSync(force){var now=Date.now();if(!isCrashActive()&&!force)return Promise.resolve();if(syncing)return Promise.resolve();if(cache&&now-lastSyncAt<700){if(isCrashActive())scheduleSmart(cache);return Promise.resolve()}syncing=true;lastSyncAt=now;return pull().finally(function(){syncing=false})}
  function render(j){var list=document.getElementById('crashLiveList'),total=document.getElementById('crashLiveTotal');if(!list||!j||!j.ok)return;if(total)total.textContent=ton(j.totalNano)+' Gram';var phase=phaseOf(j);var bets=sortLiveBetsForPhase(j.bets||[],phase);var html='';if(!bets.length)html='<div class="crash-live-empty">No bets yet</div>';else html=bets.map(function(b){var cash=b.status==='cashout';var crash=b.status==='crashed';var shownNano=cash?Number(b&&b.payoutNano||0):Number(b&&b.amountNano||0);var amount=(cash?'<span class="crash-live-plus">+</span>':'')+cleanText(betTon(shownNano));var m=Number(b&&b.cashoutMultiplier)||0;var status=cash?'<span class="crash-live-mult">'+cleanText(m.toFixed(2).replace(/\.00$/,'')+'×')+'</span>':(crash?'<span class="crash-live-lost">Lost</span>':'Bet');var cls=cash?'cashout':(crash?'crashed':'');return '<div class="crash-live-row '+cls+'"><span class="crash-live-user">'+cleanText(b.user)+'</span><span class="crash-live-amount">'+amount+'</span><span class="crash-live-status">'+status+'</span></div>'}).join('');if(html!==lastRendered){var keepTop=list.scrollTop||0;list.innerHTML=html;lastRendered=html;if(keepTop>0)requestAnimationFrame(function(){list.scrollTop=keepTop})}}
  function bindDrawer(){var box=document.getElementById('crashLive'),btn=document.getElementById('crashLiveToggle'),app=document.querySelector('main.app');if(!box||!btn)return;btn.onclick=function(){var open=!box.classList.contains('open');if(!open&&app)app.scrollTop=0;box.classList.toggle('open',open);btn.setAttribute('aria-expanded',open?'true':'false')}}
  function ensureCrashLoaded(){if(!isCrashActive()){clearEventTimer();wasCrashActive=false;return}if(!wasCrashActive){wasCrashActive=true;if(cacheStillCurrent()){render(cache);scheduleSmart(cache)}else requestSync(true)}}
  function bind(){bindDrawer();window.addEventListener('vexa-crash-bet',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;var amount=Math.max(0,Math.floor(Number(d.amountNano)||0));if(!rid||!amount)return;mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/bet',{roundId:rid,userId:u.id,username:u.name,amountNano:amount}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){mergeBet({roundId:Number(r.roundId)||rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return}failEvent('vexa-crash-bet-failed',{roundId:rid,error:r&&r.error?r.error:'Bet failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-crash-cashout',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;var m=Number(d.multiplier)||1;var payout=Number(d.payoutNano)||0;if(!rid)return;var amount=amountFor(rid,u.id,payout,m);mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'cashout',cashoutMultiplier:m,payoutNano:payout,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/cashout',{roundId:rid,userId:u.id,multiplier:m}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){mergeBet({roundId:rid,userId:u.id,user:u.name,status:'cashout',cashoutMultiplier:m,payoutNano:Number(r.payoutNano)||payout,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return}failEvent('vexa-crash-cashout-failed',{roundId:rid,error:r&&r.error?r.error:'Cashout failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-crash-lost',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;if(!rid)return;markRoundCrashed(rid);post('/app/api/crash-live/crash',{roundId:rid,userId:u.id}).then(function(r){applyServerState(r)})});window.addEventListener('vexa-round-ended',function(ev){var d=ev&&ev.detail||{};var rid=Number(d.roundId)||0;markRoundCrashed(rid);if(rid&&isCrashActive()){currentScheduledRound=rid;setEventTimer(CRASH_HOLD_MS+80,function(){if(isCrashActive()&&currentScheduledRound===rid)requestSync(true)})}});window.addEventListener('vexa-crash-visible',ensureCrashLoaded);window.addEventListener('vexa-crash-hidden',function(){clearEventTimer();wasCrashActive=false});document.addEventListener('visibilitychange',function(){if(document.hidden){clearEventTimer();wasCrashActive=false}else ensureCrashLoaded()});if(window.MutationObserver){var root=document.getElementById('crash');if(root)new MutationObserver(ensureCrashLoaded).observe(root,{attributes:true,attributeFilter:['class']})}ensureCrashLoaded()}
  window.VexaCrashLiveD1={load:function(){return requestSync(true)},postBet:function(amountNano,roundId){var u=tgUser(),rid=Number(roundId)||Number(cache&&cache.roundId)||0;mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amountNano,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return post('/app/api/crash-live/bet',{roundId:rid,userId:u.id,username:u.name,amountNano:amountNano}).then(function(r){applyServerState(r);return r})},postCashout:function(roundId,multiplier){var u=tgUser();return post('/app/api/crash-live/cashout',{roundId:roundId,userId:u.id,multiplier:multiplier}).then(function(r){applyServerState(r);return r})},refresh:function(){return requestSync(true)}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;