export const CRASH_LIVE_D1_SCRIPT = `
(function(){
  var UNIT=1000000000;
  var ROUND_GAP_MS=10000;
  var cache=null, lastSyncAt=0, syncing=false, lastRendered='', localSeq=1, eventTimers=[], currentScheduledRound=0, wasCrashActive=false;
  function ton(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
  function betTon(n,isVirtual){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(2)}
  function payoutOf(b){var payout=Number(b&&b.payoutNano)||0;if(payout>0)return Math.max(0,Math.floor(payout));var m=Number(b&&b.cashoutMultiplier)||0,amount=Number(b&&b.amountNano)||0;return m>0&&amount>0?Math.max(0,Math.floor(amount*m)):0}
  function phaseOf(j){var s=j&&j.state||{};if(s.running)return 'running';if(s.inCrashHold)return 'ended';return 'betting'}
  function sortLiveBetsForPhase(bets,phase){return bets.slice().sort(function(a,b){if(phase==='betting'){var aa=Number(a&&a.amountNano)||0,bb=Number(b&&b.amountNano)||0;if(aa!==bb)return bb-aa;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}if(phase==='running'){var ar=a&&a.status==='cashout',br=b&&b.status==='cashout';if(ar!==br)return ar?-1:1;if(ar&&br){var am=Number(a&&a.cashoutMultiplier)||0,bm=Number(b&&b.cashoutMultiplier)||0;if(am!==bm)return bm-am}var aa2=Number(a&&a.amountNano)||0,bb2=Number(b&&b.amountNano)||0;if(aa2!==bb2)return bb2-aa2;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}var rank={cashout:0,crashed:1,bet:2};var ra=rank[a&&a.status]??3,rb=rank[b&&b.status]??3;if(ra!==rb)return ra-rb;var am2=Number(a&&a.cashoutMultiplier)||0,bm2=Number(b&&b.cashoutMultiplier)||0;if(am2!==bm2)return bm2-am2;var aa3=Number(a&&a.amountNano)||0,bb3=Number(b&&b.amountNano)||0;return bb3-aa3})}
  function keyOf(roundId,userId){return String(roundId||'')+'::'+String(userId||'')}
  function mergeBet(bet){if(!bet||!bet.userId)return;var rid=Number(bet.roundId)||Number(cache&&cache.roundId)||0;if(!rid)return;bet=Object.assign({},bet,{roundId:rid});var bets=(cache&&cache.bets)?cache.bets.slice():[];var k=keyOf(bet.roundId,bet.userId),found=false;for(var i=0;i<bets.length;i++){if(keyOf(bets[i].roundId,bets[i].userId)===k){bets[i]=Object.assign({},bets[i],bet);found=true;break}}if(!found)bets.unshift(bet);if(!cache)cache={ok:true,roundId:rid,totalNano:0,bets:[],state:null};cache.bets=bets;cache.totalNano=bets.reduce(function(s,b){return s+Number(b&&b.amountNano||0)},0);render(cache)}
  function markRoundCrashed(roundId){if(!cache||!cache.bets||!roundId)return;var changed=false,bets=cache.bets.map(function(b){if(Number(b&&b.roundId)===Number(roundId)&&b.status==='bet'){changed=true;return Object.assign({},b,{status:'crashed',localOrder:Date.now()+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets,state:Object.assign({},cache.state||{},{running:false,waiting:true,inCrashHold:true})});render(cache)}}
  function markVirtualCashout(roundId,userId,m){if(!cache||!cache.bets)return;var changed=false,bets=cache.bets.map(function(b){if(keyOf(b.roundId,b.userId)===keyOf(roundId,userId)&&b.isVirtual&&b.status==='bet'){changed=true;var payout=Math.max(0,Math.floor((Number(b.amountNano)||0)*m));return Object.assign({},b,{status:'cashout',cashoutMultiplier:m,payoutNano:payout,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets,state:Object.assign({},cache.state||{},{running:true,inCrashHold:false})});render(cache)}}
  function amountFor(roundId,userId,payout,m){var bets=(cache&&cache.bets)||[],k=keyOf(roundId,userId);for(var i=0;i<bets.length;i++)if(keyOf(bets[i].roundId,bets[i].userId)===k)return Number(bets[i].amountNano)||0;return payout&&m>0?Math.floor(payout/m):0}
  function tgUser(){var tg=window.Telegram&&window.Telegram.WebApp;var u=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user;var id=String((u&&u.id)||localStorage.getItem('ownerId')||'local').trim();var name=u?String(u.first_name||u.last_name||'User'):'You';return{id:id||'local',name:name||'User'}}
  function cleanText(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function isCrashActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='crash'&&!document.hidden)}
  function multAt(seconds){return 1+seconds*.12+seconds*seconds*.0042}
  function stopTime(target){target=Math.max(1,Number(target)||1);var lo=0,hi=34000;for(var i=0;i<24;i++){var mid=(lo+hi)/2;if(multAt(mid/1000)>=target)hi=mid;else lo=mid}return hi}
  function clearEventTimers(){eventTimers.forEach(function(t){clearTimeout(t)});eventTimers=[]}
  function setEventTimer(delay,fn){var ms=Math.max(0,Math.floor(Number(delay)||0));var id=setTimeout(function(){eventTimers=eventTimers.filter(function(x){return x!==id});fn()},ms);eventTimers.push(id)}
  function scheduleRoundLoad(roundId,atMs){var delay=Math.max(0,Math.floor(Number(atMs||0)-Date.now()));setEventTimer(delay,function(){if(isCrashActive()&&currentScheduledRound===roundId)requestSync(true)})}
  function scheduleSmart(j){clearEventTimers();if(!j||!j.ok||!isCrashActive())return;var state=j.state||{},now=Date.now(),roundId=Number(j.roundId)||0,bets=j.bets||[];currentScheduledRound=roundId;
    bets.forEach(function(b){var target=Number(b&&b.targetCashoutMultiplier)||0;if(!state.running||!b.isVirtual||b.status!=='bet'||!target||target>=Number(state.stop||0))return;var at=Number(state.start||0)+stopTime(target);if(at<=now+40){markVirtualCashout(roundId,b.userId,target);return}setEventTimer(at-now,function(){markVirtualCashout(roundId,b.userId,target)})});
    var start=Number(state.start)||0,runMs=Number(state.runMs)||0,nextInMs=Number(state.nextInMs)||0;
    if(state.running&&roundId){var endAt=start+runMs;setEventTimer(Math.max(120,endAt-now+80),function(){markRoundCrashed(roundId)});scheduleRoundLoad(roundId,endAt+ROUND_GAP_MS+120);return}
    if(state.waiting&&roundId){scheduleRoundLoad(roundId,start+runMs+nextInMs+90)}
  }
  async function post(path,body){for(var attempt=0;attempt<2;attempt++){try{var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),keepalive:true});var j=await r.json().catch(function(){return null});if(j)return j}catch(e){}}return null}
  function applyServerState(r){if(!r)return false;var authoritative=false;var balance=Number(r.tonBalanceNano);if(Number.isFinite(balance)&&window.VexaTonBalance&&typeof window.VexaTonBalance.write==='function'){window.VexaTonBalance.write(balance,0,false);authoritative=true}if(r.level){try{window.dispatchEvent(new CustomEvent('vexa-initial-user-state',{detail:{level:r.level}}))}catch(e){}}return authoritative}
  function failEvent(name,detail){try{window.dispatchEvent(new CustomEvent(name,{detail:detail||{}}))}catch(e){}}
  async function pull(){try{var j=await fetch('/app/api/crash-live',{cache:'no-store'}).then(function(r){return r.json().catch(function(){return null})});if(j&&j.ok){cache=j;render(j);scheduleSmart(j)}}catch(e){}}
  function requestSync(force){var now=Date.now();if(!isCrashActive()&&!force)return Promise.resolve();if(force&&cache&&now-lastSyncAt<700)return Promise.resolve();if(!force&&now-lastSyncAt<15000)return Promise.resolve();if(syncing)return Promise.resolve();syncing=true;lastSyncAt=now;return pull().finally(function(){syncing=false})}
  function render(j){var list=document.getElementById('crashLiveList'),total=document.getElementById('crashLiveTotal');if(!list||!j||!j.ok)return;if(total)total.textContent=ton(j.totalNano)+' TON';var phase=phaseOf(j);var bets=sortLiveBetsForPhase(j.bets||[],phase);var html='';if(!bets.length)html='<div class="crash-live-empty">No bets yet</div>';else html=bets.map(function(b){var cash=b.status==='cashout';var crash=b.status==='crashed';var betAmount=betTon(Number(b&&b.amountNano||0),b.isVirtual)+' TON';var amount=(cash?'<span class="crash-live-plus">+</span>':'')+cleanText(betAmount);var m=Number(b&&b.cashoutMultiplier)||0;var status=cash?'<span class="crash-live-mult">'+cleanText(m.toFixed(2).replace(/\.00$/,'')+'×')+'</span>':(crash?'<span class="crash-live-lost">Lost</span>':'Bet');var cls=cash?'cashout':(crash?'crashed':'');return '<div class="crash-live-row '+cls+'"><span class="crash-live-user">'+cleanText(b.user)+'</span><span class="crash-live-amount">'+amount+'</span><span class="crash-live-status">'+status+'</span></div>'}).join('');if(html!==lastRendered){var keepTop=list.scrollTop||0;list.innerHTML=html;lastRendered=html;if(keepTop>0)requestAnimationFrame(function(){list.scrollTop=keepTop})}}
  function bindDrawer(){var box=document.getElementById('crashLive'),btn=document.getElementById('crashLiveToggle'),list=document.getElementById('crashLiveList');if(list&&!list.dataset.scrollBound){list.dataset.scrollBound='1';['touchstart','touchmove','wheel'].forEach(function(type){list.addEventListener(type,function(ev){if(list.scrollHeight>list.clientHeight)ev.stopPropagation()},{passive:true})})}if(!box||!btn)return;btn.onclick=function(){var open=!box.classList.contains('open');box.classList.toggle('open',open);btn.setAttribute('aria-expanded',open?'true':'false')}}
  function ensureCrashLoaded(){if(!isCrashActive()){clearEventTimers();wasCrashActive=false;return}if(!wasCrashActive){wasCrashActive=true;requestSync(true)}}
  function bind(){bindDrawer();window.addEventListener('vexa-crash-bet',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;var amount=Math.max(0,Math.floor(Number(d.amountNano)||0));if(!rid||!amount)return;mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/bet',{roundId:rid,userId:u.id,username:u.name,amountNano:amount}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){mergeBet({roundId:Number(r.roundId)||rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return}failEvent('vexa-crash-bet-failed',{roundId:rid,error:r&&r.error?r.error:'Bet failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-crash-cashout',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;var m=Number(d.multiplier)||1;var payout=Number(d.payoutNano)||0;if(!rid)return;var amount=amountFor(rid,u.id,payout,m);mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'cashout',cashoutMultiplier:m,payoutNano:payout,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/cashout',{roundId:rid,userId:u.id,multiplier:m}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){mergeBet({roundId:rid,userId:u.id,user:u.name,status:'cashout',cashoutMultiplier:m,payoutNano:Number(r.payoutNano)||payout,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return}failEvent('vexa-crash-cashout-failed',{roundId:rid,error:r&&r.error?r.error:'Cashout failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-crash-lost',function(ev){var u=tgUser(),d=ev.detail||{};var rid=Number(d.roundId)||0;if(!rid)return;markRoundCrashed(rid);post('/app/api/crash-live/crash',{roundId:rid,userId:u.id}).then(function(r){applyServerState(r)})});window.addEventListener('vexa-round-ended',function(ev){var d=ev&&ev.detail||{};markRoundCrashed(Number(d.roundId)||0)});document.addEventListener('visibilitychange',function(){if(document.hidden){clearEventTimers();wasCrashActive=false}else ensureCrashLoaded()});if(window.MutationObserver){var root=document.getElementById('crash');if(root)new MutationObserver(ensureCrashLoaded).observe(root,{attributes:true,attributeFilter:['class']})}ensureCrashLoaded()}
  window.VexaCrashLiveD1={load:function(){return requestSync(true)},postBet:function(amountNano,roundId){var u=tgUser(),rid=Number(roundId)||Number(cache&&cache.roundId)||0;mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amountNano,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return post('/app/api/crash-live/bet',{roundId:rid,userId:u.id,username:u.name,amountNano:amountNano}).then(function(r){applyServerState(r);return r})},postCashout:function(roundId,multiplier){var u=tgUser();return post('/app/api/crash-live/cashout',{roundId:roundId,userId:u.id,multiplier:multiplier}).then(function(r){applyServerState(r);return r})},refresh:function(){return requestSync(true)}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;