export const CRASH_LIVE_D1_SCRIPT = `
(function(){
  var UNIT=1000000000;
  var cache=null,lastRendered='',localSeq=1,eventTimer=0,lastRoundId=0,lastPhase='',wasCrashActive=false;
  function ton(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(4).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
  function betTon(n){var v=Math.max(0,Math.floor(Number(n)||0))/UNIT;return v.toFixed(2)}
  function keyOf(roundId,userId){return String(roundId||'')+'::'+String(userId||'')}
  function tg(){var app=window.Telegram&&window.Telegram.WebApp;var u=app&&app.initDataUnsafe&&app.initDataUnsafe.user;var id=String((u&&u.id)||localStorage.getItem('ownerId')||'local').trim();var name=u?String(u.first_name||u.last_name||'User'):'You';return{id:id||'local',name:name||'User',initData:String(app&&app.initData||'')}}
  function cleanText(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function isCrashActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='crash'&&!document.hidden)}
  function clearEventTimer(){if(eventTimer){clearTimeout(eventTimer);eventTimer=0}}
  function setEventTimer(delay,fn){clearEventTimer();eventTimer=setTimeout(function(){eventTimer=0;fn()},Math.max(0,Math.floor(Number(delay)||0)))}
  function stateNow(){var api=window.VexaCrashRound;return api&&typeof api.getState==='function'?api.getState():null}
  function mergeBet(bet){if(!bet||!bet.userId)return;var rid=Number(bet.roundId)||Number(cache&&cache.roundId)||0;if(!rid)return;bet=Object.assign({},bet,{roundId:rid});var bets=(cache&&cache.bets)?cache.bets.slice():[];var k=keyOf(rid,bet.userId),found=false;for(var i=0;i<bets.length;i++){if(keyOf(bets[i].roundId,bets[i].userId)===k){bets[i]=Object.assign({},bets[i],bet);found=true;break}}if(!found)bets.unshift(bet);if(!cache)cache={ok:true,roundId:rid,bets:[],state:stateNow()};cache.bets=bets;render(cache)}
  function markRoundCrashed(roundId){if(!cache||!cache.bets||!roundId)return;var changed=false,bets=cache.bets.map(function(b){if(Number(b&&b.roundId)===Number(roundId)&&b.status==='bet'){changed=true;return Object.assign({},b,{status:'crashed',localOrder:Date.now()+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets});render(cache)}}
  function markDueVirtualCashouts(roundId,value){if(!cache||!cache.bets)return;var now=Date.now(),changed=false,bets=cache.bets.map(function(b){var target=Number(b&&b.targetCashoutMultiplier)||0;if(Number(b&&b.roundId)===Number(roundId)&&b.isVirtual&&b.status==='bet'&&target>0&&target<=value){changed=true;var payout=Math.max(0,Math.floor((Number(b.amountNano)||0)*target));return Object.assign({},b,{status:'cashout',cashoutMultiplier:target,payoutNano:payout,updatedAt:new Date(now).toISOString(),localOrder:now+localSeq++})}return b});if(changed){cache=Object.assign({},cache,{bets:bets});render(cache)}}
  function amountFor(roundId,userId,payout,m){var bets=(cache&&cache.bets)||[],k=keyOf(roundId,userId);for(var i=0;i<bets.length;i++)if(keyOf(bets[i].roundId,bets[i].userId)===k)return Number(bets[i].amountNano)||0;return payout&&m>0?Math.floor(payout/m):0}
  function visibleBets(){var now=Date.now(),bets=(cache&&cache.bets)||[];return bets.filter(function(b){return !b.isVirtual||Number(b.virtualRevealAtMs||0)<=now})}
  function sortLiveBetsForPhase(bets,phase){return bets.slice().sort(function(a,b){if(phase==='betting'){var aa=Number(a&&a.amountNano)||0,bb=Number(b&&b.amountNano)||0;if(aa!==bb)return bb-aa;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}if(phase==='running'){var ar=a&&a.status==='cashout',br=b&&b.status==='cashout';if(ar!==br)return ar?-1:1;if(ar&&br){var am=Number(a&&a.cashoutMultiplier)||0,bm=Number(b&&b.cashoutMultiplier)||0;if(am!==bm)return bm-am}var aa2=Number(a&&a.amountNano)||0,bb2=Number(b&&b.amountNano)||0;if(aa2!==bb2)return bb2-aa2;return (Number(a&&a.virtualOrder)||0)-(Number(b&&b.virtualOrder)||0)}var rank={cashout:0,crashed:1,bet:2};var ra=rank[a&&a.status]??3,rb=rank[b&&b.status]??3;if(ra!==rb)return ra-rb;var am2=Number(a&&a.cashoutMultiplier)||0,bm2=Number(b&&b.cashoutMultiplier)||0;if(am2!==bm2)return bm2-am2;var aa3=Number(a&&a.amountNano)||0,bb3=Number(b&&b.amountNano)||0;return bb3-aa3})}
  function render(j){var list=document.getElementById('crashLiveList'),total=document.getElementById('crashLiveTotal');if(!list||!j||!j.ok)return;var state=stateNow()||j.state||{},phase=state.phase||'betting',bets=sortLiveBetsForPhase(visibleBets(),phase),totalNano=bets.reduce(function(sum,b){return sum+Number(b&&b.amountNano||0)},0);if(total)total.textContent=ton(totalNano)+' Gram';var html='';if(!bets.length)html='<div class="crash-live-empty">No bets yet</div>';else html=bets.map(function(b){var cash=b.status==='cashout',crash=b.status==='crashed',shownNano=cash?Number(b&&b.payoutNano||0):Number(b&&b.amountNano||0),amount=(cash?'<span class="crash-live-plus">+</span>':'')+cleanText(betTon(shownNano)),m=Number(b&&b.cashoutMultiplier)||0,status=cash?'<span class="crash-live-mult">'+cleanText(m.toFixed(2).replace(/\.00$/,'')+'×')+'</span>':(crash?'<span class="crash-live-lost">Lost</span>':'Bet'),cls=cash?'cashout':(crash?'crashed':'');return '<div class="crash-live-row '+cls+'"><span class="crash-live-user">'+cleanText(b.user)+'</span><span class="crash-live-amount">'+amount+'</span><span class="crash-live-status">'+status+'</span></div>'}).join('');if(html!==lastRendered){var keepTop=list.scrollTop||0;list.innerHTML=html;lastRendered=html;if(keepTop>0)requestAnimationFrame(function(){list.scrollTop=keepTop})}}
  function scheduleNextReveal(){clearEventTimer();if(!cache||!isCrashActive())return;var state=stateNow();if(!state||state.phase!=='betting')return;var now=Date.now(),next=0,bets=cache.bets||[];for(var i=0;i<bets.length;i++){var r=Number(bets[i]&&bets[i].virtualRevealAtMs)||0;if(bets[i]&&bets[i].isVirtual&&r>now&&(!next||r<next))next=r}if(!next)return;setEventTimer(next-now+12,function(){render(cache);scheduleNextReveal()})}
  async function post(path,body){try{var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),keepalive:true});return await r.json().catch(function(){return null})}catch(e){return null}}
  function applyServerState(r){if(!r)return false;var authoritative=false,balance=Number(r.tonBalanceNano);if(Number.isFinite(balance)&&window.VexaTonBalance&&typeof window.VexaTonBalance.write==='function'){window.VexaTonBalance.write(balance,0,false);authoritative=true}if(r.level){try{window.dispatchEvent(new CustomEvent('vexa-initial-user-state',{detail:{level:r.level}}))}catch(e){}}return authoritative}
  function failEvent(name,detail){try{window.dispatchEvent(new CustomEvent(name,{detail:detail||{}}))}catch(e){}}
  async function pull(roundId){var u=tg();if(!u.initData||!roundId)return;try{var j=await fetch('/app/api/crash-live?roundId='+encodeURIComponent(String(roundId))+'&initData='+encodeURIComponent(u.initData),{cache:'no-store'}).then(function(r){return r.json().catch(function(){return null})});if(j&&j.ok){cache=j;render(j);var state=stateNow()||j.state;if(state&&state.phase==='running')markDueVirtualCashouts(roundId,Number(state.current)||1);else if(state&&state.phase==='betting')scheduleNextReveal();else if(state&&state.phase==='ended')markRoundCrashed(roundId)}}catch(e){}}
  function applyRoundState(state){if(!state||!state.id)return;var roundId=Number(state.id)||0,phase=String(state.phase||'');if(!roundId)return;if(!cache||Number(cache.roundId)!==roundId){lastRoundId=roundId;lastPhase=phase;pull(roundId);return}cache=Object.assign({},cache,{state:state});if(phase==='running'){clearEventTimer();markDueVirtualCashouts(roundId,Number(state.current)||1)}else if(phase==='ended'){clearEventTimer();markRoundCrashed(roundId)}else{scheduleNextReveal()}render(cache);lastRoundId=roundId;lastPhase=phase}
  function bindDrawer(){var box=document.getElementById('crashLive'),btn=document.getElementById('crashLiveToggle'),list=document.getElementById('crashLiveList');if(list&&!list.dataset.scrollBound){list.dataset.scrollBound='1';['touchstart','touchmove','wheel'].forEach(function(type){list.addEventListener(type,function(ev){if(list.scrollHeight>list.clientHeight)ev.stopPropagation()},{passive:true})})}if(!box||!btn)return;btn.onclick=function(){var open=!box.classList.contains('open');box.classList.toggle('open',open);btn.setAttribute('aria-expanded',open?'true':'false')}}
  function ensureCrashLoaded(){if(!isCrashActive()){clearEventTimer();wasCrashActive=false;return}if(!wasCrashActive){wasCrashActive=true;var state=stateNow();if(state)applyRoundState(state)}}
  function bind(){bindDrawer();window.addEventListener('vexa-crash-state',function(ev){applyRoundState(ev&&ev.detail||null)});window.addEventListener('vexa-crash-bet',function(ev){var u=tg(),d=ev.detail||{},rid=Number(d.roundId)||0,amount=Math.max(0,Math.floor(Number(d.amountNano)||0));if(!rid||!amount)return;mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/bet',{roundId:rid,initData:u.initData,username:u.name,amountNano:amount}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){mergeBet({roundId:Number(r.roundId)||rid,userId:u.id,user:u.name,amountNano:amount,status:'bet',isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});return}failEvent('vexa-crash-bet-failed',{roundId:rid,error:r&&r.error?r.error:'Bet failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-crash-cashout',function(ev){var u=tg(),d=ev.detail||{},rid=Number(d.roundId)||0,m=Number(d.multiplier)||1,payout=Number(d.payoutNano)||0;if(!rid)return;var amount=amountFor(rid,u.id,payout,m);mergeBet({roundId:rid,userId:u.id,user:u.name,amountNano:amount,status:'cashout',cashoutMultiplier:m,payoutNano:payout,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});post('/app/api/crash-live/cashout',{roundId:rid,initData:u.initData}).then(function(r){var authoritative=applyServerState(r);if(r&&r.ok){var sm=Number(r.multiplier)||m,sp=Number(r.payoutNano)||payout;mergeBet({roundId:rid,userId:u.id,user:u.name,status:'cashout',cashoutMultiplier:sm,payoutNano:sp,isVirtual:false,updatedAt:new Date().toISOString(),localOrder:Date.now()+localSeq++});try{window.dispatchEvent(new CustomEvent('vexa-crash-cashout-confirmed',{detail:{roundId:rid,multiplier:sm,payoutNano:sp}}))}catch(e){}return}failEvent('vexa-crash-cashout-failed',{roundId:rid,error:r&&r.error?r.error:'Cashout failed',authoritativeBalance:authoritative})})});window.addEventListener('vexa-round-ended',function(ev){var d=ev&&ev.detail||{},rid=Number(d.roundId)||0;if(rid){clearEventTimer();markRoundCrashed(rid)}});window.addEventListener('vexa-crash-visible',ensureCrashLoaded);window.addEventListener('vexa-crash-hidden',function(){clearEventTimer();wasCrashActive=false});document.addEventListener('visibilitychange',function(){if(document.hidden){clearEventTimer();wasCrashActive=false}else ensureCrashLoaded()});ensureCrashLoaded()}
  window.VexaCrashLiveD1={load:function(){var state=stateNow();return state?pull(Number(state.id)||0):Promise.resolve()}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
`;
