export const CRASH_CONTROLS_MODERN_STYLES = `
html body:has(#crash.active) #crash.crash-view .crash-controls,#crash .crash-controls{position:relative!important;margin:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;padding:14px!important;display:grid!important;gap:10px!important;align-content:space-between!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:visible!important;isolation:isolate!important}
#crash .crash-controls:before,#crash .crash-controls:after{display:none!important}
#crash .crash-controls *{box-sizing:border-box!important}
#crash .crash-control-grid{display:grid!important;grid-template-columns:1fr!important;gap:0!important;align-items:stretch!important}
#crash .crash-field{min-width:0!important;min-height:44px!important;height:44px!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;padding:0 12px!important;text-align:left!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;margin:0!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important}
#crash .crash-field small,#crash .crash-label{display:block!important;color:rgba(255,255,255,.72)!important;font-size:11px!important;line-height:1!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;white-space:nowrap!important;text-shadow:none!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field b{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:4px!important;margin-top:0!important;font-size:20px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.04em!important;font-variant-numeric:tabular-nums lining-nums!important;white-space:nowrap!important;color:#fff!important;min-width:0!important;overflow:hidden!important}
#crash .crash-field b>span:first-child{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field i{font-style:normal!important;font-size:18px!important;line-height:normal!important;color:rgba(255,255,255,.72)!important;font-weight:800!important;flex:0 0 auto!important}
#crash .crash-auto-field{margin-top:0!important}
#crash .crash-auto{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:3px!important;width:auto!important;min-width:0!important;height:auto!important;min-height:0!important;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
#crash .crash-auto input{width:50px!important;min-width:0!important;height:auto!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:right!important;font:inherit!important;font-size:20px!important;font-weight:950!important;line-height:1!important;letter-spacing:-.04em!important;box-shadow:none!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-auto input::-webkit-outer-spin-button,#crash .crash-auto input::-webkit-inner-spin-button,#crash .crash-bet-main input::-webkit-outer-spin-button,#crash .crash-bet-main input::-webkit-inner-spin-button{appearance:none!important;-webkit-appearance:none!important;margin:0!important}
#crash .crash-auto span{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:0!important;color:#fff!important;font-size:20px!important;font-weight:950!important;line-height:1!important;flex:0 0 auto!important}
#crash .crash-bet{display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;gap:8px!important;align-items:center!important}
#crash .crash-bet button{height:40px!important;border:0!important;border-radius:16px!important;background:rgba(255,255,255,.075)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:20px!important;font-weight:950!important;letter-spacing:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;text-shadow:none!important;overflow:hidden!important}
#crash .crash-bet-main{height:44px!important;border:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0 12px!important;min-width:0!important;font-size:20px!important;font-weight:950!important;overflow:hidden!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
#crash .crash-bet-main.active{background:rgba(13,13,13,.54)!important;border:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important}
#crash .crash-bet-main input{width:100%!important;height:42px!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:center!important;font-size:20px!important;font-weight:950!important;letter-spacing:-.025em!important;box-shadow:none!important;padding:0!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-primary,#crash .crash-secondary{height:38px!important;border-radius:16px!important;border:1px solid rgba(255,255,255,.12)!important;outline:0!important;background:#030303!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-weight:900!important;letter-spacing:-.025em!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;text-shadow:none!important;overflow:hidden!important}
#crash.bet-locked .crash-bet button,#crash.bet-locked .crash-bet-main{opacity:.55!important;pointer-events:none!important}
#crash.bet-locked .crash-bet-main input{opacity:1!important;pointer-events:none!important}
#crash .crash-bet-main input::placeholder,#crash .crash-auto input::placeholder{color:rgba(255,255,255,.42)!important;-webkit-text-fill-color:rgba(255,255,255,.42)!important}
#crash .crash-bet button.active{background:rgba(255,255,255,.075)!important;border:0!important}
#crash .crash-bet button:focus-visible,#crash .crash-primary:focus-visible,#crash .crash-secondary:focus-visible{outline:0!important;box-shadow:none!important}
#crash .crash-bet-main:focus-within{outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important}
#crash .crash-actions{display:grid!important;grid-template-columns:1fr!important;gap:0!important;margin-top:0!important}
#crash .crash-primary,#crash .crash-secondary{height:42px!important;border-radius:17px!important;background:#3b0715!important;border-color:rgba(255,96,128,.18)!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;font-size:15px!important;box-shadow:0 10px 22px rgba(0,0,0,.26),inset 0 1px 0 rgba(255,255,255,.08)!important;transition:transform .18s ease,opacity .18s ease,background .18s ease,color .18s ease!important}
#crash .crash-primary.cashout{background:#0f3f2a!important;border-color:rgba(120,255,179,.22)!important;color:#d8ffe8!important;-webkit-text-fill-color:#d8ffe8!important;box-shadow:0 10px 22px rgba(0,0,0,.26),inset 0 1px 0 rgba(255,255,255,.08)!important}
#crash .crash-primary.cashout:disabled{opacity:1!important;transform:none!important;filter:none!important;background:#0f3f2a!important;color:#d8ffe8!important;-webkit-text-fill-color:#d8ffe8!important}
#crash .crash-primary:not(:disabled):active,#crash .crash-secondary:not(:disabled):active,#crash .crash-bet button:active{transform:scale(.975)!important}
#crash .crash-primary:disabled,#crash .crash-secondary:disabled{opacity:.58!important;transform:scale(.985)!important;filter:none!important}
#crash .crash-history{position:absolute!important;left:18px!important;right:18px!important;top:12px!important;z-index:5!important;display:flex!important;gap:6px!important;overflow-x:auto!important;overflow-y:visible!important;margin:0!important;min-height:28px!important;padding:4px!important;scrollbar-width:none!important;visibility:visible!important;opacity:1!important;clip-path:none!important;background:rgba(255,255,255,.018)!important;border:0!important;border-radius:16px!important;box-shadow:none!important;backdrop-filter:blur(2px)!important;-webkit-backdrop-filter:blur(2px)!important}
#crash .crash-history::-webkit-scrollbar{display:none!important}
#crash .crash-history span{flex:0 0 auto!important;border-radius:999px!important;padding:4px 8px!important;min-height:20px!important;line-height:12px!important;font-size:10px!important;font-weight:890!important;color:rgba(255,255,255,.94)!important;background:transparent!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;clip-path:none!important}
html body:has(#crash.active) #crash.crash-view #crashLive,#crash .crash-live{border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;padding:14px!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),padding .28s ease,opacity .2s ease!important;max-height:min(430px,calc(100dvh - 238px))!important;display:flex!important;flex-direction:column!important;min-height:0!important}
#crash .crash-live:not(.open){max-height:54px!important;padding-bottom:12px!important}
#crash .crash-live-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:10px!important;color:#fff!important;font-size:16px!important;font-weight:950!important;letter-spacing:0!important;text-transform:none!important}
#crash .crash-live-title{display:inline-flex!important;align-items:center!important;gap:7px!important;min-width:0!important;color:#fff!important;font-size:16px!important;font-weight:950!important}
#crash .crash-live-title svg{width:17px!important;height:17px!important;display:block!important;flex:0 0 auto!important;color:rgba(255,255,255,.72)!important}
#crash .crash-live-title svg path{fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#crash .crash-live-title span{display:inline-block!important;white-space:nowrap!important}
#crash .crash-live-head-actions{display:flex!important;align-items:center!important;gap:8px!important}
#crash .crash-live-head b{color:rgba(255,255,255,.92)!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important}
#crash .crash-live-toggle{width:28px!important;height:28px!important;border:0!important;outline:0!important;border-radius:10px!important;background:rgba(255,255,255,.075)!important;color:rgba(255,255,255,.85)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important;transition:transform .22s ease,background .18s ease!important}
#crash .crash-live-toggle svg{width:18px!important;height:18px!important;display:block!important;transition:transform .28s cubic-bezier(.2,.8,.2,1)!important}
#crash .crash-live-toggle path{fill:none!important;stroke:currentColor!important;stroke-width:2.4!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#crash .crash-live.open .crash-live-toggle svg{transform:rotate(180deg)!important}
#crash .crash-live-toggle:active{transform:scale(.94)!important;background:rgba(255,255,255,.12)!important}
#crash .crash-live-list{display:grid!important;gap:8px!important;max-height:min(394px,calc(100dvh - 300px))!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;pointer-events:auto!important;padding-right:2px!important;scrollbar-width:thin!important;scrollbar-color:rgba(255,255,255,.18) transparent!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),opacity .22s ease!important}
#crash .crash-live:not(.open) .crash-live-list{max-height:0!important;opacity:0!important;pointer-events:none!important}
#crash .crash-live-list::-webkit-scrollbar{width:4px!important;display:block!important}
#crash .crash-live-list::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18)!important;border-radius:999px!important}
#crash .crash-live-empty{font-size:12px!important;font-weight:820!important;color:rgba(255,255,255,.45)!important;padding:14px 0!important;text-align:center!important}
#crash .crash-live-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto auto!important;align-items:center!important;gap:8px!important;min-height:44px!important;border-radius:18px!important;background:rgba(0,0,0,.22)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06),inset 0 -1px 0 rgba(255,255,255,.04)!important;color:#fff!important;padding:0 10px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#crash .crash-live-user{min-width:0!important;font-size:12px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;color:rgba(255,255,255,.92)!important}
#crash .crash-live-amount{font-size:11px!important;font-weight:900!important;color:rgba(255,255,255,.62)!important;white-space:nowrap!important}
#crash .crash-live-status{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:5px!important;font-size:11px!important;font-weight:930!important;color:rgba(255,255,255,.84)!important;white-space:nowrap!important}
#crash .crash-live-mult,#crash .crash-live-win{color:rgba(255,255,255,.62)!important;-webkit-text-fill-color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:950!important;font-variant-numeric:tabular-nums lining-nums!important;text-shadow:none!important}
#crash .crash-live-lost{color:#ff5b6b!important;-webkit-text-fill-color:#ff5b6b!important;font-size:12px!important;font-weight:930!important;font-variant-numeric:tabular-nums lining-nums!important}
#crash .crash-live-row.cashout .crash-live-amount{color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;text-shadow:0 0 14px rgba(120,255,179,.16)!important}
#crash .crash-live-plus{display:inline-block!important;margin-right:3px!important;color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;font-weight:950!important}
#crash .crash-live-row.crashed .crash-live-amount,#crash .crash-live-row.crashed .crash-live-status{color:rgba(255,255,255,.62)!important;-webkit-text-fill-color:rgba(255,255,255,.62)!important;text-shadow:none!important}
@media(max-width:380px){#crash .crash-field small,#crash .crash-label{font-size:10px!important}#crash .crash-primary,#crash .crash-secondary{height:40px!important;font-size:14px!important}}
`;