const CRASH_CONTROLS_MODERN_STYLES = `
html body:has(#crash.active) #crash.crash-view .crash-controls,#crash .crash-controls{position:relative!important;margin:42px 0 0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;padding:14px!important;display:grid!important;gap:10px!important;align-content:space-between!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:visible!important;isolation:isolate!important}
#crash .crash-controls:before,#crash .crash-controls:after{display:none!important}
#crash .crash-controls *{box-sizing:border-box!important}
#crash .crash-control-grid{display:grid!important;grid-template-columns:1fr!important;gap:0!important;align-items:stretch!important}
#crash .crash-field{min-width:0!important;min-height:44px!important;height:44px!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;padding:0 12px!important;text-align:left!important;color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:10px!important;margin:0!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important}
#crash .crash-field small,#crash .crash-label{display:block!important;color:rgba(255,255,255,.72)!important;font-size:11px!important;line-height:1!important;font-weight:850!important;letter-spacing:-.02em!important;text-transform:none!important;white-space:nowrap!important;text-shadow:none!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field b{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:4px!important;margin-top:0!important;font-size:20px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.04em!important;font-variant-numeric:tabular-nums lining-nums!important;white-space:nowrap!important;color:#fff!important;min-width:0!important;overflow:hidden!important}
#crash .crash-field b>span:first-child{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important}
#crash .crash-field i{font-style:normal!important;font-size:18px!important;line-height:normal!important;color:rgba(255,255,255,.72)!important;font-weight:800!important;flex:0 0 auto!important}
#crash .crash-auto-field{margin-top:0!important}
#crash .crash-auto{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:3px!important;width:auto!important;min-width:0!important;height:auto!important;min-height:0!important;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important}
#crash .crash-auto input{width:50px!important;min-width:0!important;height:auto!important;padding:0!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:right!important;font:inherit!important;font-size:20px!important;font-weight:950!important;line-height:1!important;letter-spacing:-.04em!important;box-shadow:none!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash .crash-auto input::-webkit-outer-spin-button,#crash .crash-auto input::-webkit-inner-spin-button,#crash .crash-bet-main input::-webkit-outer-spin-button,#crash .crash-bet-main input::-webkit-inner-spin-button{appearance:none!important;-webkit-appearance:none!important;margin:0!important}
#crash .crash-auto span{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:0!important;color:#fff!important;font-size:20px!important;font-weight:950!important;line-height:1!important;flex:0 0 auto!important}
#crash .crash-bet{display:grid!important;grid-template-columns:.68fr 1.64fr .68fr!important;gap:8px!important;align-items:center!important}
#crash .crash-bet button{height:40px!important;border:0!important;outline:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:20px!important;font-weight:950!important;letter-spacing:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;text-shadow:none!important;overflow:hidden!important}
#crash .crash-bet-main{height:44px!important;border:0!important;outline:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0 12px!important;min-width:0!important;font-size:20px!important;font-weight:950!important;overflow:hidden!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important}
#crash .crash-bet-main input{width:100%!important;height:42px!important;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;-webkit-text-fill-color:#fff!important;text-align:center!important;font-size:20px!important;font-weight:950!important;letter-spacing:-.025em!important;box-shadow:none!important;padding:0!important;appearance:textfield!important;-moz-appearance:textfield!important}
#crash.bet-locked .crash-bet button,#crash.bet-locked .crash-bet-main{opacity:.55!important;pointer-events:none!important}
#crash.bet-locked .crash-bet-main input{opacity:1!important;pointer-events:none!important}
#crash .crash-bet-main input::placeholder,#crash .crash-auto input::placeholder{color:rgba(255,255,255,.42)!important;-webkit-text-fill-color:rgba(255,255,255,.42)!important}
#crash .crash-actions{display:grid!important;grid-template-columns:1fr!important;gap:0!important;margin-top:0!important}
#crash .crash-primary,#crash .crash-secondary{height:46px!important;border-radius:16px!important;border:0!important;outline:0!important;background-color:rgba(59,7,21,.58)!important;background-image:linear-gradient(145deg,rgba(112,22,48,.62),rgba(59,7,21,.40) 62%,rgba(39,4,13,.48))!important;color:#ffdce5!important;-webkit-text-fill-color:#ffdce5!important;font-weight:900!important;letter-spacing:-.045em!important;font-size:15px!important;box-shadow:inset 0 1px 0 rgba(255,220,229,.14),inset 0 -1px 0 rgba(255,255,255,.018),0 10px 24px rgba(0,0,0,.20)!important;backdrop-filter:blur(3px)!important;-webkit-backdrop-filter:blur(3px)!important;text-shadow:none!important;overflow:hidden!important;transition:transform .18s ease,opacity .18s ease,background .18s ease!important}
#crash .crash-primary.cashout{background-color:rgba(15,63,42,.58)!important;background-image:linear-gradient(145deg,rgba(32,104,72,.60),rgba(15,63,42,.40) 62%,rgba(8,42,27,.48))!important;border:0!important;color:#d8ffe8!important;-webkit-text-fill-color:#d8ffe8!important;box-shadow:inset 0 1px 0 rgba(255,220,229,.14),inset 0 -1px 0 rgba(255,255,255,.018),0 10px 24px rgba(0,0,0,.20)!important}
#crash .crash-primary.cashout:disabled{opacity:1!important;transform:none!important;filter:none!important;background:#0f3f2a!important;color:#d8ffe8!important;-webkit-text-fill-color:#d8ffe8!important}
#crash .crash-primary:not(:disabled):active,#crash .crash-secondary:not(:disabled):active,#crash .crash-bet button:active{transform:scale(.975)!important}
#crash .crash-primary:disabled,#crash .crash-secondary:disabled{opacity:.62!important;transform:none!important;filter:none!important}
#crash .crash-history{position:absolute!important;left:18px!important;right:18px!important;top:12px!important;z-index:5!important;display:flex!important;gap:6px!important;overflow-x:auto!important;overflow-y:visible!important;margin:0!important;min-height:28px!important;padding:4px!important;scrollbar-width:none!important;visibility:visible!important;opacity:1!important;clip-path:none!important;background:rgba(255,255,255,.018)!important;border:0!important;border-radius:16px!important;box-shadow:none!important;backdrop-filter:blur(2px)!important;-webkit-backdrop-filter:blur(2px)!important}
#crash .crash-history::-webkit-scrollbar{display:none!important}
#crash .crash-history span{flex:0 0 auto!important;border-radius:999px!important;padding:4px 8px!important;min-height:20px!important;line-height:12px!important;font-size:10px!important;font-weight:890!important;color:rgba(255,255,255,.94)!important;background:transparent!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:visible!important;clip-path:none!important}
html body:has(#crash.active) #crash.crash-view #crashLive,#crash .crash-live{border-radius:28px!important;background:rgba(13,13,13,.54)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;padding:14px!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;overflow:hidden!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),padding .28s ease,opacity .2s ease!important;max-height:min(430px,calc(100dvh - 238px))!important;display:flex!important;flex-direction:column!important;min-height:0!important}
#crash .crash-live.open{max-height:none!important}
#crash .crash-live:not(.open){max-height:54px!important;padding-bottom:12px!important}
#crash .crash-live-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:10px!important;color:#fff!important;font-size:16px!important;font-weight:950!important;letter-spacing:0!important;text-transform:none!important}
#crash .crash-live-title{display:inline-flex!important;align-items:center!important;gap:7px!important;min-width:0!important;color:#fff!important;font-size:16px!important;font-weight:950!important}
#crash .crash-live-title svg{width:17px!important;height:17px!important;display:block!important;flex:0 0 auto!important;color:rgba(255,255,255,.72)!important}
#crash .crash-live-title svg path{fill:none!important;stroke:currentColor!important;stroke-width:1.9!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#crash .crash-live-title span{display:inline-block!important;white-space:nowrap!important}
#crash .crash-live-head-actions{display:flex!important;align-items:center!important;gap:8px!important}
#crash .crash-live-head b{color:rgba(255,255,255,.92)!important;font-size:13px!important;font-weight:900!important;letter-spacing:-.02em!important;text-transform:none!important}
#crash .crash-live-toggle{width:28px!important;height:28px!important;border:0!important;outline:0!important;border-radius:10px!important;background:rgba(255,255,255,.075)!important;color:rgba(255,255,255,.85)!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important;transition:transform .22s ease,background .18s ease!important}
#crash .crash-live-toggle svg{width:18px!important;height:18px!important;display:block!important;transition:transform .28s cubic-bezier(.2,.8,.2,1)!important}
#crash .crash-live-toggle path{fill:none!important;stroke:currentColor!important;stroke-width:2.4!important;stroke-linecap:round!important;stroke-linejoin:round!important}
#crash .crash-live.open .crash-live-toggle svg{transform:rotate(180deg)!important}
#crash .crash-live-toggle:active{transform:scale(.94)!important;background:rgba(255,255,255,.12)!important}
#crash .crash-live-list{display:grid!important;gap:8px!important;max-height:min(394px,calc(100dvh - 300px))!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;pointer-events:auto!important;padding-right:2px!important;scrollbar-width:thin!important;scrollbar-color:rgba(255,255,255,.18) transparent!important;transition:max-height .34s cubic-bezier(.2,.8,.2,1),opacity .22s ease!important}
#crash .crash-live.open .crash-live-list{max-height:none!important;overflow-y:visible!important;overscroll-behavior-y:auto!important;scrollbar-width:none!important}
#crash .crash-live:not(.open) .crash-live-list{max-height:0!important;opacity:0!important;pointer-events:none!important}
#crash .crash-live-list::-webkit-scrollbar{width:4px!important;display:block!important}
#crash .crash-live.open .crash-live-list::-webkit-scrollbar{display:none!important}
#crash .crash-live-list::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18)!important;border-radius:999px!important}
#crash .crash-live-empty{font-size:12px!important;font-weight:820!important;color:rgba(255,255,255,.45)!important;padding:14px 0!important;text-align:center!important}
#crash .crash-live-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto auto!important;align-items:center!important;gap:8px!important;min-height:44px!important;border-radius:18px!important;background:rgba(0,0,0,.22)!important;border:0!important;outline:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06),inset 0 -1px 0 rgba(255,255,255,.04)!important;color:#fff!important;padding:0 10px!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
#crash .crash-live-user{min-width:0!important;font-size:12px!important;font-weight:900!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;color:rgba(255,255,255,.92)!important}
#crash .crash-live-amount{font-size:11px!important;font-weight:900!important;color:rgba(255,255,255,.62)!important;white-space:nowrap!important}
#crash .crash-live-status{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:5px!important;font-size:11px!important;font-weight:930!important;color:rgba(255,255,255,.84)!important;white-space:nowrap!important}
#crash .crash-live-mult,#crash .crash-live-win{color:rgba(255,255,255,.62)!important;-webkit-text-fill-color:rgba(255,255,255,.62)!important;font-size:12px!important;font-weight:950!important;font-variant-numeric:tabular-nums lining-nums!important;text-shadow:none!important}
#crash .crash-live-lost{color:#ff5b6b!important;-webkit-text-fill-color:#ff5b6b!important;font-size:12px!important;font-weight:930!important;font-variant-numeric:tabular-nums lining-nums!important}
#crash .crash-live-row.cashout .crash-live-amount{color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;text-shadow:0 0 14px rgba(120,255,179,.16)!important}
#crash .crash-live-plus{display:inline-block!important;margin-right:3px!important;color:#78ffb3!important;-webkit-text-fill-color:#78ffb3!important;font-weight:950!important}
#crash .crash-live-row.crashed .crash-live-amount,#crash .crash-live-row.crashed .crash-live-status{color:rgba(255,255,255,.62)!important;-webkit-text-fill-color:rgba(255,255,255,.62)!important;text-shadow:none!important}
@media(max-width:380px){#crash .crash-field small,#crash .crash-label{font-size:10px!important}#crash .crash-primary,#crash .crash-secondary{height:46px!important;font-size:15px!important}}
`;

const CRASH_BASE_STYLES = `
#crash.crash-view{height:100%;overflow-y:auto!important;overflow-x:visible!important;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding-bottom:22px}
#crash.crash-view::-webkit-scrollbar{display:none}
body:has(#crash.active) .tabs{display:none!important}
body:has(#crash.active) .content{padding-bottom:0!important;overflow:visible!important}
#crash .crash-page{min-height:100%;box-sizing:border-box;display:flex;flex-direction:column;gap:6px;padding:4px 0 max(34px,env(safe-area-inset-bottom))}
html body:has(#crash.active) #crash.crash-view .crash-stage{position:relative;width:100%!important;margin-left:0!important;transform:none!important;aspect-ratio:1/1;height:auto!important;min-height:0!important;max-height:none!important;flex:0 0 auto;z-index:2!important;border-radius:0!important;overflow:visible!important;background-color:transparent!important;background-image:none!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;isolation:isolate}
#crash .crash-stage:before,#crash .crash-stage:after{content:"";position:absolute;inset:0;background:none!important;pointer-events:none;z-index:1}
#crash .crash-chart-square{display:none!important}
#crash .crash-rocket-scene{position:absolute;inset:0;z-index:2;overflow:hidden;pointer-events:none;perspective:900px}
#crash .crash-rocket-flight{--rocket-thrust:.3;--rocket-angle:80deg;--rocket-entry-x:0px;position:absolute;left:50%;top:50%;width:min(56vw,220px);height:min(56vw,220px);transform:translate3d(calc(-50% + var(--rocket-entry-x)), -50%,0) rotate(var(--rocket-angle)) scale(.78);transform-origin:50% 50%;will-change:transform,opacity;animation:crashRocketDrift 3.6s ease-in-out infinite;transition:opacity .22s ease;opacity:1}
#crash .crash-rocket-model{position:absolute;inset:0;width:100%;height:100%;z-index:3;background:transparent!important;--poster-color:transparent;pointer-events:none;image-rendering:auto}
#crash .crash-rocket-model::part(default-progress-bar){display:none}
#crash .crash-rocket-flame{position:absolute;left:50%;top:83%;width:21%;height:calc(31% * var(--rocket-thrust));min-height:8px;z-index:1;transform:translateX(-50%);transform-origin:50% 0;filter:drop-shadow(0 10px 13px rgba(101,5,30,.72));opacity:calc(.18 + var(--rocket-thrust) * .82);will-change:height,opacity,filter}
#crash .crash-flame-outer,#crash .crash-flame-middle,#crash .crash-flame-core{position:absolute;left:50%;top:-2%;height:102%;border-radius:50% 50% 62% 62%/18% 18% 82% 82%;transform-origin:50% 0;will-change:transform,filter}
#crash .crash-flame-outer{width:100%;transform:translateX(-50%);background:radial-gradient(ellipse at 50% 4%,rgba(255,225,220,.82) 0 7%,rgba(125,12,43,.98) 22%,rgba(83,3,27,.88) 52%,rgba(32,0,10,0) 88%);filter:blur(3px);animation:crashFlameOuter .09s steps(2,end) infinite}
#crash .crash-flame-middle{width:57%;height:86%;transform:translateX(-50%);background:linear-gradient(180deg,#fff 0 11%,#ffd9d5 21%,#a10c3d 52%,rgba(82,0,24,0) 100%);filter:blur(1px);animation:crashFlameMiddle .075s ease-in-out infinite alternate}
#crash .crash-flame-core{width:22%;height:58%;transform:translateX(-50%);background:linear-gradient(180deg,#fff 0 38%,#ffe8df 55%,rgba(255,102,115,.12) 100%);filter:blur(.35px);animation:crashFlameCore .055s ease-in-out infinite alternate}
#crash .crash-rocket-heat{position:absolute;left:50%;top:74%;width:30%;height:39%;z-index:0;transform:translateX(-50%);border-radius:50%;background:repeating-radial-gradient(ellipse at 50% 0,rgba(255,255,255,.08) 0 2px,rgba(95,4,29,.04) 3px 6px,transparent 7px 11px);mix-blend-mode:screen;filter:blur(2px);opacity:calc(var(--rocket-thrust) * .42);animation:crashHeatHaze .24s linear infinite}
#crash .crash-rocket-flight[data-state="waiting"]{--rocket-thrust:.18;opacity:1}
#crash .crash-rocket-flight[data-state="crashed"]{--rocket-thrust:0;opacity:.15}
@keyframes crashRocketDrift{0%,100%{transform:translate3d(calc(-50% + var(--rocket-entry-x) - 2px),calc(-50% + 2px),0) rotate(var(--rocket-angle)) scale(.78)}50%{transform:translate3d(calc(-50% + var(--rocket-entry-x) + 2px),calc(-50% - 2px),0) rotate(var(--rocket-angle)) scale(.78)}}
@keyframes crashFlameOuter{0%{transform:translateX(-50%) scaleX(.88) scaleY(.94);filter:blur(3.6px)}100%{transform:translateX(-50%) scaleX(1.08) scaleY(1.06);filter:blur(2.6px)}}
@keyframes crashFlameMiddle{0%{transform:translateX(-50%) scaleX(.84) scaleY(.92)}100%{transform:translateX(-50%) scaleX(1.08) scaleY(1.08)}}
@keyframes crashFlameCore{0%{transform:translateX(-50%) scaleY(.86)}100%{transform:translateX(-50%) scaleY(1.13)}}
@keyframes crashHeatHaze{0%{transform:translate3d(-50%,0,0) scaleX(.9)}50%{transform:translate3d(-48%,3px,0) scaleX(1.08)}100%{transform:translate3d(-51%,7px,0) scaleX(.94)}}
@media (prefers-reduced-motion:reduce){#crash .crash-rocket-flight{animation:none!important}#crash .crash-rocket-flame span,#crash .crash-rocket-heat{animation-duration:.35s!important}#crash .crash-rocket-flight[data-state="crashed"]{opacity:.15}}
#crash .crash-multiplier-wrap{position:absolute;left:20px;right:20px;top:18%;text-align:center;z-index:4;pointer-events:none;background:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;filter:none!important}
#crash .crash-multiplier{position:relative!important;display:inline-block!important;transform:none!important;text-align:center;font-size:clamp(32px,10vw,44px);font-weight:930;letter-spacing:-.075em;color:rgba(255,255,255,.82)!important;-webkit-text-fill-color:rgba(255,255,255,.82)!important;background:none!important;border:0!important;outline:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;filter:none!important;text-shadow:0 1px 0 rgba(255,255,255,.22),0 16px 34px rgba(0,0,0,.55);pointer-events:none;will-change:transform,opacity,color}
#crash .crash-multiplier.crash-broken{color:#5f0618!important;-webkit-text-fill-color:#5f0618!important;text-shadow:0 0 14px rgba(95,6,24,.72),0 16px 32px rgba(0,0,0,.72)!important;animation:crashBreakMain .86s cubic-bezier(.17,.84,.24,1) both}
#crash .crash-multiplier.crash-broken:before,#crash .crash-multiplier.crash-broken:after{content:attr(data-crash-text);position:absolute;inset:0;color:#8d1830;-webkit-text-fill-color:#8d1830;text-shadow:0 0 18px rgba(120,0,28,.55);pointer-events:none;opacity:.82;mix-blend-mode:screen;clip-path:polygon(0 0,100% 0,82% 46%,0 62%)}
#crash .crash-multiplier.crash-broken:before{animation:crashShardTop .82s cubic-bezier(.14,.86,.22,1) both}
#crash .crash-multiplier.crash-broken:after{clip-path:polygon(0 60%,82% 46%,100% 100%,0 100%);animation:crashShardBottom .82s cubic-bezier(.14,.86,.22,1) both;color:#3e0310;-webkit-text-fill-color:#3e0310}
@keyframes crashBreakMain{0%{transform:translate3d(0,0,0) scale(1);filter:none;opacity:1}10%{transform:translate3d(-2px,1px,0) rotate(-1deg) scale(1.045);filter:brightness(1.35)}20%{transform:translate3d(3px,-2px,0) rotate(1.2deg) scale(.99)}34%{transform:translate3d(-5px,2px,0) rotate(-2.4deg) scale(1.025);letter-spacing:-.095em}48%{transform:translate3d(4px,1px,0) rotate(1.7deg) scale(.985);filter:contrast(1.25)}66%{transform:translate3d(-1px,4px,0) rotate(-.8deg) scale(.96);opacity:.96}100%{transform:translate3d(0,2px,0) rotate(0deg) scale(.94);filter:contrast(1.12);opacity:.92}}
@keyframes crashShardTop{0%{transform:translate3d(0,0,0) rotate(0);opacity:0}12%{opacity:.95}100%{transform:translate3d(-13px,-16px,0) rotate(-7deg);opacity:0}}
@keyframes crashShardBottom{0%{transform:translate3d(0,0,0) rotate(0);opacity:0}12%{opacity:.82}100%{transform:translate3d(14px,18px,0) rotate(8deg);opacity:0}}
#crash .crash-next-round{margin-top:6px;color:rgba(255,255,255,.60);font-size:10px;font-weight:850;letter-spacing:.02em;text-shadow:0 8px 18px rgba(0,0,0,.42)}
#crash .crash-hidden-state,#crash .crash-starting,#crash .crash-network{display:none!important}
body #crash .crash-bet-main{display:flex!important;align-items:center!important;justify-content:center!important;gap:4px!important;padding:0 10px!important}
body #crash .crash-bet-main::before{content:""!important;display:block!important;width:24px!important;height:24px!important;flex:0 0 24px!important;background:url('/app/api/uploaded-image/ton-icon.png') center/contain no-repeat!important;filter:drop-shadow(0 2px 8px rgba(0,0,0,.34))!important;opacity:.98!important;pointer-events:none!important}
body #crash .crash-bet-main input{width:auto!important;max-width:88px!important;flex:0 1 auto!important;text-align:left!important}
`;

const CRASH_SECTION_STYLES = `
html body:has(#crash.active){isolation:isolate!important;background:#000!important}
html body:has(#crash.active)::before{content:""!important;display:block!important;position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;z-index:-1!important;pointer-events:none!important;background-color:#000!important;background-image:url('/assets/Crash.PNG?v=1')!important;background-size:cover!important;background-position:center top!important;background-repeat:no-repeat!important;transform:none!important;animation:none!important;filter:none!important;opacity:1!important}
html body:has(#crash.active)::after,html body:has(#crash.active) .app::before,html body:has(#crash.active) .app::after{display:none!important;content:none!important;background:none!important;background-image:none!important}
html body:has(#crash.active) .app,html body:has(#crash.active) main.app,html body:has(#crash.active) .content,html body:has(#crash.active) .view.active,html body:has(#crash.active) #crash,html body:has(#crash.active) .crash-view,html body:has(#crash.active) .crash-page,html body:has(#crash.active) .top,html body:has(#crash.active) header.top{background:transparent!important;background-color:transparent!important;background-image:none!important;box-shadow:none!important;overflow:visible!important}
html body:has(#crash.active) #crash.crash-view:has(#crashLive.open){overflow-y:auto!important;touch-action:pan-y!important;-webkit-overflow-scrolling:touch!important}
html body:has(#crash.active) #crash .crash-page{position:relative!important;isolation:isolate!important}
html body:has(#crash.active) #crash .crash-stage-background{position:absolute!important;left:50%!important;top:0!important;width:calc(100vw + 24px)!important;aspect-ratio:1/1!important;transform:translateX(-50%)!important;overflow:hidden!important;z-index:0!important;background:#000!important;box-shadow:0 -11px 10px -4px #000,0 11px 10px -4px #000!important;pointer-events:none!important}
html body:has(#crash.active) #crash .crash-stage-background-track{display:flex!important;width:600%!important;height:100%!important;transform:translate3d(0,0,0);will-change:transform;opacity:0;animation:crashStageBackgroundPan 75s linear infinite!important;animation-play-state:paused!important;transition:opacity .22s ease}
html body:has(#crash.active) #crash .crash-stage-background-track.ready{opacity:1;animation-play-state:running!important}
html body:has(#crash.active) #crash .crash-stage-background-slide{flex:0 0 calc(100% / 6)!important;width:calc(100% / 6)!important;height:100%!important;background:#000!important;overflow:hidden!important}
html body:has(#crash.active) #crash .crash-stage-background-slide img{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important;object-position:center!important;user-select:none!important;-webkit-user-drag:none!important}
html body:has(#crash.active) #crash #crashSpaceCanvas{position:absolute!important;left:50%!important;top:0!important;width:calc(100vw + 24px)!important;height:auto!important;aspect-ratio:1/1!important;transform:translateX(-50%)!important;z-index:1!important;border-radius:0!important;background:transparent!important;pointer-events:none!important}
html body:has(#crash.active) #crash .crash-controls{position:relative!important;z-index:3!important}
html body:has(#crash.active) #crash .crash-multiplier-wrap{left:18px!important;right:18px!important;top:50px!important;transform:none!important;text-align:center!important}
html body:has(#crash.active) #crash .crash-multiplier{font-size:clamp(27px,calc(10vw - 5px),39px)!important}
html body:has(#crash.active) #crash #crashLive{width:100%!important;margin:0!important;padding:14px!important}
@keyframes crashStageBackgroundPan{from{transform:translate3d(0,0,0)}to{transform:translate3d(-83.333333%,0,0)}}
@media(prefers-reduced-motion:reduce){html body:has(#crash.active) #crash .crash-stage-background-track{animation-duration:150s!important}}
`;

export const CRASH_STYLES = CRASH_BASE_STYLES + CRASH_CONTROLS_MODERN_STYLES + CRASH_SECTION_STYLES;