export const PLINKO_CONTROLS_MODERN_STYLES = `
#plinko .plinko-controls{width:min(92vw,360px)!important;display:grid!important;gap:10px!important;margin:14px auto 0!important;padding:14px!important;box-sizing:border-box!important;border:0!important;border-radius:28px!important;background:rgba(13,13,13,.54)!important;background-image:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.105),inset 0 -1px 0 rgba(255,255,255,.06),inset 0 0 22px rgba(255,255,255,.055),0 16px 36px rgba(0,0,0,.22)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;position:relative!important;z-index:20!important;overflow:visible!important;align-content:space-between!important}
#plinko .plinko-controls::before,#plinko .plinko-controls::after,#plinko .plinko-stage::before,#plinko .plinko-stage::after{display:none!important;content:none!important}
#plinko .plinko-control-grid,#plinko .plinko-field,#plinko .plinko-bet,#plinko .plinko-stats,#plinko .plinko-stat{display:none!important}
#plinko .plinko-console-row{display:grid!important;grid-template-columns:76px minmax(0,1fr)!important;align-items:center!important;gap:10px!important;width:100%!important;min-width:0!important}
#plinko .plinko-control-label{color:#fff!important;font-size:16px!important;font-weight:950!important;letter-spacing:0!important;text-transform:none!important;white-space:nowrap!important}
#plinko .plinko-rows-selector,#plinko .plinko-risk-selector{height:44px!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:8px!important;padding:0!important;box-sizing:border-box!important;background:transparent!important;background-image:none!important}
#plinko .plinko-rows-selector button,#plinko .plinko-risk-selector button{height:40px!important;min-width:0!important;border:0!important;border-radius:16px!important;background:rgba(255,255,255,.075)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font:950 13px/1 Arial,system-ui,sans-serif!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important;cursor:pointer!important;touch-action:manipulation!important;opacity:1!important;filter:none!important;text-shadow:none!important;transition:transform .12s ease,background-color .15s ease!important;align-self:center!important}
#plinko .plinko-risk-selector button{font-size:12px!important;letter-spacing:0!important}
#plinko .plinko-rows-selector button.active,#plinko .plinko-risk-selector button.active{background:rgba(255,255,255,.18)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;opacity:1!important;filter:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 12px 24px rgba(0,0,0,.2)!important;text-shadow:none!important}
#plinko .plinko-rows-selector button:active,#plinko .plinko-risk-selector button:active{transform:scale(.97)!important}
#plinko .plinko-bet-asset{height:44px!important;display:grid!important;grid-template-columns:42px minmax(0,1fr) 42px!important;align-items:center!important;gap:8px!important;min-width:0!important}
#plinko .plinko-asset-hit{height:40px!important;min-width:0!important;border:0!important;padding:0!important;border-radius:16px!important;background:rgba(255,255,255,.075)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:13px!important;font-weight:950!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important;cursor:pointer!important;touch-action:manipulation!important;text-shadow:none!important;transition:transform .12s ease,background-color .15s ease!important}
#plinko .plinko-asset-hit:active{transform:scale(.97)!important;filter:none!important}
#plinko .plinko-asset-input{display:flex!important;align-items:center!important;justify-content:center!important;gap:0!important;height:44px!important;border-radius:18px!important;background:rgba(0,0,0,.22)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:20px!important;font-weight:950!important;letter-spacing:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06),inset 0 -1px 0 rgba(255,255,255,.04)!important}
#plinko .plinko-asset-half,#plinko .plinko-asset-double{background:rgba(255,255,255,.075)!important;background-image:none!important}
#plinko .plinko-asset-input::before{display:none!important;content:none!important}
#plinko .plinko-console-actions{display:grid!important;grid-template-columns:76px minmax(0,1fr)!important;gap:10px!important;width:100%!important;height:42px!important}
#plinko .plinko-auto-asset,#plinko .plinko-drop-asset{min-width:0!important;height:42px!important;border:0!important;margin:0!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;-webkit-text-fill-color:#fff!important;cursor:pointer!important;touch-action:manipulation!important;text-shadow:none!important;transition:transform .12s ease,background-color .15s ease!important}
#plinko .plinko-auto-asset{border-radius:16px!important;flex-direction:column!important;gap:1px!important;background:rgba(255,255,255,.075)!important;background-image:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),inset 0 -1px 0 rgba(255,255,255,.045),0 10px 22px rgba(0,0,0,.18)!important}
#plinko .plinko-auto-asset span{font-size:11px!important;font-weight:950!important;line-height:1!important}
#plinko .plinko-auto-asset small{font-size:8px!important;font-weight:850!important;line-height:1!important;color:rgba(255,255,255,.55)!important;-webkit-text-fill-color:rgba(255,255,255,.55)!important;text-transform:uppercase!important}
#plinko .plinko-auto-asset.active{background:rgba(255,255,255,.18)!important;background-image:none!important;filter:none!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 12px 24px rgba(0,0,0,.2)!important}
#plinko .plinko-auto-asset.active small{color:#fff!important;-webkit-text-fill-color:#fff!important}
#plinko .plinko-drop-asset{border-radius:17px!important;background:rgba(255,255,255,.12)!important;background-image:none!important;font-size:13px!important;font-weight:950!important;letter-spacing:0!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.09),inset 0 -1px 0 rgba(255,255,255,.055),0 12px 24px rgba(0,0,0,.2)!important}
#plinko .plinko-auto-asset:active,#plinko .plinko-drop-asset:active,#plinko .plinko-drop-asset.plinko-drop-tap,#plinko .plinko-drop-asset.plinko-drop-press{transform:scale(.98)!important;filter:none!important}
#plinko .plinko-drop-asset span{display:block!important;color:inherit!important;-webkit-text-fill-color:inherit!important;white-space:nowrap!important}
#plinko .plinko-bet-value,#plinko .plinko-hidden-status{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;left:-9999px!important}
#plinko .plinko-stage{overflow:visible!important;background:transparent!important;background-image:none!important;box-shadow:none!important;border:0!important;filter:none!important}
#plinko .plinko-canvas{clip-path:none!important;background:transparent!important;background-image:none!important}
#plinko .plinko-bet-editor,#plinko .plinko-bet-editor.active,#plinko .plinko-bet-box,#plinko .plinko-bet-box small,#plinko .plinko-bet-done{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#plinko .plinko-bet-input{position:fixed!important;left:-9999px!important;top:0!important;width:1px!important;height:1px!important;opacity:.01!important;border:0!important;background:transparent!important;background-image:none!important;color:#fff!important;text-align:center!important;font-size:22px!important;font-weight:900!important;outline:none!important;pointer-events:auto!important;z-index:-1!important}
@media(max-width:380px){#plinko .plinko-controls{width:94vw!important;padding:14px!important;gap:10px!important}#plinko .plinko-console-row{grid-template-columns:68px minmax(0,1fr)!important;gap:8px!important}#plinko .plinko-console-actions{grid-template-columns:68px minmax(0,1fr)!important;gap:8px!important}}
`;
