export const PLINKO_CONTROLS_MODERN_STYLES = `
#plinko .plinko-controls{width:min(92vw,360px)!important;display:grid!important;grid-template-columns:minmax(0,1fr) 124px!important;gap:9px!important;margin:0 auto!important;align-items:end!important;padding:0!important;box-sizing:border-box!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;position:relative!important;z-index:20!important;overflow:visible!important}
#plinko .plinko-controls::before,#plinko .plinko-controls::after,#plinko .plinko-stage::before,#plinko .plinko-stage::after{display:none!important;content:none!important}
#plinko .plinko-control-grid,#plinko .plinko-field,#plinko .plinko-bet,#plinko .plinko-stats,#plinko .plinko-stat{display:none!important}
#plinko .plinko-console-row{display:grid!important;gap:5px!important;width:100%!important;min-width:0!important;align-items:end!important}
#plinko .plinko-bet-row{grid-column:1!important}
#plinko .plinko-rows-row{grid-column:2!important}
#plinko .plinko-risk-row{grid-column:1/-1!important}
#plinko .plinko-control-label{color:rgba(255,255,255,.58)!important;font-size:10px!important;font-weight:760!important;letter-spacing:.01em!important;text-transform:none!important;white-space:nowrap!important}
#plinko .plinko-bet-asset{height:43px!important;border-radius:18px!important;border:1px solid rgba(255,255,255,.12)!important;background:rgba(0,0,0,.36)!important;background-image:none!important;display:grid!important;grid-template-columns:minmax(0,1fr) 86px!important;align-items:center!important;gap:7px!important;padding:4px!important;box-sizing:border-box!important;min-width:0!important}
#plinko .plinko-asset-input{min-width:0!important;height:35px!important;border:0!important;border-radius:0!important;background:transparent!important;background-image:none!important;padding:0 8px!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:18px!important;font-weight:900!important;text-align:center!important;box-shadow:none!important;font-variant-numeric:tabular-nums!important;outline:none!important;letter-spacing:0!important;cursor:pointer!important;touch-action:manipulation!important}
#plinko .plinko-bet-quick{height:35px!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:4px!important}
#plinko .plinko-bet-quick .plinko-asset-hit{height:35px!important;min-width:0!important;border-radius:13px!important;border:1px solid rgba(255,255,255,.1)!important;background:rgba(255,255,255,.07)!important;background-image:none!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:11px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.02em!important;padding:0!important;box-shadow:none!important;text-shadow:none!important;cursor:pointer!important;touch-action:manipulation!important;transition:transform .13s ease!important}
#plinko .plinko-bet-quick .plinko-asset-hit:active{transform:scale(.97)!important}
#plinko .plinko-asset-input::before{display:none!important;content:none!important}
#plinko .plinko-rows-selector,#plinko .plinko-risk-selector{width:100%!important;height:43px!important;border:1px solid rgba(255,255,255,.12)!important;border-radius:18px!important;background:rgba(0,0,0,.36)!important;background-image:none!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:4px!important;padding:4px!important;box-sizing:border-box!important;overflow:hidden!important}
#plinko .plinko-rows-selector button,#plinko .plinko-risk-selector button{height:35px!important;min-width:0!important;border-radius:13px!important;border:1px solid transparent!important;background:transparent!important;background-image:none!important;color:rgba(255,255,255,.72)!important;-webkit-text-fill-color:rgba(255,255,255,.72)!important;font-size:11px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.02em!important;padding:0!important;box-shadow:none!important;text-shadow:none!important;cursor:pointer!important;touch-action:manipulation!important;transition:transform .13s ease,background-color .15s ease,border-color .15s ease!important;opacity:1!important;filter:none!important}
#plinko .plinko-rows-selector button.active,#plinko .plinko-risk-selector button.active{background:rgba(255,255,255,.07)!important;background-image:none!important;border-color:rgba(255,255,255,.1)!important;color:#fff!important;-webkit-text-fill-color:#fff!important;box-shadow:none!important;opacity:1!important;filter:none!important}
#plinko .plinko-rows-selector button:active,#plinko .plinko-risk-selector button:active{transform:scale(.97)!important}
#plinko .plinko-console-actions{width:min(92vw,360px)!important;display:grid!important;grid-template-columns:1fr!important;gap:8px!important;margin:7px auto 0!important;position:relative!important;z-index:20!important}
#plinko .plinko-drop-asset{width:100%!important;height:42px!important;border:0!important;border-radius:16px!important;margin:0!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-weight:900!important;letter-spacing:-.02em!important;font-size:15px!important;background:linear-gradient(135deg,#5b0f24,#8f1d3d,#c03a5b)!important;background-image:linear-gradient(135deg,#5b0f24,#8f1d3d,#c03a5b)!important;box-shadow:0 13px 28px rgba(143,29,61,.32),inset 0 1px 0 rgba(255,255,255,.16)!important;cursor:pointer!important;touch-action:manipulation!important;text-shadow:none!important;transition:transform .13s ease!important}
#plinko .plinko-drop-asset:active,#plinko .plinko-drop-asset.plinko-drop-tap,#plinko .plinko-drop-asset.plinko-drop-press{transform:scale(.98)!important}
#plinko .plinko-drop-asset span{display:block!important;color:inherit!important;-webkit-text-fill-color:inherit!important;white-space:nowrap!important}
#plinko .plinko-bet-value,#plinko .plinko-hidden-status{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;left:-9999px!important}
#plinko .plinko-stage{overflow:visible!important;background:transparent!important;background-image:none!important;box-shadow:none!important;border:0!important;filter:none!important}
#plinko .plinko-canvas{clip-path:none!important;background:transparent!important;background-image:none!important}
#plinko .plinko-bet-editor,#plinko .plinko-bet-editor.active,#plinko .plinko-bet-box,#plinko .plinko-bet-box small,#plinko .plinko-bet-done{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#plinko .plinko-bet-input{position:fixed!important;left:-9999px!important;top:0!important;width:1px!important;height:1px!important;opacity:.01!important;border:0!important;background:transparent!important;background-image:none!important;color:#fff!important;text-align:center!important;font-size:18px!important;font-weight:900!important;outline:none!important;pointer-events:auto!important;z-index:-1!important}
@media(max-width:380px){#plinko .plinko-controls{width:min(94vw,360px)!important;grid-template-columns:1fr!important;gap:8px!important}#plinko .plinko-bet-row,#plinko .plinko-rows-row,#plinko .plinko-risk-row{grid-column:1!important}#plinko .plinko-bet-asset,#plinko .plinko-rows-selector,#plinko .plinko-risk-selector{height:40px!important;border-radius:16px!important}#plinko .plinko-asset-input{height:32px!important}#plinko .plinko-bet-quick,#plinko .plinko-bet-quick .plinko-asset-hit,#plinko .plinko-rows-selector button,#plinko .plinko-risk-selector button{height:32px!important}#plinko .plinko-console-actions{width:min(94vw,360px)!important}#plinko .plinko-drop-asset{height:39px!important}}
`;
