export function adminHtml(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Vexa Admin</title><style>${adminCss()}</style></head><body><main class="panel"><h1>Vexa Admin</h1><p class="muted">Enter your admin password to open the control panel.</p><div class="field"><label>Admin key</label><input id="key" type="password" placeholder="ADMIN_KEY" autocomplete="current-password"/></div><button class="btn" id="login">Enter admin panel</button><div id="status" class="status"></div></main><script>
const key=document.getElementById('key');const statusEl=document.getElementById('status');async function login(){const value=key.value.trim();if(!value){statusEl.textContent='Enter admin key.';return}statusEl.textContent='Checking...';const r=await fetch('/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:value})});const j=await r.json().catch(()=>({error:'Login failed'}));if(!r.ok||!j.ok){statusEl.textContent=j.error||'Wrong admin key.';return}sessionStorage.setItem('vexa_admin_key',value);const panel=await fetch('/admin/panel',{headers:{'x-admin-key':value}});if(!panel.ok){statusEl.textContent='Could not open panel.';return}document.open();document.write(await panel.text());document.close()}document.getElementById('login').onclick=login;key.addEventListener('keydown',e=>{if(e.key==='Enter')login()});
</script></body></html>`;
}

export function adminPanelHtml(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Vexa Admin Panel</title><style>${adminCss()}</style></head><body><main class="panel"><div class="top"><div><h1>Admin Panel</h1><p class="muted">Private tools for Vexa FLOW. More controls can be added here later.</p></div><button class="small" id="logout">Logout</button></div><section class="box"><h2>Credit icon</h2><p class="muted">Upload the image shown next to the user credit count in the mini app.</p><div class="field"><label>Credit icon</label><input id="file" type="file" accept="image/*"/></div><button class="btn" id="upload">Upload icon</button><div class="preview"><img id="preview" src="/app/api/credit-icon" alt=""/><div><strong>Current credit icon</strong><p class="muted" style="margin:4px 0 0">Updates after upload.</p></div></div></section><section class="box muted-box"><h2>Coming next</h2><p class="muted">Future admin settings will live here, behind the same login.</p></section><div id="status" class="status"></div></main><script>
const adminKey=sessionStorage.getItem('vexa_admin_key')||'';const file=document.getElementById('file');const statusEl=document.getElementById('status');const preview=document.getElementById('preview');document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('vexa_admin_key');location.href='/admin'};document.getElementById('upload').onclick=async()=>{if(!adminKey){location.href='/admin';return}if(!file.files||!file.files[0]){statusEl.textContent='Choose an image first.';return}statusEl.textContent='Uploading...';const form=new FormData();form.append('icon',file.files[0]);const r=await fetch('/admin/upload-credit-icon',{method:'POST',headers:{'x-admin-key':adminKey},body:form});const j=await r.json().catch(()=>({error:'Upload failed'}));if(!r.ok){statusEl.textContent=j.error||'Upload failed';return}preview.src='/app/api/credit-icon?t='+Date.now();statusEl.textContent='Uploaded successfully.'};
</script></body></html>`;
}

function adminCss(): string {
  return `:root{color-scheme:dark;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#000;color:#fff}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#000;display:grid;place-items:center;padding:22px}.panel{width:min(100%,500px);border:1px solid rgba(255,255,255,.14);border-radius:32px;background:linear-gradient(180deg,rgba(255,255,255,.09),rgba(255,255,255,.03));padding:22px;box-shadow:0 28px 90px rgba(0,0,0,.72)}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}h1{margin:0 0 8px;font-size:34px;letter-spacing:-.06em}h2{margin:0 0 8px;font-size:20px;letter-spacing:-.03em}.muted{color:rgba(255,255,255,.58);margin:0 0 18px;line-height:1.45}.field{display:grid;gap:8px;margin:14px 0}label{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:rgba(255,255,255,.58)}input{height:52px;border-radius:18px;border:1px solid rgba(255,255,255,.14);background:#050505;color:#fff;padding:0 14px;font:inherit}input[type=file]{height:auto;padding:13px}.btn{width:100%;height:52px;border:0;border-radius:999px;background:#fff;color:#050505;font-weight:900;font-size:15px;margin-top:10px}.small{height:36px;border:1px solid rgba(255,255,255,.14);border-radius:999px;background:rgba(255,255,255,.07);color:#fff;padding:0 12px;font-weight:800}.box{border:1px solid rgba(255,255,255,.12);border-radius:24px;padding:16px;margin-top:16px;background:rgba(255,255,255,.035)}.muted-box{opacity:.75}.preview{display:flex;align-items:center;gap:12px;border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:12px;margin-top:16px}.preview img{width:42px;height:42px;border-radius:50%;object-fit:cover}.status{margin-top:14px;color:rgba(255,255,255,.62);font-size:13px;min-height:20px}`;
}

export function defaultCreditIconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="32" fill="black"/><circle cx="32" cy="32" r="24" fill="none" stroke="white" stroke-opacity=".7" stroke-width="3"/><path d="M32 13l5.7 12.3L51 27.1l-9.8 9.3 2.4 13.1L32 43.1 20.4 49.5l2.4-13.1-9.8-9.3 13.3-1.8L32 13z" fill="white"/></svg>`;
}
