export const ADMIN_USER_MENU_PANEL_SCRIPT = `<script>(function(){
  var activeSource='ai_bot';
  var usersCache=[];
  function esc(v){return String(v??'').replace(/[&<>]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[s]||s})}
  function fmt(v){return Number(v||0).toLocaleString('en-US')}
  function fmtTonNano(v){var n=Number(v||0);var ton=n/1000000000;return ton.toLocaleString('en-US',{maximumFractionDigits:3})+' TON'}
  function ago(v){if(!v)return '—';var t=Date.parse(v);if(!t)return v;var d=Math.max(0,Date.now()-t);if(d<60000)return 'now';if(d<3600000)return Math.floor(d/60000)+'m';if(d<86400000)return Math.floor(d/3600000)+'h';return Math.floor(d/86400000)+'d'}
  function title(src){return src==='ai_bot'?'AI Bot Users':src==='game_bot'?'Game Bot Users':src==='user_bot'?'User Bots':src==='all'?'Users List':'Other Users'}
  function balance(u){return u.tonBalance||fmtTonNano(u.tonBalanceNano||u.credit||0)}
  function installMenu(){var menu=document.getElementById('adminMenu');if(!menu||document.getElementById('aiUsersMenu'))return;var old=menu.querySelector('[data-section="users"]');if(old)old.remove();menu.insertAdjacentHTML('afterbegin','<button class="menu-item active" id="aiUsersMenu" data-user-menu="ai_bot" type="button"><strong>AI Bot Users</strong><span>Users of AI bot</span></button><button class="menu-item" data-user-menu="game_bot" type="button"><strong>Game Bot Users</strong><span>Users of game bot</span></button><button class="menu-item" data-user-menu="user_bot" type="button"><strong>User Bots</strong><span>Connected bot users</span></button><button class="menu-item" data-user-menu="all" type="button"><strong>Users List</strong><span>All users in one list</span></button>');document.querySelectorAll('[data-user-menu]').forEach(function(b){b.onclick=function(){activeSource=b.getAttribute('data-user-menu')||'ai_bot';document.querySelectorAll('.menu-item').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.admin-section').forEach(function(s){s.classList.toggle('active',s.id==='sectionUsers')});var h=document.getElementById('adminTitle'),sub=document.getElementById('adminSubtitle');if(h)h.textContent=title(activeSource);if(sub)sub.textContent='Manage '+title(activeSource).toLowerCase()+'.';renderList();window.scrollTo({top:0,behavior:'smooth'})}})}
  function row(u){return '<article class="user" id="user-'+esc(u.id)+'"><div class="user-top"><div class="user-name"><b>'+esc(u.username||'—')+'</b><span class="badge '+(u.isActive?'on':'off')+'">'+esc(u.status||'Inactive')+'</span></div><strong>'+esc(balance(u))+'</strong></div><div class="user-info"><span>ID '+esc(u.id)+'</span><span>'+esc(u.firstName||'—')+'</span><span>'+esc(u.currentSection||u.sourceLabel||title(u.source))+'</span><span>'+ago(u.lastSeenAt)+'</span></div><button class="manage-btn" data-manage-user="'+esc(u.id)+'" type="button">Manage user</button><button class="reset-user-btn" data-reset-user="'+esc(u.id)+'" type="button">Reset user</button><div class="user-manage" data-manage-panel="'+esc(u.id)+'" hidden></div></article>'}
  function bindRows(){document.querySelectorAll('[data-manage-user]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-manage-user');toggleManage(id)}});document.querySelectorAll('[data-reset-user]').forEach(function(btn){btn.onclick=function(){resetUser(btn.getAttribute('data-reset-user'))}})}
  function renderList(){var list=document.getElementById('usersList'),search=document.getElementById('userSearch');if(!list)return;var q=String(search&&search.value||'').trim().toLowerCase();var rows=usersCache.filter(function(u){return activeSource==='all'||(u.source||'unknown')===activeSource}).filter(function(u){return !q||String(u.id).toLowerCase().includes(q)||String(u.username).toLowerCase().includes(q)||String(u.firstName).toLowerCase().includes(q)||String(u.currentSection).toLowerCase().includes(q)});list.innerHTML=rows.length?rows.map(row).join(''):'<div class="empty">No users in '+title(activeSource)+'.</div>';bindRows()}

  var openManage='';
  var sectionLabels={home:'Home',connect:'Connect',flow:'TTS',plinko:'Plinko',playzone:'Play Zone',mines:'Mines',crash:'Crash',wheel:'Wheel',dice:'Dice',rps:'RPS',limbo:'Limbo',tower:'Tower',slot:'Slot',coinflip:'Coin Flip',hilo:'HiLo',ghostrun:'Ghost Run'};
  function nanoFromTonText(v){var n=Number(String(v||'').replace(/,/g,'').trim());if(!Number.isFinite(n))throw new Error('Enter a valid TON number');return Math.round(n*1000000000)}
  function toggleManage(userId){openManage=openManage===userId?'':userId;document.querySelectorAll('.user-manage').forEach(function(p){p.hidden=true;p.innerHTML=''});if(openManage)renderManage(openManage)}
  async function renderManage(userId){var panel=document.querySelector('[data-manage-panel="'+userId+'"]');if(!panel)return;panel.hidden=false;panel.innerHTML='<div class="mini-status">Loading controls...</div>';try{var r=await fetch('/admin/api/user-controls?userId='+encodeURIComponent(userId),{credentials:'same-origin'});var c=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(c.error||'Could not load controls');var blocked=new Set(c.blockedSections||[]);panel.innerHTML='<div class="admin-user-tool"><label>Win chance percent</label><div class="inline-send"><input data-win-chance type="number" min="0" max="100" placeholder="0-100" value="'+Number(c.winChancePercent||0)+'"><button data-save-win>Set chance</button></div></div><div class="admin-user-tool"><button class="save-credit" data-change-credit>Change credit</button><div class="inline-send" data-credit-box hidden><input data-credit-delta type="number" step="0.000000001" placeholder="+1.5 or -0.25 TON"><button data-send-credit>Apply</button></div></div><div class="section-user-blocks user-lock-grid">'+Object.keys(sectionLabels).map(function(id){return '<button class="section-block '+(blocked.has(id)?'blocked':'')+'" data-user-section="'+id+'">'+sectionLabels[id]+' '+(blocked.has(id)?'Locked':'Open')+'</button>'}).join('')+'</div><div class="admin-user-tool"><label>Bot chat message</label><textarea data-direct-text placeholder="Text or media caption"></textarea><input data-direct-file type="file" accept="image/*,video/*,audio/*"><button class="save-credit" data-send-direct>Send to bot chat</button></div><p class="mini-status" data-user-status></p>';panel.querySelector('[data-save-win]').onclick=function(){saveWin(userId,panel)};panel.querySelector('[data-change-credit]').onclick=function(){var box=panel.querySelector('[data-credit-box]');box.hidden=!box.hidden;if(!box.hidden)box.querySelector('input').focus()};panel.querySelector('[data-send-credit]').onclick=function(){changeCredit(userId,panel)};panel.querySelector('[data-send-direct]').onclick=function(){sendDirect(userId,panel)};panel.querySelectorAll('[data-user-section]').forEach(function(btn){btn.onclick=function(){blockSection(userId,btn.getAttribute('data-user-section'),!btn.classList.contains('blocked'))}})}catch(e){panel.innerHTML='<div class="mini-status">'+esc(e.message||'Could not load controls')+'</div>'}}
  async function saveWin(userId,panel){var status=panel.querySelector('[data-user-status]');try{status.textContent='Saving chance...';var input=panel.querySelector('[data-win-chance]');var r=await fetch('/admin/api/users/win-chance',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({userId:userId,winChancePercent:Number(input.value||0)})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save chance');input.value='';status.textContent='Chance saved';renderManage(userId)}catch(e){status.textContent=e.message||'Could not save chance'}}
  async function changeCredit(userId,panel){var status=panel.querySelector('[data-user-status]');try{status.textContent='Changing credit...';var input=panel.querySelector('[data-credit-delta]');var r=await fetch('/admin/api/users/ton-balance-adjust',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({userId:userId,deltaNano:nanoFromTonText(input.value)})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not change credit');input.value='';status.textContent='Credit changed';await refreshUsers();renderManage(userId)}catch(e){status.textContent=e.message||'Could not change credit'}}
  async function blockSection(userId,sectionId,blocked){var panel=document.querySelector('[data-manage-panel="'+userId+'"]'),status=panel&&panel.querySelector('[data-user-status]');if(status)status.textContent='Saving access...';try{var r=await fetch('/admin/api/users/section-block',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({userId:userId,sectionId:sectionId,blocked:blocked})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update access');if(status)status.textContent='Access updated';renderManage(userId)}catch(e){if(status)status.textContent=e.message||'Could not update access'}}
  async function sendDirect(userId,panel){var status=panel.querySelector('[data-user-status]');try{var text=(panel.querySelector('[data-direct-text]').value||'').trim();var file=panel.querySelector('[data-direct-file]').files[0];if(!text&&!file)throw new Error('Write text or choose media first');status.textContent='Sending bot chat message...';var form=new FormData();form.append('targetUserId',userId);form.append('text',text);if(file)form.append('media',file);var r=await fetch('/admin/api/vexa-voice/user-bot-message',{method:'POST',credentials:'same-origin',body:form});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Could not send message');panel.querySelector('[data-direct-text]').value='';panel.querySelector('[data-direct-file]').value='';status.textContent='Sent to bot chat'}catch(e){status.textContent=e.message||'Could not send message'}}

  async function refreshUsers(){var status=document.getElementById('usersStatus');try{installMenu();if(status)status.textContent='Loading users...';var r=await fetch('/admin/api/users',{credentials:'same-origin'});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Could not load users');usersCache=j.users||[];var stats=j.stats||{};var total=document.getElementById('statTotal'),online=document.getElementById('statOnline'),inactive=document.getElementById('statInactive'),credit=document.getElementById('statCredit');if(total)total.textContent=String(stats.total||usersCache.length);if(online)online.textContent=String(stats.online||0);if(inactive)inactive.textContent=String(stats.inactive||0);if(credit)credit.textContent=fmtTonNano(stats.totalTonBalanceNano||stats.totalCredit||0);if(status)status.textContent=title(activeSource)+' updated '+new Date().toLocaleTimeString();renderList()}catch(e){if(status)status.textContent=e.message||'Could not load users'}}
  async function resetUser(userId){if(!userId)return;if(!confirm('Reset user '+userId+'?'))return;var status=document.getElementById('usersStatus');if(status)status.textContent='Resetting user...';try{var r=await fetch('/admin/api/users/'+encodeURIComponent(userId),{method:'DELETE',credentials:'same-origin'});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Could not reset user');await refreshUsers()}catch(e){if(status)status.textContent=e.message||'Could not reset user'}}
  window.VexaRenderUserMenu=refreshUsers;
  setTimeout(refreshUsers,250);
  setTimeout(refreshUsers,900);
  var search=document.getElementById('userSearch');if(search)search.addEventListener('input',function(){setTimeout(renderList,30)});
  var refresh=document.getElementById('refreshUsers');if(refresh)refresh.addEventListener('click',function(){setTimeout(refreshUsers,30)},true);
})();</script>`;
