export const ADMIN_ONLINE_USER_COUNTS_PANEL_SCRIPT = `<script>
(function(){
  var state={sections:[],schedule:{}};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return ch==='&'?'&amp;':ch==='<'?'&lt;':ch==='>'?'&gt;':ch==='"'?'&quot;':'&#39;'})}
  function boot(){injectCss();var menu=document.querySelector('.menu-panel'),main=document.querySelector('main')||document.body;if(!menu||!main||document.getElementById('sectionOnlineUserCounts'))return;var btn=document.createElement('button');btn.className='menu-item';btn.type='button';btn.dataset.section='onlineUserCounts';btn.innerHTML='<strong>Online Counts</strong><span>Hourly users per section</span>';menu.appendChild(btn);var section=document.createElement('section');section.className='section admin-section online-counts-admin';section.id='sectionOnlineUserCounts';section.hidden=true;section.dataset.title='Online Counts';section.dataset.subtitle='Set the online user number shown for each section during every hour.';section.innerHTML='<div class="row-title"><div><h2>Online Counts</h2><p class="muted small-text">Set exact online user counts per section for each hour of the day. The mini app shows the number for the current device hour.</p></div><button class="ghost" id="refreshOnlineCounts">Refresh</button></div><div class="online-count-actions"><button type="button" class="ghost" id="copyOnlineCountsFirst">Copy first hour to all hours</button><button type="button" class="ghost" id="resetOnlineCounts">Reset defaults</button></div><div class="online-count-table-wrap"><table class="online-count-table"><thead id="onlineCountHead"></thead><tbody id="onlineCountBody"></tbody></table></div><div class="online-count-save"><button type="button" class="primary" id="saveOnlineCounts">Save online counts</button></div><p class="status" id="onlineCountStatus"></p>';main.appendChild(section);btn.onclick=function(){document.querySelectorAll('.menu-item').forEach(function(x){x.classList.toggle('active',x===btn)});document.querySelectorAll('.admin-section').forEach(function(x){x.classList.toggle('active',x===section);x.hidden=x!==section});var t=document.getElementById('adminTitle'),st=document.getElementById('adminSubtitle');if(t)t.textContent='Online Counts';if(st)st.textContent='Hourly online user counts shown in each mini app section.';menu.hidden=true;window.scrollTo({top:0,behavior:'smooth'});loadCounts()};document.getElementById('refreshOnlineCounts').onclick=loadCounts;document.getElementById('saveOnlineCounts').onclick=saveCounts;document.getElementById('resetOnlineCounts').onclick=resetCounts;document.getElementById('copyOnlineCountsFirst').onclick=copyFirstHour;}
  function injectCss(){if(document.getElementById('onlineCountsCss'))return;var style=document.createElement('style');style.id='onlineCountsCss';style.textContent='.online-count-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.online-count-table-wrap{max-height:62vh;overflow:auto;border:1px solid rgba(255,255,255,.10);border-radius:18px;background:rgba(255,255,255,.025)}.online-count-table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0}.online-count-table th,.online-count-table td{border-bottom:1px solid rgba(255,255,255,.07);border-right:1px solid rgba(255,255,255,.06);padding:6px;text-align:center}.online-count-table th{position:sticky;top:0;z-index:2;background:#080808;color:rgba(255,255,255,.72);font-size:10px;font-weight:950}.online-count-table th:first-child,.online-count-table td:first-child{position:sticky;left:0;z-index:1;background:#070707;text-align:left;min-width:112px}.online-count-table th:first-child{z-index:3}.online-count-table td:first-child{font-size:12px;font-weight:950;color:#fff}.online-count-table input{width:62px;height:34px;border-radius:11px;border:1px solid rgba(255,255,255,.12);background:#020202;color:#fff;text-align:center;font-size:12px;font-weight:900}.online-count-save{display:grid;margin-top:14px}.online-count-save .primary{height:42px;border-radius:999px;font-weight:950}@media(max-width:520px){.online-count-actions{grid-template-columns:1fr}.online-count-table input{width:54px}}';document.head.appendChild(style)}
  function render(){var head=document.getElementById('onlineCountHead'),body=document.getElementById('onlineCountBody');if(!head||!body)return;head.innerHTML='<tr><th>Section</th>'+Array.from({length:24},function(_,h){return '<th>'+String(h).padStart(2,'0')+':00</th>'}).join('')+'</tr>';body.innerHTML=(state.sections||[]).map(function(sec){var values=state.schedule[sec.id]||[];return '<tr><td>'+esc(sec.label||sec.id)+'</td>'+Array.from({length:24},function(_,h){return '<td><input type="number" min="0" max="999999" step="1" data-count="'+esc(sec.id)+':'+h+'" value="'+esc(values[h]||0)+'"/></td>'}).join('')+'</tr>'}).join('');body.querySelectorAll('[data-count]').forEach(function(input){input.oninput=function(){var parts=input.dataset.count.split(':'),id=parts[0],hour=Number(parts[1]);state.schedule[id]=state.schedule[id]||Array(24).fill(0);state.schedule[id][hour]=Math.max(0,Math.floor(Number(input.value)||0))}})}
  async function loadCounts(){var status=document.getElementById('onlineCountStatus');if(status)status.textContent='Loading online counts...';try{var r=await fetch('/admin/api/online-user-counts',{credentials:'same-origin',cache:'no-store'});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load');state.sections=Array.isArray(j.sections)?j.sections:[];state.schedule=j.schedule||{};render();if(status)status.textContent='Loaded '+state.sections.length+' sections.'}catch(e){if(status)status.textContent=e.message||'Could not load online counts'}}
  async function saveCounts(){var status=document.getElementById('onlineCountStatus');if(status)status.textContent='Saving...';try{var r=await fetch('/admin/api/online-user-counts',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({schedule:state.schedule})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save');state.sections=Array.isArray(j.sections)?j.sections:state.sections;state.schedule=j.schedule||{};render();if(status)status.textContent='Saved. The mini app will pick the saved count for the current hour.'}catch(e){if(status)status.textContent=e.message||'Could not save online counts'}}
  async function resetCounts(){var status=document.getElementById('onlineCountStatus');if(status)status.textContent='Resetting...';try{var r=await fetch('/admin/api/online-user-counts/reset',{method:'POST',credentials:'same-origin'});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not reset');state.sections=Array.isArray(j.sections)?j.sections:[];state.schedule=j.schedule||{};render();if(status)status.textContent='Defaults restored.'}catch(e){if(status)status.textContent=e.message||'Could not reset'}}
  function copyFirstHour(){(state.sections||[]).forEach(function(sec){var arr=state.schedule[sec.id]||Array(24).fill(0),first=Math.max(0,Math.floor(Number(arr[0])||0));state.schedule[sec.id]=Array(24).fill(first)});render()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,600);
})();
</script>`;
