export const ADMIN_PLINKO_VIRTUAL_USERS_SCRIPT = `<script>
(function(){
  var state={users:[]};
  function esc(v){return String(v??'').replace(/[&<>"']/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]||s})}
  function addMenu(){
    var menu=document.getElementById('adminMenu');
    var main=document.querySelector('main.page');
    if(!menu||!main||document.getElementById('sectionPlinkoVirtualUsers'))return;
    var btn=document.createElement('button');
    btn.className='menu-item';btn.type='button';btn.dataset.section='plinkoVirtualUsers';
    btn.innerHTML='<strong>Plinko Live Bets</strong><span>Edit virtual users and bet amounts</span>';
    menu.appendChild(btn);
    var section=document.createElement('section');
    section.className='section admin-section plinko-virtual-admin';
    section.id='sectionPlinkoVirtualUsers';
    section.dataset.title='Plinko Live Bets';
    section.dataset.subtitle='Virtual users shown in live bets.';
    section.innerHTML='<div class="row-title"><div><h2>Plinko Live Bets</h2><p class="muted small-text">Edit every virtual user name and the exact bet amount that appears in the Plinko live bet feed.</p></div><button class="ghost" id="refreshPlinkoVirtualUsers">Refresh</button></div><div class="plinko-virtual-toolbar"><button type="button" class="ghost" id="addPlinkoVirtualUser">+ Add user</button><button type="button" class="ghost" id="resetPlinkoVirtualUsers">Reset defaults</button></div><div class="plinko-virtual-head"><span>Name</span><span>Bet amount (TON)</span><span></span></div><div id="plinkoVirtualRows" class="plinko-virtual-rows"></div><div class="plinko-virtual-actions"><button type="button" class="primary" id="savePlinkoVirtualUsers">Save live bets</button></div><p class="status" id="plinkoVirtualStatus"></p>';
    main.appendChild(section);
    btn.onclick=function(){document.querySelectorAll('.menu-item').forEach(function(x){x.classList.toggle('active',x===btn)});document.querySelectorAll('.admin-section').forEach(function(s){s.classList.toggle('active',s.id==='sectionPlinkoVirtualUsers')});var t=document.getElementById('adminTitle');if(t)t.textContent='Plinko Live Bets';var sub=document.getElementById('adminSubtitle');if(sub)sub.textContent='Virtual users shown in live bets.';menu.hidden=true;window.scrollTo({top:0,behavior:'smooth'});loadUsers();};
    document.getElementById('refreshPlinkoVirtualUsers').onclick=loadUsers;
    document.getElementById('savePlinkoVirtualUsers').onclick=saveUsers;
    document.getElementById('addPlinkoVirtualUser').onclick=function(){state.users.push({name:'New Player',amount:1});renderRows();};
    document.getElementById('resetPlinkoVirtualUsers').onclick=resetUsers;
    injectCss();
  }
  function injectCss(){if(document.getElementById('plinkoVirtualUsersCss'))return;var style=document.createElement('style');style.id='plinkoVirtualUsersCss';style.textContent='.plinko-virtual-admin .row-title{align-items:flex-start}.plinko-virtual-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.plinko-virtual-toolbar button,.plinko-virtual-row button{height:34px;border-radius:999px;border:1px solid rgba(255,255,255,.14);background:#070707;color:#fff;font-weight:900;font-size:11px}.plinko-virtual-head,.plinko-virtual-row{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(92px,.75fr) 34px;gap:8px;align-items:center}.plinko-virtual-head{padding:0 2px 7px;color:rgba(255,255,255,.55);font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.plinko-virtual-rows{display:grid;gap:8px;max-height:58vh;overflow:auto;padding-right:2px}.plinko-virtual-row{padding:9px;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:rgba(255,255,255,.035)}.plinko-virtual-row input{width:100%;height:38px;border-radius:13px;border:1px solid rgba(255,255,255,.13);background:#050505;color:#fff;padding:0 11px;font-size:12px;font-weight:800;box-sizing:border-box}.plinko-virtual-row input[type=number]{text-align:center}.plinko-virtual-row button{width:34px;padding:0;color:#ffb3b3;background:rgba(255,80,80,.10)}.plinko-virtual-actions{margin-top:14px;display:grid}.plinko-virtual-actions .primary{height:42px;border-radius:999px;font-weight:950}@media(max-width:520px){.plinko-virtual-head,.plinko-virtual-row{grid-template-columns:minmax(0,1fr) 92px 32px;gap:6px}.plinko-virtual-row{padding:7px}.plinko-virtual-row input{height:36px;font-size:11px;padding:0 8px}}';document.head.appendChild(style)}
  function renderRows(){var box=document.getElementById('plinkoVirtualRows');if(!box)return;box.innerHTML=state.users.map(function(u,i){return '<div class="plinko-virtual-row"><input data-name="'+i+'" value="'+esc(u.name)+'" placeholder="User name"/><input data-amount="'+i+'" type="number" min="0.01" step="0.01" value="'+esc(u.amount)+'"/><button type="button" data-remove="'+i+'">×</button></div>'}).join('')||'<p class="muted small-text">No virtual users yet.</p>';box.querySelectorAll('[data-name]').forEach(function(input){input.oninput=function(){state.users[Number(input.dataset.name)].name=input.value}});box.querySelectorAll('[data-amount]').forEach(function(input){input.oninput=function(){state.users[Number(input.dataset.amount)].amount=Number(input.value)||0}});box.querySelectorAll('[data-remove]').forEach(function(btn){btn.onclick=function(){state.users.splice(Number(btn.dataset.remove),1);renderRows()}})}
  async function loadUsers(){var status=document.getElementById('plinkoVirtualStatus');if(status)status.textContent='Loading virtual users...';try{var r=await fetch('/admin/api/plinko-virtual-users',{credentials:'same-origin'});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load virtual users');state.users=Array.isArray(j.users)?j.users:[];renderRows();if(status)status.textContent='Loaded '+state.users.length+' users.'}catch(e){if(status)status.textContent=e.message||'Could not load virtual users'}}
  async function saveUsers(){var status=document.getElementById('plinkoVirtualStatus');if(status)status.textContent='Saving...';try{var clean=state.users.map(function(u){return {name:String(u.name||'').trim(),amount:Number(u.amount)||0}}).filter(function(u){return u.name&&u.amount>0});var r=await fetch('/admin/api/plinko-virtual-users',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({users:clean})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save');state.users=Array.isArray(j.users)?j.users:[];renderRows();if(status)status.textContent='Saved. New Plinko live bets will use these names and amounts.'}catch(e){if(status)status.textContent=e.message||'Could not save virtual users'}}
  async function resetUsers(){var status=document.getElementById('plinkoVirtualStatus');if(status)status.textContent='Resetting...';try{var r=await fetch('/admin/api/plinko-virtual-users/reset',{method:'POST',credentials:'same-origin'});var j=await r.json();if(!r.ok)throw new Error(j.error||'Could not reset');state.users=Array.isArray(j.users)?j.users:[];renderRows();if(status)status.textContent='Defaults restored.'}catch(e){if(status)status.textContent=e.message||'Could not reset'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addMenu);else addMenu();
})();
</script>`;
