export const ADMIN_ANNOUNCEMENT_PANEL_SCRIPT = `<script>
(function(){
  function q(id){return document.getElementById(id)}
  function ensure(){
    if(q('announcementPanel'))return;
    var css=document.createElement('style');
    css.textContent='#sectionAnnouncement{margin-top:22px}' + '#announcementPanel{margin:16px 0;padding:16px;border-radius:22px;background:rgba(255,255,255,.045);color:#fff;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}#announcementPanel h3{margin:0 0 6px;font-size:16px}#announcementPanel p{margin:0 0 12px;color:rgba(255,255,255,.58);font-size:12px;line-height:1.35}#announcementPanel textarea,#announcementPanel input,#announcementPanel select{width:100%;border:0;outline:0;border-radius:16px;background:rgba(0,0,0,.24);color:#fff;padding:11px 12px;box-sizing:border-box;margin:0 0 8px;font-size:13px}#announcementPanel textarea{min-height:92px;resize:vertical}#announcementPanel .ann-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}#announcementPanel button{height:40px;border:0;border-radius:999px;background:rgba(255,255,255,.10);color:#fff;font-weight:850;font-size:12px}#announcementPanel button:disabled{opacity:.45}#announcementPanel button.primary{background:linear-gradient(135deg,#5b0f24,#9f294b)}#announcementPanel .ann-regions{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin:6px 0 10px}#announcementPanel .ann-options{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:6px 0 10px}#announcementPanel .ann-options label{border-radius:16px;justify-content:flex-start}#announcementPanel .ann-options input{width:auto;height:auto;margin:0}#announcementPanel label{font-size:11px;color:rgba(255,255,255,.72);display:flex;align-items:center;gap:4px;background:rgba(255,255,255,.06);border-radius:999px;padding:8px 7px}#announcementPanel audio{width:100%;margin:8px 0}#announcementPanel .ann-file{background:rgba(0,0,0,.18);border:1px dashed rgba(255,255,255,.18)}#announcementPanel .ann-note{font-size:10.5px;color:rgba(255,255,255,.48);margin:-3px 0 8px}#announcementStatus{white-space:pre-wrap;color:rgba(255,255,255,.62);font-size:11px;margin-top:8px}';
    document.head.appendChild(css);
    var s=document.createElement('section');
    s.id='announcementPanel';
    s.innerHTML='<h3>Vexa Admin Message</h3><p>Write text, generate audio preview, listen, then approve and send.</p><input id="annTitle" value="Vexa wants to say something" placeholder="Small popup title"><input id="annUserId" inputmode="numeric" placeholder="Telegram User ID — optional"><select id="annTtl"><option value="0">Unlimited delivery window</option><option value="5">Available for 5 minutes</option><option value="10">Available for 10 minutes</option><option value="20" selected>Available for 20 minutes</option><option value="30">Available for 30 minutes</option><option value="60">Available for 1 hour</option><option value="1440">Available for 24 hours</option></select><div class="ann-options"><label><input id="annMiniApp" type="checkbox" checked>Mini App</label><label><input id="annBotChat" type="checkbox">Bot chat</label></div><textarea id="annText" placeholder="Write the message text or image caption here..."></textarea><input id="annImage" class="ann-file" type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp"><input id="annButtonText" placeholder="Button text — optional, e.g. Open App"><select id="annButtonSection"><option value="home">Open Home</option><option value="playzone">Open Play Zone</option><option value="predictzone">Open Predict</option><option value="market">Open Market</option><option value="connect">Open Connect</option><option value="settings">Open Settings</option><option value="deposit">Open Deposit</option></select><div class="ann-note">Bot chat can send text, image with or without caption, and one custom Mini App button.</div><div class="ann-grid"><select id="annLang"><option value="en">English</option><option value="fa">Persian</option><option value="tr">Turkish</option><option value="ru">Russian</option></select><button type="button" data-ann="preview">Generate Voice Preview</button></div><div class="ann-regions"><label><input type="checkbox" value="ALL" checked>All</label><label><input type="checkbox" value="EN">EN</label><label><input type="checkbox" value="IR">IR</label><label><input type="checkbox" value="TR">TR</label><label><input type="checkbox" value="RU">RU</label></div><audio id="annPlayer" controls hidden></audio><div class="ann-grid"><button class="primary" type="button" data-ann="publish">Approve Voice & Send</button><button type="button" data-ann="send-bot">Send Bot Message</button><button type="button" data-ann="disable">Disable Message</button></div><div id="announcementStatus"></div>';
    var section=document.createElement('section');section.className='section admin-section';section.id='sectionAnnouncement';section.dataset.title='Vexa Admin Message';section.dataset.subtitle='Send voice messages to the Mini App or bot chat.';section.appendChild(s);var target=document.querySelector('main')||document.querySelector('.admin-content')||document.body;target.appendChild(section);var menu=document.getElementById('adminMenu');if(menu&&!document.getElementById('announcementMenu')){var btn=document.createElement('button');btn.className='menu-item';btn.id='announcementMenu';btn.type='button';btn.innerHTML='<strong>Admin Message</strong><span>Voice message delivery</span>';btn.onclick=function(){document.querySelectorAll('.menu-item').forEach(function(x){x.classList.toggle('active',x===btn)});document.querySelectorAll('.admin-section').forEach(function(x){x.classList.toggle('active',x.id==='sectionAnnouncement')});var h=document.getElementById('adminTitle'),sub=document.getElementById('adminSubtitle');if(h)h.textContent='Vexa Admin Message';if(sub)sub.textContent='Send voice messages to Mini App or bot chat.';menu.hidden=true;window.scrollTo({top:0,behavior:'smooth'})};menu.appendChild(btn)}
  }
  function regions(){var a=[];document.querySelectorAll('#announcementPanel .ann-regions input[type=checkbox]:checked').forEach(function(x){a.push(x.value)});return a.length?a:['ALL']}
  function userId(){return (q('annUserId')&&q('annUserId').value||'').replace(/[^0-9]/g,'').trim()}
  function ttlMinutes(){var n=Number(q('annTtl')&&q('annTtl').value||0);return n>0?Math.floor(n):0}
  function delivery(){return {miniApp:!!(q('annMiniApp')&&q('annMiniApp').checked),botChat:!!(q('annBotChat')&&q('annBotChat').checked)}}
  async function postForm(path,form){var r=await fetch(path,{method:'POST',credentials:'same-origin',body:form});var txt=await r.text();var j={};try{j=txt?JSON.parse(txt):{}}catch(e){j={error:txt||'Bad response'}}if(!r.ok)throw new Error((j&&j.error?j.error:'Request failed')+' (HTTP '+r.status+')');return j}
  function botMessageForm(){var form=new FormData();var image=q('annImage')&&q('annImage').files&&q('annImage').files[0];form.append('text',(q('annText')&&q('annText').value||'').trim());form.append('targetUserId',userId());form.append('regions',JSON.stringify(regions()));form.append('buttonText',(q('annButtonText')&&q('annButtonText').value||'').trim());form.append('buttonSection',(q('annButtonSection')&&q('annButtonSection').value||'home'));if(image)form.append('image',image);return form}
  function status(t){var n=q('announcementStatus');if(n)n.textContent=t}
  function lock(v){document.querySelectorAll('#announcementPanel button').forEach(function(b){b.disabled=!!v})}
  async function post(path,body){var controller=new AbortController();var timer=setTimeout(function(){controller.abort()},45000);try{var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{}),signal:controller.signal});var txt=await r.text();var j={};try{j=txt?JSON.parse(txt):{}}catch(e){j={error:txt||'Bad response'}}if(!r.ok)throw new Error((j&&j.error?j.error:'Request failed')+' (HTTP '+r.status+')');return j}catch(e){if(e&&e.name==='AbortError')throw new Error('Generation timed out. Try shorter text or check ElevenLabs key/plan.');throw e}finally{clearTimeout(timer)}}
  async function live(){try{await post('/admin/api/section-lock-events/broadcast',{})}catch(e){}}
  var draftId='';
  document.addEventListener('click',async function(e){var b=e.target&&e.target.closest?e.target.closest('[data-ann]'):null;if(!b)return;try{var act=b.getAttribute('data-ann');var uid=userId();lock(true);if(act==='preview'){var text=q('annText').value.trim();if(!text)throw new Error('Write the message text first.');status('Generating preview... this can take 5-20 seconds.');var d=delivery();if(!d.miniApp&&!d.botChat)throw new Error('Choose Mini App, Bot chat, or both.');var res=await post('/admin/api/vexa-voice/preview',{title:q('annTitle').value,text:text,language:q('annLang').value,regions:regions()});draftId=res.draftId||'';var p=q('annPlayer');p.hidden=false;p.src=res.previewUrl;p.load();p.play().catch(function(){});status('Preview ready. Listen first, then approve.')}if(act==='send-bot'){status('Sending bot message...');var text=(q('annText')&&q('annText').value||'').trim();var image=q('annImage')&&q('annImage').files&&q('annImage').files[0];if(!text&&!image)throw new Error('Write text or choose an image first.');var uid=userId();var sent=await postForm(uid?'/admin/api/vexa-voice/user-bot-message':'/admin/api/vexa-voice/bot-message',botMessageForm());status(JSON.stringify(sent,null,2))}if(act==='publish'){if(!draftId)throw new Error('Generate preview first.');status('Publishing...');var d=delivery();if(!d.miniApp&&!d.botChat)throw new Error('Choose Mini App, Bot chat, or both.');var published=uid?await post('/admin/api/vexa-voice/user-publish',{draftId:draftId,targetUserId:uid,ttlMinutes:ttlMinutes(),deliverMiniApp:d.miniApp,deliverBotChat:d.botChat}):await post('/admin/api/vexa-voice/publish',{draftId:draftId,regions:regions(),ttlMinutes:ttlMinutes(),deliverMiniApp:d.miniApp,deliverBotChat:d.botChat});await live();status(JSON.stringify(Object.assign({live:true},published),null,2))}if(act==='disable'){status('Disabling...');var disabled=uid?await post('/admin/api/vexa-voice/user-disable',{targetUserId:uid}):await post('/admin/api/vexa-voice/admin-message',{enabled:false,regions:regions()});await live();status(JSON.stringify(Object.assign({live:true},disabled),null,2))}}catch(err){status(err&&err.message?err.message:'Failed')}finally{lock(false)}},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();
</script>`;