export const ADMIN_USER_MENU_PANEL_SCRIPT = `<script>(function(){
  var activeSource='ai_bot';
  var usersCache=[];
  function esc(v){return String(v??'').replace(/[&<>]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[s]||s})}
  function fmt(v){return Number(v||0).toLocaleString('en-US')}
  function fmtTonNano(v){var n=Number(v||0);var ton=n/1000000000;return ton.toLocaleString('en-US',{maximumFractionDigits:3})+' TON'}
  function ago(v){if(!v)return '—';var t=Date.parse(v);if(!t)return v;var d=Math.max(0,Date.now()-t);if(d<60000)return 'now';if(d<3600000)return Math.floor(d/60000)+'m';if(d<86400000)return Math.floor(d/3600000)+'h';return Math.floor(d/86400000)+'d'}
  function title(src){return src==='ai_bot'?'AI Bot Users':src==='game_bot'?'Game Bot Users':src==='user_bot'?'User Bots':'Other Users'}
  function balance(u){return u.tonBalance||fmtTonNano(u.tonBalanceNano||u.credit||0)}
  function installMenu(){var menu=document.getElementById('adminMenu');if(!menu||document.getElementById('aiUsersMenu'))return;var old=menu.querySelector('[data-section="users"]');if(old)old.remove();menu.insertAdjacentHTML('afterbegin','<button class="menu-item active" id="aiUsersMenu" data-user-menu="ai_bot" type="button"><strong>AI Bot Users</strong><span>Users of AI bot</span></button><button class="menu-item" data-user-menu="game_bot" type="button"><strong>Game Bot Users</strong><span>Users of game bot</span></button><button class="menu-item" data-user-menu="user_bot" type="button"><strong>User Bots</strong><span>Connected bot users</span></button>');document.querySelectorAll('[data-user-menu]').forEach(function(b){b.onclick=function(){activeSource=b.getAttribute('data-user-menu')||'ai_bot';document.querySelectorAll('.menu-item').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.admin-section').forEach(function(s){s.classList.toggle('active',s.id==='sectionUsers')});var h=document.getElementById('adminTitle'),sub=document.getElementById('adminSubtitle');if(h)h.textContent=title(activeSource);if(sub)sub.textContent='Manage '+title(activeSource).toLowerCase()+'.';renderList();window.scrollTo({top:0,behavior:'smooth'})}})}
  function row(u){return '<article class="user" id="user-'+esc(u.id)+'"><div class="user-top"><div class="user-name"><b>'+esc(u.username||'—')+'</b><span class="badge '+(u.isActive?'on':'off')+'">'+esc(u.status||'Inactive')+'</span></div><strong>'+esc(balance(u))+'</strong></div><div class="user-info"><span>ID '+esc(u.id)+'</span><span>'+esc(u.firstName||'—')+'</span><span>'+esc(u.currentSection||u.sourceLabel||title(u.source))+'</span><span>'+ago(u.lastSeenAt)+'</span></div><button class="manage-btn" data-manage-user="'+esc(u.id)+'" type="button">Manage user</button><button class="reset-user-btn" data-reset-user="'+esc(u.id)+'" type="button">Reset user</button><div class="user-manage" data-manage-panel="'+esc(u.id)+'" hidden></div></article>'}
  function bindRows(){document.querySelectorAll('[data-manage-user]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-manage-user');if(typeof toggleUserManage==='function')toggleUserManage(id)}});document.querySelectorAll('[data-reset-user]').forEach(function(btn){btn.onclick=function(){resetUser(btn.getAttribute('data-reset-user'))}})}
  function renderList(){var list=document.getElementById('usersList'),search=document.getElementById('userSearch');if(!list)return;var q=String(search&&search.value||'').trim().toLowerCase();var rows=usersCache.filter(function(u){return (u.source||'unknown')===activeSource}).filter(function(u){return !q||String(u.id).toLowerCase().includes(q)||String(u.username).toLowerCase().includes(q)||String(u.firstName).toLowerCase().includes(q)||String(u.currentSection).toLowerCase().includes(q)});list.innerHTML=rows.length?rows.map(row).join(''):'<div class="empty">No users in '+title(activeSource)+'.</div>';bindRows()}
  async function refreshUsers(){var status=document.getElementById('usersStatus');try{installMenu();if(status)status.textContent='Loading users...';var r=await fetch('/admin/api/users',{credentials:'same-origin'});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Could not load users');usersCache=j.users||[];var stats=j.stats||{};var total=document.getElementById('statTotal'),online=document.getElementById('statOnline'),inactive=document.getElementById('statInactive'),credit=document.getElementById('statCredit');if(total)total.textContent=String(stats.total||usersCache.length);if(online)online.textContent=String(stats.online||0);if(inactive)inactive.textContent=String(stats.inactive||0);if(credit)credit.textContent=fmtTonNano(stats.totalTonBalanceNano||stats.totalCredit||0);if(status)status.textContent=title(activeSource)+' updated '+new Date().toLocaleTimeString();renderList()}catch(e){if(status)status.textContent=e.message||'Could not load users'}}
  async function resetUser(userId){if(!userId)return;if(!confirm('Reset user '+userId+'?'))return;var status=document.getElementById('usersStatus');if(status)status.textContent='Resetting user...';try{var r=await fetch('/admin/api/users/'+encodeURIComponent(userId),{method:'DELETE',credentials:'same-origin'});var j=await r.json().catch(function(){return{error:'Invalid response'}});if(!r.ok)throw new Error(j.error||'Could not reset user');await refreshUsers()}catch(e){if(status)status.textContent=e.message||'Could not reset user'}}
  window.VexaRenderUserMenu=refreshUsers;
  setTimeout(refreshUsers,250);
  setTimeout(refreshUsers,900);
  var search=document.getElementById('userSearch');if(search)search.addEventListener('input',function(){setTimeout(renderList,30)});
  var refresh=document.getElementById('refreshUsers');if(refresh)refresh.addEventListener('click',function(){setTimeout(refreshUsers,30)},true);
})();</script>`;
