export const ADMIN_PLAY_ZONE_CARDS_PANEL_SCRIPT = `
<style>
.play-zone-card-admin{margin-top:24px;padding-top:16px;border-top:1px solid rgba(255,255,255,.09)}.play-zone-card-admin h2{margin:0 0 4px;font-size:18px}.play-zone-card-admin h3{margin:18px 0 4px;font-size:14px}.play-zone-card-list{display:grid;gap:14px}.play-zone-card-row{display:grid;grid-template-columns:78px 1fr;gap:12px;align-items:center;padding:12px 0;border-top:1px solid rgba(255,255,255,.08)}.play-zone-card-preview{width:78px;height:98px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#080808;object-fit:contain}.play-zone-card-preview--wide{height:78px;border-radius:18px;background:transparent!important;object-fit:contain}.play-zone-card-tools{display:grid;gap:7px}.play-zone-card-title{display:flex;align-items:center;justify-content:space-between;gap:8px}.play-zone-card-badge{border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:4px 8px;color:rgba(255,255,255,.62);font-size:10px;font-weight:950}.play-zone-card-row.is-hidden{opacity:.58}.play-zone-card-row.is-hidden .play-zone-card-badge{background:rgba(255,80,80,.16);color:#ffb3b3}.play-zone-card-tools input{height:auto!important;border-radius:15px!important;padding:9px!important;font-size:11px!important}.play-zone-card-tools button{height:32px;border-radius:999px;border:1px solid rgba(255,255,255,.16);background:#070707;color:#fff;font-weight:900;font-size:11px}.play-zone-card-tools button.play-zone-card-restore{background:#fff;color:#050505}.play-zone-card-status{min-height:15px;color:rgba(255,255,255,.55);font-size:11px;margin-top:8px}</style>
<script>(function(){
const games=[['mines','Mines'],['plinko','Plinko'],['crash','Crash'],['wheel','Wheel'],['dice','Dice'],['rps','Rock Paper Scissors'],['slot','Slot'],['coinflip','Pump'],['hilo','Chicken Cross'],['ghostrun','Ghost Run']],wide=[['predict-zone-card','Predict Zone card image']],allowed=['image/png','image/jpeg','image/webp'];let visibility={};
function url(id){return '/app/api/section-lock-image/'+id+'/locked.png?v='+Date.now()}
function row(g,kind){const hidden=visibility[g[0]]===false;return '<article class="play-zone-card-row '+(hidden?'is-hidden':'')+'" data-play-card-row="'+g[0]+'"><img class="play-zone-card-preview '+(kind==='wide'?'play-zone-card-preview--wide':'')+'" id="playCardPreview-'+g[0]+'" src="'+url(g[0])+'" onerror="this.style.opacity=.28"/><div class="play-zone-card-tools"><div class="play-zone-card-title"><strong>'+g[1]+'</strong>'+(kind==='card'?'<span class="play-zone-card-badge" data-play-card-badge="'+g[0]+'">'+(hidden?'Hidden from UI':'Visible')+'</span>':'')+'</div><input data-play-card-file="'+g[0]+'" type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp"/><button type="button" data-play-card-upload="'+g[0]+'">Upload '+g[1]+'</button><button type="button" data-play-card-delete="'+g[0]+'">Delete image</button>'+(kind==='card'?'<button class="'+(hidden?'play-zone-card-restore':'')+'" type="button" data-play-card-visible="'+g[0]+'" data-visible="'+(hidden?'true':'false')+'">'+(hidden?'Restore card to UI':'Remove card from UI')+'</button>':'')+'</div></article>'}
function render(){const wrap=document.getElementById('playZoneCardsPanel');if(!wrap)return;wrap.innerHTML='<h2>Play Zone card images</h2><p class="muted small-text">Upload card images, or remove/restore each Play Zone game card. Visibility is stored in D1 only.</p><div class="play-zone-card-list">'+games.map(g=>row(g,'card')).join('')+'</div><h3>Predict Zone image</h3><p class="muted small-text">This image appears on the right side of the Predict Zone glass card.</p><div class="play-zone-card-list">'+wide.map(g=>row(g,'wide')).join('')+'</div><p id="playZoneCardStatus" class="play-zone-card-status"></p>';wrap.querySelectorAll('[data-play-card-upload]').forEach(btn=>btn.onclick=()=>upload(btn.getAttribute('data-play-card-upload')));wrap.querySelectorAll('[data-play-card-delete]').forEach(btn=>btn.onclick=()=>deleteImage(btn.getAttribute('data-play-card-delete')));wrap.querySelectorAll('[data-play-card-visible]').forEach(btn=>btn.onclick=()=>setVisible(btn.getAttribute('data-play-card-visible'),btn.getAttribute('data-visible')==='true'))}
function ensureMenuShortcut(){const menu=document.getElementById('adminMenu');if(!menu||document.getElementById('playZoneCardsMenuItem'))return;const btn=document.createElement('button');btn.id='playZoneCardsMenuItem';btn.className='menu-item';btn.type='button';btn.innerHTML='<strong>Play Zone Cards</strong><span>Remove/restore Play Zone cards</span>';btn.onclick=()=>{document.querySelectorAll('.menu-item').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.admin-section').forEach(section=>section.classList.toggle('active',section.id==='sectionImages'));const title=document.getElementById('adminTitle'),subtitle=document.getElementById('adminSubtitle'),panel=document.getElementById('playZoneCardsPanel');if(title)title.textContent='Play Zone Cards';if(subtitle)subtitle.textContent='Remove or restore game cards in the Play Zone UI.';menu.hidden=true;setTimeout(()=>{(panel||document.getElementById('sectionImages')||document.body).scrollIntoView({behavior:'smooth',block:'start'})},50)};menu.appendChild(btn)}
function mount(){ensureMenuShortcut();const target=document.getElementById('sectionImages')||document.querySelector('main')||document.body;if(!target||document.getElementById('playZoneCardsPanel'))return;const wrap=document.createElement('div');wrap.id='playZoneCardsPanel';wrap.className='play-zone-card-admin';target.appendChild(wrap);render();loadVisibility()}
function setStatus(text){const status=document.getElementById('playZoneCardStatus');if(status)status.textContent=text}
function clearCaches(){try{['vexaPlayZoneImageUrls:v1','vexaPlayZoneImageUrls:v2','vexaPlayZoneImageUrls:v3','vexaPlayZoneImageUrls:v4','vexaPlayZoneImageUrls:v5','vexaPlayZoneImageUrls:v6','vexaPlayZoneImageUrls:v7','vexaPlayZoneImageUrls:v8','vexaPlayZoneImageUrls:v9','vexaPlayZoneImageUrls:v10','vexaPlayZoneImageUrls:v11','vexaPlayZoneImageUrls:v12','vexaPlayZoneImageUrls:v13','vexaSectionLocks:v1'].forEach(k=>localStorage.removeItem(k));Object.keys(localStorage).forEach(k=>{if(k.indexOf('vexaPlayZoneImageUrls')===0||k.indexOf('vexaPlayZoneImageUrlsUpdatedAt')===0)localStorage.removeItem(k)})}catch(e){}}
async function loadVisibility(){try{const r=await fetch('/admin/api/play-zone-cards',{credentials:'same-origin',cache:'no-store'}),j=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(j.error||'Could not load card visibility');visibility={};(j.cards||[]).forEach(card=>visibility[card.id]=card.visible!==false);render();setStatus('Visibility loaded from D1.')}catch(e){setStatus(e.message||'Could not load card visibility')}}
async function setVisible(id,visible){setStatus(visible?'Restoring card...':'Removing card from UI...');try{const r=await fetch('/admin/api/play-zone-cards',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({gameId:id,visible})}),j=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(j.error||'Could not update card');visibility={};(j.cards||[]).forEach(card=>visibility[card.id]=card.visible!==false);render();try{if(window.VexaRefreshPlayZoneCards)window.VexaRefreshPlayZoneCards()}catch(e){}setStatus(visible?'Card restored to Play Zone UI.':'Card removed from Play Zone UI.')}catch(e){setStatus(e.message||'Could not update card')}}
function imageFile(file){return new Promise((resolve,reject)=>{if(!file||!file.type||!file.type.startsWith('image/'))return reject(new Error('Choose an image file.'));resolve(file)})}
async function deleteImage(id){setStatus('Deleting image...');try{const r=await fetch('/admin/api/section-lock-image',{method:'DELETE',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({sectionId:id,kind:'locked'})}),j=await r.json().catch(()=>({error:'Delete failed'}));if(!r.ok)throw new Error(j.error||'Delete failed');clearCaches();const preview=document.getElementById('playCardPreview-'+id);if(preview){preview.style.opacity='.28';preview.src=url(id)}try{if(window.VexaRefreshPlayZoneImages)window.VexaRefreshPlayZoneImages()}catch(e){}setStatus('Image deleted. Reopen Play Zone to see it.')}catch(e){setStatus(e.message||'Delete failed.')}}
async function upload(id){const input=document.querySelector('[data-play-card-file="'+id+'"]');if(!input||!input.files||!input.files[0]){setStatus('Choose an image first.');return}if(!allowed.includes(input.files[0].type)){setStatus('Only PNG, JPG, JPEG or WebP.');return}setStatus('Uploading original image without crop...');try{const image=await imageFile(input.files[0]);const form=new FormData();form.append('sectionId',id);form.append('kind','locked');form.append('image',image);const r=await fetch('/admin/api/section-lock-image',{method:'POST',credentials:'same-origin',body:form}),j=await r.json().catch(()=>({error:'Upload failed'}));if(!r.ok)throw new Error(j.error||'Upload failed');clearCaches();const preview=document.getElementById('playCardPreview-'+id);if(preview){preview.style.opacity='1';preview.src=url(id)}try{if(window.VexaRefreshPlayZoneImages)window.VexaRefreshPlayZoneImages()}catch(e){}setStatus('Original image uploaded with no crop. Reopen Play Zone to see it.')}catch(e){setStatus(e.message||'Upload failed.')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();document.addEventListener('click',()=>setTimeout(mount,80),true);setTimeout(mount,300);setTimeout(mount,1200)
})();</script>
`;
