import { mobileAdminLoginHtml, mobileAdminPanelHtml } from './admin-mobile';
import { ADMIN_IMAGE_PANEL_SCRIPT } from './admin-image-panel';
import { ADMIN_UPLOAD_CACHE_SCRIPT } from './admin-upload-cache-panel';
import { ADMIN_PLINKO_CONTROL_SCRIPT } from './admin-plinko-control-panel';

const ADMIN_UI_REFRESH = `<style>
body{background:#000!important;padding-left:14px!important;padding-right:14px!important}.page{max-width:440px!important}.head{margin-bottom:12px!important}.head h1{font-size:28px!important}.head .muted{font-size:11px!important}.icon-menu{display:none!important}.head-actions{gap:6px!important}.ghost{height:28px!important;padding:0 9px!important;font-size:11px!important;background:#070707!important;border-color:rgba(255,255,255,.15)!important}
.menu-panel{display:flex!important;gap:8px!important;overflow-x:auto!important;margin:2px 0 18px!important;padding:0 0 8px!important;border:0!important;background:transparent!important;scrollbar-width:none}.menu-panel::-webkit-scrollbar{display:none}.menu-item{flex:0 0 auto!important;min-width:92px!important;border:1px solid rgba(255,255,255,.14)!important;border-radius:999px!important;background:#070707!important;color:#fff!important;text-align:center!important;padding:8px 12px!important}.menu-item strong{display:block!important;font-size:12px!important;line-height:1.1!important}.menu-item span{display:none!important}.menu-item.active{background:#fff!important;color:#050505!important;border-color:#fff!important}
.admin-section{margin-top:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}.row-title{align-items:center!important;margin-bottom:10px!important}.row-title h2,.admin-section h2{font-size:18px!important}.small-text{font-size:10px!important}.stats{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:0!important;margin:14px 0 16px!important;border-top:1px solid rgba(255,255,255,.1)!important;border-bottom:1px solid rgba(255,255,255,.1)!important}.stats div{border:0!important;border-right:1px solid rgba(255,255,255,.08)!important;border-radius:0!important;background:transparent!important;padding:10px 8px!important}.stats div:last-child{border-right:0!important}.stats span{font-size:8px!important}.stats b{font-size:18px!important;margin-top:5px!important}.search{position:static!important;background:transparent!important;padding:0!important;margin-bottom:6px!important}label{font-size:9px!important;margin:10px 0 6px!important}input{height:38px!important;font-size:13px!important;background:#050505!important;border-color:rgba(255,255,255,.16)!important}.status,.mini-status{font-size:11px!important;color:rgba(255,255,255,.5)!important}
.users{display:block!important}.user{padding:13px 0!important;border:0!important;border-bottom:1px solid rgba(255,255,255,.11)!important;border-radius:0!important;background:transparent!important}.user:first-child{border-top:1px solid rgba(255,255,255,.11)!important}.user-top{align-items:center!important}.user-name{display:flex!important;align-items:center!important;gap:7px!important;min-width:0!important}.user-name b{font-size:15px!important;max-width:210px!important;letter-spacing:-.02em!important}.badge{font-size:9px!important;padding:4px 7px!important}.user-top>strong{font-size:17px!important}.user-info{display:grid!important;grid-template-columns:1fr 1fr!important;gap:3px 12px!important;margin-top:8px!important;padding:0!important;border:0!important}.user-info span{font-size:11px!important;color:rgba(255,255,255,.45)!important}.manage-btn{height:32px!important;margin-top:10px!important;font-size:12px!important;border-radius:999px!important;background:#070707!important;border-color:rgba(255,255,255,.15)!important}.user-manage{margin-top:10px!important;padding:10px 0 0!important;border:0!important;border-top:1px solid rgba(255,255,255,.08)!important;border-radius:0!important;background:transparent!important}.credit-tools{grid-template-columns:64px 1fr 64px!important;gap:7px!important}.credit-tools button,.credit-tools input,.save-credit,.section-block{height:34px!important;font-size:12px!important}.section-user-blocks{gap:7px!important}.section-block.blocked,.save-credit{background:#fff!important;color:#050505!important}.empty{border:0!important;border-radius:0!important;background:transparent!important;padding:22px 0!important}
.locks-list{display:block!important}.lock-row{padding:13px 0!important;border:0!important;border-bottom:1px solid rgba(255,255,255,.11)!important;border-radius:0!important;background:transparent!important}.lock-row:first-child{border-top:1px solid rgba(255,255,255,.11)!important}.lock-main strong{font-size:15px!important}.lock-main p{font-size:11px!important}.lock-state{font-size:9px!important;color:rgba(255,255,255,.55)!important}.lock-preview{height:62px!important;border-radius:14px!important;background:#050505!important}.lock-toggle{height:32px!important;font-size:11px!important}.code-input,.lock-image-upload input{height:32px!important}.image-current{border:0!important;border-top:1px solid rgba(255,255,255,.1)!important;border-bottom:1px solid rgba(255,255,255,.1)!important;border-radius:0!important;background:transparent!important;padding:12px 0!important}.image-current img{width:40px!important;height:40px!important}.primary{height:40px!important;font-size:13px!important}.plinko-control-admin{display:none}.plinko-control-admin.active{display:block}.plinko-simple-card{border:0!important;border-top:1px solid rgba(255,255,255,.1)!important;border-bottom:1px solid rgba(255,255,255,.1)!important;border-radius:0!important;background:transparent!important;padding:12px 0!important}.plinko-picker{gap:8px!important}.preset-row{gap:7px!important}.preset-row button,.plinko-control-actions .ghost{height:32px!important;font-size:11px!important}.plinko-summary{border:0!important;border-top:1px solid rgba(255,255,255,.1)!important;border-bottom:1px solid rgba(255,255,255,.1)!important;border-radius:0!important;background:transparent!important;color:#fff!important;padding:10px 0!important}.plinko-summary b{color:#fff!important}.plinko-house-row{grid-template-columns:36px 1fr 1fr!important;border:0!important;border-bottom:1px solid rgba(255,255,255,.08)!important;border-radius:0!important;background:transparent!important;padding:8px 0!important}.plinko-house-row strong{font-size:11px!important}.plinko-house-row input{height:32px!important}.plinko-control-actions{grid-template-columns:1fr 80px 64px!important;gap:7px!important}
@media(max-width:430px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))!important}.stats div:nth-child(2){border-right:0!important}.stats div:nth-child(-n+2){border-bottom:1px solid rgba(255,255,255,.08)!important}.code-lock,.lock-image-upload,.plinko-control-actions{grid-template-columns:1fr!important}.plinko-house-row{grid-template-columns:32px 1fr!important}.plinko-house-row>div:last-child{grid-column:2}.plinko-picker{grid-template-columns:1fr 1fr!important}}
</style><script>(function(){function keepMenu(){var menu=document.getElementById('adminMenu');if(menu)menu.hidden=false;var btn=document.getElementById('menuBtn');if(btn)btn.hidden=true;}function relabel(){document.querySelectorAll('[data-manage-user]').forEach(function(b){b.textContent=b.closest('.user')?.querySelector('.user-manage:not([hidden])')?'Close':'Manage';});}document.addEventListener('click',function(e){setTimeout(function(){keepMenu();relabel();},30);});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){keepMenu();relabel();new MutationObserver(keepMenu).observe(document.body,{childList:true,subtree:true,attributes:true});});else{keepMenu();relabel();new MutationObserver(keepMenu).observe(document.body,{childList:true,subtree:true,attributes:true});}})();</script>`;

export function adminHtml(): string {
  return mobileAdminLoginHtml();
}

export function adminPanelHtml(): string {
  return mobileAdminPanelHtml().replace('</body></html>', ADMIN_UI_REFRESH + ADMIN_IMAGE_PANEL_SCRIPT + ADMIN_UPLOAD_CACHE_SCRIPT + ADMIN_PLINKO_CONTROL_SCRIPT + '</body></html>');
}

export function defaultCreditIconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="32" fill="black"/><circle cx="32" cy="32" r="22" fill="white"/></svg>`;
}
