export const PLINKO_PANEL_SCRIPT = `
(function(){
  var NANO=1000000000;
  var MIN_BET=.01;
  var inlineInputHome=null;
  var lastAmountPointerAt=0;
  function q(id){return document.getElementById(id)}
  function ensureFirstLoadStyle(){if(document.getElementById('plinkoFirstLoadNoOverlayStyle'))return;var style=document.createElement('style');style.id='plinkoFirstLoadNoOverlayStyle';style.textContent='body.plinko-control-loading #plinko.view .plinko-stage{opacity:1!important;pointer-events:auto!important}body.plinko-control-loading #plinko.view .plinko-controls{opacity:1!important;pointer-events:auto!important}body.plinko-control-loading #plinko.view:after{display:none!important;content:none!important;opacity:0!important;pointer-events:none!important}';document.head.appendChild(style)}
  function tonToNano(value){return Math.max(0,Math.floor((Number(String(value||'').replace(',','.'))||0)*NANO))}
  function readBalanceNano(){if(window.VexaTonBalance&&typeof window.VexaTonBalance.read==='function')return Math.max(0,Math.floor(Number(window.VexaTonBalance.read())||0));var source=q('plinkoTonBalance')||q('topTonBalance')||q('plinkoCredit');return tonToNano(source&&source.textContent)}
  function isPlinkoActive(){var active=document.querySelector('.view.active');return !!(active&&active.id==='plinko')}
  function roundCurrency(value){var next=Math.round((Math.max(0,Number(value)||0)+Number.EPSILON)*100)/100;return next}
  function money(value){var next=roundCurrency(value);return next.toFixed(2).replace(/\.00$/,'').replace(/(\.\d)0$/,'$1')}
  function syncHiddenInput(){var input=q('plinkoBet'),open=document.querySelector('[data-plinko-bet-input-open]');if(input&&open)input.value=money(open.textContent||input.value||MIN_BET)}
  function currentBet(){var input=q('plinkoBet');var value=Number(String(input&&input.value||'').replace(',','.'));return Number.isFinite(value)&&value>=MIN_BET?roundCurrency(value):MIN_BET}
  function setBet(value){var input=q('plinkoBet'),open=document.querySelector('[data-plinko-bet-input-open]'),editorInput=document.querySelector('[data-plinko-bet-input]');var next=roundCurrency(value);if(!Number.isFinite(next)||next<MIN_BET)next=MIN_BET;var balance=roundCurrency(readBalanceNano()/NANO);if(balance>=MIN_BET&&next>balance)next=balance;var display=money(next);if(input)input.value=display;if(open)open.textContent=display;if(editorInput&&document.activeElement!==editorInput)editorInput.value=display;renderStats()}
  function multiplyBet(multiplier){var value=currentBet();setBet(multiplier===.5?Math.max(MIN_BET,value/2):value*2)}
  function renderStats(){var bet=currentBet(),balance=roundCurrency(readBalanceNano()/NANO);var current=document.querySelector('[data-plinko-current]'),balanceEl=document.querySelector('[data-plinko-balance]');if(current)current.textContent=money(bet);if(balanceEl)balanceEl.textContent=money(balance);syncHiddenInput()}
  function setInputStyle(input,anchor){var rect=anchor&&anchor.getBoundingClientRect?anchor.getBoundingClientRect():null;if(!input||!rect)return;input.style.setProperty('position','fixed','important');input.style.setProperty('left',rect.left+'px','important');input.style.setProperty('top',rect.top+'px','important');input.style.setProperty('width',rect.width+'px','important');input.style.setProperty('height',rect.height+'px','important');input.style.setProperty('z-index','9999','important');input.style.setProperty('opacity','1','important');input.style.setProperty('pointer-events','auto','important');input.style.setProperty('background','transparent','important');input.style.setProperty('border','0','important');input.style.setProperty('outline','0','important');input.style.setProperty('box-shadow','none','important');input.style.setProperty('color','#fff','important');input.style.setProperty('-webkit-text-fill-color','#fff','important');input.style.setProperty('caret-color','#fff','important');input.style.setProperty('text-align','center','important');input.style.setProperty('font-size','22px','important');input.style.setProperty('font-weight','900','important');input.style.setProperty('letter-spacing','-.02em','important');input.style.setProperty('line-height',rect.height+'px','important');input.style.setProperty('padding','0','important');input.style.setProperty('margin','0','important');input.style.setProperty('transform','none','important');input.style.setProperty('appearance','none','important');input.style.setProperty('-webkit-appearance','none','important')}
  function clearInputStyle(input){if(!input)return;input.removeAttribute('style')}
  function focusAmountInput(anchor){var editor=document.querySelector('[data-plinko-bet-editor]'),editorInput=document.querySelector('[data-plinko-bet-input]'),hidden=q('plinkoBet');if(editor)editor.classList.remove('active');if(!editorInput)return;inlineInputHome=inlineInputHome||editorInput.parentNode;editorInput.value=money(currentBet());editorInput.setAttribute('inputmode','decimal');editorInput.setAttribute('autocomplete','off');editorInput.setAttribute('enterkeyhint','done');editorInput.min=String(MIN_BET);editorInput.step='0.01';if(hidden)hidden.value=editorInput.value;document.body.appendChild(editorInput);setInputStyle(editorInput,anchor);var open=document.querySelector('[data-plinko-bet-input-open]');if(open)open.style.setProperty('color','transparent','important');try{editorInput.focus({preventScroll:true});editorInput.setSelectionRange(String(editorInput.value).length,String(editorInput.value).length)}catch(e){try{editorInput.focus();editorInput.select()}catch(_){}}}
  function restoreInlineInput(save){var input=document.querySelector('[data-plinko-bet-input]'),open=document.querySelector('[data-plinko-bet-input-open]');if(input&&save)setBet(input.value);if(open)open.style.removeProperty('color');if(input){clearInputStyle(input);if(inlineInputHome&&input.parentNode!==inlineInputHome)inlineInputHome.appendChild(input)}}
  function closeEditor(save){var editor=document.querySelector('[data-plinko-bet-editor]');restoreInlineInput(save);if(editor)editor.classList.remove('active')}
  function syncHeaderCredit(){var source=q('plinkoTonBalance')||q('topTonBalance')||q('plinkoCredit');var header=q('plinkoCreditHeader');if(source&&header)header.textContent=source.textContent||'0';renderStats()}
  function setLastWin(value){var win=document.querySelector('[data-plinko-win]');if(win)win.textContent=money(value)}
  function amountButtonFromPoint(x,y){var controls=[document.querySelector('[data-action="plinko-bet-half"]'),document.querySelector('[data-plinko-bet-input-open]'),document.querySelector('[data-action="plinko-bet-double"]')];for(var i=0;i<controls.length;i++){var el=controls[i];if(!el||!el.getBoundingClientRect)return null;var r=el.getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom)return el}return null}
  function handleAmountPoint(ev){if(!isPlinkoActive())return false;if(ev&&ev.type==='touchstart'&&window.PointerEvent)return false;var x=ev.clientX,y=ev.clientY;if((x==null||y==null)&&ev.touches&&ev.touches[0]){x=ev.touches[0].clientX;y=ev.touches[0].clientY}if(x==null||y==null)return false;var btn=amountButtonFromPoint(x,y);if(!btn)return false;if(ev.cancelable!==false)ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();if(btn.hasAttribute('data-plinko-bet-input-open'))focusAmountInput(btn);else if(btn.getAttribute('data-action')==='plinko-bet-half')multiplyBet(.5);else if(btn.getAttribute('data-action')==='plinko-bet-double')multiplyBet(2);return true}
  function smoothPress(el){if(!el)return;if(el.__plinkoSmoothFrame)cancelAnimationFrame(el.__plinkoSmoothFrame);el.classList.add('plinko-drop-press');el.__plinkoSmoothFrame=requestAnimationFrame(function(){el.classList.add('plinko-drop-tap');clearTimeout(el.__plinkoSmoothTimer);el.__plinkoSmoothTimer=setTimeout(function(){el.classList.remove('plinko-drop-tap');el.classList.remove('plinko-drop-press')},220)})}
  function smoothRelease(el){if(el)el.classList.remove('plinko-drop-press')}
  function dropAssetFromEvent(ev){var btn=ev&&ev.target&&ev.target.closest?ev.target.closest('[data-action="drop-plinko-ball"]'):null;if(!btn)return null;return btn.closest('.plinko-drop-asset')||btn}
  document.addEventListener('pointerdown',function(ev){if(handleAmountPoint(ev)){lastAmountPointerAt=Date.now();return}var el=dropAssetFromEvent(ev);if(el)smoothPress(el)},{capture:true,passive:false});
  document.addEventListener('touchstart',function(ev){if(handleAmountPoint(ev))lastAmountPointerAt=Date.now()},{capture:true,passive:false});
  document.addEventListener('pointerup',function(ev){smoothRelease(dropAssetFromEvent(ev))},{capture:true,passive:true});
  document.addEventListener('pointercancel',function(ev){smoothRelease(dropAssetFromEvent(ev))},{capture:true,passive:true});
  document.addEventListener('click',function(ev){if(Date.now()-lastAmountPointerAt<450){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();return}if(handleAmountPoint(ev))return;var button=ev.target&&ev.target.closest&&ev.target.closest('button');if(!button)return;if(button.hasAttribute('data-plinko-bet-input-open')){ev.preventDefault();focusAmountInput(button);return}if(button.hasAttribute('data-plinko-bet-done')){ev.preventDefault();closeEditor(true);return}var action=button.getAttribute('data-action');if(action==='plinko-bet-half'){ev.preventDefault();multiplyBet(.5);return}if(action==='plinko-bet-double'){ev.preventDefault();multiplyBet(2);return}},true);
  document.addEventListener('click',function(ev){var editor=document.querySelector('[data-plinko-bet-editor]');if(editor&&editor.classList.contains('active')&&ev.target===editor)closeEditor(true)});
  document.addEventListener('keydown',function(ev){var input=document.querySelector('[data-plinko-bet-input]');if(input&&document.activeElement===input){if(ev.key==='Enter'){ev.preventDefault();input.blur();restoreInlineInput(true)}if(ev.key==='Escape'){ev.preventDefault();input.blur();restoreInlineInput(false)}return}var editor=document.querySelector('[data-plinko-bet-editor]');if(!editor||!editor.classList.contains('active'))return;if(ev.key==='Escape')closeEditor(false);if(ev.key==='Enter')closeEditor(true)});
  document.addEventListener('input',function(ev){if(ev.target&&ev.target.id==='plinkoBet')setBet(ev.target.value);if(ev.target&&ev.target.hasAttribute&&ev.target.hasAttribute('data-plinko-bet-input')){var hidden=q('plinkoBet'),open=document.querySelector('[data-plinko-bet-input-open]');if(hidden)hidden.value=ev.target.value;if(open)open.textContent=money(ev.target.value);renderStats()}});
  document.addEventListener('focusout',function(ev){if(ev.target&&ev.target.hasAttribute&&ev.target.hasAttribute('data-plinko-bet-input'))restoreInlineInput(true)});
  document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'&&isPlinkoActive())syncHeaderCredit()});
  window.addEventListener('focus',function(){if(isPlinkoActive())syncHeaderCredit()});
  window.addEventListener('vexa-ton-balance-sync',function(){if(isPlinkoActive())syncHeaderCredit()});
  window.addEventListener('vexa:view-changed',function(ev){if(ev&&ev.detail&&ev.detail.id==='plinko')syncHeaderCredit()});
  window.addEventListener('vexa-plinko-last-win',function(ev){setLastWin(ev&&ev.detail?ev.detail.total:0);renderStats()});
  var start=function(){ensureFirstLoadStyle();setBet(currentBet());syncHeaderCredit()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
`;
